Even More Modifiers: Loot.Api.Strategy.RollingStrategy Class Reference
Loot.Api.Strategy.RollingStrategy Class Reference
Public Member Functions
virtual void PlaySoundEffect (Item item)
virtual void PostRoll (ref List< Modifier > modifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual void PostRollLine (ref List< Modifier > modifiers, Modifier line, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual List< Modifier > PreRoll (ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual Modifier PreRollLine (ref List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual List< Modifier > Roll (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual Modifier RollLine (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties, WeightedRandom< Modifier > weightedRandom)
Protected Attributes
bool _forceNextRoll
LootModItem modifierItem
RollingStrategyProperties properties
Private Member Functions
WeightedRandom< Modifier > GetRandomList (ModifierContext context, ModifierPool pool)
void InitFields (Item item, RollingStrategyProperties properties)
void RollProperties (Modifier modifier, List< Modifier > modifiers, ModifierContext modifierContext, RollingStrategyProperties properties)
Detailed Description
Definition at line 15 of file RollingStrategy.cs.
Member Function Documentation
WeightedRandom<Modifier> Loot.Api.Strategy.RollingStrategy.GetRandomList (ModifierContext context, ModifierPool pool) private
Definition at line 29 of file RollingStrategy.cs.
References Loot.Api.Core.ModifierContext.Item, and Loot.Api.Graphics.GraphicsGlobalItem.UpdateGraphicsEntities().
         {
             WeightedRandom<Modifier> wr = new WeightedRandom<Modifier>();
             foreach (var e in pool.GetRollableModifiers(context))
             {
                 wr.Add(e, e.Properties.RollChance);
             }
             return wr;
         }
void Loot.Api.Strategy.RollingStrategy.InitFields (Item item, RollingStrategyProperties properties) private
Definition at line 23 of file RollingStrategy.cs.
References Loot.LootModItem.GetInfo().
         {
             this.properties = properties;
             modifierItem = LootModItem.GetInfo(item);
         }
virtual void Loot.Api.Strategy.RollingStrategy.PlaySoundEffect (Item item) virtual
Reimplemented in Loot.RollingStrategies.SealingRollingStrategy.
Definition at line 49 of file RollingStrategy.cs.
         {
             Main.PlaySound(SoundID.Item37, -1, -1);
         }
virtual void Loot.Api.Strategy.RollingStrategy.PostRoll (ref List< Modifier > modifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented in Loot.RollingStrategies.SealingRollingStrategy.
Definition at line 122 of file RollingStrategy.cs.
         {
         }
virtual void Loot.Api.Strategy.RollingStrategy.PostRollLine (ref List< Modifier > modifiers, Modifier line, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Definition at line 164 of file RollingStrategy.cs.
         {
         }
virtual List<Modifier> Loot.Api.Strategy.RollingStrategy.PreRoll (ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented in Loot.RollingStrategies.SealingRollingStrategy.
Definition at line 114 of file RollingStrategy.cs.
References Loot.Api.Strategy.RollingStrategyProperties.PresetLines.
         {
             var preset = properties?.PresetLines?.Invoke() ?? new List<Modifier>();
             preset.ForEach(x => RollProperties(x, preset, modifierContext, properties));
             preset.ForEach(x => x.Roll(modifierContext, preset));
             return preset;
         }
virtual Modifier Loot.Api.Strategy.RollingStrategy.PreRollLine (ref List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Definition at line 127 of file RollingStrategy.cs.
         {
             return null;
         }
virtual List<Modifier> Loot.Api.Strategy.RollingStrategy.Roll (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented in Loot.RollingStrategies.SealingRollingStrategy.
Definition at line 54 of file RollingStrategy.cs.
References Loot.Api.Core.ModifierProperties.IsUnique, Loot.Api.Strategy.RollingStrategyProperties.MaxRollableLines, Loot.Api.Strategy.RollingStrategyProperties.MinRollableLines, Loot.Api.Core.ModifierContext.Pool, Loot.Api.Core.ModifierContext.PoolSet, Loot.Api.Core.Modifier.Properties, and Loot.Api.Core.Modifier.Type.
         {
             if (currentModifiers.Count >= properties.MaxRollableLines)
             {
                 return currentModifiers;
             }
             WeightedRandom<Modifier> wr = new WeightedRandom<Modifier>();
             if (modifierContext.Pool != null)
             {
                 foreach (var modifier in modifierContext.Pool.GetRollableModifiers(modifierContext))
                 {
                     wr.Add(modifier, modifier.Properties.RollChance);
                 }
             }
             else if (modifierContext.PoolSet != null && modifierContext.PoolSet.Any())
             {
                 var randomPool = modifierContext.PoolSet[Main.rand.Next(modifierContext.PoolSet.Count - 1)];
                 foreach (var modifier in randomPool.GetRollableModifiers(modifierContext))
                 {
                     wr.Add(modifier, modifier.Properties.RollChance);
                 }
             }
             else
             {
                 wr = GetRandomList(modifierContext, drawPool);
             }
             var list = currentModifiers;
             if (properties.MinRollableLines > properties.MaxRollableLines)
                 properties.MaxRollableLines = properties.MinRollableLines;
             // Up to n times, try rolling a mod
             for (int i = 0; i < properties.MaxRollableLines; ++i)
             {
                 int z = currentModifiers.Count;
                 Modifier line = null;
                 int tries = 0;
                 while (tries < 4 && currentModifiers.Count < properties.MaxRollableLines)
                 {
                     line = PreRollLine(ref currentModifiers, drawPool, modifierContext, properties) ?? RollLine(currentModifiers, drawPool, modifierContext, properties, wr);
                     if (line == null) continue;
                     currentModifiers.Add(line);
                     PostRollLine(ref currentModifiers, line, drawPool, modifierContext, properties);
                     if (currentModifiers.Count > z) break;
                 }
                 // If it is a unique modifier, remove it from the list to be rolled
                 if (line != null && line.Properties.IsUnique)
                 {
                     wr.elements.RemoveAll(x => x.Item1.Type == line.Type);
                     wr.needsRefresh = true;
                 }
             }
             return list;
         }
virtual Modifier Loot.Api.Strategy.RollingStrategy.RollLine (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties, WeightedRandom< Modifier > weightedRandom) virtual
Definition at line 132 of file RollingStrategy.cs.
References Loot.Api.Core.Modifier.Clone(), Loot.Api.Strategy.RollingStrategyProperties.MinRollableLines, Loot.Api.Core.Modifier.PostRoll(), Loot.Api.Core.Modifier.Roll(), and Loot.Api.Strategy.RollingStrategyProperties.RollNextChance.
         {
             // If there are no mods left, or we fail the roll, break.
             if (weightedRandom.elements.Count <= 0
                 || !_forceNextRoll
                 && currentModifiers.Count >= properties.MinRollableLines
                 && Main.rand.NextFloat() > properties.RollNextChance)
             {
                 return null;
             }
             _forceNextRoll = false;
             // Get a next weighted random mod
             // Clone the mod (new instance) and roll its properties, then roll it
             Modifier rolledModifier = (Modifier)weightedRandom.Get().Clone();
             RollProperties(rolledModifier, currentModifiers, modifierContext, properties);
             rolledModifier.Roll(modifierContext, currentModifiers);
             // If the mod deemed to be unable to be added,
             // Force that the next roll is successful
             // (no RNG on top of RNG)
             if (!rolledModifier.PostRoll(modifierContext, currentModifiers))
             {
                 _forceNextRoll = true;
                 return null;
             }
             return rolledModifier;
         }
void Loot.Api.Strategy.RollingStrategy.RollProperties (Modifier modifier, List< Modifier > modifiers, ModifierContext modifierContext, RollingStrategyProperties properties) private
Definition at line 168 of file RollingStrategy.cs.
References Loot.Api.Core.ModifierRarity.ExtraLuck, Loot.Api.Strategy.RollingStrategyProperties.ExtraLuck, Loot.Api.Core.ModifierRarity.ExtraMagnitudePower, Loot.Api.Delegators.ModifierDelegatorPlayer.GetEffect(), Loot.Api.Core.Modifier.GetModifierProperties(), Loot.Api.Delegators.ModifierDelegatorPlayer.GetPlayer(), Loot.Api.Core.ModifierContext.Item, Loot.Api.Strategy.RollingStrategyProperties.MagnitudePower, Loot.Api.Core.ModifierContext.Player, Loot.Api.Core.Modifier.Properties, Loot.Api.Core.ModifierContext.Rarity, and Loot.Api.Core.ModifierProperties.RollMagnitudeAndPower().
         {
             float luck = properties.ExtraLuck;
             float magnitudePower = properties.MagnitudePower;
             if (modifierContext.Player != null)
             {
                 luck += ModifierDelegatorPlayer.GetPlayer(modifierContext.Player).GetEffect<LuckEffect>().Luck;
             }
             if (modifierContext.Rarity != null)
             {
                 luck += modifierContext.Rarity.ExtraLuck;
                 magnitudePower += modifierContext.Rarity.ExtraMagnitudePower;
             }
             modifier.Properties =
                 modifier.GetModifierProperties(modifierContext.Item)
                     .Build()
                     .RollMagnitudeAndPower(magnitudePower, luck);
         }
Member Data Documentation
bool Loot.Api.Strategy.RollingStrategy._forceNextRoll protected
Definition at line 18 of file RollingStrategy.cs.
LootModItem Loot.Api.Strategy.RollingStrategy.modifierItem protected
Definition at line 21 of file RollingStrategy.cs.
RollingStrategyProperties Loot.Api.Strategy.RollingStrategy.properties protected
Definition at line 20 of file RollingStrategy.cs.