Even More Modifiers: Loot.ModifierItem Class Reference
Loot.ModifierItem Class Reference
Calls GlobalItem hooks on modifiers
Public Member Functions
override bool AltFunctionUse (Item item, Player player)
override bool CanEquipAccessory (Item item, Player player, int slot)
override bool CanHitNPC (Item item, Player player, NPC target)
override bool CanHitPvp (Item item, Player player, Player target)
override bool CanPickup (Item item, Player player)
override bool CanRightClick (Item item)
override bool CanUseItem (Item item, Player player)
override int ChoosePrefix (Item item, UnifiedRandom rand)
override bool ConsumeAmmo (Item item, Player player)
override bool ConsumeItem (Item item, Player player)
override Color GetAlpha (Item item, Color lightColor)
override void GetWeaponCrit (Item item, Player player, ref int crit)
override void GetWeaponDamage (Item item, Player player, ref int damage)
override void GetWeaponKnockback (Item item, Player player, ref float knockback)
override void GrabRange (Item item, Player player, ref int grabRange)
override bool GrabStyle (Item item, Player player)
override void HoldItem (Item item, Player player)
override bool HoldItemFrame (Item item, Player player)
override void HoldStyle (Item item, Player player)
override void HorizontalWingSpeeds (Item item, Player player, ref float speed, ref float acceleration)
override bool ItemSpace (Item item, Player player)
override void MeleeEffects (Item item, Player player, Rectangle hitbox)
override float MeleeSpeedMultiplier (Item item, Player player)
override void ModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit)
override void ModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit)
override bool NewPreReforge (Item item)
override void OnCraft (Item item, Recipe recipe)
override void OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit)
override void OnHitPvp (Item item, Player player, Player target, int damage, bool crit)
override bool OnPickup (Item item, Player player)
override void PickAmmo (Item item, Player player, ref int type, ref float speed, ref int damage, ref float knockback)
override void PostDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
override void PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI)
override void PostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines)
override void PostDrawTooltipLine (Item item, DrawableTooltipLine line)
override void PostReforge (Item item)
override void PostUpdate (Item item)
override bool PreDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
override bool PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
override bool PreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y)
override bool PreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset)
override bool ReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount)
override void RightClick (Item item, Player player)
override void SetDefaults (Item item)
override bool Shoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
override void Update (Item item, ref float gravity, ref float maxFallSpeed)
override void UpdateAccessory (Item item, Player player, bool hideVisual)
override void UpdateEquip (Item item, Player player)
override void UpdateInventory (Item item, Player player)
override bool UseItem (Item item, Player player)
override bool UseItemFrame (Item item, Player player)
override void UseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox)
override void UseStyle (Item item, Player player)
override float UseTimeMultiplier (Item item, Player player)
override void VerticalWingSpeeds (Item item, Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend)
Public Attributes
override bool CloneNewInstances => false
override bool InstancePerEntity => false
Private Member Functions
ActivatedModifierItem MItem (Item item)
Detailed Description
Calls GlobalItem hooks on modifiers
Definition at line 72 of file ModifierItem.cs.
Member Function Documentation
override bool Loot.ModifierItem.AltFunctionUse (Item item, Player player)
Definition at line 78 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.AltFunctionUse(item, player);
             }
             bool b = base.AltFunctionUse(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.AltFunctionUse(item, player);
             }
             return b;
         }
override bool Loot.ModifierItem.CanEquipAccessory (Item item, Player player, int slot)
Definition at line 95 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanEquipAccessory(item, player, slot);
             }
             bool b = base.CanEquipAccessory(item, player, slot);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanEquipAccessory(item, player, slot);
             }
             return b;
         }
override bool Loot.ModifierItem.CanHitNPC (Item item, Player player, NPC target)
Definition at line 112 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanHitNPC(item, player, target);
             }
             bool? b = base.CanHitNPC(item, player, target);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanHitNPC(item, player, target);
             }
             return b;
         }
override bool Loot.ModifierItem.CanHitPvp (Item item, Player player, Player target)
Definition at line 129 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanHitPvp(item, player, target);
             }
             bool b = base.CanHitPvp(item, player, target);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanHitPvp(item, player, target);
             }
             return b;
         }
override bool Loot.ModifierItem.CanPickup (Item item, Player player)
Definition at line 146 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanPickup(item, player);
             }
             bool b = base.CanPickup(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanPickup(item, player);
             }
             return b;
         }
override bool Loot.ModifierItem.CanRightClick (Item item)
Definition at line 163 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanRightClick(item);
             }
             bool b = base.CanRightClick(item);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanRightClick(item);
             }
             return b;
         }
override bool Loot.ModifierItem.CanUseItem (Item item, Player player)
Definition at line 180 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.CanUseItem(item, player);
             }
             bool b = base.CanUseItem(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.CanUseItem(item, player);
             }
             return b;
         }
override int Loot.ModifierItem.ChoosePrefix (Item item, UnifiedRandom rand)
Definition at line 197 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.ChoosePrefix(item, rand);
             }
             int p = base.ChoosePrefix(item, rand);
             if (p != -1)
             {
                 return p;
             }
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 p = m.ChoosePrefix(item, rand);
                 // TODO which modifier takes precedence ?
                 if (p != -1)
                 {
                     return p;
                 }
             }
             return -1;
         }
override bool Loot.ModifierItem.ConsumeAmmo (Item item, Player player)
Definition at line 223 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.ConsumeAmmo(item, player);
             }
             bool b = base.ConsumeAmmo(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.ConsumeAmmo(item, player);
             }
             return b;
         }
override bool Loot.ModifierItem.ConsumeItem (Item item, Player player)
Definition at line 240 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.ConsumeItem(item, player);
             }
             bool b = base.ConsumeItem(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.ConsumeItem(item, player);
             }
             return b;
         }
override Color Loot.ModifierItem.GetAlpha (Item item, Color lightColor)
Definition at line 257 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.GetAlpha(item, lightColor);
             }
             Color? a = base.GetAlpha(item, lightColor);
             if (a.HasValue)
             {
                 return a;
             }
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 a = m.GetAlpha(item, lightColor);
                 // TODO which modifier takes precedence ?
                 if (a.HasValue)
                 {
                     return a;
                 }
             }
             return null;
         }
override void Loot.ModifierItem.GetWeaponCrit (Item item, Player player, ref int crit)
Definition at line 283 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.GetWeaponCrit(item, player, ref crit);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.GetWeaponCrit(item, player, ref crit);
             }
         }
override void Loot.ModifierItem.GetWeaponDamage (Item item, Player player, ref int damage)
Definition at line 298 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.GetWeaponDamage(item, player, ref damage);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.GetWeaponDamage(item, player, ref damage);
             }
         }
override void Loot.ModifierItem.GetWeaponKnockback (Item item, Player player, ref float knockback)
Definition at line 313 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.GetWeaponKnockback(item, player, ref knockback);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.GetWeaponKnockback(item, player, ref knockback);
             }
         }
override void Loot.ModifierItem.GrabRange (Item item, Player player, ref int grabRange)
Definition at line 328 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.GrabRange(item, player, ref grabRange);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.GrabRange(item, player, ref grabRange);
             }
         }
override bool Loot.ModifierItem.GrabStyle (Item item, Player player)
Definition at line 343 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.GrabStyle(item, player);
             }
             bool b = base.GrabStyle(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.GrabStyle(item, player);
             }
             return b;
         }
override void Loot.ModifierItem.HoldItem (Item item, Player player)
Definition at line 360 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.HoldItem(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.HoldItem(item, player);
             }
         }
override bool Loot.ModifierItem.HoldItemFrame (Item item, Player player)
Definition at line 375 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.HoldItemFrame(item, player);
             }
             bool b = base.HoldItemFrame(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.HoldItemFrame(item, player);
             }
             return b;
         }
override void Loot.ModifierItem.HoldStyle (Item item, Player player)
Definition at line 392 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.HoldStyle(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.HoldStyle(item, player);
             }
         }
override void Loot.ModifierItem.HorizontalWingSpeeds (Item item, Player player, ref float speed, ref float acceleration)
Definition at line 407 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.HorizontalWingSpeeds(item, player, ref speed, ref acceleration);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.HorizontalWingSpeeds(item, player, ref speed, ref acceleration);
             }
         }
override bool Loot.ModifierItem.ItemSpace (Item item, Player player)
Definition at line 422 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.ItemSpace(item, player);
             }
             bool b = base.ItemSpace(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.ItemSpace(item, player);
             }
             return b;
         }
override void Loot.ModifierItem.MeleeEffects (Item item, Player player, Rectangle hitbox)
Definition at line 439 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.MeleeEffects(item, player, hitbox);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.MeleeEffects(item, player, hitbox);
             }
         }
override float Loot.ModifierItem.MeleeSpeedMultiplier (Item item, Player player)
Definition at line 454 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.MeleeSpeedMultiplier(item, player);
             }
             float mult = base.MeleeSpeedMultiplier(item, player);
             if (mult != 1f)
             {
                 return mult;
             }
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 mult = m.MeleeSpeedMultiplier(item, player);
                 // TODO which modifier takes precedence ?
                 if (mult != 1f)
                 {
                     return mult;
                 }
             }
             return 1f;
         }
ActivatedModifierItem Loot.ModifierItem.MItem (Item item) private
override void Loot.ModifierItem.ModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit)
Definition at line 480 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.ModifyHitNPC(item, player, target, ref damage, ref knockBack, ref crit);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.ModifyHitNPC(item, player, target, ref damage, ref knockBack, ref crit);
             }
         }
override void Loot.ModifierItem.ModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit)
Definition at line 495 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.ModifyHitPvp(item, player, target, ref damage, ref crit);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.ModifyHitPvp(item, player, target, ref damage, ref crit);
             }
         }
override bool Loot.ModifierItem.NewPreReforge (Item item)
Definition at line 542 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.NewPreReforge(item);
             }
             bool b = base.NewPreReforge(item);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.NewPreReforge(item);
             }
             return b;
         }
override void Loot.ModifierItem.OnCraft (Item item, Recipe recipe)
Definition at line 559 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.OnCraft(item, recipe);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.OnCraft(item, recipe);
             }
         }
override void Loot.ModifierItem.OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit)
Definition at line 574 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.OnHitNPC(item, player, target, damage, knockBack, crit);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.OnHitNPC(item, player, target, damage, knockBack, crit);
             }
         }
override void Loot.ModifierItem.OnHitPvp (Item item, Player player, Player target, int damage, bool crit)
Definition at line 589 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.OnHitPvp(item, player, target, damage, crit);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.OnHitPvp(item, player, target, damage, crit);
             }
         }
override bool Loot.ModifierItem.OnPickup (Item item, Player player)
Definition at line 604 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.OnPickup(item, player);
             }
             bool b = base.OnPickup(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.OnPickup(item, player);
             }
             return b;
         }
override void Loot.ModifierItem.PickAmmo (Item item, Player player, ref int type, ref float speed, ref int damage, ref float knockback)
Definition at line 621 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PickAmmo(item, player, ref type, ref speed, ref damage, ref knockback);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PickAmmo(item, player, ref type, ref speed, ref damage, ref knockback);
             }
         }
override void Loot.ModifierItem.PostDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
Definition at line 636 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             }
         }
override void Loot.ModifierItem.PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI)
Definition at line 651 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostDrawInWorld(item, spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostDrawInWorld(item, spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI);
             }
         }
override void Loot.ModifierItem.PostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines)
Definition at line 666 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostDrawTooltip(item, lines);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostDrawTooltip(item, lines);
             }
         }
override void Loot.ModifierItem.PostDrawTooltipLine (Item item, DrawableTooltipLine line)
Definition at line 681 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostDrawTooltipLine(item, line);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostDrawTooltipLine(item, line);
             }
         }
override void Loot.ModifierItem.PostReforge (Item item)
Definition at line 696 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostReforge(item);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostReforge(item);
             }
         }
override void Loot.ModifierItem.PostUpdate (Item item)
Definition at line 711 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.PostUpdate(item);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.PostUpdate(item);
             }
         }
override bool Loot.ModifierItem.PreDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
Definition at line 726 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.PreDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             }
             bool b = base.PreDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.PreDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             }
             return b;
         }
override bool Loot.ModifierItem.PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
Definition at line 743 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.PreDrawInWorld(item, spriteBatch, lightColor, alphaColor, ref rotation, ref scale, whoAmI);
             }
             bool b = base.PreDrawInWorld(item, spriteBatch, lightColor, alphaColor, ref rotation, ref scale, whoAmI);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.PreDrawInWorld(item, spriteBatch, lightColor, alphaColor, ref rotation, ref scale, whoAmI);
             }
             return b;
         }
override bool Loot.ModifierItem.PreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y)
Definition at line 760 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.PreDrawTooltip(item, lines, ref x, ref y);
             }
             bool b = base.PreDrawTooltip(item, lines, ref x, ref y);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.PreDrawTooltip(item, lines, ref x, ref y);
             }
             return b;
         }
override bool Loot.ModifierItem.PreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset)
Definition at line 777 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.PreDrawTooltipLine(item, line, ref yOffset);
             }
             bool b = base.PreDrawTooltipLine(item, line, ref yOffset);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.PreDrawTooltipLine(item, line, ref yOffset);
             }
             return b;
         }
override bool Loot.ModifierItem.ReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount)
Definition at line 794 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.ReforgePrice(item, ref reforgePrice, ref canApplyDiscount);
             }
             bool b = base.ReforgePrice(item, ref reforgePrice, ref canApplyDiscount);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.ReforgePrice(item, ref reforgePrice, ref canApplyDiscount);
             }
             return b;
         }
override void Loot.ModifierItem.RightClick (Item item, Player player)
Definition at line 811 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.RightClick(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.RightClick(item, player);
             }
         }
override void Loot.ModifierItem.SetDefaults (Item item)
Definition at line 826 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), Loot.ActivatedModifierItem.IsVanityActivated, and Loot.Core.Modifier.SetDefaults().
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.SetDefaults(item);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.SetDefaults(item);
             }
         }
override bool Loot.ModifierItem.Shoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
Definition at line 841 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.Shoot(item, player, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
             };
             bool b = base.Shoot(item, player, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.Shoot(item, player, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
             }
             return b;
         }
override void Loot.ModifierItem.Update (Item item, ref float gravity, ref float maxFallSpeed)
Definition at line 858 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.Update(item, ref gravity, ref maxFallSpeed);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.Update(item, ref gravity, ref maxFallSpeed);
             }
         }
override void Loot.ModifierItem.UpdateAccessory (Item item, Player player, bool hideVisual)
Definition at line 873 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.UpdateAccessory(item, player, hideVisual);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.UpdateAccessory(item, player, hideVisual);
             }
         }
override void Loot.ModifierItem.UpdateEquip (Item item, Player player)
Definition at line 888 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.UpdateEquip(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.UpdateEquip(item, player);
             }
         }
override void Loot.ModifierItem.UpdateInventory (Item item, Player player)
Definition at line 903 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.UpdateInventory(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.UpdateInventory(item, player);
             }
         }
override bool Loot.ModifierItem.UseItem (Item item, Player player)
Definition at line 918 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.UseItem(item, player);
             }
             bool b = base.UseItem(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.UseItem(item, player);
             }
             return b;
         }
override bool Loot.ModifierItem.UseItemFrame (Item item, Player player)
Definition at line 935 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.UseItemFrame(item, player);
             }
             bool b = base.UseItemFrame(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 b &= m.UseItemFrame(item, player);
             }
             return b;
         }
override void Loot.ModifierItem.UseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox)
Definition at line 952 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.UseItemHitbox(item, player, ref hitbox, ref noHitbox);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.UseItemHitbox(item, player, ref hitbox, ref noHitbox);
             }
         }
override void Loot.ModifierItem.UseStyle (Item item, Player player)
Definition at line 967 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.UseStyle(item, player);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.UseStyle(item, player);
             }
         }
override float Loot.ModifierItem.UseTimeMultiplier (Item item, Player player)
Definition at line 982 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return base.UseTimeMultiplier(item, player);
             }
             float f = base.UseTimeMultiplier(item, player);
             if (f != 1f)
             {
                 return f;
             }
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 f = m.UseTimeMultiplier(item, player);
                 // TODO which modifier takes precedence ?
                 if (f != 1f)
                 {
                     return f;
                 }
             }
             return f;
         }
override void Loot.ModifierItem.VerticalWingSpeeds (Item item, Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend)
Definition at line 1008 of file ModifierItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.ActivatedModifierItem.IsVanityActivated.
         {
             if (MItem(item).IsVanityActivated)
             {
                 return;
             }
             base.VerticalWingSpeeds(item, player, ref ascentWhenFalling, ref ascentWhenRising, ref maxCanAscendMultiplier, ref maxAscentMultiplier, ref constantAscend);
             foreach (Modifier m in EMMItem.GetActivePool(item))
             {
                 m.VerticalWingSpeeds(item, player, ref ascentWhenFalling, ref ascentWhenRising, ref maxCanAscendMultiplier, ref maxAscentMultiplier, ref constantAscend);
             }
         }
Member Data Documentation
override bool Loot.ModifierItem.CloneNewInstances => false
Definition at line 75 of file ModifierItem.cs.
override bool Loot.ModifierItem.InstancePerEntity => false
Definition at line 74 of file ModifierItem.cs.