Even More Modifiers: Loot.EMMItem Class Reference
Loot.EMMItem Class Reference
Defines an item that may be modified by modifiers from mods
Public Member Functions
override GlobalItem Clone (Item item, Item itemClone)
override void Load (Item item, TagCompound tag)
override void ModifyTooltips (Item item, List< TooltipLine > tooltips)
Will modify vanilla tooltips to add additional information for the affected item's modifiers
override bool NeedsSaving (Item item)
override void NetReceive (Item item, BinaryReader reader)
override void NetSend (Item item, BinaryWriter writer)
override void OnCraft (Item item, Recipe recipe)
override bool OnPickup (Item item, Player player)
override void PostReforge (Item item)
ModifierPool RollNewPool (ModifierContext ctx, RollingStrategyProperties rollingStrategyProperties=null)
Attempts to roll new modifiers Has a set chance to hit a predefined pool of modifiers
override TagCompound Save (Item item)
Static Public Member Functions
static IEnumerable< Modifier > GetActivePool (Item item)
static EMMItem GetItemInfo (Item item)
Public Attributes
override bool CloneNewInstances => true
bool HasRolled
override bool InstancePerEntity => true
bool JustTinkerModified
ModifierPool ModifierPool
ModifierRarity ModifierRarity
bool SealedModifiers
bool SlottedInCubeUI
Private Member Functions
string GetPrefixNormString (float cpStat, float rStat, ref double num, ref Color?color)
void InvalidateRolls ()
Private Attributes
const int SAVE_VERSION = 3
Detailed Description
Defines an item that may be modified by modifiers from mods
Definition at line 22 of file EMMItem.cs.
Member Function Documentation
override GlobalItem Loot.EMMItem.Clone (Item item, Item itemClone)
Definition at line 157 of file EMMItem.cs.
References Loot.EMMItem.Clone(), Loot.EMMItem.ModifierPool, and Loot.EMMItem.ModifierRarity.
Referenced by Loot.EMMItem.Clone().
         {
             EMMItem clone = (EMMItem)base.Clone(item, itemClone);
             clone.ModifierRarity = (ModifierRarity)ModifierRarity?.Clone() ?? mod.GetNullModifierRarity();
             clone.ModifierPool = (ModifierPool)ModifierPool?.Clone() ?? mod.GetNullModifierPool();
             // there is no need to apply here, we already cloned the item which stats are already modified by its pool
             return clone;
         }
static IEnumerable<Modifier> Loot.EMMItem.GetActivePool (Item item) static
Referenced by Loot.Core.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.UI.Sealing.CubeSealUI.TrySealingSlottedItem(), Loot.Core.Caching.ModifierCachePlayer.UpdateCheatSheetCache(), Loot.Core.Graphics.ShaderGlobalItem.UpdateEntities(), Loot.Core.Graphics.GlowmaskGlobalItem.UpdateEntities(), Loot.Core.Caching.ModifierCachePlayer.UpdateEquipsCache(), Loot.Core.Caching.ModifierCachePlayer.UpdateHeldItemCache(), Loot.UI.Rerolling.CubeRerollUI.UpdateModifierLines(), Loot.Core.Caching.ModifierCachePlayer.UpdateMouseItemCache(), and Loot.Core.Caching.ModifierCachePlayer.UpdateVanityCache().
static EMMItem Loot.EMMItem.GetItemInfo (Item item) static
Referenced by Loot.ArmorItemHack.ChoosePrefix(), Loot.Core.Cubes.PoorCube.GetRollingStrategy(), Loot.Core.System.Strategy.NormalRollingStrategy.InitFields(), Loot.UI.Sealing.CubeSealUI.IsSlottedItemInCubeUI(), Loot.Core.System.Modifier.ModifierPool.Load(), Loot.UI.Rerolling.CubeRerollUI.MatchesRerollRequirements(), Loot.EMMItem.ModifyTooltips(), Loot.EMMWorld.ModifyWorldGenTasks(), Loot.EMMItem.OnCraft(), Loot.EMMItem.OnPickup(), Loot.UI.Rerolling.CubeRerollUI.OnRerollClick(), Loot.UI.Rerolling.UIRerollItemPanel.PostOnClick(), Loot.UI.Sealing.UISealItemPanel.PostOnClick(), Loot.ArmorItemHack.PostReforge(), Loot.EMMPlayer.PostUpdate(), Loot.UI.Rerolling.UIRerollItemPanel.PreOnClick(), Loot.UI.Sealing.UISealItemPanel.PreOnClick(), Loot.UI.Rerolling.CubeRerollUI.RerollModifierPool(), Loot.UI.Rerolling.CubeRerollUI.ToggleUI(), Loot.UI.Sealing.CubeSealUI.TrySealingSlottedItem(), and Loot.UI.Rerolling.UIRerollItemPanel.UIRerollItemPanel().
string Loot.EMMItem.GetPrefixNormString (float cpStat, float rStat, ref double num, ref Color? color) private
Definition at line 318 of file EMMItem.cs.
Referenced by Loot.EMMItem.ModifyTooltips().
         {
             //float num19 = (float)Main.mouseTextColor / 255f;
             //patch file: num20
             float defColorVal = Main.mouseTextColor / 255f;
             int alphaColor = Main.mouseTextColor;
             if (cpStat == 0f && rStat != 0f)
             {
                 num = 1;
                 if (rStat > 0f)
                 {
                     color = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                     return "+" + rStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
                 }
                 color = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                 return rStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
             }
             double diffStat = rStat - cpStat;
             diffStat = diffStat / cpStat * 100.0;
             diffStat = Math.Round(diffStat);
             num = diffStat;
             // for some reason - is handled automatically, but + is not
             if (diffStat > 0.0)
             {
                 color = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                 return "+" + diffStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
             }
             color = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
             return diffStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
                                                                     //if (num12 < 0.0)
                                                                     //{
                                                                     //  array3[num4] = true;
                                                                     //}
         }
void Loot.EMMItem.InvalidateRolls () private
Definition at line 41 of file EMMItem.cs.
Referenced by Loot.EMMItem.Load(), and Loot.EMMItem.RollNewPool().
         {
             ModifierRarity = mod.GetNullModifierRarity();
             ModifierPool = mod.GetNullModifierPool();
         }
override void Loot.EMMItem.Load (Item item, TagCompound tag)
Definition at line 166 of file EMMItem.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, and Loot.EMMItem.InvalidateRolls().
         {
             // enforce illegitimate rolls to go away (needed for earliest versions saves)
             if (!item.IsModifierRollableItem())
             {
                 InvalidateRolls();
             }
             else
             {
                 // SaveVersion >= 2
                 if (tag.ContainsKey("SaveVersion"))
                 {
                     int saveVersion = tag.GetInt("SaveVersion");
                     SealedModifiers = tag.GetBool("SealedModifiers");
                     HasRolled = tag.GetBool("HasRolled");
                     if (saveVersion < 3)
                     {
                         // Rarity should be set by pool loading
                         ModifierPool = ModifierPool._Load(item, tag);
                     }
                     else
                     {
                         ModifierRarity = ModifierRarity._Load(item, tag.GetCompound("ModifierRarity"));
                         ModifierPool = ModifierPool._Load(item, tag.GetCompound("ModifierPool"));
                     }
                 }
                 else // SaveVersion 1
                 {
                     HasRolled = tag.GetBool("HasRolled");
                     ModifierPool = ModifierPool._Load(item, tag);
                 }
                 if (ModifierPool != null)
                 {
                     // enforce illegitimate rolls to go away
                     if (ModifierPool.ActiveModifiers == null || ModifierPool.ActiveModifiers.Length <= 0)
                     {
                         InvalidateRolls();
                     }
                     else
                     {
                         ModifierPool.ApplyModifiers(item);
                     }
                 }
             }
         }
override void Loot.EMMItem.ModifyTooltips (Item item, List< TooltipLine > tooltips)
Will modify vanilla tooltips to add additional information for the affected item's modifiers
Definition at line 361 of file EMMItem.cs.
References Loot.Core.System.Modifier.ModifierRarity.Color, Loot.EMMItem.GetItemInfo(), Loot.EMMItem.GetPrefixNormString(), Loot.ActivatedModifierItem.Item(), Loot.Core.System.Modifier.ModifierRarity.ItemPrefix, Loot.Core.System.Modifier.ModifierRarity.ItemSuffix, Loot.EMMItem.ModifierPool, Loot.Core.System.Modifier.ModifierRarity.OverrideNameColor, and Loot.ActivatedModifierItem.ShouldBeIgnored().
         {
             var pool = GetItemInfo(item).ModifierPool;
             if (pool != null && pool.ActiveModifiers.Length > 0)
             {
                 // the following part, recalculate the vanilla prefix tooltips
                 // this is because our mods modify the stats, which was never intended by vanilla, causing the differences to be innacurate and bugged
                 // RECALC START
                 var vanillaTooltips = tooltips.Where(x => x.mod.Equals("Terraria")).ToArray();
                 var baseItem = new Item();
                 baseItem.netDefaults(item.netID);
                 // the item with just the modifiers applied
                 // var poolItem = baseItem.CloneWithModdedDataFrom(item);
                 // GetItemInfo(poolItem)?.ModifierPool.ApplyModifiers(poolItem);
                 // the item with just the prefix applied
                 var prefixItem = baseItem.Clone();
                 prefixItem.Prefix(item.prefix);
                 try
                 {
                     foreach (var tooltipLine in vanillaTooltips)
                     {
                         double outNumber = 0d;
                         string newTooltipLine = tooltipLine.text;
                         Color? newColor = tooltipLine.overrideColor;
                         string tooltipEndText =
                             new string(tooltipLine.text
                                 .Reverse()
                                 .TakeWhile(x => !char.IsDigit(x))
                                 .Reverse()
                                 .ToArray());
                         //private string[] _prefixTooltipLines = {
                         //      "PrefixDamage", "PrefixSpeed", "PrefixCritChance", "PrefixUseMana", "PrefixSize",
                         //      "PrefixShootSpeed", "PrefixKnockback", "PrefixAccDefense", "PrefixAccMaxMana",
                         //      "PrefixAccCritChance", "PrefixAccDamage", "PrefixAccMoveSpeed", "PrefixAccMeleeSpeed"
                         //  };
                         if (tooltipLine.Name.Equals("PrefixDamage"))
{
                             newTooltipLine = baseItem.damage > 0
                                 ? GetPrefixNormString(baseItem.damage, prefixItem.damage, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.damage, baseItem.damage, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixSpeed"))
{
                             newTooltipLine = baseItem.useAnimation <= 0
                                 ? GetPrefixNormString(baseItem.useAnimation, prefixItem.useAnimation, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.useAnimation, baseItem.useAnimation, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixCritChance"))
{
                             outNumber = prefixItem.crit - baseItem.crit;
                             float defColorVal = Main.mouseTextColor / 255f;
                             int alphaColor = Main.mouseTextColor;
                             newTooltipLine = "";
                             if (outNumber >= 0)
{
                                 newTooltipLine += "+";
                                 newColor = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                             else
{
                                 newColor = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                             newTooltipLine += outNumber.ToString(CultureInfo.InvariantCulture);
                         }
                         else if (tooltipLine.Name.Equals("PrefixUseMana"))
{
                             if (baseItem.mana != 0)
{
                                 float defColorVal = Main.mouseTextColor / 255f;
                                 int alphaColor = Main.mouseTextColor;
                                 newTooltipLine = GetPrefixNormString(baseItem.mana, prefixItem.mana, ref outNumber, ref newColor);
                                 newColor = prefixItem.mana < baseItem.mana
                                     ? new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor)
                                     : new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                         }
                         else if (tooltipLine.Name.Equals("PrefixSize"))
{
                             newTooltipLine = baseItem.scale > 0
                                 ? GetPrefixNormString(baseItem.scale, prefixItem.scale, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.scale, baseItem.scale, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixShootSpeed"))
{
                             newTooltipLine = baseItem.shootSpeed > 0
                                 ? GetPrefixNormString(baseItem.shootSpeed, prefixItem.shootSpeed, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.shootSpeed, baseItem.shootSpeed, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixKnockback"))
{
                             newTooltipLine = baseItem.knockBack > 0
                                 ? GetPrefixNormString(baseItem.knockBack, prefixItem.knockBack, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.knockBack, baseItem.knockBack, ref outNumber, ref newColor);
                         }
                         else
{
                             continue;
                         }
                         int ttlI = tooltips.FindIndex(x => x.mod.Equals(tooltipLine.mod) && x.Name.Equals(tooltipLine.Name));
                         if (ttlI == -1)
{
                             continue;
                         }
                         if (outNumber == 0d)
{
                             tooltips.RemoveAt(ttlI);
                         }
                         else
{
                             tooltips[ttlI].text = $"{newTooltipLine}{tooltipEndText}";
                             tooltips[ttlI].overrideColor = newColor;
                         }
                     }
                 }
                 catch (Exception e)
                 {
                     Loot.Logger.Error(
                         $"A problem occurred during modification of the item's tooltip." +
                         $"\nItem in question: {item.AffixName()}",
                         e);
                 }
                 // RECALC END
                 // Modifies the tooltips, to insert generic mods data
                 int i = tooltips.FindIndex(x => x.mod == "Terraria" && x.Name == "ItemName");
                 if (i != -1)
                 {
                     var namelayer = tooltips[i];
                     if (ModifierRarity.ItemPrefix != null)
                     {
                         namelayer.text = $"{ModifierRarity.ItemPrefix} {namelayer.text}";
                     }
                     if (ModifierRarity.ItemSuffix != null)
                     {
                         namelayer.text = $"{namelayer.text} {ModifierRarity.ItemSuffix}";
                     }
                     if (ModifierRarity.OverrideNameColor != null)
                     {
                         namelayer.overrideColor = ModifierRarity.OverrideNameColor;
                     }
                     tooltips[i] = namelayer;
                 }
                 // Insert modifier rarity
                 ActivatedModifierItem activatedModifierItem = ActivatedModifierItem.Item(item);
                 bool isVanityIgnored = activatedModifierItem.ShouldBeIgnored(item, Main.LocalPlayer);
                 Color? inactiveColor = isVanityIgnored ? (Color?)Color.DarkSlateGray : null;
                 i = tooltips.Count;
                 tooltips.Insert(i, new TooltipLine(mod, "Loot: Modifier:Rarity", $"[{ModifierRarity.RarityName}]{(isVanityIgnored ? " [IGNORED]" : "")}")
                 {
                     overrideColor = inactiveColor ?? ModifierRarity.Color * Main.inventoryScale
                 });
                 foreach (var modifier in pool.ActiveModifiers)
                 {
                     foreach (var tt in modifier.GetTooltip().Build())
                     {
                         tooltips.Insert(++i, new TooltipLine(mod, $"Loot: Modifier:Line:{i}", $"{modifier.GetFormattedUniqueName()} {tt.Text}".TrimStart())
{
                             overrideColor = inactiveColor ?? (tt.Color ?? Color.White) * Main.inventoryScale
                         });
                     }
                 }
                 if (SealedModifiers)
                 {
                     var ttl = new TooltipLine(mod, "Loot: Modifier:Sealed", "Modifiers cannot be changed")
                     {
                         overrideColor = inactiveColor ?? Color.Cyan
                     };
                     tooltips.Insert(++i, ttl);
                 }
                 foreach (var e in pool.ActiveModifiers)
                 {
                     e.ModifyTooltips(item, tooltips);
                 }
             }
         }
override bool Loot.EMMItem.NeedsSaving (Item item)
Referenced by Loot.EMMItem.Save().
override void Loot.EMMItem.NetReceive (Item item, BinaryReader reader)
Definition at line 231 of file EMMItem.cs.
         {
             if (reader.ReadBoolean())
             {
                 ModifierRarity = ModifierRarity._NetReceive(item, reader); // Since SaveVersion 3
                 ModifierPool = ModifierPool._NetReceive(item, reader);
             }
             HasRolled = reader.ReadBoolean();
             SealedModifiers = reader.ReadBoolean(); // Since SaveVersion 2
             ModifierPool?.ApplyModifiers(item);
             JustTinkerModified = reader.ReadBoolean();
         }
override void Loot.EMMItem.NetSend (Item item, BinaryWriter writer)
Definition at line 247 of file EMMItem.cs.
         {
             bool hasPool = ModifierPool != null;
             writer.Write(hasPool);
             if (hasPool)
             {
                 ModifierRarity._NetSend(ModifierRarity, item, writer); // Since SaveVersion 3
                 ModifierPool._NetSend(ModifierPool, item, writer);
             }
             writer.Write(HasRolled);
             writer.Write(SealedModifiers); // Since SaveVersion 2
             writer.Write(JustTinkerModified);
         }
override void Loot.EMMItem.OnCraft (Item item, Recipe recipe)
Definition at line 263 of file EMMItem.cs.
References Loot.EMMItem.GetItemInfo(), Loot.EMMItem.ModifierPool, and Loot.EMMItem.RollNewPool().
         {
             ModifierPool pool = GetItemInfo(item).ModifierPool;
             if (!HasRolled && pool == null)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnCraft,
                     Item = item,
                     Player = Main.LocalPlayer,
                     Recipe = recipe
                 };
                 pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
             base.OnCraft(item, recipe);
         }
override bool Loot.EMMItem.OnPickup (Item item, Player player)
Definition at line 283 of file EMMItem.cs.
References Loot.EMMItem.GetItemInfo(), Loot.EMMItem.ModifierPool, and Loot.EMMItem.RollNewPool().
         {
             ModifierPool pool = GetItemInfo(item).ModifierPool;
             if (!HasRolled && pool == null)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnPickup,
                     Item = item,
                     Player = player
                 };
                 pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
             return base.OnPickup(item, player);
         }
override void Loot.EMMItem.PostReforge (Item item)
Definition at line 302 of file EMMItem.cs.
References Loot.EMMItem.RollNewPool().
         {
             if (!SealedModifiers)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnReforge,
                     Item = item,
                     Player = Main.LocalPlayer
                 };
                 ModifierPool pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
         }
ModifierPool Loot.EMMItem.RollNewPool (ModifierContext ctx, RollingStrategyProperties rollingStrategyProperties = null)
Attempts to roll new modifiers Has a set chance to hit a predefined pool of modifiers
Definition at line 51 of file EMMItem.cs.
References Loot.Core.System.Modifier.ModifierRarity.Downgrade, Loot.Core.System.Modifier.ModifierRarity.DowngradeChance, Loot.Ext.ModUtils.GetModifierRarity(), Loot.EMMItem.InvalidateRolls(), Loot.Core.System.Modifier.ModifierContext.Item, Loot.Core.System.Loaders.ContentLoader.ModifierPool, Loot.EMMItem.ModifierPool, Loot.EMMItem.ModifierRarity, Loot.Core.System.Modifier.ModifierContext.Rarity, Loot.Core.System.Strategy.IRollingStrategy< in in T >.Roll(), Loot.Core.System.Modifier.ModifierContext.Strategy, Loot.Core.System.Modifier.ModifierRarity.Type, Loot.Core.System.Modifier.ModifierRarity.Upgrade, and Loot.Core.System.Modifier.ModifierRarity.UpgradeChance.
Referenced by Loot.EMMWorld.ModifyWorldGenTasks(), Loot.EMMItem.OnCraft(), Loot.EMMItem.OnPickup(), Loot.EMMItem.PostReforge(), and Loot.UI.Rerolling.CubeRerollUI.RerollModifierPool().
         {
             if (rollingStrategyProperties == null)
             {
                 rollingStrategyProperties = new RollingStrategyProperties();
             }
             HasRolled = true;
             bool noForce = true;
             // Custom rarity provided
             if (rollingStrategyProperties.OverrideRollModifierRarity != null)
             {
                 ModifierRarity = rollingStrategyProperties.OverrideRollModifierRarity.Invoke();
             }
             else if (rollingStrategyProperties.ForceModifierRarity != null)
             {
                 ModifierRarity = rollingStrategyProperties.ForceModifierRarity;
             }
             else if (ModifierRarity == null || ModifierRarity.Type == 0)
             {
                 ModifierRarity = mod.GetModifierRarity<CommonRarity>();
             }
             ctx.Rarity = ModifierRarity;
             // Upgrade rarity
             if (rollingStrategyProperties.CanUpgradeRarity(ctx)
                 && Main.rand.NextFloat() <= (ModifierRarity.UpgradeChance ?? 0f))
             {
                 var newRarity = ModifierRarity.Upgrade;
                 var newFromLoader = ModUtils.GetModifierRarity(newRarity);
                 if (newRarity != null && newFromLoader != null)
                 {
                     ModifierRarity = newFromLoader;
                 }
             }
             // Downgrade rarity
             else if (rollingStrategyProperties.CanDowngradeRarity(ctx)
                     && Main.rand.NextFloat() <= (ModifierRarity.DowngradeChance ?? 0f))
             {
                 var newRarity = ModifierRarity.Downgrade;
                 var newFromLoader = ModUtils.GetModifierRarity(newRarity);
                 if (newRarity != null && newFromLoader != null)
                 {
                     ModifierRarity = newFromLoader;
                 }
             }
             ctx.Rarity = ModifierRarity;
             // Custom pool provided
             if (rollingStrategyProperties.OverrideRollModifierPool != null)
             {
                 ModifierPool = rollingStrategyProperties.OverrideRollModifierPool.Invoke();
                 noForce = !ModifierPool?._CanRoll(ctx) ?? true;
             }
             // No behavior provided
             if (noForce)
             {
                 // A pool is forced to roll
                 if (rollingStrategyProperties.ForceModifierPool != null)
                 {
                     ModifierPool = mod.GetModifierPool(rollingStrategyProperties.ForceModifierPool.GetType());
                     noForce = !ModifierPool?._CanRoll(ctx) ?? true;
                 }
                 // No pool forced to roll or it's not valid
                 if (noForce)
                 {
                     // Try rolling a predefined (weighted) pool
                     bool rollPredefinedPool = Main.rand.NextFloat() <= rollingStrategyProperties.RollPredefinedPoolChance;
                     noForce = !rollPredefinedPool;
                     if (rollPredefinedPool)
                     {
                         // GetWeightedPool already checks _CanRoll
                         ModifierPool = ContentLoader.ModifierPool.GetWeightedPool(ctx);
                         noForce = ModifierPool == null || !ModifierPool._CanRoll(ctx);
                     }
                     // Roll from all modifiers
                     if (noForce)
                     {
                         ModifierPool = mod.GetAllModifiersPool();
                         if (!ModifierPool._CanRoll(ctx))
{
                             InvalidateRolls();
                             return null;
                         }
                     }
                 }
             }
             // Attempt rolling modifiers
             if (!ctx.Strategy?.Roll(ctx, new RollingStrategyContext(ctx.Item, rollingStrategyProperties)) ?? true)
             {
                 InvalidateRolls();
             }
             ctx.Item.GetGlobalItem<ShaderGlobalItem>().NeedsUpdate = true;
             ctx.Item.GetGlobalItem<GlowmaskGlobalItem>().NeedsUpdate = true;
             return ModifierPool;
         }
override TagCompound Loot.EMMItem.Save (Item item)
Definition at line 213 of file EMMItem.cs.
References Loot.EMMItem.HasRolled, Loot.EMMItem.NeedsSaving(), Loot.Core.System.Modifier.ModifierRarity.Save(), and Loot.Core.System.Modifier.ModifierPool.Save().
         {
             TagCompound tag = new TagCompound
             {
                 // SaveVersion saved since SaveVersion 2, version 1 not present
                 {"SaveVersion", SAVE_VERSION},
                 {"SealedModifiers", SealedModifiers},
                 {"HasRolled", HasRolled},
                 {"ModifierRarity", ModifierRarity.Save(item, ModifierRarity)},
                 {"ModifierPool", ModifierPool.Save(item, ModifierPool)}
             };
             return tag;
         }
Member Data Documentation
override bool Loot.EMMItem.CloneNewInstances => true
Definition at line 30 of file EMMItem.cs.
bool Loot.EMMItem.HasRolled
Definition at line 34 of file EMMItem.cs.
Referenced by Loot.EMMWorld.ModifyWorldGenTasks(), and Loot.EMMItem.Save().
override bool Loot.EMMItem.InstancePerEntity => true
Definition at line 29 of file EMMItem.cs.
bool Loot.EMMItem.JustTinkerModified
Definition at line 38 of file EMMItem.cs.
Referenced by Loot.EMMPlayer.PostUpdate().
ModifierPool Loot.EMMItem.ModifierPool
Definition at line 33 of file EMMItem.cs.
Referenced by Loot.EMMItem.Clone(), Loot.EMMItem.ModifyTooltips(), Loot.EMMWorld.ModifyWorldGenTasks(), Loot.EMMItem.OnCraft(), Loot.EMMItem.OnPickup(), Loot.UI.Rerolling.CubeRerollUI.OnRerollClick(), Loot.Core.System.Strategy.NormalRollingStrategy.Roll(), and Loot.EMMItem.RollNewPool().
ModifierRarity Loot.EMMItem.ModifierRarity
Definition at line 32 of file EMMItem.cs.
Referenced by Loot.EMMItem.Clone(), Loot.Core.Cubes.PoorCube.GetRollingStrategy(), Loot.Core.System.Modifier.ModifierPool.Load(), and Loot.EMMItem.RollNewPool().
const int Loot.EMMItem.SAVE_VERSION = 3 private
Definition at line 24 of file EMMItem.cs.
bool Loot.EMMItem.SealedModifiers
Definition at line 35 of file EMMItem.cs.
Referenced by Loot.UI.Rerolling.CubeRerollUI.MatchesRerollRequirements(), Loot.UI.Sealing.CubeSealUI.TrySealingSlottedItem(), and Loot.UI.Rerolling.UIRerollItemPanel.UIRerollItemPanel().
bool Loot.EMMItem.SlottedInCubeUI
Definition at line 39 of file EMMItem.cs.
Referenced by Loot.UI.Sealing.CubeSealUI.IsSlottedItemInCubeUI(), Loot.UI.Rerolling.UIRerollItemPanel.PostOnClick(), Loot.UI.Sealing.UISealItemPanel.PostOnClick(), Loot.UI.Rerolling.UIRerollItemPanel.PreOnClick(), Loot.UI.Sealing.UISealItemPanel.PreOnClick(), and Loot.UI.Rerolling.CubeRerollUI.ToggleUI().