Even More Modifiers: Loot.LoadingFunneler Class Reference
Loot.LoadingFunneler Class Reference
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Static Public Member Functions
static void AddMod (Mod mod)
Static Private Member Functions
static void LoadMod ()
static void LoadModForClient ()
static void UnloadMod ()
static void UnloadStaticRefs ()
Detailed Description
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Definition at line 17 of file LoadingFunneler.cs.
Member Function Documentation
static void Loot.LoadingFunneler.AddMod (Mod mod) static
Definition at line 19 of file LoadingFunneler.cs.
References Loot.Core.System.Loaders.MainLoader.AddContent(), Loot.LoadingFunneler.LoadMod(), Loot.LoadingFunneler.LoadModForClient(), Loot.Core.System.Loaders.MainLoader.RegisterMod(), and Loot.LoadingFunneler.UnloadMod().
Referenced by Loot.LoadingFunneler.LoadMod().
         {
             MainLoader.RegisterMod(mod);
             MainLoader.AddContent(mod);
         }
static void Loot.LoadingFunneler.LoadMod () static private
Definition at line 50 of file LoadingFunneler.cs.
References Loot.LoadingFunneler.AddMod().
Referenced by Loot.LoadingFunneler.AddMod().
         {
             ModSupportTunneler.Init();
             ContentLoader.Initialize();
             ContentLoader.Load();
             MainLoader.Initialize();
             MainLoader.Load();
             AddMod(Loot.Instance);
             if (Main.dedServ)
             {
                 ModSupportTunneler.AddServerSupport();
             }
         }
static void Loot.LoadingFunneler.LoadModForClient () static private
Definition at line 68 of file LoadingFunneler.cs.
References Loot.Core.System.Loaders.AssetLoader.RegisterAssets().
Referenced by Loot.LoadingFunneler.AddMod().
         {
             Loot.ModContentManager = new ModContentManager();
             Loot.ModContentManager.Initialize(Loot.Instance);
             Loot.Instance.GuiInterface = new UserInterface();
             Loot.Instance.GuiState = new GuiTabWindow();
             Loot.Instance.GuiState.Activate();
             AssetLoader.RegisterAssets(Loot.Instance, "GraphicsAssets");
             ModSupportTunneler.AddClientSupport();
         }
static void Loot.LoadingFunneler.UnloadMod () static private
Definition at line 81 of file LoadingFunneler.cs.
Referenced by Loot.LoadingFunneler.AddMod().
         {
             ContentLoader.Unload();
             MainLoader.Unload();
             Loot.ModContentManager?.Unload();
             Loot.ModContentManager = null;
             //UnloadStaticRefs()
         }
static void Loot.LoadingFunneler.UnloadStaticRefs () static private
Definition at line 90 of file LoadingFunneler.cs.
         {
             // TODO causes trouble in unload?
             // Attempt to unload our static variables
             Stack<Type> typesToProcess = new Stack<Type>(Loot.Instance.Code.GetTypes());
             while (typesToProcess.Count > 0)
             {
                 Type type = typesToProcess.Pop();
                 foreach (FieldInfo info in type.GetFields(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                 {
                     info.SetValue(null, info.FieldType.IsValueType ? Activator.CreateInstance(info.FieldType) : null);
                 }
                 foreach (Type nestedType in type.GetNestedTypes(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                 {
                     typesToProcess.Push(nestedType);
                 }
             }
         }