Even More Modifiers: Loot.Loot Class Reference
Loot.Loot Class Reference
Public Member Functions
Loot ()
override void AddRecipes ()
override void HandlePacket (BinaryReader reader, int whoAmI)
override void Load ()
override void ModifyInterfaceLayers (List< GameInterfaceLayer > layers)
override void PreSaveAndQuit ()
override void Unload ()
override void UpdateUI (GameTime gameTime)
Static Public Attributes
static bool CheatSheetLoaded
static bool Loaded
static bool WingSlotLoaded
static bool WingSlotVersionInvalid
Private Member Functions
void SetupContentMgr ()
void SetupUIs ()
Private Attributes
GameTime _lastUpdateUIGameTime
Detailed Description
Definition at line 26 of file Loot.cs.
Constructor & Destructor Documentation
Loot.Loot.Loot ()
Definition at line 44 of file Loot.cs.
         {
             Properties = new ModProperties
             {
                 Autoload = true,
                 AutoloadGores = true,
                 AutoloadSounds = true
             };
         }
Member Function Documentation
override void Loot.Loot.AddRecipes ()
Definition at line 110 of file Loot.cs.
         {
             if (!Main.dedServ)
             {
                 ContentManager.Load();
             }
             Loaded = true;
         }
override void Loot.Loot.HandlePacket (BinaryReader reader, int whoAmI)
Definition at line 198 of file Loot.cs.
         {
         }
override void Loot.Loot.Load ()
Definition at line 54 of file Loot.cs.
References Loot.EMMLoader.RegisterAssets(), Loot.EMMLoader.RegisterMod(), and Loot.EMMLoader.SetupContent().
Referenced by LootTests.UnitTests.LogEMMLoaderEntries().
         {
             Instance = this;
             // Ensure cheat sheet loaded and required version
             var cheatSheetMod = ModLoader.GetMod("CheatSheet");
             CheatSheetLoaded = cheatSheetMod != null && cheatSheetMod.Version >= new Version(0, 4, 3, 1);
             var wingSlotMod = ModLoader.GetMod("WingSlot");
             WingSlotLoaded = wingSlotMod != null;
             WingSlotVersionInvalid = WingSlotLoaded && wingSlotMod.Version < new Version(1, 6, 1);
             //(string Name, string test) variable = ("Compiled with", "C#7");
             EMMLoader.Initialize();
             EMMLoader.Load();
             EMMLoader.RegisterMod(this);
             EMMLoader.SetupContent(this);
             if (!Main.dedServ)
             {
                 SetupContentMgr();
                 SetupUIs();
                 EMMLoader.RegisterAssets(this, "GraphicsAssets");
                 if (WingSlotLoaded)
                 {
                     wingSlotMod.Call("add", (Func<bool>)(
                         () =>
{
                             if (CubeInterface.CurrentState == null) return false;
                             // ReSharper disable once PossibleNullReferenceException
                             return (CubeInterface.CurrentState as CubeUI)?.Visible ?? false;
                         }));
                 }
             }
         }
override void Loot.Loot.ModifyInterfaceLayers (List< GameInterfaceLayer > layers)
Definition at line 176 of file Loot.cs.
         {
             int mouseTextIndex = layers.FindIndex(layer => layer.Name.Equals("Vanilla: Mouse Text"));
             if (mouseTextIndex != -1)
             {
                 layers.Insert(mouseTextIndex, new LegacyGameInterfaceLayer(
                     "Loot: CubeUI",
                     delegate
                     {
                         if (((CubeInterface.CurrentState as CubeUI)?.Visible ?? false)
                             && _lastUpdateUIGameTime != null)
{
                             CubeInterface.Draw(Main.spriteBatch, _lastUpdateUIGameTime);
                         }
                         return true;
                     },
                     InterfaceScaleType.UI));
             }
         }
override void Loot.Loot.PreSaveAndQuit ()
Definition at line 148 of file Loot.cs.
References Loot.UI.UIItemPanel.item, and Loot.UI.CubeSealUI.SlottedItem.
         {
             if (CubeRerollUI._rerollItemPanel != null
                 && !CubeRerollUI._rerollItemPanel.item.IsAir)
             {
                 // Runs only in SP or client, so this is safe
                 Main.LocalPlayer.QuickSpawnClonedItem(CubeRerollUI._rerollItemPanel.item, CubeRerollUI._rerollItemPanel.item.stack);
                 CubeRerollUI._rerollItemPanel.item.TurnToAir();
             }
             if (CubeSealUI.SlottedItem != null
                 & !CubeSealUI.SlottedItem.IsAir)
             {
                 Main.LocalPlayer.QuickSpawnClonedItem(CubeSealUI.SlottedItem, CubeSealUI.SlottedItem.stack);
                 CubeSealUI.SlottedItem.TurnToAir();
             }
         }
void Loot.Loot.SetupContentMgr () private
Definition at line 92 of file Loot.cs.
         {
             ContentManager = new ContentManager();
             ContentManager.Initialize(this);
         }
void Loot.Loot.SetupUIs () private
Definition at line 98 of file Loot.cs.
         {
             CubeRerollUI = new CubeRerollUI();
             CubeRerollUI.Activate();
             CubeSealUI = new CubeSealUI();
             CubeSealUI.Activate();
             CubeInterface = new UserInterface();
         }
override void Loot.Loot.Unload ()
Definition at line 119 of file Loot.cs.
         {
             Instance = null;
             EMMLoader.Unload();
             ContentManager?.Unload();
             ContentManager = null;
             // TODO causes trouble in unload?
             // @todo this is not a feature of tml
             // Attempt to unload our static variables
             //Stack<Type> typesToProcess = new Stack<Type>(this.Code.GetTypes());
             //while (typesToProcess.Count > 0)
             //{
             //    Type type = typesToProcess.Pop();
             //    foreach (FieldInfo info in type.GetFields(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
             //    {
             //        info.SetValue(null, info.FieldType.IsValueType ? Activator.CreateInstance(info.FieldType) : null);
             //    }
             //    foreach (Type nestedType in type.GetNestedTypes(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
             //    {
             //        typesToProcess.Push(nestedType);
             //    }
             //}
             Loaded = false;
         }
override void Loot.Loot.UpdateUI (GameTime gameTime)
Definition at line 167 of file Loot.cs.
         {
             _lastUpdateUIGameTime = gameTime;
             if (CubeInterface?.CurrentState != null)
             {
                 CubeInterface.Update(gameTime);
             }
         }
Member Data Documentation
GameTime Loot.Loot._lastUpdateUIGameTime private
Definition at line 166 of file Loot.cs.
bool Loot.Loot.CheatSheetLoaded static
Definition at line 29 of file Loot.cs.
bool Loot.Loot.Loaded static
Definition at line 42 of file Loot.cs.
bool Loot.Loot.WingSlotLoaded static
Definition at line 30 of file Loot.cs.
bool Loot.Loot.WingSlotVersionInvalid static
Definition at line 31 of file Loot.cs.