Even More Modifiers: Loot.Api.Graphics.Glowmask.GlowmaskEntity Class Reference
Loot.Api.Graphics.Glowmask.GlowmaskEntity Class Reference
Defines a Glowmask entity, part of GraphicsEntity The entity defines a particular 'glowmask' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Public Member Functions
GlowmaskEntity (object subjectIdentity, bool drawHitbox=false, short order=0, Color?drawColor=null, GlowmaskGraphicsProperties props=null)
void DoDrawGlowmask (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask=null)
Will draw the glowmask texture
void DoDrawHitbox (SpriteBatch spriteBatch)
Will draw the hitbox around the entity
Public Member Functions inherited from Loot.Api.Graphics.GraphicsEntity< GlowmaskGraphicsProperties >
void DrawEntity (SpriteBatch spriteBatch)
void TryGettingDrawData (float rotation, float scale)
Sets up drawing data initially
void TryUpdatingDrawData (Texture2D texture)
Protected Member Functions
override void LoadAssets (Item item)
Protected Member Functions inherited from Loot.Api.Graphics.GraphicsEntity< GlowmaskGraphicsProperties >
GraphicsEntity (object subjectIdentity)
Properties
bool DrawHitbox [get, set]
Texture2D GlowmaskTexture [get, protected set]
bool NeedsUpdate [get, set]
Properties inherited from Loot.Api.Graphics.GraphicsEntity< GlowmaskGraphicsProperties >
Color DrawColor [get, set]
Entity Entity [get, protected set]
bool NeedsUpdate [get, set]
short Order [get, protected set]
T Properties [get, protected set]
Additional Inherited Members
Public Attributes inherited from Loot.Api.Graphics.GraphicsEntity< GlowmaskGraphicsProperties >
Rectangle DestinationRectangle
DrawData DrawData
bool UseDestinationRectangle
Detailed Description
Defines a Glowmask entity, part of GraphicsEntity The entity defines a particular 'glowmask' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Definition at line 15 of file GlowmaskEntity.cs.
Constructor & Destructor Documentation
Loot.Api.Graphics.Glowmask.GlowmaskEntity.GlowmaskEntity (object subjectIdentity, bool drawHitbox = false, short order = 0, Color? drawColor = null, GlowmaskGraphicsProperties props = null)
Definition at line 21 of file GlowmaskEntity.cs.
References Loot.Api.Builder.PropertyBuilder< T >.Build(), and Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.Builder.
             : base(subjectIdentity)
         {
             DrawHitbox = drawHitbox;
             NeedsUpdate = false;
             Order = order;
             DrawColor = drawColor ?? Color.White;
             Properties = props ?? GlowmaskGraphicsProperties.Builder.Build();
         }
Member Function Documentation
void Loot.Api.Graphics.Glowmask.GlowmaskEntity.DoDrawGlowmask (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask = null)
Will draw the glowmask texture
Definition at line 43 of file GlowmaskEntity.cs.
Referenced by Loot.Api.Graphics.Shader.ShaderEntity.DoDrawGlowmask().
         {
             if (!Properties.SkipDrawing || !Properties.SkipDrawingGlowmask) return;
             TryGettingDrawData(rotation, scale);
             if (Entity is Item item) LoadAssets(item);
             else Loot.Logger.Warn("Could not identify shader entity identity as item");
             Texture2D useGlowmaskTexture = suppliedGlowmask ?? GlowmaskTexture;
             if (useGlowmaskTexture != null)
             {
                 var drawDataTexture = DrawData.texture;
                 var drawDataColor = DrawData.color;
                 var drawDataDestinationRectangle = DrawData.destinationRectangle;
                 DrawData.texture = useGlowmaskTexture;
                 DrawData.color = lightColor;
                 TryUpdatingDrawData(useGlowmaskTexture);
                 DrawEntity(spriteBatch);
                 DrawData.texture = drawDataTexture;
                 DrawData.color = drawDataColor;
                 DrawData.destinationRectangle = drawDataDestinationRectangle;
             }
             Properties.SkipUpdatingDrawData = false;
         }
void Loot.Api.Graphics.Glowmask.GlowmaskEntity.DoDrawHitbox (SpriteBatch spriteBatch)
Will draw the hitbox around the entity
Definition at line 72 of file GlowmaskEntity.cs.
         {
             if (!DrawHitbox) return;
             Rectangle hitbox = Entity.Hitbox;
             hitbox.Offset((int)-Main.screenPosition.X, (int)-Main.screenPosition.Y);
             spriteBatch.Draw(Main.magicPixel, hitbox, Color.White);
         }
override void Loot.Api.Graphics.Glowmask.GlowmaskEntity.LoadAssets (Item item) protected virtual
Implements Loot.Api.Graphics.GraphicsEntity< GlowmaskGraphicsProperties >.
Definition at line 32 of file GlowmaskEntity.cs.
References Loot.Api.ModContent.GraphicsModContent.Prepare().
         {
             if (GlowmaskTexture != null) return;
             var graphicsContent = Loot.ModContentManager.GetContent<GraphicsModContent>();
             graphicsContent?.Prepare(item);
             GlowmaskTexture = graphicsContent?.GetPreparedGlowmask(item.type.ToString()) ?? Main.itemTexture[item.type];
         }
Property Documentation
bool Loot.Api.Graphics.Glowmask.GlowmaskEntity.DrawHitbox get set
Definition at line 17 of file GlowmaskEntity.cs.
Texture2D Loot.Api.Graphics.Glowmask.GlowmaskEntity.GlowmaskTexture get protected set
Definition at line 19 of file GlowmaskEntity.cs.
bool Loot.Api.Graphics.Glowmask.GlowmaskEntity.NeedsUpdate get set
Definition at line 18 of file GlowmaskEntity.cs.