Even More Modifiers: Loot.Core.System.ModifierProperties Class Reference
Loot.Core.System.ModifierProperties Class Reference
Defines the properties of a modifier
Public Member Functions
ModifierProperties (float minMagnitude=1f, float maxMagnitude=1f, float magnitudeStrength=1f, float basePower=1f, float rarityLevel=1f, float rollChance=1f, int roundPrecision=0, bool uniqueRoll=false, bool mergeTooltips=false)
virtual void Load (Item item, TagCompound tag)
virtual void NetReceive (Item item, BinaryReader reader)
virtual void NetSend (Item item, BinaryWriter writer)
ModifierProperties RollMagnitudeAndPower (float magnitudePower=1f, float lukStat=0f)
virtual void Save (Item item, TagCompound tag)
ModifierProperties Set (float?minMagnitude=null, float?maxMagnitude=null, float?magnitudeStrength=null, float?basePower=null, float?rarityLevel=null, float?rollChance=null, int?roundPrecision=null, bool?uniqueRoll=null)
Properties
float BasePower [get, private set]
float Magnitude [get, set]
float MagnitudeStrength [get, private set]
float MaxMagnitude [get, private set]
float MinMagnitude [get, private set]
float Power [get, set]
float RarityLevel [get, private set]
float RollChance [get, private set]
float RoundedPower [get, private set]
int RoundPrecision [get, private set]
bool UniqueModifier [get, private set]
Private Member Functions
float RollMagnitude (float magnitudePower, float lukStat)
float RollPower ()
Private Attributes
float _power
Detailed Description
Defines the properties of a modifier
Definition at line 13 of file ModifierProperties.cs.
Constructor & Destructor Documentation
Loot.Core.System.ModifierProperties.ModifierProperties (float minMagnitude = 1f, float maxMagnitude = 1f, float magnitudeStrength = 1f, float basePower = 1f, float rarityLevel = 1f, float rollChance = 1f, int roundPrecision = 0, bool uniqueRoll = false, bool mergeTooltips = false)
Definition at line 40 of file ModifierProperties.cs.
         {
             Set(minMagnitude, maxMagnitude, magnitudeStrength, basePower, rarityLevel, rollChance, roundPrecision);
         }
Member Function Documentation
virtual void Loot.Core.System.ModifierProperties.Load (Item item, TagCompound tag) virtual
Definition at line 134 of file ModifierProperties.cs.
References Loot.Core.System.ModifierProperties.Load(), and Loot.Core.System.ModifierProperties.RollMagnitudeAndPower().
Referenced by Loot.Core.System.ModifierProperties.Load().
         {
         }
virtual void Loot.Core.System.ModifierProperties.NetReceive (Item item, BinaryReader reader) virtual
Definition at line 92 of file ModifierProperties.cs.
References Loot.Core.System.ModifierProperties.NetReceive().
Referenced by Loot.Core.System.ModifierProperties.NetReceive().
         {
         }
virtual void Loot.Core.System.ModifierProperties.NetSend (Item item, BinaryWriter writer) virtual
Definition at line 107 of file ModifierProperties.cs.
References Loot.Core.System.ModifierProperties.Magnitude, Loot.Core.System.ModifierProperties.NetSend(), and Loot.Core.System.ModifierProperties.Power.
Referenced by Loot.Core.System.ModifierProperties.NetSend().
         {
         }
float Loot.Core.System.ModifierProperties.RollMagnitude (float magnitudePower, float lukStat) private
Definition at line 79 of file ModifierProperties.cs.
         {
             float useMin = MinMagnitude * (1f + magnitudePower / 10f);
             float useMax = MaxMagnitude * magnitudePower;
             float randomMag = (useMin + Main.rand.NextFloat() * (useMax - useMin));
             return randomMag * MagnitudeStrength;
         }
ModifierProperties Loot.Core.System.ModifierProperties.RollMagnitudeAndPower (float magnitudePower = 1f, float lukStat = 0f)
Definition at line 58 of file ModifierProperties.cs.
Referenced by Loot.Core.System.ModifierProperties.Load().
         {
             Magnitude = RollMagnitude(magnitudePower, lukStat);
             int iterations = (int)Math.Ceiling(lukStat) / 2;
             // makes you more lucky rolling better magnitudes
             for (int i = 0; i < iterations; i++)
             {
                 float rolledMagnitude = RollMagnitude(magnitudePower, lukStat);
                 if (rolledMagnitude > Magnitude)
                 {
                     Magnitude = rolledMagnitude;
                 }
             }
             Power = RollPower();
             return this;
         }
float Loot.Core.System.ModifierProperties.RollPower () private
Definition at line 87 of file ModifierProperties.cs.
         {
             return BasePower * Magnitude;
         }
virtual void Loot.Core.System.ModifierProperties.Save (Item item, TagCompound tag) virtual
Definition at line 118 of file ModifierProperties.cs.
References Loot.Core.System.ModifierProperties.Magnitude, Loot.Core.System.ModifierProperties.Power, and Loot.Core.System.ModifierProperties.Save().
Referenced by Loot.Core.System.ModifierProperties.Save().
         {
         }
ModifierProperties Loot.Core.System.ModifierProperties.Set (float? minMagnitude = null, float? maxMagnitude = null, float? magnitudeStrength = null, float? basePower = null, float? rarityLevel = null, float? rollChance = null, int? roundPrecision = null, bool? uniqueRoll = null)
Definition at line 45 of file ModifierProperties.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.Thorns.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.SpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.KnockbackPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.VelocityPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.FishingPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.AmmoReduce.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.VelocityDamage.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.ManaReduce.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.CritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.WingTimePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetModifierProperties(), Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.GetModifierProperties().
         {
             MinMagnitude = minMagnitude ?? MinMagnitude;
             MaxMagnitude = maxMagnitude ?? MaxMagnitude;
             MagnitudeStrength = magnitudeStrength ?? MagnitudeStrength;
             BasePower = basePower ?? BasePower;
             RarityLevel = rarityLevel ?? RarityLevel;
             RollChance = rollChance ?? RollChance;
             RoundPrecision = roundPrecision ?? RoundPrecision;
             UniqueModifier = uniqueRoll ?? UniqueModifier;
             return this;
         }
Member Data Documentation
float Loot.Core.System.ModifierProperties._power private
Definition at line 23 of file ModifierProperties.cs.
Property Documentation
float Loot.Core.System.ModifierProperties.BasePower get private set
Definition at line 18 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.Magnitude get set
Definition at line 22 of file ModifierProperties.cs.
Referenced by Loot.Core.System.Modifier.Clone(), Loot.Core.System.Modifier.Load(), Loot.Core.System.ModifierProperties.NetSend(), and Loot.Core.System.ModifierProperties.Save().
float Loot.Core.System.ModifierProperties.MagnitudeStrength get private set
Definition at line 17 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.MaxMagnitude get private set
Definition at line 16 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.MinMagnitude get private set
Definition at line 15 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.Power get set
Definition at line 25 of file ModifierProperties.cs.
Referenced by Loot.Core.System.Modifier.Clone(), Loot.Core.System.Modifier.Load(), Loot.Core.System.ModifierProperties.NetSend(), and Loot.Core.System.ModifierProperties.Save().
float Loot.Core.System.ModifierProperties.RarityLevel get private set
Definition at line 19 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.RollChance get private set
Definition at line 20 of file ModifierProperties.cs.
float Loot.Core.System.ModifierProperties.RoundedPower get private set
Definition at line 34 of file ModifierProperties.cs.
int Loot.Core.System.ModifierProperties.RoundPrecision get private set
Definition at line 21 of file ModifierProperties.cs.
bool Loot.Core.System.ModifierProperties.UniqueModifier get private set
Definition at line 38 of file ModifierProperties.cs.