Even More Modifiers: Loot.Core.System.ModifierPool Class Reference
Loot.Core.System.ModifierPool Class Reference
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Public Member Functions
ModifierPool AsNewInstance ()
virtual bool CanRoll (ModifierContext ctx)
Returns if this pool can roll in the given context Returns true by default
virtual void Clone (ref ModifierPool clone)
Allows modders to do custom cloning Happens after default cloning
object Clone ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual bool MatchesRarity (ModifierRarity rarity)
By default returns if this pool matches the given ModifierRarity's ModifierRarity.RequiredRarityLevel
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(TagCompound)
Static Public Member Functions
static ModifierPool GetModifierPool (ushort type)
Returns the ModifierPool specified by type, null if not present
Public Attributes
IEnumerable< ModifierTooltipLine[]> Description => ActiveModifiers.Select(m => m.TooltipLines)
Returns an enumerable of the tooltiplines of the active modifiers
virtual string Name => GetType().Name
virtual float RollChance => 1f
float TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
Protected Member Functions
ModifierPool ()
Properties
Modifier[] ActiveModifiers [get, set]
Mod Mod [get, set]
ModifierRarity Rarity [get, set]
uint Type [get, set]
Detailed Description
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Definition at line 19 of file ModifierPool.cs.
Constructor & Destructor Documentation
Loot.Core.System.ModifierPool.ModifierPool () protected
Definition at line 30 of file ModifierPool.cs.
References Loot.Core.Attributes.PopulatePoolFromAttribute.GetClasses(), and Loot.EMMLoader.GetModifier().
         {
             var attr = GetType().GetCustomAttribute<PopulatePoolFromAttribute>(true);
             if (attr != null)
             {
                 var classes = attr.GetClasses().SelectMany(x => x.Value).ToList();
                 var list = new List<Modifier>();
                 foreach (var @class in classes)
                 {
                     var mod = EMMLoader.GetModifier(@class);
                     if (mod != null)
                     {
                         list.Add(mod);
                     }
                 }
                 Modifiers = list.ToArray();
             }
         }
Member Function Documentation
ModifierPool Loot.Core.System.ModifierPool.AsNewInstance ()
virtual bool Loot.Core.System.ModifierPool.CanRoll (ModifierContext ctx) virtual
Returns if this pool can roll in the given context Returns true by default
Reimplemented in Loot.Pools.AllModifiersPool.
virtual void Loot.Core.System.ModifierPool.Clone (ref ModifierPool clone) virtual
Allows modders to do custom cloning Happens after default cloning
Definition at line 134 of file ModifierPool.cs.
Referenced by Loot.Ext.ModUtils.GetModifierPool(), and Loot.EMMLoader.RegisterAssets().
         {
         }
object Loot.Core.System.ModifierPool.Clone ()
Definition at line 138 of file ModifierPool.cs.
References Loot.Core.System.ModifierPool.ActiveModifiers, Loot.Core.System.ModifierPool.Mod, Loot.Core.System.ModifierPool.Rarity, and Loot.Core.System.ModifierPool.Type.
         {
             ModifierPool clone = (ModifierPool)MemberwiseClone();
             clone.Type = Type;
             clone.Mod = Mod;
             clone.Rarity = (ModifierRarity)Rarity?.Clone();
             clone.Modifiers =
                 Modifiers?
                     .Select(x => x?.Clone())
                     .Cast<Modifier>()
                     .ToArray();
             clone.ActiveModifiers =
                 ActiveModifiers?
                     .Select(x => x?.Clone())
                     .Cast<Modifier>()
                     .ToArray();
             Clone(ref clone);
             return clone;
         }
static ModifierPool Loot.Core.System.ModifierPool.GetModifierPool (ushort type) static
Returns the ModifierPool specified by type, null if not present
Referenced by Loot.Core.Cubes.PoorCube.SetRollLogic().
virtual void Loot.Core.System.ModifierPool.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 221 of file ModifierPool.cs.
References Loot.Core.System.ModifierPool.ActiveModifiers, Loot.EMMLoader.GetModifierPool(), Loot.Core.System.ModifierPool.Load(), and Loot.Core.System.ModifierPool.Rarity.
Referenced by Loot.Core.System.ModifierPool.Load().
         {
         }
virtual bool Loot.Core.System.ModifierPool.MatchesRarity (ModifierRarity rarity) virtual
By default returns if this pool matches the given ModifierRarity's ModifierRarity.RequiredRarityLevel
virtual void Loot.Core.System.ModifierPool.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Definition at line 161 of file ModifierPool.cs.
References Loot.Core.System.ModifierPool.ActiveModifiers, Loot.Core.System.ModifierPool.Mod, Loot.Core.System.ModifierPool.NetReceive(), Loot.Core.System.ModifierPool.Rarity, and Loot.Core.System.ModifierPool.Type.
Referenced by Loot.Core.System.ModifierPool.NetReceive().
         {
         }
virtual void Loot.Core.System.ModifierPool.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Definition at line 196 of file ModifierPool.cs.
References Loot.Core.System.ModifierPool.ActiveModifiers, Loot.Core.System.ModifierPool.Mod, Loot.Core.System.ModifierPool.NetSend(), Loot.Core.System.ModifierPool.Rarity, and Loot.Core.System.ModifierPool.Type.
Referenced by Loot.Core.System.ModifierPool.NetSend().
         {
         }
virtual void Loot.Core.System.ModifierPool.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(TagCompound)
Parameters
tag
Definition at line 310 of file ModifierPool.cs.
References Loot.Core.System.ModifierPool.ActiveModifiers, Loot.Core.System.ModifierPool.Mod, Loot.Core.System.ModifierPool.Name, Loot.Core.System.ModifierPool.Rarity, Loot.Core.System.ModifierRarity.Save(), Loot.Core.System.Modifier.Save(), and Loot.Core.System.ModifierPool.Save().
Referenced by Loot.EMMItem.Save(), and Loot.Core.System.ModifierPool.Save().
         {
         }
Member Data Documentation
IEnumerable<ModifierTooltipLine[]> Loot.Core.System.ModifierPool.Description => ActiveModifiers.Select(m => m.TooltipLines)
Returns an enumerable of the tooltiplines of the active modifiers
Definition at line 69 of file ModifierPool.cs.
virtual string Loot.Core.System.ModifierPool.Name => GetType().Name
Definition at line 71 of file ModifierPool.cs.
Referenced by Loot.EMMLoader.AddModifierPool(), and Loot.Core.System.ModifierPool.Save().
virtual float Loot.Core.System.ModifierPool.RollChance => 1f
Definition at line 72 of file ModifierPool.cs.
float Loot.Core.System.ModifierPool.TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
Definition at line 63 of file ModifierPool.cs.
Property Documentation
Modifier [] Loot.Core.System.ModifierPool.ActiveModifiers get set
Definition at line 25 of file ModifierPool.cs.
Referenced by Loot.Core.System.ModifierPool.Clone(), Loot.EMMItem.Load(), Loot.Core.System.ModifierPool.Load(), Loot.Core.System.ModifierPool.NetReceive(), Loot.Core.System.ModifierPool.NetSend(), and Loot.Core.System.ModifierPool.Save().
Mod Loot.Core.System.ModifierPool.Mod get set
Definition at line 22 of file ModifierPool.cs.
Referenced by Loot.EMMLoader.AddModifierPool(), Loot.Core.System.ModifierPool.Clone(), Loot.EMMLoader.GetNewPoolInstance(), Loot.Core.System.ModifierPool.NetReceive(), Loot.Core.System.ModifierPool.NetSend(), and Loot.Core.System.ModifierPool.Save().
ModifierRarity Loot.Core.System.ModifierPool.Rarity get set
Definition at line 23 of file ModifierPool.cs.
Referenced by Loot.Core.System.ModifierPool.Clone(), Loot.Core.System.ModifierPool.Load(), Loot.Core.System.ModifierPool.NetReceive(), Loot.Core.System.ModifierPool.NetSend(), and Loot.Core.System.ModifierPool.Save().
uint Loot.Core.System.ModifierPool.Type get set
Definition at line 21 of file ModifierPool.cs.
Referenced by Loot.EMMLoader.AddModifierPool(), Loot.Core.System.ModifierPool.Clone(), Loot.Ext.ModUtils.GetModifierPool(), Loot.EMMLoader.GetNewPoolInstance(), Loot.Core.System.ModifierPool.NetReceive(), and Loot.Core.System.ModifierPool.NetSend().