Even More Modifiers: Loot.Core.System.Modifier.ModifierPropertiesBuilder Class Reference
Loot.Core.System.Modifier.ModifierPropertiesBuilder Class Reference
The ModifierPropertiesBuilder implements the builder pattern for ModifierProperties It provides a structured way to create ("build") an instance of ModifierProperties It is used in Modifier.GetModifierProperties to dynamically build the ModifierProperties for that Modifier.
Public Member Functions
ModifierPropertiesBuilder ()
ModifierPropertiesBuilder (ModifierProperties defaultProperties)
ModifierPropertiesBuilder (ModifierPropertiesBuilder defaultBuilder)
ModifierProperties Build ()
ModifierPropertiesBuilder IsUniqueModifier (bool val)
ModifierPropertiesBuilder UsingDefault (ModifierProperties val)
ModifierPropertiesBuilder UsingDefault (ModifierPropertiesBuilder val)
ModifierPropertiesBuilder WithBasePower (float val)
ModifierPropertiesBuilder WithMagnitudeStrength (float val)
ModifierPropertiesBuilder WithMaxMagnitude (float val)
ModifierPropertiesBuilder WithMinMagnitude (float val)
ModifierPropertiesBuilder WithRarityLevel (float val)
ModifierPropertiesBuilder WithRollChance (float val)
ModifierPropertiesBuilder WithRoundPrecision (int val)
Properties
float BasePower [protected get, set]
ModifierPropertiesBuilder DefaultBuilder [set]
ModifierProperties DefaultProperties [set]
bool IsUnique [protected get, set]
float MagnitudeStrength [protected get, set]
float MaxMagnitude [protected get, set]
float MinMagnitude [protected get, set]
float RarityLevel [protected get, set]
float RollChance [protected get, set]
int RoundPrecision [protected get, set]
Detailed Description
The ModifierPropertiesBuilder implements the builder pattern for ModifierProperties It provides a structured way to create ("build") an instance of ModifierProperties It is used in Modifier.GetModifierProperties to dynamically build the ModifierProperties for that Modifier.
Definition at line 9 of file ModifierPropertiesBuilder.cs.
Constructor & Destructor Documentation
Loot.Core.System.Modifier.ModifierPropertiesBuilder.ModifierPropertiesBuilder ()
Definition at line 11 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = new ModifierProperties();
         }
Loot.Core.System.Modifier.ModifierPropertiesBuilder.ModifierPropertiesBuilder (ModifierProperties defaultProperties)
Definition at line 16 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = defaultProperties;
         }
Loot.Core.System.Modifier.ModifierPropertiesBuilder.ModifierPropertiesBuilder (ModifierPropertiesBuilder defaultBuilder)
Definition at line 21 of file ModifierPropertiesBuilder.cs.
         {
             DefaultBuilder = defaultBuilder;
         }
Member Function Documentation
ModifierProperties Loot.Core.System.Modifier.ModifierPropertiesBuilder.Build ()
Definition at line 122 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.Modifier.Load(), and Loot.EMMItem.RollNewModifiers().
         {
             return new ModifierProperties(
                 MinMagnitude,
                 MaxMagnitude,
                 MagnitudeStrength,
                 BasePower,
                 RarityLevel,
                 RollChance,
                 RoundPrecision,
                 IsUnique);
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.IsUniqueModifier (bool val)
Definition at line 116 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.Ice.IcyModifier.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties().
         {
             IsUnique = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.UsingDefault (ModifierProperties val)
Definition at line 62 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.UsingDefault (ModifierPropertiesBuilder val)
Definition at line 68 of file ModifierPropertiesBuilder.cs.
         {
             DefaultBuilder = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithBasePower (float val)
Definition at line 92 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.SpeedPlus.GetModifierProperties().
         {
             BasePower = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithMagnitudeStrength (float val)
Definition at line 86 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifier.GetModifierProperties().
         {
             MagnitudeStrength = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithMaxMagnitude (float val)
Definition at line 80 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.SpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.Thorns.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.KnockbackPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.FishingPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.AmmoReduce.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.ManaReduce.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.VelocityDamage.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.WingTimePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.CritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.Ice.IcyModifier.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.LightPlus.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties().
         {
             MaxMagnitude = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithMinMagnitude (float val)
Definition at line 74 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.Ice.IcyModifier.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties().
         {
             MinMagnitude = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithRarityLevel (float val)
Definition at line 98 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties().
         {
             RarityLevel = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithRollChance (float val)
Definition at line 104 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.Ice.IcyModifier.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetModifierProperties(), and Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetModifierProperties().
         {
             RollChance = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithRoundPrecision (int val)
Definition at line 110 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.WeaponModifiers.VelocityDamage.GetModifierProperties(), and Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties().
         {
             RoundPrecision = val;
             return this;
         }
Property Documentation
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.BasePower protected get set
Definition at line 32 of file ModifierPropertiesBuilder.cs.
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierPropertiesBuilder.DefaultBuilder set
Definition at line 58 of file ModifierPropertiesBuilder.cs.
ModifierProperties Loot.Core.System.Modifier.ModifierPropertiesBuilder.DefaultProperties set
Definition at line 43 of file ModifierPropertiesBuilder.cs.
bool Loot.Core.System.Modifier.ModifierPropertiesBuilder.IsUnique protected get set
Definition at line 40 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.MagnitudeStrength protected get set
Definition at line 30 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.MaxMagnitude protected get set
Definition at line 28 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.MinMagnitude protected get set
Definition at line 26 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.RarityLevel protected get set
Definition at line 34 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.Modifier.ModifierPropertiesBuilder.RollChance protected get set
Definition at line 36 of file ModifierPropertiesBuilder.cs.
int Loot.Core.System.Modifier.ModifierPropertiesBuilder.RoundPrecision protected get set
Definition at line 38 of file ModifierPropertiesBuilder.cs.