Even More Modifiers: Loot.Modifiers.ModifierCachePlayer Class Reference
Loot.Modifiers.ModifierCachePlayer Class Reference
The following code caches the item held and items equipped by players When equips and held items change, their respective modifiers' effects are automatically called to detach and attach their delegations
Public Member Functions
override void Initialize ()
override void PostUpdate ()
Private Member Functions
void AddAttachItem (Item item, Modifier modifier)
void AddDetachItem (Item item, Modifier modifier)
void CacheItemModifierEffects (Item item)
void CacheModifierEffects (Player player)
List< ModifierEffect > GetModifierEffectsForDelegations (List< AutoDelegationEntry > list, ModifierPlayer modPlayer, Func< ModifierEffect, bool > conditionFunc)
This method will return a list of ModifierEffects based on Modifiers passed to it
bool IsMouseUsable (Item item)
List< OrderedDelegationEntry > OrderDelegationList (List< AutoDelegationEntry > list, ModifierPlayer modPlayer)
This method orders a list of AutoDelegationEntry into a list of OrderedDelegationEntry following the rules of DelegationPrioritizationAttribute which orders by Early/Late prioritization and a level ranging from 0-999 which indicates how much that prioritization should be enforced.
void UpdateAttachments ()
This method handles updating all delegations First, it will perform 'manual' detachments calling ModifierEffect.DetachDelegations(ModifierPlayer) then it will perform 'manual' attachments calling ModifierEffect.AttachDelegations(ModifierPlayer) These will unbind/bind ModifierEffect.ResetEffects to ModifierPlayer.OnResetEffects and set ModifierEffect.IsBeingDelegated to false or true.
void UpdateCheatSheetCache ()
void UpdateEquipsCache ()
void UpdateHeldItemCache ()
bool UpdateMouseItemCache ()
void UpdateVanityCache ()
Private Attributes
List< AutoDelegationEntry > _attachList
List< AutoDelegationEntry > _detachList
bool _forceEquipUpdate
List< Type > _modifierEffects
Item[] _oldCheatSheetEquips
Item[] _oldEquips
Item _oldHeldItem
Item _oldMouseItem
Item[] _oldVanityEquips
Detailed Description
The following code caches the item held and items equipped by players When equips and held items change, their respective modifiers' effects are automatically called to detach and attach their delegations
Definition at line 45 of file ModifierCachePlayer.cs.
Member Function Documentation
void Loot.Modifiers.ModifierCachePlayer.AddAttachItem (Item item, Modifier modifier) private
Definition at line 288 of file ModifierCachePlayer.cs.
References Loot.ActivatedModifierItem.IsActivated, and Loot.ActivatedModifierItem.Item().
         {
             ActivatedModifierItem.Item(item).IsActivated = true;
             _attachList.Add(new AutoDelegationEntry(item, modifier));
         }
void Loot.Modifiers.ModifierCachePlayer.AddDetachItem (Item item, Modifier modifier) private
Definition at line 282 of file ModifierCachePlayer.cs.
References Loot.ActivatedModifierItem.IsActivated, and Loot.ActivatedModifierItem.Item().
         {
             ActivatedModifierItem.Item(item).IsActivated = false;
             _detachList.Add(new AutoDelegationEntry(item, modifier));
         }
void Loot.Modifiers.ModifierCachePlayer.CacheItemModifierEffects (Item item) private
Definition at line 544 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool(), Loot.ModifierPlayer.GetEffect(), and Loot.ModifierPlayer.Player().
         {
             var mods = EMMItem.GetActivePool(item);
             foreach (var modifier in mods)
             {
                 var effectsAttribute = modifier
                     .GetType()
                     .GetCustomAttribute<UsesEffectAttribute>();
                 if (effectsAttribute != null)
                 {
                     ModifierPlayer modPlayer = ModifierPlayer.Player(player);
                     foreach (Type effect in effectsAttribute.Effects)
                     {
                         var modEffect = modPlayer.GetEffect(effect);
                         if (modEffect != null && !_modifierEffects.Contains(modEffect.GetType()))
{
                             _modifierEffects.Add(modEffect.GetType());
                         }
                     }
                 }
             }
         }
void Loot.Modifiers.ModifierCachePlayer.CacheModifierEffects (Player player) private
Definition at line 495 of file ModifierCachePlayer.cs.
References Loot.ActivatedModifierItem.IsVanityActivated, and Loot.ActivatedModifierItem.Item().
         {
             bool anyDifferentEquip = player.armor.Take(8 + player.extraAccessorySlots)
                 .Select((x, i) => new { Value = x, Index = i })
                 .Any(x => _oldEquips[x.Index] != null && x.Value.IsNotTheSameAs(_oldEquips[x.Index]));
             // vanity, processed if hijacked to activate (antisocial)
             anyDifferentEquip &= player.armor.Skip(13)
                 .Select((x, i) => new { Value = x, Index = i })
                 .Any(x => _oldVanityEquips[x.Index] != null && x.Value.IsNotTheSameAs(_oldVanityEquips[x.Index]));
             // Only recache if needed, so check if there are changes
             if (_forceEquipUpdate || anyDifferentEquip)
             {
                 _modifierEffects.Clear();
                 for (int i = 0; i < 8 + player.extraAccessorySlots; i++)
                 {
                     var equip = player.armor[i];
                     if (equip != null && !equip.IsAir)
                     {
                         CacheItemModifierEffects(equip);
                     }
                 }
                 // vanity
                 for (int k = 13; k < 18 + player.extraAccessorySlots; k++)
                 {
                     var equip = player.armor[k];
                     if (equip != null
                         && !equip.IsAir
                         && ActivatedModifierItem.Item(equip).IsVanityActivated)
                     {
                         CacheItemModifierEffects(equip);
                     }
                 }
             }
             // else because in mouse should override held item
             if (Main.mouseItem != null && !Main.mouseItem.IsAir && Main.mouseItem.IsWeapon())
             {
                 CacheItemModifierEffects(Main.mouseItem);
             }
             else if ((_oldMouseItem?.IsAir ?? true) && player.HeldItem != null && !player.HeldItem.IsAir && player.HeldItem.IsWeapon())
             {
                 CacheItemModifierEffects(player.HeldItem);
             }
         }
List<ModifierEffect> Loot.Modifiers.ModifierCachePlayer.GetModifierEffectsForDelegations (List< AutoDelegationEntry > list, ModifierPlayer modPlayer, Func< ModifierEffect, bool > conditionFunc) private
This method will return a list of ModifierEffects based on Modifiers passed to it
Definition at line 77 of file ModifierCachePlayer.cs.
         {
             var tempList = new List<ModifierEffect>();
             foreach (var delegationTuple in list)
             {
                 var effectsAttribute =
                     delegationTuple.Modifier
                         .GetType()
                         .GetCustomAttribute<UsesEffectAttribute>();
                 if (effectsAttribute != null)
                 {
                     foreach (Type effect in effectsAttribute.Effects)
                     {
                         var modEffect = modPlayer.GetEffect(effect);
                         if (modEffect != null && conditionFunc.Invoke(modEffect))
{
                             tempList.Add(modEffect);
                         }
                     }
                 }
             }
             return tempList;
         }
override void Loot.Modifiers.ModifierCachePlayer.Initialize ()
Definition at line 60 of file ModifierCachePlayer.cs.
         {
             _oldHeldItem = null;
             _oldMouseItem = null;
             _oldEquips = new Item[8];
             _oldVanityEquips = new Item[8];
             _forceEquipUpdate = false;
             _oldCheatSheetEquips = new Item[6]; // MaxExtraAccessories = 6
             _modifierEffects = new List<Type>();
             _detachList = new List<AutoDelegationEntry>();
             _attachList = new List<AutoDelegationEntry>();
             Ready = false;
         }
bool Loot.Modifiers.ModifierCachePlayer.IsMouseUsable (Item item) private
List<OrderedDelegationEntry> Loot.Modifiers.ModifierCachePlayer.OrderDelegationList (List< AutoDelegationEntry > list, ModifierPlayer modPlayer) private
This method orders a list of AutoDelegationEntry into a list of OrderedDelegationEntry following the rules of DelegationPrioritizationAttribute which orders by Early/Late prioritization and a level ranging from 0-999 which indicates how much that prioritization should be enforced.
Definition at line 169 of file ModifierCachePlayer.cs.
         {
             var tempList = new List<OrderedDelegationEntry>();
             var tempEarlyMethods = new List<OrderedDelegationEntry>();
             var tempMiddleMethods = new List<OrderedDelegationEntry>();
             var tempLateMethods = new List<OrderedDelegationEntry>();
             var effects = GetModifierEffectsForDelegations(list, modPlayer, (e) => true);
             foreach (var modEffect in effects)
             {
                 var delegatedMethods = modEffect
                     .GetType()
                     .GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance)
                     .Where(x => x.GetCustomAttributes(typeof(AutoDelegation), false).Length > 0)
                     .ToArray();
                 tempEarlyMethods.AddRange(delegatedMethods.Where(x =>
                 {
                     var attr = x.GetCustomAttribute(typeof(DelegationPrioritizationAttribute));
                     if (attr != null && (attr as DelegationPrioritizationAttribute).DelegationPrioritization == DelegationPrioritization.Early)
                     {
                         return true;
                     }
                     return false;
                 }).Select(x => new OrderedDelegationEntry
                 {
                     MethodInfo = x,
                     Effect = modEffect
                 }));
                 tempMiddleMethods.AddRange(delegatedMethods.Where(x =>
                 {
                     var attr = x.GetCustomAttribute(typeof(DelegationPrioritizationAttribute));
                     return attr == null;
                 }).Select(x => new OrderedDelegationEntry
                 {
                     MethodInfo = x,
                     Effect = modEffect
                 }));
                 tempLateMethods.AddRange(delegatedMethods.Where(x =>
                 {
                     var attr = x.GetCustomAttribute(typeof(DelegationPrioritizationAttribute));
                     if (attr != null && (attr as DelegationPrioritizationAttribute).DelegationPrioritization == DelegationPrioritization.Late)
                     {
                         return true;
                     }
                     return false;
                 }).Select(x => new OrderedDelegationEntry
                 {
                     MethodInfo = x,
                     Effect = modEffect
                 }));
             }
             tempEarlyMethods = tempEarlyMethods.OrderByDescending(x =>
             {
                 var attr = x.MethodInfo.GetCustomAttribute(typeof(DelegationPrioritizationAttribute));
                 return ((DelegationPrioritizationAttribute)attr).DelegationLevel;
             }).ToList();
             tempLateMethods = tempLateMethods.OrderByDescending(x =>
             {
                 var attr = x.MethodInfo.GetCustomAttribute(typeof(DelegationPrioritizationAttribute));
                 return ((DelegationPrioritizationAttribute)attr).DelegationLevel;
             }).ToList();
             tempList.AddRange(tempEarlyMethods);
             tempList.AddRange(tempMiddleMethods);
             tempList.AddRange(tempLateMethods);
             return tempList;
         }
override void Loot.Modifiers.ModifierCachePlayer.PostUpdate ()
Definition at line 245 of file ModifierCachePlayer.cs.
         {
             // If our equips cache is not the right size we resize it and force an update
             if (_oldEquips.Length != 8 + player.extraAccessorySlots)
             {
                 Ready = false;
                 _forceEquipUpdate = true;
                 Array.Resize(ref _oldEquips, 8 + player.extraAccessorySlots);
             }
             if (_oldVanityEquips.Length != 8 + player.extraAccessorySlots)
             {
                 Ready = false;
                 _forceEquipUpdate = true;
                 Array.Resize(ref _oldVanityEquips, 8 + player.extraAccessorySlots);
             }
             _detachList.Clear();
             _attachList.Clear();
             CacheModifierEffects(player);
             bool flag = UpdateMouseItemCache();
             if (flag) UpdateHeldItemCache();
             UpdateEquipsCache();
             if (Loot.CheatSheetLoaded)
             {
                 UpdateCheatSheetCache();
             }
             UpdateVanityCache();
             UpdateAttachments();
             _forceEquipUpdate = false;
             Ready = true;
         }
void Loot.Modifiers.ModifierCachePlayer.UpdateAttachments () private
This method handles updating all delegations First, it will perform 'manual' detachments calling ModifierEffect.DetachDelegations(ModifierPlayer) then it will perform 'manual' attachments calling ModifierEffect.AttachDelegations(ModifierPlayer) These will unbind/bind ModifierEffect.ResetEffects to ModifierPlayer.OnResetEffects and set ModifierEffect.IsBeingDelegated to false or true.
After this, the automatic detachments/attachments are done which will bind any methods to whichever method noted in their AutoDelegation attribute.
Definition at line 113 of file ModifierCachePlayer.cs.
References Loot.Core.Attributes.AutoDelegation.Attach(), Loot.Core.Attributes.AutoDelegation.Detach(), and Loot.ModifierPlayer.Player().
         {
             ModifierPlayer modplr = ModifierPlayer.Player(player);
             // Manual detach
             var detachEffects = GetModifierEffectsForDelegations(_detachList, modplr, (e) => e.IsBeingDelegated && !_modifierEffects.Contains(e.GetType()));
             var attachEffects = GetModifierEffectsForDelegations(_attachList, modplr, (e) => !e.IsBeingDelegated);
             // Automatic delegation lists
             var orderedDetachList = OrderDelegationList(_detachList, modplr)
                 .Where(x => x.Effect.IsBeingDelegated && !_modifierEffects.Contains(x.Effect.GetType()))
                 .GroupBy(x => x.MethodInfo)
                 .Select(x => x.First())
                 .ToList();
             var orderedAttachList = OrderDelegationList(_attachList, modplr)
                 .Where(x => !x.Effect.IsBeingDelegated)
                 .GroupBy(x => x.MethodInfo)
                 .Select(x => x.First())
                 .ToList();
             // Manual detach
             foreach (var effect in detachEffects.Distinct())
             {
                 modplr.OnResetEffects -= effect.ResetEffects;
                 effect._DetachDelegations(modplr);
                 effect.IsBeingDelegated = false;
             }
             // Manual attach
             foreach (var effect in attachEffects.Distinct())
             {
                 modplr.OnResetEffects += effect.ResetEffects;
                 effect.AttachDelegations(modplr);
                 effect.IsBeingDelegated = true;
             }
             // Auto delegation detach
             foreach (var info in orderedDetachList)
             {
                 var attr = info.MethodInfo.GetCustomAttribute<AutoDelegation>();
                 attr.Detach(modplr, info.MethodInfo, info.Effect);
             }
             // Auto delegation attach
             foreach (var info in orderedAttachList)
             {
                 var attr = info.MethodInfo.GetCustomAttribute<AutoDelegation>();
                 attr.Attach(modplr, info.MethodInfo, info.Effect);
             }
         }
void Loot.Modifiers.ModifierCachePlayer.UpdateCheatSheetCache () private
Definition at line 437 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool().
         {
             // get cheat sheet slots
             var curEquips = CheatSheetInterface.GetEnabledExtraAccessories(player).Take(_oldCheatSheetEquips.Length).ToArray();
             // go over enabled slots
             for (int i = 0; i < curEquips.Length; i++)
             {
                 var oldEquip = _oldCheatSheetEquips[i];
                 var newEquip = curEquips[i];
                 // update delegations
                 if (oldEquip == null || newEquip.IsNotTheSameAs(oldEquip))
                 {
                     Ready = false;
                     // detach old first
                     if (oldEquip != null && !oldEquip.IsAir)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(oldEquip))
{
                             AddDetachItem(oldEquip, m);
                         }
                     }
                     // attach new
                     if (newEquip != null && !newEquip.IsAir)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(newEquip))
{
                             AddAttachItem(newEquip, m);
                         }
                     }
                     _oldCheatSheetEquips[i] = newEquip;
                 }
             }
             // current enabled is smaller than total
             if (curEquips.Length < _oldCheatSheetEquips.Length)
             {
                 var outOfDateEquips = _oldCheatSheetEquips.Skip(curEquips.Length);
                 if (outOfDateEquips.Any())
                 {
                     Ready = false;
                 }
                 // for all disabled slots but still had a registered item, detach it
                 foreach (var item in outOfDateEquips.Where(x => x != null && !x.IsAir))
                 {
                     foreach (Modifier m in EMMItem.GetActivePool(item))
                     {
                         AddDetachItem(item, m);
                     }
                 }
             }
         }
void Loot.Modifiers.ModifierCachePlayer.UpdateEquipsCache () private
Definition at line 400 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool().
         {
             for (int i = 0; i < 8 + player.extraAccessorySlots; i++)
             {
                 var oldEquip = _oldEquips[i];
                 var newEquip = player.armor[i];
                 // If equip slot needs an update
                 if (_forceEquipUpdate || oldEquip == null || newEquip.IsNotTheSameAs(oldEquip))
                 {
                     Ready = false;
                     // detach old first
                     if (oldEquip != null && !oldEquip.IsAir)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(oldEquip))
{
                             AddDetachItem(oldEquip, m);
                         }
                     }
                     // attach new
                     if (newEquip != null && !newEquip.IsAir)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(newEquip))
{
                             AddAttachItem(newEquip, m);
                         }
                     }
                     _oldEquips[i] = newEquip;
                 }
             }
         }
void Loot.Modifiers.ModifierCachePlayer.UpdateHeldItemCache () private
Definition at line 330 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool().
         {
             // If held item needs an update
             if (_oldHeldItem == null || _oldHeldItem.IsNotTheSameAs(player.HeldItem))
             {
                 Ready = false;
                 // detach old held item
                 if (_oldHeldItem != null && !_oldHeldItem.IsAir && IsMouseUsable(_oldHeldItem))
                 {
                     foreach (Modifier m in EMMItem.GetActivePool(_oldHeldItem))
                     {
                         AddDetachItem(_oldHeldItem, m);
                     }
                 }
                 // attach new held item
                 if (player.HeldItem != null && !player.HeldItem.IsAir && IsMouseUsable(player.HeldItem))
                 {
                     foreach (Modifier m in EMMItem.GetActivePool(player.HeldItem))
                     {
                         AddAttachItem(player.HeldItem, m);
                     }
                 }
                 _oldHeldItem = player.HeldItem;
             }
         }
bool Loot.Modifiers.ModifierCachePlayer.UpdateMouseItemCache () private
Definition at line 359 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool().
         {
             bool flag = (_oldMouseItem?.IsAir ?? true);
             if (_oldMouseItem == null || _oldMouseItem.IsNotTheSameAs(Main.mouseItem))
             {
                 Ready = false;
                 if (_oldMouseItem != null && !_oldMouseItem.IsAir && IsMouseUsable(_oldMouseItem))
                 {
                     foreach (Modifier m in EMMItem.GetActivePool(_oldMouseItem))
                     {
                         AddDetachItem(_oldMouseItem, m);
                     }
                 }
                 if (Main.mouseItem != null && !Main.mouseItem.IsAir && IsMouseUsable(Main.mouseItem))
                 {
                     flag = false;
                     // Detach first so we override 'IsActivated' again in case it's the same item
                     if (_oldHeldItem != null && !_oldHeldItem.IsAir)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(_oldHeldItem))
{
                             AddDetachItem(_oldHeldItem, m);
                         }
                     }
                     foreach (Modifier m in EMMItem.GetActivePool(Main.mouseItem))
                     {
                         AddAttachItem(Main.mouseItem, m);
                     }
                 }
                 _oldMouseItem = Main.mouseItem;
             }
             return flag;
         }
void Loot.Modifiers.ModifierCachePlayer.UpdateVanityCache () private
Definition at line 294 of file ModifierCachePlayer.cs.
References Loot.EMMItem.GetActivePool(), Loot.ActivatedModifierItem.IsVanityActivated, and Loot.ActivatedModifierItem.Item().
         {
             // vanity
             for (int i = 13; i < 18 + player.extraAccessorySlots; i++)
             {
                 var oldEquip = _oldVanityEquips[i - 13];
                 var newEquip = player.armor[i];
                 // If equip slot needs an update
                 if (_forceEquipUpdate || oldEquip == null || newEquip.IsNotTheSameAs(oldEquip))
                 {
                     Ready = false;
                     // detach old first
                     if (oldEquip != null && !oldEquip.IsAir && ActivatedModifierItem.Item(oldEquip).IsVanityActivated)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(oldEquip))
{
                             AddDetachItem(oldEquip, m);
                         }
                     }
                     // attach new
                     if (newEquip != null && !newEquip.IsAir && ActivatedModifierItem.Item(newEquip).IsVanityActivated)
                     {
                         foreach (Modifier m in EMMItem.GetActivePool(newEquip))
{
                             AddAttachItem(newEquip, m);
                         }
                     }
                     _oldVanityEquips[i - 13] = newEquip;
                 }
             }
         }
Member Data Documentation
List<AutoDelegationEntry> Loot.Modifiers.ModifierCachePlayer._attachList private
Definition at line 58 of file ModifierCachePlayer.cs.
List<AutoDelegationEntry> Loot.Modifiers.ModifierCachePlayer._detachList private
Definition at line 57 of file ModifierCachePlayer.cs.
bool Loot.Modifiers.ModifierCachePlayer._forceEquipUpdate private
Definition at line 53 of file ModifierCachePlayer.cs.
List<Type> Loot.Modifiers.ModifierCachePlayer._modifierEffects private
Definition at line 56 of file ModifierCachePlayer.cs.
Item [] Loot.Modifiers.ModifierCachePlayer._oldCheatSheetEquips private
Definition at line 54 of file ModifierCachePlayer.cs.
Item [] Loot.Modifiers.ModifierCachePlayer._oldEquips private
Definition at line 51 of file ModifierCachePlayer.cs.
Item Loot.Modifiers.ModifierCachePlayer._oldHeldItem private
Definition at line 49 of file ModifierCachePlayer.cs.
Item Loot.Modifiers.ModifierCachePlayer._oldMouseItem private
Definition at line 50 of file ModifierCachePlayer.cs.
Item [] Loot.Modifiers.ModifierCachePlayer._oldVanityEquips private
Definition at line 52 of file ModifierCachePlayer.cs.