Even More Modifiers: Loot.UI.Rerolling.UIRerollItemPanel Class Reference
Loot.UI.Rerolling.UIRerollItemPanel Class Reference
Public Member Functions
UIRerollItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
override bool CanTakeItem (Item item)
override void PostOnClick (UIMouseEvent evt, UIElement e)
override void PreOnClick (UIMouseEvent evt, UIElement e)
Public Member Functions inherited from Loot.UI.Core.UIInteractableItemPanel
UIInteractableItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
virtual void PostOnRightClick ()
override void Update (GameTime gameTime)
Public Member Functions inherited from Loot.UI.Core.UIItemPanel
UIItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null, string hintOnHover=null)
Additional Inherited Members
Public Attributes inherited from Loot.UI.Core.UIItemPanel
Item item
Protected Member Functions inherited from Loot.UI.Core.UIItemPanel
override void DrawSelf (SpriteBatch spriteBatch)
Protected Attributes inherited from Loot.UI.Core.UIInteractableItemPanel
bool RightClickFunctionalityEnabled = true
bool TakeUserItemOnClick = true
Properties inherited from Loot.UI.Core.UIItemPanel
string HintOnHover [get, set]
string HintText [get, set]
Texture2D HintTexture [get, set]
Detailed Description
Definition at line 9 of file UIRerollItemPanel.cs.
Constructor & Destructor Documentation
Loot.UI.Rerolling.UIRerollItemPanel.UIRerollItemPanel (int netID = 0, int stack = 0, Texture2D hintTexture = null, string hintText = null)
Definition at line 11 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SealedModifiers.
                                                                                                                      :
             base(netID, stack, hintTexture, hintText)
         {
             this.RightClickFunctionalityEnabled = false;
             this.HintOnHover = " (click to take item)";
         }
Member Function Documentation
override bool Loot.UI.Rerolling.UIRerollItemPanel.CanTakeItem (Item item) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Referenced by Loot.UI.Rerolling.CubeRerollUI.IsItemValidForUISlot(), and Loot.UI.Rerolling.CubeRerollUI.MatchesRerollRequirements().
override void Loot.UI.Rerolling.UIRerollItemPanel.PostOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Definition at line 28 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = true;
             }
             Loot.Instance.CubeRerollUI.UpdateModifierLines();
         }
override void Loot.UI.Rerolling.UIRerollItemPanel.PreOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Definition at line 20 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = false;
             }
         }