Even More Modifiers: Loot.UI.Sealing.CubeSealUI Class Reference
Loot.UI.Sealing.CubeSealUI Class Reference
Public Member Functions
override bool IsItemValidForUISlot (Item item)
override bool IsSlottedItemInCubeUI ()
override void OnInitialize ()
override void ToggleUI (Terraria.UI.UserInterface theInterface, UIState uiStateInstance)
Public Member Functions inherited from Loot.UI.Core.DraggableUIState
override void OnInitialize ()
Public Member Functions inherited from Loot.UI.Core.VisibilityUI
virtual void ToggleUI (UserInterface theInterface, UIState uiStateInstance)
Public Attributes
override Item SlottedItem => _itemPanel.item
Public Attributes inherited from Loot.UI.Core.VisibilityUI
bool Visible
Protected Member Functions
override void DrawChildren (SpriteBatch spriteBatch)
override void DrawSelf (SpriteBatch spriteBatch)
Protected Member Functions inherited from Loot.UI.Core.DraggableUIState
void AddDragPanel (UIPanel panel)
override void DrawSelf (SpriteBatch spriteBatch)
Private Member Functions
void TrySealingSlottedItem (UIMouseEvent evt, UIElement listeningelement)
Private Attributes
UIPanel _backPanel
int _cubeCount
UIImageButton _cubePanel
const float padding = 5f
Additional Inherited Members
Properties inherited from Loot.UI.Core.CubeUI
abstract Item SlottedItem [get]
Detailed Description
Definition at line 15 of file CubeSealUI.cs.
Member Function Documentation
override void Loot.UI.Sealing.CubeSealUI.DrawChildren (SpriteBatch spriteBatch) protected
Definition at line 113 of file CubeSealUI.cs.
         {
             base.DrawChildren(spriteBatch);
             var cubeDimensions = _cubePanel.GetInnerDimensions();
             Utils.DrawBorderStringFourWay(
                 spriteBatch,
                 Main.fontItemStack,
                 _cubeCount.ToString(),
                 cubeDimensions.Position().X + 10f,
                 cubeDimensions.Position().Y + 26f,
                 Color.White,
                 Color.Black,
                 Vector2.Zero,
                 0.8f);
         }
override void Loot.UI.Sealing.CubeSealUI.DrawSelf (SpriteBatch spriteBatch) protected
Definition at line 102 of file CubeSealUI.cs.
         {
             base.DrawSelf(spriteBatch);
             if (_cubePanel.IsMouseHovering)
             {
                 Main.hoverItemName = "Click to seal slotted item's modifiers" +
                                      "\nIf an item is already sealed the seal will be removed";
             }
         }
override bool Loot.UI.Sealing.CubeSealUI.IsItemValidForUISlot (Item item) virtual
Implements Loot.UI.Core.CubeUI.
Definition at line 23 of file CubeSealUI.cs.
References Loot.UI.Sealing.UISealItemPanel.CanTakeItem().
         {
             return _itemPanel != null && _itemPanel.CanTakeItem(item);
         }
override bool Loot.UI.Sealing.CubeSealUI.IsSlottedItemInCubeUI () virtual
Implements Loot.UI.Core.CubeUI.
Definition at line 28 of file CubeSealUI.cs.
References Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UIItemPanel.item, and Loot.EMMItem.SlottedInCubeUI.
         {
             return _itemPanel != null && !_itemPanel.item.IsAir && EMMItem.GetItemInfo(_itemPanel.item).SlottedInCubeUI;
         }
override void Loot.UI.Sealing.CubeSealUI.OnInitialize ()
Definition at line 64 of file CubeSealUI.cs.
         {
             // Makes back panel, and assigns it as the drag panel
             _backPanel = new UIPanel();
             _backPanel.Width.Set(135f, 0f);
             _backPanel.Height.Set(70f, 0f);
             _backPanel.Left.Set(Main.screenWidth / 2f - _backPanel.Width.Pixels / 2f, 0f);
             _backPanel.Top.Set(Main.screenHeight / 2f - _backPanel.Height.Pixels / 2f, 0f);
             _backPanel.BackgroundColor = new Color(73, 94, 171);
             base.Append(_backPanel);
             AddDragPanel(_backPanel);
             base.OnInitialize();
             var sealCubeTexture = Loot.Instance.GetTexture("Core/Cubes/CubeOfSealing");
             _cubePanel = new UIImageButton(sealCubeTexture);
             _cubePanel.Width.Set(sealCubeTexture.Width, 0f);
             _cubePanel.Height.Set(sealCubeTexture.Height, 0f);
             _cubePanel.Left.Set(padding, 0f);
             _cubePanel.Top.Set(padding, 0f);
             _cubePanel.OnClick += TrySealingSlottedItem;
             _backPanel.Append(_cubePanel);
             _itemPanel = new UISealItemPanel(hintTexture: ModContent.GetTexture("Terraria/Item_24"), hintText: "Place an item to seal here");
             _itemPanel.Width.Set(UIItemPanel.PANEL_WIDTH, 0f);
             _itemPanel.Height.Set(UIItemPanel.PANEL_HEIGHT, 0f);
             _itemPanel.Left.Set(_cubePanel.Left.Pixels + _cubePanel.Width.Pixels + padding, 0f);
             _backPanel.Append(_itemPanel);
             Texture2D btnCloseTexture = ModContent.GetTexture("Terraria/UI/InfoIcon_8");
             UIImageButton closeButton = new UIImageButton(btnCloseTexture);
             closeButton.Left.Set(_backPanel.Width.Pixels - btnCloseTexture.Width - 20f, 0f);
             closeButton.Top.Set(0f, 0f);
             closeButton.Width.Set(btnCloseTexture.Width, 0f);
             closeButton.Height.Set(btnCloseTexture.Height, 0f);
             closeButton.OnClick += (evt, element) => { ToggleUI(Loot.Instance.CubeInterface, Loot.Instance.CubeSealUI); };
             _backPanel.Append(closeButton);
         }
override void Loot.UI.Sealing.CubeSealUI.ToggleUI (Terraria.UI.UserInterface theInterface, UIState uiStateInstance)
Definition at line 44 of file CubeSealUI.cs.
References Loot.UI.Core.UIItemPanel.item.
         {
             base.ToggleUI(theInterface, uiStateInstance);
             if (!Visible)
             {
                 SoundHelper.PlayCustomSound(SoundHelper.SoundType.CloseUI);
                 if (_itemPanel != null && !_itemPanel.item.IsAir)
                 {
                     Main.LocalPlayer.QuickSpawnClonedItem(_itemPanel.item);
                     _itemPanel.item.TurnToAir();
                 }
             }
             else
             {
                 RecalculateCubeCount();
             }
         }
void Loot.UI.Sealing.CubeSealUI.TrySealingSlottedItem (UIMouseEvent evt, UIElement listeningelement) private
Definition at line 130 of file CubeSealUI.cs.
References Loot.EMMItem.GetActivePool(), Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UIItemPanel.item, and Loot.EMMItem.SealedModifiers.
         {
             if (_cubeCount <= 0
                 || _itemPanel.item.IsAir
                 || !_itemPanel.item.IsModifierRollableItem()
                 || !EMMItem.GetActivePool(_itemPanel.item).Any())
             {
                 SoundHelper.PlayCustomSound(SoundHelper.SoundType.Decline);
                 return;
             }
             var cube = Main.LocalPlayer.inventory.FirstOrDefault(x => x.modItem is CubeOfSealing);
             if (cube != null)
             {
                 cube.stack--;
                 if (cube.stack <= 0)
                 {
                     cube.TurnToAir();
                 }
                 RecalculateCubeCount();
                 var info = EMMItem.GetItemInfo(_itemPanel.item);
                 info.SealedModifiers = !info.SealedModifiers;
                 SoundHelper.PlayCustomSound(info.SealedModifiers ? SoundHelper.SoundType.GainSeal : SoundHelper.SoundType.LoseSeal);
             }
         }
Member Data Documentation
UIPanel Loot.UI.Sealing.CubeSealUI._backPanel private
Definition at line 17 of file CubeSealUI.cs.
int Loot.UI.Sealing.CubeSealUI._cubeCount private
Definition at line 18 of file CubeSealUI.cs.
UIImageButton Loot.UI.Sealing.CubeSealUI._cubePanel private
Definition at line 19 of file CubeSealUI.cs.
const float Loot.UI.Sealing.CubeSealUI.padding = 5f private
Definition at line 21 of file CubeSealUI.cs.
override Item Loot.UI.Sealing.CubeSealUI.SlottedItem => _itemPanel.item
Definition at line 33 of file CubeSealUI.cs.
Referenced by Loot.Loot.PreSaveAndQuit().