Even More Modifiers: Loot.Core.ModContent.ModContent Class Reference
Loot.Core.ModContent.ModContent Class Reference abstract
Public Member Functions
void _Initialize ()
void _Load ()
void _Unload ()
void AddTexture (string key, Texture2D texture)
abstract string GetRegistryKey ()
Texture2D GetTexture (string key)
Protected Member Functions
void AddTo (IDictionary< string, Texture2D > dictionary, string key, Texture2D texture)
Texture2D GetFrom (IDictionary< string, Texture2D > dictionary, string key)
virtual void Initialize ()
virtual void Load ()
virtual void ProcessTexture2D (ref Texture2D texture)
virtual void Unload ()
Protected Attributes
IDictionary< string, Texture2D > _textures
Detailed Description
Definition at line 7 of file ModContent.cs.
Member Function Documentation
void Loot.Core.ModContent.ModContent._Initialize ()
Definition at line 39 of file ModContent.cs.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
         {
             _textures = new Dictionary<string, Texture2D>();
             Initialize();
         }
void Loot.Core.ModContent.ModContent._Load ()
Definition at line 45 of file ModContent.cs.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
         {
             Load();
         }
void Loot.Core.ModContent.ModContent._Unload ()
Definition at line 50 of file ModContent.cs.
         {
             _textures = null;
             Unload();
         }
void Loot.Core.ModContent.ModContent.AddTexture (string key, Texture2D texture)
Definition at line 34 of file ModContent.cs.
         {
             AddTo(_textures, key, texture);
         }
void Loot.Core.ModContent.ModContent.AddTo (IDictionary< string, Texture2D > dictionary, string key, Texture2D texture) protected
Definition at line 24 of file ModContent.cs.
         {
             if (dictionary.ContainsKey(key))
             {
                 throw new Exception($"Key '{key}' already present in ModContent");
             }
             ProcessTexture2D(ref texture);
             dictionary.Add(key, texture);
         }
Texture2D Loot.Core.ModContent.ModContent.GetFrom (IDictionary< string, Texture2D > dictionary, string key) protected
Definition at line 11 of file ModContent.cs.
         {
             // need c#7
             // ReSharper disable once InlineOutVariableDeclaration
             Texture2D texture;
             return dictionary.TryGetValue(key, out texture) ? texture : null;
         }
abstract string Loot.Core.ModContent.ModContent.GetRegistryKey () pure virtual
Implemented in Loot.Core.ModContent.ModGraphicsContent.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
Texture2D Loot.Core.ModContent.ModContent.GetTexture (string key)
Definition at line 19 of file ModContent.cs.
         {
             return GetFrom(_textures, key);
         }
virtual void Loot.Core.ModContent.ModContent.Initialize () protected virtual
Reimplemented in Loot.Core.ModContent.ModGraphicsContent.
Definition at line 56 of file ModContent.cs.
 { }
virtual void Loot.Core.ModContent.ModContent.Load () protected virtual
Reimplemented in Loot.Core.ModContent.ModGraphicsContent.
Definition at line 57 of file ModContent.cs.
 { }
virtual void Loot.Core.ModContent.ModContent.ProcessTexture2D (ref Texture2D texture) protected virtual
Reimplemented in Loot.Core.ModContent.ModGraphicsContent.
Definition at line 55 of file ModContent.cs.
 { }
virtual void Loot.Core.ModContent.ModContent.Unload () protected virtual
Reimplemented in Loot.Core.ModContent.ModGraphicsContent.
Definition at line 58 of file ModContent.cs.
 { }
Member Data Documentation
IDictionary<string, Texture2D> Loot.Core.ModContent.ModContent._textures protected
Definition at line 9 of file ModContent.cs.