Even More Modifiers: Loot.Core.Graphics.GlowmaskGlobalItem Class Reference
Loot.Core.Graphics.GlowmaskGlobalItem Class Reference
Public Member Functions
override void PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI)
void UpdateEntities (Item item)
Public Attributes
override bool CloneNewInstances => true
GlowmaskEntity[] GlowmaskEntities
override bool InstancePerEntity => true
bool NeedsUpdate
Detailed Description
Definition at line 10 of file GlowmaskGlobalItem.cs.
Member Function Documentation
override void Loot.Core.Graphics.GlowmaskGlobalItem.PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI)
Definition at line 40 of file GlowmaskGlobalItem.cs.
References Loot.Core.Graphics.GlowmaskEntity.DoDrawGlowmask(), Loot.Core.Graphics.GlowmaskEntity.DoDrawHitbox(), Loot.Core.Graphics.ShaderGlobalItem.ShaderEntities, and Loot.Core.Graphics.GlowmaskGlobalItem.UpdateEntities().
         {
             ShaderGlobalItem shaderInfo = item.GetGlobalItem<ShaderGlobalItem>();
             GlowmaskGlobalItem glowmaskInfo = item.GetGlobalItem<GlowmaskGlobalItem>();
             glowmaskInfo.UpdateEntities(item);
             for (int i = 0; i < glowmaskInfo.GlowmaskEntities.Length; i++)
             {
                 GlowmaskEntity glowmaskEntity = glowmaskInfo.GlowmaskEntities[i];
                 if (glowmaskEntity != null && shaderInfo.ShaderEntities[i] == null)
                 {
                     glowmaskEntity.DoDrawGlowmask(spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI);
                     glowmaskEntity.DoDrawHitbox(spriteBatch);
                 }
             }
         }
void Loot.Core.Graphics.GlowmaskGlobalItem.UpdateEntities (Item item)
Definition at line 18 of file GlowmaskGlobalItem.cs.
References Loot.EMMItem.GetActivePool(), and Loot.Core.System.Modifier.GetGlowmaskEntity().
Referenced by Loot.Core.Graphics.GlowmaskGlobalItem.PostDrawInWorld().
         {
             bool updateEntitiesArray = false;
             var pool = EMMItem.GetActivePool(item).ToArray();
             if (NeedsUpdate || GlowmaskEntities == null || GlowmaskEntities.Any(x => x != null && x.NeedsUpdate))
             {
                 GlowmaskEntities = new GlowmaskEntity[pool.Length];
                 updateEntitiesArray = true;
                 NeedsUpdate = false;
             }
             if (updateEntitiesArray)
             {
                 for (int i = 0; i < pool.Length; i++)
                 {
                     Modifier m = pool[i];
                     GlowmaskEntities[i] = m.GetGlowmaskEntity(item);
                 }
             }
         }
Member Data Documentation
override bool Loot.Core.Graphics.GlowmaskGlobalItem.CloneNewInstances => true
Definition at line 16 of file GlowmaskGlobalItem.cs.
GlowmaskEntity [] Loot.Core.Graphics.GlowmaskGlobalItem.GlowmaskEntities
Definition at line 12 of file GlowmaskGlobalItem.cs.
override bool Loot.Core.Graphics.GlowmaskGlobalItem.InstancePerEntity => true
Definition at line 15 of file GlowmaskGlobalItem.cs.
bool Loot.Core.Graphics.GlowmaskGlobalItem.NeedsUpdate
Definition at line 13 of file GlowmaskGlobalItem.cs.