Even More Modifiers: Loot.Modifiers.WeaponModifiers.CursedEffect Class Reference
Loot.Modifiers.WeaponModifiers.CursedEffect Class Reference
Public Member Functions
override void ResetEffects (ModifierPlayer player)
Automatically called when the ModPlayer does its ResetEffects Also automatically called when the delegations of the effect detach
Public Member Functions inherited from Loot.Core.System.Modifier.ModifierEffect
virtual void AttachDelegations (ModifierPlayer player)
Allows modders to perform various delegations when this modifier is detected to become active This method will be invoked one time when the modifier becomes 'active' Alternatively automatic delegation can be used, using the AutoDelegation attribute
virtual void Clone (ref ModifierEffect clone)
A modder can provide custom cloning of effects in this hook
object Clone ()
virtual void DetachDelegations (ModifierPlayer player)
Allows modders to undo their performed delegations in AttachDelegations
virtual void OnInitialize (ModifierPlayer player)
Called when the ModPlayer initializes the effect
Public Attributes
int CurseCount
Public Attributes inherited from Loot.Core.System.Modifier.ModifierEffect
string Name => GetType().Name
Private Member Functions
void Curse (ModifierPlayer player)
void CurseHolding (ModifierPlayer player)
Additional Inherited Members
Properties inherited from Loot.Core.System.Modifier.ModifierEffect
bool IsBeingDelegated [get, set]
Keeps track of if this particular modifier is being delegated or not This is used to check if this effect's automatic delegation needs to be performed
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Core.System.Core.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Detailed Description
Definition at line 12 of file CursedDamage.cs.
Member Function Documentation
void Loot.Modifiers.WeaponModifiers.CursedEffect.Curse (ModifierPlayer player) private
Definition at line 44 of file CursedDamage.cs.
         {
             if (CurseCount <= 0 || player.player.buffImmune[BuffID.Cursed])
                 return;
             if (player.player.lifeRegen > 0)
             {
                 player.player.lifeRegen = 0;
             }
             player.player.lifeRegen -= 2 * CurseCount;
             player.player.lifeRegenTime = 0;
         }
void Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding (ModifierPlayer player) private
Definition at line 25 of file CursedDamage.cs.
References Loot.EMMItem.GetActivePool(), Loot.ModifierPlayer.GetEffect(), Loot.ActivatedModifierItem.IsActivated, Loot.ActivatedModifierItem.Item(), and Loot.ModifierPlayer.Player().
         {
             Item checkItem = Main.mouseItem != null && !Main.mouseItem.IsAir ? Main.mouseItem : player.player.HeldItem;
             if (checkItem == null || checkItem.IsAir || !checkItem.IsWeapon()
                 || !ActivatedModifierItem.Item(checkItem).IsActivated)
                 return;
             int c = EMMItem.GetActivePool(checkItem).Count(x => x.GetType() == typeof(CursedDamage));
             if (c > 0)
             {
                 ModifierPlayer.Player(player.player).GetEffect<CursedEffect>().CurseCount += c;
             }
         }
override void Loot.Modifiers.WeaponModifiers.CursedEffect.ResetEffects (ModifierPlayer player) virtual
Automatically called when the ModPlayer does its ResetEffects Also automatically called when the delegations of the effect detach
Reimplemented from Loot.Core.System.Modifier.ModifierEffect.
Definition at line 16 of file CursedDamage.cs.
         {
             CurseCount = 0;
         }
Member Data Documentation
int Loot.Modifiers.WeaponModifiers.CursedEffect.CurseCount
Definition at line 14 of file CursedDamage.cs.