Even More Modifiers: Loot.RollingStrategies.SealingRollingStrategy Class Reference
Loot.RollingStrategies.SealingRollingStrategy Class Reference
Public Member Functions
override void PlaySoundEffect (Item item)
override void PostRoll (ref List< Modifier > modifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
override List< Modifier > PreRoll (ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
override List< Modifier > Roll (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
Public Member Functions inherited from Loot.Api.Strategy.RollingStrategy
virtual void PostRollLine (ref List< Modifier > modifiers, Modifier line, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual Modifier PreRollLine (ref List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties)
virtual Modifier RollLine (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties, WeightedRandom< Modifier > weightedRandom)
Additional Inherited Members
Protected Attributes inherited from Loot.Api.Strategy.RollingStrategy
bool _forceNextRoll
LootModItem modifierItem
RollingStrategyProperties properties
Detailed Description
Definition at line 9 of file SealingRollingStrategy.cs.
Member Function Documentation
override void Loot.RollingStrategies.SealingRollingStrategy.PlaySoundEffect (Item item) virtual
Reimplemented from Loot.Api.Strategy.RollingStrategy.
Definition at line 29 of file SealingRollingStrategy.cs.
References Loot.LootModItem.GetInfo(), and Loot.LootModItem.SealedModifiers.
         {
             SoundHelper.PlayCustomSound(LootModItem.GetInfo(item).SealedModifiers ? SoundHelper.SoundType.GainSeal : SoundHelper.SoundType.LoseSeal);
         }
override void Loot.RollingStrategies.SealingRollingStrategy.PostRoll (ref List< Modifier > modifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented from Loot.Api.Strategy.RollingStrategy.
Definition at line 23 of file SealingRollingStrategy.cs.
References Loot.LootModItem.GetInfo(), Loot.Api.Core.ModifierContext.Item, and Loot.LootModItem.SealedModifiers.
         {
             var info = LootModItem.GetInfo(modifierContext.Item);
             info.SealedModifiers = !info.SealedModifiers;
         }
override List<Modifier> Loot.RollingStrategies.SealingRollingStrategy.PreRoll (ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented from Loot.Api.Strategy.RollingStrategy.
Definition at line 11 of file SealingRollingStrategy.cs.
References Loot.LootModItem.GetActivePool(), and Loot.Api.Core.ModifierContext.Item.
         {
             return LootModItem.GetActivePool(modifierContext.Item);
         }
override List<Modifier> Loot.RollingStrategies.SealingRollingStrategy.Roll (List< Modifier > currentModifiers, ModifierPool drawPool, ModifierContext modifierContext, RollingStrategyProperties properties) virtual
Reimplemented from Loot.Api.Strategy.RollingStrategy.
Definition at line 16 of file SealingRollingStrategy.cs.
References Loot.Api.Strategy.RollingStrategyProperties.MaxRollableLines, and Loot.Api.Strategy.RollingStrategyProperties.MinModifierRolls.
         {
             properties.MinModifierRolls = 0;
             properties.MaxRollableLines = 0;
             return base.Roll(currentModifiers, drawPool, modifierContext, properties);
         }