Even More Modifiers: Loot.ModifierPlayer Class Reference
Loot.ModifierPlayer Class Reference
Holds player-entity data and handles it
Public Member Functions
ModifierEffect GetEffect (Type type)
T GetEffect< T > ()
bool HasEffect (Type type)
bool HasEffect< T > ()
override void Initialize ()
override void ModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
delegate void ModifyHitNPCEventRaiser (ModifierPlayer player, Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
override void ModifyHitPvp (Item item, Player target, ref int damage, ref bool crit)
delegate void ModifyHitPvpEventRaiser (ModifierPlayer player, Item item, Player target, ref int damage, ref bool crit)
override void OnEnterWorld (Player player)
override void OnHitNPC (Item item, NPC target, int damage, float knockback, bool crit)
delegate void OnHitNPCEventRaiser (ModifierPlayer player, Item item, NPC target, int damage, float knockback, bool crit)
override void OnHitPvp (Item item, Player target, int damage, bool crit)
delegate void OnHitPvpEventRaiser (ModifierPlayer player, Item item, Player target, int damage, bool crit)
override void PostHurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
delegate void PostHurtEventRaiser (ModifierPlayer player, bool pvp, bool quiet, double damage, int hitDirection, bool crit)
override void PostUpdate ()
override void PostUpdateEquips ()
override bool PreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool PreHurtEventRaiser (ModifierPlayer player, bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override bool PreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool PreKillEventRaiser (ModifierPlayer player, double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override void PreUpdate ()
override void ResetEffects ()
override void SetupStartInventory (IList< Item > items, bool mediumcoreDeath)
override void UpdateBadLifeRegen ()
override void UpdateLifeRegen ()
delegate void VoidEventRaiser (ModifierPlayer player)
Static Public Member Functions
static ModifierPlayer Player (Player player)
Events
VoidEventRaiser OnInitialize
ModifyHitNPCEventRaiser OnModifyHitNPC
ModifyHitPvpEventRaiser OnModifyHitPvp
OnHitNPCEventRaiser OnOnHitNPC
OnHitPvpEventRaiser OnOnHitPvp
PostHurtEventRaiser OnPostHurt
VoidEventRaiser OnPostUpdate
VoidEventRaiser OnPostUpdateEquips
PreHurtEventRaiser OnPreHurt
PreKillEventRaiser OnPreKill
VoidEventRaiser OnPreUpdate
VoidEventRaiser OnResetEffects
VoidEventRaiser OnUpdateBadLifeRegen
VoidEventRaiser OnUpdateLifeRegen
Private Attributes
IList< ModifierEffect > _modifierEffects
Detailed Description
Holds player-entity data and handles it
Definition at line 17 of file ModifierPlayer.cs.
Member Function Documentation
ModifierEffect Loot.ModifierPlayer.GetEffect (Type type)
Definition at line 24 of file ModifierPlayer.cs.
Referenced by Loot.Core.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.Modifiers.Base.WeaponDebuffModifier.HoldItem(), Loot.ModifierProjectile.PreAI(), Loot.EMMItem.RollNewModifiers(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.UpdateEquip(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.UpdateEquip().
         {
             return _modifierEffects.FirstOrDefault(x => x.GetType() == type);
         }
T Loot.ModifierPlayer.GetEffect< T > ()
Type Constraints
T : ModifierEffect
Definition at line 29 of file ModifierPlayer.cs.
                                         : ModifierEffect
         {
             return (T) _modifierEffects.FirstOrDefault(x => x.GetType() == typeof(T));
         }
bool Loot.ModifierPlayer.HasEffect (Type type)
bool Loot.ModifierPlayer.HasEffect< T > ()
Type Constraints
T : ModifierEffect
T : _modifierEffects.Any
T : x
T : x.GetType()
T : typeof
T : T
override void Loot.ModifierPlayer.Initialize ()
Definition at line 53 of file ModifierPlayer.cs.
References Loot.Core.System.Loaders.ContentLoader.ModifierEffect.
         {
             // Initialize the effects list for this player
             _modifierEffects = new List<ModifierEffect>();
             // Need to initialize with a fresh set of new effect instances
             foreach (var effect in ContentLoader.ModifierEffect.Content.Select(x => x.Value))
             {
                 var clone = (ModifierEffect) effect.Clone();
                 clone.OnInitialize(this);
                 _modifierEffects.Add(clone);
             }
             OnInitialize?.Invoke(this);
         }
override void Loot.ModifierPlayer.ModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
Definition at line 141 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.ModifyHitPvpEventRaiser(), and Loot.ModifierPlayer.Player().
         {
             OnModifyHitNPC?.Invoke(this, item, target, ref damage, ref knockback, ref crit);
         }
delegate void Loot.ModifierPlayer.ModifyHitNPCEventRaiser (ModifierPlayer player, Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
Referenced by Loot.ModifierPlayer.PostHurt().
override void Loot.ModifierPlayer.ModifyHitPvp (Item item, Player target, ref int damage, ref bool crit)
Definition at line 150 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.OnHitNPCEventRaiser().
         {
             OnModifyHitPvp?.Invoke(this, item, target, ref damage, ref crit);
         }
delegate void Loot.ModifierPlayer.ModifyHitPvpEventRaiser (ModifierPlayer player, Item item, Player target, ref int damage, ref bool crit)
Referenced by Loot.ModifierPlayer.ModifyHitNPC().
override void Loot.ModifierPlayer.OnEnterWorld (Player player)
Definition at line 42 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.Player(), and Loot.ModifierPlayer.VoidEventRaiser().
         {
             EMMWorld.WorldGenModifiersPass.GenerateModifiers(null, ModifierContextMethod.FirstLoad, player.inventory.Where(x => !x.IsAir && x.IsModifierRollableItem()).Concat(player.armor.Where(x => !x.IsAir && !x.IsModifierRollableItem())), player);
         }
override void Loot.ModifierPlayer.OnHitNPC (Item item, NPC target, int damage, float knockback, bool crit)
Definition at line 159 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.OnHitPvpEventRaiser(), and Loot.ModifierPlayer.Player().
         {
             OnOnHitNPC?.Invoke(this, item, target, damage, knockback, crit);
         }
delegate void Loot.ModifierPlayer.OnHitNPCEventRaiser (ModifierPlayer player, Item item, NPC target, int damage, float knockback, bool crit)
Referenced by Loot.ModifierPlayer.ModifyHitPvp().
override void Loot.ModifierPlayer.OnHitPvp (Item item, Player target, int damage, bool crit)
Definition at line 168 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.PreKillEventRaiser().
         {
             OnOnHitPvp?.Invoke(this, item, target, damage, crit);
         }
delegate void Loot.ModifierPlayer.OnHitPvpEventRaiser (ModifierPlayer player, Item item, Player target, int damage, bool crit)
Referenced by Loot.ModifierPlayer.OnHitNPC().
static ModifierPlayer Loot.ModifierPlayer.Player (Player player) static
Referenced by Loot.Core.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.Modifiers.Base.WeaponDebuffModifier.HoldItem(), Loot.ModifierPlayer.ModifyHitNPC(), Loot.ModifierPlayer.OnEnterWorld(), Loot.ModifierPlayer.OnHitNPC(), Loot.EMMItem.RollNewModifiers(), Loot.Core.Caching.ModifierCachePlayer.UpdateAttachments(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.UpdateEquip(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.UpdateEquip().
override void Loot.ModifierPlayer.PostHurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
Definition at line 132 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.ModifyHitNPCEventRaiser().
         {
             OnPostHurt?.Invoke(this, pvp, quiet, damage, hitDirection, crit);
         }
delegate void Loot.ModifierPlayer.PostHurtEventRaiser (ModifierPlayer player, bool pvp, bool quiet, double damage, int hitDirection, bool crit)
Referenced by Loot.ModifierPlayer.PreHurt().
override void Loot.ModifierPlayer.PostUpdate ()
Definition at line 108 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.PreHurtEventRaiser().
         {
             OnPostUpdate?.Invoke(this);
         }
override void Loot.ModifierPlayer.PostUpdateEquips ()
Definition at line 101 of file ModifierPlayer.cs.
         {
             OnPostUpdateEquips?.Invoke(this);
         }
override bool Loot.ModifierPlayer.PreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Definition at line 117 of file ModifierPlayer.cs.
References Loot.ModifierPlayer.PostHurtEventRaiser().
         {
             bool b = base.PreHurt(pvp, quiet, ref damage, ref hitDirection, ref crit, ref customDamage, ref playSound, ref genGore, ref damageSource);
             if (OnPreHurt != null)
             {
                 b &= OnPreHurt.Invoke(this, pvp, quiet, ref damage, ref hitDirection, ref crit, ref customDamage, ref playSound, ref genGore, ref damageSource);
             }
             return b;
         }
delegate bool Loot.ModifierPlayer.PreHurtEventRaiser (ModifierPlayer player, bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Referenced by Loot.ModifierPlayer.PostUpdate().
override bool Loot.ModifierPlayer.PreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Definition at line 177 of file ModifierPlayer.cs.
         {
             bool b = base.PreKill(damage, hitDirection, pvp, ref playSound, ref genGore, ref damageSource);
             if (OnPreKill != null)
             {
                 b &= OnPreKill.Invoke(this, damage, hitDirection, pvp, ref playSound, ref genGore, ref damageSource);
             }
             return b;
         }
delegate bool Loot.ModifierPlayer.PreKillEventRaiser (ModifierPlayer player, double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Referenced by Loot.ModifierPlayer.OnHitPvp().
override void Loot.ModifierPlayer.PreUpdate ()
Definition at line 70 of file ModifierPlayer.cs.
         {
             OnPreUpdate?.Invoke(this);
         }
override void Loot.ModifierPlayer.ResetEffects ()
Definition at line 77 of file ModifierPlayer.cs.
         {
             if (player.GetModPlayer<ModifierCachePlayer>().Ready)
             {
                 OnResetEffects?.Invoke(this);
             }
         }
override void Loot.ModifierPlayer.SetupStartInventory (IList< Item > items, bool mediumcoreDeath)
Definition at line 34 of file ModifierPlayer.cs.
         {
             if (!mediumcoreDeath)
             {
                 EMMWorld.WorldGenModifiersPass.GenerateModifiers(null, ModifierContextMethod.SetupStartInventory, items.Where(x => !x.IsAir && x.IsModifierRollableItem()), player);
             }
         }
override void Loot.ModifierPlayer.UpdateBadLifeRegen ()
Definition at line 94 of file ModifierPlayer.cs.
         {
             OnUpdateBadLifeRegen?.Invoke(this);
         }
override void Loot.ModifierPlayer.UpdateLifeRegen ()
Definition at line 87 of file ModifierPlayer.cs.
         {
             OnUpdateLifeRegen?.Invoke(this);
         }
delegate void Loot.ModifierPlayer.VoidEventRaiser (ModifierPlayer player)
Referenced by Loot.ModifierPlayer.OnEnterWorld().
Member Data Documentation
IList<ModifierEffect> Loot.ModifierPlayer._modifierEffects private
Definition at line 19 of file ModifierPlayer.cs.
Event Documentation
VoidEventRaiser Loot.ModifierPlayer.OnInitialize
Definition at line 51 of file ModifierPlayer.cs.
ModifyHitNPCEventRaiser Loot.ModifierPlayer.OnModifyHitNPC
Definition at line 139 of file ModifierPlayer.cs.
ModifyHitPvpEventRaiser Loot.ModifierPlayer.OnModifyHitPvp
Definition at line 148 of file ModifierPlayer.cs.
OnHitNPCEventRaiser Loot.ModifierPlayer.OnOnHitNPC
Definition at line 157 of file ModifierPlayer.cs.
OnHitPvpEventRaiser Loot.ModifierPlayer.OnOnHitPvp
Definition at line 166 of file ModifierPlayer.cs.
PostHurtEventRaiser Loot.ModifierPlayer.OnPostHurt
Definition at line 130 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnPostUpdate
Definition at line 106 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnPostUpdateEquips
Definition at line 99 of file ModifierPlayer.cs.
PreHurtEventRaiser Loot.ModifierPlayer.OnPreHurt
Definition at line 115 of file ModifierPlayer.cs.
PreKillEventRaiser Loot.ModifierPlayer.OnPreKill
Definition at line 175 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnPreUpdate
Definition at line 68 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnResetEffects
Definition at line 75 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnUpdateBadLifeRegen
Definition at line 92 of file ModifierPlayer.cs.
VoidEventRaiser Loot.ModifierPlayer.OnUpdateLifeRegen
Definition at line 85 of file ModifierPlayer.cs.