Even More Modifiers: Loot.UI.CubeRerollUI Class Reference
Loot.UI.CubeRerollUI Class Reference
A UIState that provides the ability to reroll an item's modifier
Public Member Functions
override bool IsItemValidForUISlot (Item item)
override bool IsSlottedItemInCubeUI ()
override void OnInitialize ()
override void ToggleUI (UserInterface theInterface, UIState uiStateInstance)
void UpdateModifierLines ()
Public Member Functions inherited from Loot.UI.DraggableUIState
override void OnInitialize ()
Public Attributes
override Item SlottedItem => _rerollItemPanel.item
Public Attributes inherited from Loot.UI.VisibilityUI
bool Visible
Private Member Functions
bool MatchesRerollRequirements ()
void OnRerollClick (UIMouseEvent evt, UIElement listeningelement)
void RerollModifierPool (Item newItem)
Private Attributes
UIPanel _backPanel
UIModifierPanel[] _modifierPanels
UIImageButton _rerollButton
const float padding = 5f
Additional Inherited Members
Protected Member Functions inherited from Loot.UI.DraggableUIState
void AssignDragPanel (UIPanel panel)
override void DrawSelf (SpriteBatch spriteBatch)
Properties inherited from Loot.UI.CubeUI
abstract Item SlottedItem [get]
Detailed Description
A UIState that provides the ability to reroll an item's modifier
Definition at line 21 of file CubeRerollUI.cs.
Member Function Documentation
override bool Loot.UI.CubeRerollUI.IsItemValidForUISlot (Item item) virtual
Implements Loot.UI.CubeUI.
Definition at line 58 of file CubeRerollUI.cs.
References Loot.UI.UIRerollItemPanel.CanTakeItem().
         {
             return _rerollItemPanel != null && _rerollItemPanel.CanTakeItem(item);
         }
override bool Loot.UI.CubeRerollUI.IsSlottedItemInCubeUI () virtual
Implements Loot.UI.CubeUI.
Definition at line 63 of file CubeRerollUI.cs.
References Loot.EMMItem.GetItemInfo(), Loot.UI.UIItemPanel.item, and Loot.EMMItem.SlottedInCubeUI.
         {
             return _rerollItemPanel != null && !_rerollItemPanel.item.IsAir && EMMItem.GetItemInfo(_rerollItemPanel.item).SlottedInCubeUI;
         }
bool Loot.UI.CubeRerollUI.MatchesRerollRequirements () private
Definition at line 125 of file CubeRerollUI.cs.
References Loot.UI.UIRerollItemPanel.CanTakeItem(), Loot.UI.UICubeItemPanel.CanTakeItem(), Loot.EMMItem.GetItemInfo(), Loot.UI.UIItemPanel.item, and Loot.EMMItem.SealedModifiers.
         {
             bool match = _rerollItemPanel != null
                    && _cubePanel != null
                    && !_rerollItemPanel.item.IsAir && !_cubePanel.item.IsAir
                    && _rerollItemPanel.CanTakeItem(_rerollItemPanel.item)
                    && _cubePanel.CanTakeItem(_cubePanel.item)
                    && !EMMItem.GetItemInfo(_rerollItemPanel.item).SealedModifiers;
             bool hasItem = Main.LocalPlayer.inventory.Any(x => x.type == _cubePanel.item.type)
                            || (Main.mouseItem?.type == _cubePanel?.item?.type);
             return match && hasItem;
         }
override void Loot.UI.CubeRerollUI.OnInitialize ()
Definition at line 70 of file CubeRerollUI.cs.
         {
             _itemRollProperties = new ItemRollProperties();
             // Makes back panel, and assigns it as the drag panel
             _backPanel = new UIPanel();
             _backPanel.Width.Set(600f, 0f);
             _backPanel.Height.Set(200f, 0f);
             _backPanel.Left.Set(Main.screenWidth / 2f - _backPanel.Width.Pixels / 2f, 0f);
             _backPanel.Top.Set(Main.screenHeight / 2f - _backPanel.Height.Pixels / 2f, 0f);
             _backPanel.BackgroundColor = new Color(73, 94, 171);
             base.Append(_backPanel);
             AssignDragPanel(_backPanel);
             base.OnInitialize();
             Texture2D btnCloseTexture = ModLoader.GetTexture("Terraria/UI/InfoIcon_8");
             UIImageButton closeButton = new UIImageButton(btnCloseTexture);
             closeButton.Left.Set(_backPanel.Width.Pixels - btnCloseTexture.Width * 2f - padding, 0f);
             closeButton.Top.Set(0f, 0f);
             closeButton.Width.Set(btnCloseTexture.Width, 0f);
             closeButton.Height.Set(btnCloseTexture.Height, 0f);
             closeButton.OnClick += (evt, element) => { ToggleUI(Loot.Instance.CubeInterface, Loot.Instance.CubeRerollUI); };
             _backPanel.Append(closeButton);
             _cubePanel = new UICubeItemPanel(hintTexture: Loot.Instance.GetTexture("Core/Cubes/MagicalCube"), hintText: "Place a cube here");
             _cubePanel.Top.Set(0f, 0f);
             _backPanel.Append(_cubePanel);
             _rerollItemPanel = new UIRerollItemPanel(hintTexture: ModLoader.GetTexture("Terraria/Item_24"), hintText: "Place an item to reroll here");
             _rerollItemPanel.Top.Set(_cubePanel.Top.Pixels + _rerollItemPanel.Height.Pixels + padding, 0f);
             _backPanel.Append(_rerollItemPanel);
             _modifierPanels = new UIModifierPanel[4];
             for (int i = 0; i < 4; i++)
             {
                 _modifierPanels[i] = new UIModifierPanel();
                 var panel = _modifierPanels[i];
                 panel.Left.Set(padding + _cubePanel.Left.Pixels + _cubePanel.Width.Pixels, 0f);
                 panel.Height.Set(40, 0f);
                 panel.Top.Set(i * padding + panel.Height.Pixels * i, 0f);
                 panel.Width.Set(_backPanel.Width.Pixels - closeButton.Width.Pixels * 2f - panel.Left.Pixels - padding * 2f, 0f);
                 panel.BackgroundColor = new Color(73, 94, 171);
                 _backPanel.Append(panel);
             }
             Texture2D rerollTexture = ModLoader.GetTexture("Terraria/UI/Craft_Toggle_3");
             _rerollButton = new UIImageButton(rerollTexture);
             _rerollButton.Width.Set(UIItemPanel.panelwidth, 0f);
             _rerollButton.Height.Set(UIItemPanel.panelwidth, 0f);
             _rerollButton.Top.Set(_rerollItemPanel.Top.Pixels + _rerollItemPanel.Height.Pixels + padding, 0f);
             _rerollButton.OnClick += OnRerollClick;
             _backPanel.Append(_rerollButton);
         }
void Loot.UI.CubeRerollUI.OnRerollClick (UIMouseEvent evt, UIElement listeningelement) private
Definition at line 158 of file CubeRerollUI.cs.
References Loot.EMMItem.GetItemInfo(), Loot.UI.UICubeItemPanel.InteractionLogic(), Loot.UI.UIItemPanel.item, and Loot.EMMItem.ModifierPool.
         {
             if (MatchesRerollRequirements())
             {
                 _itemRollProperties = new ItemRollProperties();
                 _cubePanel.InteractionLogic(_itemRollProperties);
                 _cubePanel.RecalculateStack();
                 // No slotted cubes available
                 if (_cubePanel.item.stack <= 0)
                 {
                     SoundHelper.PlayCustomSound(SoundHelper.SoundType.Decline);
                     _cubePanel.item.TurnToAir();
                     return;
                 }
                 // Refresh item
                 Item newItem = new Item();
                 newItem.netDefaults(_rerollItemPanel.item.type);
                 // Clone to preserve modded data
                 newItem = newItem.CloneWithModdedDataFrom(_rerollItemPanel.item);
                 EMMItem.GetItemInfo(newItem).ModifierPool = null; // unload previous pool
                 // Restore prefix
                 if (_rerollItemPanel.item.prefix > 0)
                 {
                     newItem.Prefix(_rerollItemPanel.item.prefix);
                 }
                 RerollModifierPool(newItem);
                 UpdateModifierLines();
                 Main.PlaySound(SoundID.Item37, -1, -1);
                 bool checkMouse = true;
                 // Remove stack from player's inventory
                 // .Take 58 because 59th slot is MouseItem for some reason.
                 foreach (Item item in Main.LocalPlayer.inventory.Take(58))
                 {
                     if (item.type == _cubePanel.item.type)
                     {
                         checkMouse = false;
                         item.stack--;
                         break;
                     }
                 }
                 if (checkMouse)
                 {
                     // This check should be redundant; otherwise we should never have reached this point
                     //if (Main.mouseItem?.type == _cubePanel.item.type)
                     Main.mouseItem.stack--;
                     if (Main.mouseItem.stack <= 0)
                     {
                         Main.mouseItem.TurnToAir();
                     }
                 }
                 _cubePanel.RecalculateStack();
                 // No slotted cubes available
                 if (_cubePanel.item.stack <= 0)
                 {
                     _cubePanel.item.TurnToAir();
                 }
             }
             else
             {
                 SoundHelper.PlayCustomSound(SoundHelper.SoundType.Decline);
             }
         }
void Loot.UI.CubeRerollUI.RerollModifierPool (Item newItem) private
Definition at line 140 of file CubeRerollUI.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.UI.UIItemPanel.item.
         {
             ModifierContext ctx = new ModifierContext
             {
                 Method = ModifierContextMethod.OnCubeReroll,
                 Item = newItem,
                 Player = Main.LocalPlayer,
                 CustomData = new Dictionary<string, object>
                 {
                     {"Source", "CubeRerollUI"}
                 }
             };
             var pool = EMMItem.GetItemInfo(newItem).RollNewPool(ctx, _itemRollProperties);
             pool?.ApplyModifiers(newItem);
             _rerollItemPanel.item = newItem.Clone();
         }
override void Loot.UI.CubeRerollUI.ToggleUI (UserInterface theInterface, UIState uiStateInstance) virtual
Reimplemented from Loot.UI.VisibilityUI.
Definition at line 31 of file CubeRerollUI.cs.
         {
             base.ToggleUI(theInterface, uiStateInstance);
             // If ui closed, we need to retrieve the slotted items
             if (!Visible)
             {
                 var ui = Loot.Instance.CubeRerollUI;
                 SoundHelper.PlayCustomSound(SoundHelper.SoundType.CloseUI);
                 // Clear of the slotted cube type
                 ui._cubePanel?.item.TurnToAir();
                 // If there is an item slotted
                 if (ui._rerollItemPanel != null
                     && !ui._rerollItemPanel.item.IsAir)
                 {
                     Main.LocalPlayer.QuickSpawnClonedItem(ui._rerollItemPanel.item, ui._rerollItemPanel.item.stack);
                     ui._rerollItemPanel.item.TurnToAir();
                 }
                 // Clear lines
                 ui.UpdateModifierLines();
             }
         }
void Loot.UI.CubeRerollUI.UpdateModifierLines ()
Definition at line 229 of file CubeRerollUI.cs.
References Loot.EMMItem.GetActivePool(), and Loot.UI.UIItemPanel.item.
Referenced by Loot.Core.Cubes.CubeUIExtensions.RerollUITakeItem().
         {
             foreach (var panel in _modifierPanels)
             {
                 panel.ResetText();
             }
             if (_rerollItemPanel != null
                 && !_rerollItemPanel.item.IsAir
                 && _modifierPanels != null)
             {
                 int i = 0;
                 foreach (var lines in EMMItem.GetActivePool(_rerollItemPanel.item).Select(x => x.TooltipLines).Take(4))
                 {
                     string line = lines.Aggregate("", (current, tooltipLine) => current + $"{tooltipLine.Text} ");
                     line = line.TrimEnd();
                     _modifierPanels[i].UpdateText(line);
                     i++;
                 }
                 Recalculate();
             }
         }
Member Data Documentation
UIPanel Loot.UI.CubeRerollUI._backPanel private
Definition at line 23 of file CubeRerollUI.cs.
UIModifierPanel [] Loot.UI.CubeRerollUI._modifierPanels private
Definition at line 27 of file CubeRerollUI.cs.
UIImageButton Loot.UI.CubeRerollUI._rerollButton private
Definition at line 28 of file CubeRerollUI.cs.
const float Loot.UI.CubeRerollUI.padding = 5f private
Definition at line 29 of file CubeRerollUI.cs.
override Item Loot.UI.CubeRerollUI.SlottedItem => _rerollItemPanel.item
Definition at line 68 of file CubeRerollUI.cs.