Even More Modifiers: Loot.Hacks.CheatedItemHackGlobalItem Class Reference
Loot.Hacks.CheatedItemHackGlobalItem Class Reference
Can detect if an item was activated via cheats
Public Member Functions
bool IsInInventory (Item item, Player player)
bool IsInVanitySot (Item item, Player player)
Returns if the item is in a player's vanity slot
override void PostUpdate (Item item)
bool ShouldBeIgnored (Item item, Player player)
override void UpdateAccessory (Item item, Player player, bool hideVisual)
override void UpdateEquip (Item item, Player player)
override void UpdateInventory (Item item, Player player)
Static Public Member Functions
static CheatedItemHackGlobalItem GetInfo (Item item)
Public Attributes
override bool CloneNewInstances => true
override bool InstancePerEntity => true
Properties
bool IsCheated [get, set]
Keeps track of if the item was activated (by another mod) In this case activated means giving its regular bonuses Example: anti social in vanity slots
Private Member Functions
bool IsNotEquippedAtAll (Item item, Player player)
Detailed Description
Can detect if an item was activated via cheats
Definition at line 10 of file CheatedItemHackGlobalItem.cs.
Member Function Documentation
static CheatedItemHackGlobalItem Loot.Hacks.CheatedItemHackGlobalItem.GetInfo (Item item) static
Referenced by Loot.Caching.ModifierCachePlayer.CacheModifierEffects(), Loot.LootModItem.ModifyTooltips(), and Loot.Caching.ModifierCachePlayer.UpdateVanityCache().
bool Loot.Hacks.CheatedItemHackGlobalItem.IsInInventory (Item item, Player player)
bool Loot.Hacks.CheatedItemHackGlobalItem.IsInVanitySot (Item item, Player player)
Returns if the item is in a player's vanity slot
bool Loot.Hacks.CheatedItemHackGlobalItem.IsNotEquippedAtAll (Item item, Player player) private
override void Loot.Hacks.CheatedItemHackGlobalItem.PostUpdate (Item item)
Definition at line 59 of file CheatedItemHackGlobalItem.cs.
         {
             IsCheated = false;
         }
bool Loot.Hacks.CheatedItemHackGlobalItem.ShouldBeIgnored (Item item, Player player)
Referenced by Loot.LootModItem.ModifyTooltips().
override void Loot.Hacks.CheatedItemHackGlobalItem.UpdateAccessory (Item item, Player player, bool hideVisual)
Definition at line 38 of file CheatedItemHackGlobalItem.cs.
         {
             if (IsInVanitySot(item, player) || IsNotEquippedAtAll(item, player))
                 IsCheated = true;
             else
                 IsCheated = false;
         }
override void Loot.Hacks.CheatedItemHackGlobalItem.UpdateEquip (Item item, Player player)
Definition at line 46 of file CheatedItemHackGlobalItem.cs.
         {
             if (IsInVanitySot(item, player) || IsNotEquippedAtAll(item, player))
                 IsCheated = true;
             else
                 IsCheated = false;
         }
override void Loot.Hacks.CheatedItemHackGlobalItem.UpdateInventory (Item item, Player player)
Definition at line 54 of file CheatedItemHackGlobalItem.cs.
         {
             IsCheated = false;
         }
Member Data Documentation
override bool Loot.Hacks.CheatedItemHackGlobalItem.CloneNewInstances => true
Definition at line 13 of file CheatedItemHackGlobalItem.cs.
override bool Loot.Hacks.CheatedItemHackGlobalItem.InstancePerEntity => true
Definition at line 12 of file CheatedItemHackGlobalItem.cs.
Property Documentation
bool Loot.Hacks.CheatedItemHackGlobalItem.IsCheated get set
Keeps track of if the item was activated (by another mod) In this case activated means giving its regular bonuses Example: anti social in vanity slots
Definition at line 20 of file CheatedItemHackGlobalItem.cs.
Referenced by Loot.Caching.ModifierCachePlayer.CacheModifierEffects(), and Loot.Caching.ModifierCachePlayer.UpdateVanityCache().