Even More Modifiers: Loot.Core.System.Loaders.LoadingFunneler Class Reference
Loot.Core.System.Loaders.LoadingFunneler Class Reference
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Static Public Member Functions
static void AddMod (Mod mod)
Static Private Member Functions
static void LoadMod ()
static void LoadModForClient ()
static void UnloadMod ()
static void UnloadStaticRefs ()
Detailed Description
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Definition at line 17 of file LoadingFunneler.cs.
Member Function Documentation
static void Loot.Core.System.Loaders.LoadingFunneler.AddMod (Mod mod) static
Definition at line 19 of file LoadingFunneler.cs.
References Loot.Core.System.Loaders.MainLoader.AddContent(), and Loot.Core.System.Loaders.MainLoader.RegisterMod().
         {
             MainLoader.RegisterMod(mod);
             MainLoader.AddContent(mod);
         }
static void Loot.Core.System.Loaders.LoadingFunneler.LoadMod () static private
Definition at line 50 of file LoadingFunneler.cs.
References Loot.Core.System.Loaders.MainLoader.AddContent(), Loot.Core.System.Loaders.ContentLoader.Modifier, Loot.Core.System.Loaders.ContentLoader.ModifierEffect, Loot.Core.System.Loaders.ContentLoader.ModifierPool, Loot.Core.System.Loaders.ContentLoader.ModifierRarity, and Loot.Core.System.Loaders.MainLoader.RegisterMod().
         {
             ModSupportTunneler.Init();
             ContentLoader.Initialize();
             ContentLoader.Load();
             MainLoader.Initialize();
             MainLoader.Load();
             MainLoader.RegisterMod(Loot.Instance);
             ContentLoader.Modifier.AddContent(typeof(NullModifier), Loot.Instance);
             ContentLoader.ModifierPool.AddContent(typeof(NullModifierPool), Loot.Instance);
             ContentLoader.ModifierRarity.AddContent(typeof(NullModifierRarity), Loot.Instance);
             ContentLoader.ModifierEffect.AddContent(typeof(NullModifierEffect), Loot.Instance);
             MainLoader.AddContent(Loot.Instance);
             if (Main.dedServ)
             {
                 ModSupportTunneler.AddServerSupport();
             }
         }
static void Loot.Core.System.Loaders.LoadingFunneler.LoadModForClient () static private
Definition at line 73 of file LoadingFunneler.cs.
References Loot.Core.System.Loaders.AssetLoader.RegisterAssets().
         {
             Loot.ModContentManager = new ModContentManager();
             Loot.ModContentManager.Initialize(Loot.Instance);
             Loot.Instance.GuiInterface = new UserInterface();
             Loot.Instance.GuiState = new GuiTabWindow();
             Loot.Instance.GuiState.Activate();
             AssetLoader.RegisterAssets(Loot.Instance, "GraphicsAssets");
             ModSupportTunneler.AddClientSupport();
         }
static void Loot.Core.System.Loaders.LoadingFunneler.UnloadMod () static private
Definition at line 86 of file LoadingFunneler.cs.
         {
             ContentLoader.Unload();
             MainLoader.Unload();
             Loot.ModContentManager?.Unload();
             Loot.ModContentManager = null;
             //UnloadStaticRefs()
         }
static void Loot.Core.System.Loaders.LoadingFunneler.UnloadStaticRefs () static private
Definition at line 95 of file LoadingFunneler.cs.
         {
             // TODO causes trouble in unload?
             // Attempt to unload our static variables
             Stack<Type> typesToProcess = new Stack<Type>(Loot.Instance.Code.GetTypes());
             while (typesToProcess.Count > 0)
             {
                 Type type = typesToProcess.Pop();
                 foreach (FieldInfo info in type.GetFields(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                 {
                     info.SetValue(null, info.FieldType.IsValueType ? Activator.CreateInstance(info.FieldType) : null);
                 }
                 foreach (Type nestedType in type.GetNestedTypes(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                 {
                     typesToProcess.Push(nestedType);
                 }
             }
         }