Even More Modifiers: Loot.UI.Core.UICubeItemPanel Class Reference
Loot.UI.Core.UICubeItemPanel Class Reference
Public Member Functions
UICubeItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
override bool CanTakeItem (Item item)
void ChangeItem (int type)
void InteractionLogic (ItemRollProperties itemRollProperties)
override void PostOnClick (UIMouseEvent evt, UIElement e)
void RecalculateStack ()
Public Member Functions inherited from Loot.UI.Core.UIInteractableItemPanel
UIInteractableItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
virtual void PostOnRightClick ()
virtual void PreOnClick (UIMouseEvent evt, UIElement e)
override void Update (GameTime gameTime)
Public Member Functions inherited from Loot.UI.Core.UIItemPanel
UIItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null, string hintOnHover=null)
Additional Inherited Members
Public Attributes inherited from Loot.UI.Core.UIItemPanel
Item item = null
Protected Member Functions inherited from Loot.UI.Core.UIItemPanel
override void DrawSelf (SpriteBatch spriteBatch)
Protected Attributes inherited from Loot.UI.Core.UIInteractableItemPanel
bool RightClickFunctionalityEnabled = true
bool TakeUserItemOnClick = true
Properties inherited from Loot.UI.Core.UIInteractableItemPanel
bool PerformRegularClickInteraction [get, set]
Properties inherited from Loot.UI.Core.UIItemPanel
bool DrawBackgroundPanel [get, set]
Color DrawColor = 1f [get, set]
float DrawScale = false [get, set]
bool DrawStack = true [get, set]
string HintOnHover [get, set]
string HintText [get, set]
Texture2D HintTexture [get, set]
bool ShowOnlyHintOnHover = true [get, set]
Detailed Description
Definition at line 11 of file UICubeItemPanel.cs.
Constructor & Destructor Documentation
Loot.UI.Core.UICubeItemPanel.UICubeItemPanel (int netID = 0, int stack = 0, Texture2D hintTexture = null, string hintText = null)
Definition at line 13 of file UICubeItemPanel.cs.
                                                                                                                    :
             base(netID, stack, hintTexture, hintText)
         {
             this.RightClickFunctionalityEnabled = false;
             this.TakeUserItemOnClick = false;
             this.HintOnHover = " (click to unslot)";
         }
Member Function Documentation
override bool Loot.UI.Core.UICubeItemPanel.CanTakeItem (Item item) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Referenced by Loot.UI.Rerolling.CubeRerollUI.MatchesRerollRequirements().
void Loot.UI.Core.UICubeItemPanel.ChangeItem (int type)
Definition at line 32 of file UICubeItemPanel.cs.
         {
             item.SetDefaults(type);
             RecalculateStack();
         }
void Loot.UI.Core.UICubeItemPanel.InteractionLogic (ItemRollProperties itemRollProperties)
Definition at line 38 of file UICubeItemPanel.cs.
Referenced by Loot.UI.Rerolling.CubeRerollUI.OnRerollClick().
         {
             (item.modItem as RerollingCube)?.SetRollLogic(itemRollProperties);
         }
override void Loot.UI.Core.UICubeItemPanel.PostOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Definition at line 23 of file UICubeItemPanel.cs.
         {
             if (!this.item.IsAir)
             {
                 RecalculateStack();
             }
             Loot.Instance.CubeRerollUI.DetermineAvailableCubes();
         }
void Loot.UI.Core.UICubeItemPanel.RecalculateStack ()
Definition at line 43 of file UICubeItemPanel.cs.
Referenced by Loot.UI.Rerolling.CubeRerollUI.OnRerollClick().
         {
             item.stack = Main.LocalPlayer.inventory.CountItemStack(item.type, true);
             item.stack = (int)MathHelper.Clamp(item.stack, 0f, 999f);
         }