Even More Modifiers: Loot.Core.System.Modifier.ModifierTooltipBuilder Class Reference
Loot.Core.System.Modifier.ModifierTooltipBuilder Class Reference
Public Member Functions
ModifierTooltipLine[] Build ()
ModifierTooltipBuilder WithLine (ModifierTooltipLine line)
ModifierTooltipBuilder WithLine (string text, Color?color=null)
ModifierTooltipBuilder WithLines (IEnumerable< ModifierTooltipLine > lines)
ModifierTooltipBuilder WithNegative (string text)
ModifierTooltipBuilder WithNegatives (params string[] texts)
ModifierTooltipBuilder WithPositive (string text)
ModifierTooltipBuilder WithPositives (params string[] texts)
Private Attributes
readonly List< ModifierTooltipLine > _lines = new List<ModifierTooltipLine>()
Detailed Description
Definition at line 6 of file ModifierTooltipBuilder.cs.
Member Function Documentation
ModifierTooltipLine [] Loot.Core.System.Modifier.ModifierTooltipBuilder.Build ()
Definition at line 68 of file ModifierTooltipBuilder.cs.
         {
             return _lines.ToArray();
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithLine (ModifierTooltipLine line)
Definition at line 16 of file ModifierTooltipBuilder.cs.
         {
             _lines.Add(line);
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithLine (string text, Color? color = null)
Definition at line 22 of file ModifierTooltipBuilder.cs.
         {
             _lines.Add(new ModifierTooltipLine
             {
                 Text = text,
                 Color = color
             });
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithLines (IEnumerable< ModifierTooltipLine > lines)
Definition at line 10 of file ModifierTooltipBuilder.cs.
         {
             _lines.AddRange(lines);
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithNegative (string text)
Definition at line 40 of file ModifierTooltipBuilder.cs.
         {
             _lines.Add(new NegativeTooltipLine(
                 text
             ));
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithNegatives (params string[] texts)
Definition at line 58 of file ModifierTooltipBuilder.cs.
         {
             foreach (string text in texts)
             {
                 WithNegative(text);
             }
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithPositive (string text)
Definition at line 32 of file ModifierTooltipBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.Thorns.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.SpeedPlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.KnockbackPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.VelocityPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.FishingPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.AmmoReduce.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.CritPlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.VelocityDamage.GetTooltip(), Loot.Modifiers.WeaponModifiers.DamagePlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.ManaReduce.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.WingTimePlus.GetTooltip(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetTooltip(), Loot.Modifiers.WeaponModifiers.Ice.IcyModifier.GetTooltip(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetTooltip(), Loot.Modifiers.WeaponDebuffModifier.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetTooltip(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetTooltip(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetTooltip(), Loot.Modifiers.EquipModifiers.Utility.LightPlus.GetTooltip(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetTooltip().
         {
             _lines.Add(new PositiveTooltipLine(
                 text
             ));
             return this;
         }
ModifierTooltipBuilder Loot.Core.System.Modifier.ModifierTooltipBuilder.WithPositives (params string[] texts)
Definition at line 48 of file ModifierTooltipBuilder.cs.
         {
             foreach (string text in texts)
             {
                 WithPositive(text);
             }
             return this;
         }
Member Data Documentation
readonly List<ModifierTooltipLine> Loot.Core.System.Modifier.ModifierTooltipBuilder._lines = new List<ModifierTooltipLine>() private
Definition at line 8 of file ModifierTooltipBuilder.cs.