Even More Modifiers: Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder Class Reference
Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder Class Reference
Public Member Functions
GlowmaskGraphicsPropertiesBuilder SkipDrawing (bool value)
GlowmaskGraphicsPropertiesBuilder SkipDrawingGlowmask (bool val)
Public Member Functions inherited from Loot.Api.Builder.PropertyBuilder< GlowmaskGraphicsProperties >
virtual T Build ()
void WithDefault (IPropertyBuilder< T > defaultPropertyBuilder)
void WithDefault (T defaultValue)
Properties
override GlowmaskGraphicsProperties DefaultProperty [set]
Properties inherited from Loot.Api.Builder.PropertyBuilder< GlowmaskGraphicsProperties >
abstract T DefaultProperty [set]
Additional Inherited Members
Protected Member Functions inherited from Loot.Api.Builder.PropertyBuilder< GlowmaskGraphicsProperties >
PropertyBuilder ()
PropertyBuilder (IPropertyBuilder< T > defaultPropertyBuilder)
PropertyBuilder (T defaultValue)
Protected Attributes inherited from Loot.Api.Builder.PropertyBuilder< GlowmaskGraphicsProperties >
T Property
Detailed Description
Definition at line 11 of file GlowmaskGraphicsProperties.cs.
Member Function Documentation
GlowmaskGraphicsPropertiesBuilder Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawing (bool value)
Definition at line 22 of file GlowmaskGraphicsProperties.cs.
References Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawing().
Referenced by Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawing().
             {
                 Property.SkipDrawing = value;
                 return this;
             }
GlowmaskGraphicsPropertiesBuilder Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawingGlowmask (bool val)
Definition at line 28 of file GlowmaskGraphicsProperties.cs.
References Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawingGlowmask().
Referenced by Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.SkipDrawingGlowmask().
             {
                 Property.SkipDrawingGlowmask = val;
                 return this;
             }
Property Documentation
override GlowmaskGraphicsProperties Loot.Api.Graphics.Glowmask.GlowmaskGraphicsProperties.GlowmaskGraphicsPropertiesBuilder.DefaultProperty set protected
Definition at line 14 of file GlowmaskGraphicsProperties.cs.