Even More Modifiers: Loot.Api.Builder.PropertyBuilder< T > Class Template Reference
Loot.Api.Builder.PropertyBuilder< T > Class Template Reference
Defines an abstract implementation of IPropertyBuilder<T>
Public Member Functions
virtual T Build ()
void WithDefault (IPropertyBuilder< T > defaultPropertyBuilder)
void WithDefault (T defaultValue)
Protected Member Functions
PropertyBuilder ()
PropertyBuilder (IPropertyBuilder< T > defaultPropertyBuilder)
PropertyBuilder (T defaultValue)
Protected Attributes
T Property = new T()
Properties
abstract T DefaultProperty [set]
Detailed Description
Defines an abstract implementation of IPropertyBuilder<T>
Type Constraints
T : class
T : new()
Definition at line 6 of file PropertyBuilder.cs.
Constructor & Destructor Documentation
Loot.Api.Builder.PropertyBuilder< T >.PropertyBuilder () protected
Definition at line 11 of file PropertyBuilder.cs.
         {
         }
Loot.Api.Builder.PropertyBuilder< T >.PropertyBuilder (IPropertyBuilder< T > defaultPropertyBuilder) protected
Definition at line 15 of file PropertyBuilder.cs.
         {
             WithDefault(defaultPropertyBuilder);
         }
Loot.Api.Builder.PropertyBuilder< T >.PropertyBuilder (T defaultValue) protected
Definition at line 20 of file PropertyBuilder.cs.
         {
             WithDefault(defaultValue);
         }
Member Function Documentation
virtual T Loot.Api.Builder.PropertyBuilder< T >.Build () virtual
Implements Loot.Api.Builder.IPropertyBuilder< T >.
Definition at line 35 of file PropertyBuilder.cs.
Referenced by Loot.Modifiers.WeaponModifiers.Ice.IceModifier.GetShaderEntity(), Loot.Api.Graphics.Glowmask.GlowmaskEntity.GlowmaskEntity(), Loot.Api.Graphics.Shader.Style.ShaderDrawStyle.ShaderDrawStyle(), and Loot.Api.Graphics.Shader.ShaderEntity.ShaderEntity().
         {
             return Property;
         }
void Loot.Api.Builder.PropertyBuilder< T >.WithDefault (IPropertyBuilder< T > defaultPropertyBuilder)
Implements Loot.Api.Builder.IPropertyBuilder< T >.
Definition at line 25 of file PropertyBuilder.cs.
         {
             DefaultProperty = defaultPropertyBuilder.Build();
         }
void Loot.Api.Builder.PropertyBuilder< T >.WithDefault (T defaultValue)
Implements Loot.Api.Builder.IPropertyBuilder< T >.
Definition at line 30 of file PropertyBuilder.cs.
         {
             DefaultProperty = defaultValue;
         }
Member Data Documentation
T Loot.Api.Builder.PropertyBuilder< T >.Property = new T() protected
Definition at line 8 of file PropertyBuilder.cs.
Property Documentation
abstract T Loot.Api.Builder.PropertyBuilder< T >.DefaultProperty set protected
Definition at line 9 of file PropertyBuilder.cs.