Even More Modifiers: Loot.Api.Loaders.RegistryLoader Class Reference
Loot.Api.Loaders.RegistryLoader Class Reference
The MainLoader is responsible for loading mods into EMM Mods can be registered and triggered to have their content added via this class
Static Public Member Functions
static void AddContent (Mod mod)
static void RegisterMod (Mod mod)
Registers specified mod, enabling autoloading for that mod
Static Public Attributes
static int ModCount => Mods.Count
Detailed Description
The MainLoader is responsible for loading mods into EMM Mods can be registered and triggered to have their content added via this class
Definition at line 19 of file RegistryLoader.cs.
Member Function Documentation
static void Loot.Api.Loaders.RegistryLoader.AddContent (Mod mod) static
Definition at line 76 of file RegistryLoader.cs.
References Loot.Api.Loaders.ContentLoader.Modifier, Loot.Api.Loaders.ContentLoader.ModifierEffect, Loot.Api.Loaders.ContentLoader.ModifierPool, and Loot.Api.Loaders.ContentLoader.ModifierRarity.
Referenced by Loot.Api.Loaders.LoadingFunneler.AddMod(), and Loot.Api.Loaders.LoadingFunneler.LoadMod().
         {
             CheckModLoading(mod, "SetupContent");
             CheckModRegistered(mod);
             var ordered = Mods.FirstOrDefault(x => x.Key.Equals(mod.Name))
                 .Value
                 .GetTypes()
                 .OrderBy(x => x.FullName, StringComparer.InvariantCulture)
                 .Where(t => t.IsClass && !t.IsAbstract)
                 .ToList();
             var rarities = ordered.Where(x => x.IsSubclassOf(typeof(ModifierRarity)) && x != typeof(NullModifierRarity));
             var modifiers = ordered.Where(x => x.IsSubclassOf(typeof(Modifier.Modifier)) && x != typeof(NullModifier));
             var pools = ordered.Where(x => x.IsSubclassOf(typeof(ModifierPool)) && x != typeof(NullModifierPool));
             var effects = ordered.Where(x => x.IsSubclassOf(typeof(ModifierEffect)) && x != typeof(NullModifierEffect));
             // Kinda meh, but no need to recheck here..
             ContentLoader.SkipModChecks(true);
             // important: load things in order. (modifiers relies on all.. etc.)
             foreach (Type type in rarities)
             {
                 ContentLoader.ModifierRarity.AddContent(type, mod);
             }
             foreach (Type type in modifiers)
             {
                 ContentLoader.Modifier.AddContent(type, mod);
             }
             foreach (Type type in pools)
             {
                 ContentLoader.ModifierPool.AddContent(type, mod);
             }
             foreach (Type type in effects)
             {
                 ContentLoader.ModifierEffect.AddContent(type, mod);
             }
             ContentLoader.SkipModChecks(false);
         }
static void Loot.Api.Loaders.RegistryLoader.RegisterMod (Mod mod) static
Registers specified mod, enabling autoloading for that mod
Definition at line 62 of file RegistryLoader.cs.
Referenced by Loot.Api.Loaders.LoadingFunneler.AddMod(), and Loot.Api.Loaders.LoadingFunneler.LoadMod().
         {
             CheckModLoading(mod, "RegisterMod");
             if (Mods.ContainsKey(mod.Name))
             {
                 throw new Exception($"Mod {mod.Name} is already registered");
             }
             Assembly code = mod.Code;
             Mods.Add(new KeyValuePair<string, Assembly>(mod.Name, code));
             ContentLoader.RegisterMod(mod);
         }
Member Data Documentation
int Loot.Api.Loaders.RegistryLoader.ModCount => Mods.Count static
Definition at line 22 of file RegistryLoader.cs.