Even More Modifiers: Loot.UI.UIRerollItemPanel Class Reference
Loot.UI.UIRerollItemPanel Class Reference
Public Member Functions
UIRerollItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
override bool CanTakeItem (Item item)
override void PostOnClick (UIMouseEvent evt, UIElement e)
override void PreOnClick (UIMouseEvent evt, UIElement e)
Public Member Functions inherited from Loot.UI.UIInteractableItemPanel
UIInteractableItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
virtual void PostOnRightClick ()
override void Update (GameTime gameTime)
Public Member Functions inherited from Loot.UI.UIItemPanel
UIItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null, string hintOnHover=null)
Additional Inherited Members
Public Attributes inherited from Loot.UI.UIItemPanel
Item item
Protected Member Functions inherited from Loot.UI.UIItemPanel
override void DrawSelf (SpriteBatch spriteBatch)
Protected Attributes inherited from Loot.UI.UIInteractableItemPanel
bool RightClickFunctionalityEnabled = true
bool TakeUserItemOnClick = true
Properties inherited from Loot.UI.UIItemPanel
string HintOnHover [get, set]
string HintText [get, set]
Texture2D HintTexture [get, set]
Detailed Description
Definition at line 7 of file UIRerollItemPanel.cs.
Constructor & Destructor Documentation
Loot.UI.UIRerollItemPanel.UIRerollItemPanel (int netID = 0, int stack = 0, Texture2D hintTexture = null, string hintText = null)
Definition at line 9 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SealedModifiers.
                                                                                                                      :
             base(netID, stack, hintTexture, hintText)
         {
             this.RightClickFunctionalityEnabled = false;
             this.HintOnHover = " (click to take item)";
         }
Member Function Documentation
override bool Loot.UI.UIRerollItemPanel.CanTakeItem (Item item) virtual
Reimplemented from Loot.UI.UIInteractableItemPanel.
Referenced by Loot.UI.CubeRerollUI.IsItemValidForUISlot(), and Loot.UI.CubeRerollUI.MatchesRerollRequirements().
override void Loot.UI.UIRerollItemPanel.PostOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.UIInteractableItemPanel.
Definition at line 26 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = true;
             }
             Loot.Instance.CubeRerollUI.UpdateModifierLines();
         }
override void Loot.UI.UIRerollItemPanel.PreOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.UIInteractableItemPanel.
Definition at line 18 of file UIRerollItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = false;
             }
         }