Even More Modifiers: Loot.LootModItem Class Reference
Loot.LootModItem Class Reference
Defines an item that may be modified by modifiers from mods
Public Member Functions
override GlobalItem Clone (Item item, Item itemClone)
override void Load (Item item, TagCompound tag)
override void ModifyTooltips (Item item, List< TooltipLine > tooltips)
Will modify vanilla tooltips to add additional information for the affected item's modifiers
override bool NeedsSaving (Item item)
override void NetReceive (Item item, BinaryReader reader)
override void NetSend (Item item, BinaryWriter writer)
override void OnCraft (Item item, Recipe recipe)
override bool OnPickup (Item item, Player player)
override void PostReforge (Item item)
ModifierPool RollNewPool (ModifierContext ctx, RollingStrategyProperties rollingStrategyProperties=null)
Attempts to roll new modifiers Has a set chance to hit a predefined pool of modifiers
override TagCompound Save (Item item)
Static Public Member Functions
static IEnumerable< Modifier > GetActivePool (Item item)
static LootModItem GetInfo (Item item)
Public Attributes
override bool CloneNewInstances => true
override bool InstancePerEntity => true
Properties
bool HasRolled [get, set]
bool IsActivated [get, set]
Keeps track of if the particular item was activated ('delegated') Specific usecase see CursedEffect and modifier
bool JustTinkerModified [get, set]
ModifierPool ModifierPool [get, set]
ModifierRarity ModifierRarity [get, set]
bool SealedModifiers [get, set]
bool SlottedInCubeUI [get, set]
Private Member Functions
string GetPrefixNormString (float cpStat, float rStat, ref double num, ref Color?color)
void InvalidateRolls ()
Private Attributes
const int SAVE_VERSION = 3
Detailed Description
Defines an item that may be modified by modifiers from mods
Definition at line 23 of file LootModItem.cs.
Member Function Documentation
override GlobalItem Loot.LootModItem.Clone (Item item, Item itemClone)
Definition at line 163 of file LootModItem.cs.
References Loot.LootModItem.Clone(), Loot.LootModItem.ModifierPool, and Loot.LootModItem.ModifierRarity.
Referenced by Loot.LootModItem.Clone().
         {
             LootModItem clone = (LootModItem)base.Clone(item, itemClone);
             clone.ModifierRarity = (ModifierRarity)ModifierRarity?.Clone() ?? mod.GetNullModifierRarity();
             clone.ModifierPool = (ModifierPool)ModifierPool?.Clone() ?? mod.GetNullModifierPool();
             // there is no need to apply here, we already cloned the item which stats are already modified by its pool
             return clone;
         }
static IEnumerable<Modifier> Loot.LootModItem.GetActivePool (Item item) static
Referenced by Loot.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.Caching.ModifierCachePlayer.UpdateCheatSheetCache(), Loot.Api.Graphics.GraphicsGlobalItem.UpdateEntities(), Loot.Caching.ModifierCachePlayer.UpdateEquipsCache(), Loot.Caching.ModifierCachePlayer.UpdateHeldItemCache(), Loot.Caching.ModifierCachePlayer.UpdateMouseItemCache(), and Loot.Caching.ModifierCachePlayer.UpdateVanityCache().
static LootModItem Loot.LootModItem.GetInfo (Item item) static
Referenced by Loot.Caching.ModifierCachePlayer.AddAttachItem(), Loot.Caching.ModifierCachePlayer.AddDetachItem(), Loot.Hacks.TinkererArmorHackGlobalItem.ChoosePrefix(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.Cubes.PoorCube.GetRollingStrategy(), Loot.RollingStrategies.NormalRollingStrategy.InitFields(), Loot.Api.Modifier.ModifierPool.Load(), Loot.ModSupport.WingSlotSupport.WingSlotSupportGlobalItem.ModifyTooltips(), Loot.LootModItem.ModifyTooltips(), Loot.LootModWorld.ModifyWorldGenTasks(), Loot.LootModItem.OnCraft(), Loot.LootModItem.OnPickup(), Loot.Hacks.TinkererArmorHackGlobalItem.PostReforge(), and Loot.Hacks.TinkererArmorHackModPlayer.PostUpdate().
string Loot.LootModItem.GetPrefixNormString (float cpStat, float rStat, ref double num, ref Color? color) private
Definition at line 324 of file LootModItem.cs.
Referenced by Loot.LootModItem.ModifyTooltips().
         {
             //float num19 = (float)Main.mouseTextColor / 255f;
             //patch file: num20
             float defColorVal = Main.mouseTextColor / 255f;
             int alphaColor = Main.mouseTextColor;
             if (cpStat == 0f && rStat != 0f)
             {
                 num = 1;
                 if (rStat > 0f)
                 {
                     color = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                     return "+" + rStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
                 }
                 color = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                 return rStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
             }
             double diffStat = rStat - cpStat;
             diffStat = diffStat / cpStat * 100.0;
             diffStat = Math.Round(diffStat);
             num = diffStat;
             // for some reason - is handled automatically, but + is not
             if (diffStat > 0.0)
             {
                 color = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                 return "+" + diffStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
             }
             color = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
             return diffStat.ToString(CultureInfo.InvariantCulture); /* + Lang.tip[39].Value;*/
                                                                     //if (num12 < 0.0)
                                                                     //{
                                                                     //  array3[num4] = true;
                                                                     //}
         }
void Loot.LootModItem.InvalidateRolls () private
Definition at line 48 of file LootModItem.cs.
Referenced by Loot.LootModItem.Load(), and Loot.LootModItem.RollNewPool().
         {
             ModifierRarity = mod.GetNullModifierRarity();
             ModifierPool = mod.GetNullModifierPool();
         }
override void Loot.LootModItem.Load (Item item, TagCompound tag)
Definition at line 172 of file LootModItem.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.LootModItem.HasRolled, Loot.LootModItem.InvalidateRolls(), and Loot.LootModItem.SealedModifiers.
         {
             // enforce illegitimate rolls to go away (needed for earliest versions saves)
             if (!item.IsModifierRollableItem())
             {
                 InvalidateRolls();
             }
             else
             {
                 // SaveVersion >= 2
                 if (tag.ContainsKey("SaveVersion"))
                 {
                     int saveVersion = tag.GetInt("SaveVersion");
                     SealedModifiers = tag.GetBool("SealedModifiers");
                     HasRolled = tag.GetBool("HasRolled");
                     if (saveVersion < 3)
                     {
                         // Rarity should be set by pool loading
                         ModifierPool = ModifierPool._Load(item, tag);
                     }
                     else
                     {
                         ModifierRarity = ModifierRarity._Load(item, tag.GetCompound("ModifierRarity"));
                         ModifierPool = ModifierPool._Load(item, tag.GetCompound("ModifierPool"));
                     }
                 }
                 else // SaveVersion 1
                 {
                     HasRolled = tag.GetBool("HasRolled");
                     ModifierPool = ModifierPool._Load(item, tag);
                 }
                 if (ModifierPool != null)
                 {
                     // enforce illegitimate rolls to go away
                     if (ModifierPool.ActiveModifiers == null || ModifierPool.ActiveModifiers.Length <= 0)
                     {
                         InvalidateRolls();
                     }
                     else
                     {
                         ModifierPool.ApplyModifiers(item);
                     }
                 }
             }
         }
override void Loot.LootModItem.ModifyTooltips (Item item, List< TooltipLine > tooltips)
Will modify vanilla tooltips to add additional information for the affected item's modifiers
Definition at line 367 of file LootModItem.cs.
References Loot.Api.Modifier.ModifierRarity.Color, Loot.LootModItem.GetInfo(), Loot.Hacks.CheatedItemHackGlobalItem.GetInfo(), Loot.LootModItem.GetPrefixNormString(), Loot.Api.Modifier.ModifierRarity.ItemPrefix, Loot.Api.Modifier.ModifierRarity.ItemSuffix, Loot.LootModItem.ModifierPool, Loot.Api.Modifier.ModifierRarity.OverrideNameColor, Loot.LootModItem.SealedModifiers, and Loot.Hacks.CheatedItemHackGlobalItem.ShouldBeIgnored().
         {
             var pool = GetInfo(item).ModifierPool;
             if (pool != null && pool.ActiveModifiers.Length > 0)
             {
                 // the following part, recalculate the vanilla prefix tooltips
                 // this is because our mods modify the stats, which was never intended by vanilla, causing the differences to be innacurate and bugged
                 // RECALC START
                 var vanillaTooltips = tooltips.Where(x => x.mod.Equals("Terraria")).ToArray();
                 var baseItem = new Item();
                 baseItem.netDefaults(item.netID);
                 // the item with just the modifiers applied
                 // var poolItem = baseItem.CloneWithModdedDataFrom(item);
                 // GetItemInfo(poolItem)?.ModifierPool.ApplyModifiers(poolItem);
                 // the item with just the prefix applied
                 var prefixItem = baseItem.Clone();
                 prefixItem.Prefix(item.prefix);
                 try
                 {
                     foreach (var tooltipLine in vanillaTooltips)
                     {
                         double outNumber = 0d;
                         string newTooltipLine = tooltipLine.text;
                         Color? newColor = tooltipLine.overrideColor;
                         string tooltipEndText =
                             new string(tooltipLine.text
                                 .Reverse()
                                 .TakeWhile(x => !char.IsDigit(x))
                                 .Reverse()
                                 .ToArray());
                         //private string[] _prefixTooltipLines = {
                         //      "PrefixDamage", "PrefixSpeed", "PrefixCritChance", "PrefixUseMana", "PrefixSize",
                         //      "PrefixShootSpeed", "PrefixKnockback", "PrefixAccDefense", "PrefixAccMaxMana",
                         //      "PrefixAccCritChance", "PrefixAccDamage", "PrefixAccMoveSpeed", "PrefixAccMeleeSpeed"
                         //  };
                         if (tooltipLine.Name.Equals("PrefixDamage"))
{
                             newTooltipLine = baseItem.damage > 0
                                 ? GetPrefixNormString(baseItem.damage, prefixItem.damage, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.damage, baseItem.damage, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixSpeed"))
{
                             newTooltipLine = baseItem.useAnimation <= 0
                                 ? GetPrefixNormString(baseItem.useAnimation, prefixItem.useAnimation, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.useAnimation, baseItem.useAnimation, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixCritChance"))
{
                             outNumber = prefixItem.crit - baseItem.crit;
                             float defColorVal = Main.mouseTextColor / 255f;
                             int alphaColor = Main.mouseTextColor;
                             newTooltipLine = "";
                             if (outNumber >= 0)
{
                                 newTooltipLine += "+";
                                 newColor = new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                             else
{
                                 newColor = new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                             newTooltipLine += outNumber.ToString(CultureInfo.InvariantCulture);
                         }
                         else if (tooltipLine.Name.Equals("PrefixUseMana"))
{
                             if (baseItem.mana != 0)
{
                                 float defColorVal = Main.mouseTextColor / 255f;
                                 int alphaColor = Main.mouseTextColor;
                                 newTooltipLine = GetPrefixNormString(baseItem.mana, prefixItem.mana, ref outNumber, ref newColor);
                                 newColor = prefixItem.mana < baseItem.mana
                                     ? new Color((byte)(120f * defColorVal), (byte)(190f * defColorVal), (byte)(120f * defColorVal), alphaColor)
                                     : new Color((byte)(190f * defColorVal), (byte)(120f * defColorVal), (byte)(120f * defColorVal), alphaColor);
                             }
                         }
                         else if (tooltipLine.Name.Equals("PrefixSize"))
{
                             newTooltipLine = baseItem.scale > 0
                                 ? GetPrefixNormString(baseItem.scale, prefixItem.scale, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.scale, baseItem.scale, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixShootSpeed"))
{
                             newTooltipLine = baseItem.shootSpeed > 0
                                 ? GetPrefixNormString(baseItem.shootSpeed, prefixItem.shootSpeed, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.shootSpeed, baseItem.shootSpeed, ref outNumber, ref newColor);
                         }
                         else if (tooltipLine.Name.Equals("PrefixKnockback"))
{
                             newTooltipLine = baseItem.knockBack > 0
                                 ? GetPrefixNormString(baseItem.knockBack, prefixItem.knockBack, ref outNumber, ref newColor)
                                 : GetPrefixNormString(prefixItem.knockBack, baseItem.knockBack, ref outNumber, ref newColor);
                         }
                         else
{
                             continue;
                         }
                         int ttlI = tooltips.FindIndex(x => x.mod.Equals(tooltipLine.mod) && x.Name.Equals(tooltipLine.Name));
                         if (ttlI == -1)
{
                             continue;
                         }
                         if (outNumber == 0d)
{
                             tooltips.RemoveAt(ttlI);
                         }
                         else
{
                             tooltips[ttlI].text = $"{newTooltipLine}{tooltipEndText}";
                             tooltips[ttlI].overrideColor = newColor;
                         }
                     }
                 }
                 catch (Exception e)
                 {
                     Loot.Logger.Error(
                         $"A problem occurred during modification of the item's tooltip." +
                         $"\nItem in question: {item.AffixName()}",
                         e);
                 }
                 // RECALC END
                 // Modifies the tooltips, to insert generic mods data
                 int i = tooltips.FindIndex(x => x.mod == "Terraria" && x.Name == "ItemName");
                 if (i != -1)
                 {
                     var namelayer = tooltips[i];
                     if (ModifierRarity.ItemPrefix != null)
                     {
                         namelayer.text = $"{ModifierRarity.ItemPrefix} {namelayer.text}";
                     }
                     if (ModifierRarity.ItemSuffix != null)
                     {
                         namelayer.text = $"{namelayer.text} {ModifierRarity.ItemSuffix}";
                     }
                     if (ModifierRarity.OverrideNameColor != null)
                     {
                         namelayer.overrideColor = ModifierRarity.OverrideNameColor;
                     }
                     tooltips[i] = namelayer;
                 }
                 // Insert modifier rarity
                 CheatedItemHackGlobalItem cheatedItemHackGlobalItem = CheatedItemHackGlobalItem.GetInfo(item);
                 bool isVanityIgnored = cheatedItemHackGlobalItem.ShouldBeIgnored(item, Main.LocalPlayer);
                 Color? inactiveColor = isVanityIgnored ? (Color?)Color.DarkSlateGray : null;
                 i = tooltips.Count;
                 tooltips.Insert(i, new TooltipLine(mod, "Loot: Modifier:Rarity", $"[{ModifierRarity.RarityName}]{(isVanityIgnored ? " [IGNORED]" : "")}")
                 {
                     overrideColor = inactiveColor ?? ModifierRarity.Color * Main.inventoryScale
                 });
                 foreach (var modifier in pool.ActiveModifiers)
                 {
                     foreach (var tt in modifier.GetTooltip().Build())
                     {
                         tooltips.Insert(++i, new TooltipLine(mod, $"Loot: Modifier:Line:{i}", $"{modifier.GetFormattedUniqueName()} {tt.Text}".TrimStart())
{
                             overrideColor = inactiveColor ?? (tt.Color ?? Color.White) * Main.inventoryScale
                         });
                     }
                 }
                 if (SealedModifiers)
                 {
                     var ttl = new TooltipLine(mod, "Loot: Modifier:Sealed", "Modifiers cannot be changed")
                     {
                         overrideColor = inactiveColor ?? Color.Cyan
                     };
                     tooltips.Insert(++i, ttl);
                 }
                 foreach (var e in pool.ActiveModifiers)
                 {
                     e.ModifyTooltips(item, tooltips);
                 }
             }
         }
override bool Loot.LootModItem.NeedsSaving (Item item)
Referenced by Loot.LootModItem.Save().
override void Loot.LootModItem.NetReceive (Item item, BinaryReader reader)
Definition at line 237 of file LootModItem.cs.
References Loot.LootModItem.HasRolled, Loot.LootModItem.JustTinkerModified, and Loot.LootModItem.SealedModifiers.
         {
             if (reader.ReadBoolean())
             {
                 ModifierRarity = ModifierRarity._NetReceive(item, reader); // Since SaveVersion 3
                 ModifierPool = ModifierPool._NetReceive(item, reader);
             }
             HasRolled = reader.ReadBoolean();
             SealedModifiers = reader.ReadBoolean(); // Since SaveVersion 2
             ModifierPool?.ApplyModifiers(item);
             JustTinkerModified = reader.ReadBoolean();
         }
override void Loot.LootModItem.NetSend (Item item, BinaryWriter writer)
Definition at line 253 of file LootModItem.cs.
References Loot.LootModItem.HasRolled, Loot.LootModItem.JustTinkerModified, and Loot.LootModItem.SealedModifiers.
         {
             bool hasPool = ModifierPool != null;
             writer.Write(hasPool);
             if (hasPool)
             {
                 ModifierRarity._NetSend(ModifierRarity, item, writer); // Since SaveVersion 3
                 ModifierPool._NetSend(ModifierPool, item, writer);
             }
             writer.Write(HasRolled);
             writer.Write(SealedModifiers); // Since SaveVersion 2
             writer.Write(JustTinkerModified);
         }
override void Loot.LootModItem.OnCraft (Item item, Recipe recipe)
Definition at line 269 of file LootModItem.cs.
References Loot.LootModItem.GetInfo(), Loot.LootModItem.HasRolled, Loot.LootModItem.ModifierPool, and Loot.LootModItem.RollNewPool().
         {
             ModifierPool pool = GetInfo(item).ModifierPool;
             if (!HasRolled && pool == null)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnCraft,
                     Item = item,
                     Player = Main.LocalPlayer,
                     Recipe = recipe
                 };
                 pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
             base.OnCraft(item, recipe);
         }
override bool Loot.LootModItem.OnPickup (Item item, Player player)
Definition at line 289 of file LootModItem.cs.
References Loot.LootModItem.GetInfo(), Loot.LootModItem.HasRolled, Loot.LootModItem.ModifierPool, and Loot.LootModItem.RollNewPool().
         {
             ModifierPool pool = GetInfo(item).ModifierPool;
             if (!HasRolled && pool == null)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnPickup,
                     Item = item,
                     Player = player
                 };
                 pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
             return base.OnPickup(item, player);
         }
override void Loot.LootModItem.PostReforge (Item item)
Definition at line 308 of file LootModItem.cs.
References Loot.LootModItem.RollNewPool(), and Loot.LootModItem.SealedModifiers.
         {
             if (!SealedModifiers)
             {
                 ModifierContext ctx = new ModifierContext
                 {
                     Method = ModifierContextMethod.OnReforge,
                     Item = item,
                     Player = Main.LocalPlayer
                 };
                 ModifierPool pool = RollNewPool(ctx);
                 pool?.ApplyModifiers(item);
             }
         }
ModifierPool Loot.LootModItem.RollNewPool (ModifierContext ctx, RollingStrategyProperties rollingStrategyProperties = null)
Attempts to roll new modifiers Has a set chance to hit a predefined pool of modifiers
Definition at line 58 of file LootModItem.cs.
References Loot.Api.Modifier.ModifierRarity.Downgrade, Loot.Api.Modifier.ModifierRarity.DowngradeChance, Loot.Api.Ext.ModUtils.GetModifierPool(), Loot.Api.Ext.ModUtils.GetModifierRarity(), Loot.LootModItem.HasRolled, Loot.LootModItem.InvalidateRolls(), Loot.Api.Modifier.ModifierContext.Item, Loot.Api.Loaders.ContentLoader.ModifierPool, Loot.LootModItem.ModifierPool, Loot.LootModItem.ModifierRarity, Loot.Api.Modifier.ModifierContext.Rarity, Loot.Api.Strategy.IRollingStrategy< in in T >.Roll(), Loot.Api.Modifier.ModifierContext.Strategy, Loot.Api.Modifier.ModifierRarity.Type, Loot.Api.Modifier.ModifierRarity.Upgrade, and Loot.Api.Modifier.ModifierRarity.UpgradeChance.
Referenced by Loot.LootModWorld.ModifyWorldGenTasks(), Loot.LootModItem.OnCraft(), Loot.LootModItem.OnPickup(), and Loot.LootModItem.PostReforge().
         {
             if (rollingStrategyProperties == null)
             {
                 rollingStrategyProperties = new RollingStrategyProperties();
             }
             HasRolled = true;
             bool noForce = true;
             // Custom rarity provided
             if (rollingStrategyProperties.OverrideRollModifierRarity != null)
             {
                 ModifierRarity = rollingStrategyProperties.OverrideRollModifierRarity.Invoke();
             }
             else if (rollingStrategyProperties.ForceModifierRarity != null)
             {
                 ModifierRarity = rollingStrategyProperties.ForceModifierRarity;
             }
             else if (ModifierRarity == null || ModifierRarity.Type == 0)
             {
                 ModifierRarity = mod.GetModifierRarity<CommonRarity>();
             }
             ctx.Rarity = ModifierRarity;
             // Upgrade rarity
             if (rollingStrategyProperties.CanUpgradeRarity(ctx)
                 && Main.rand.NextFloat() <= (ModifierRarity.UpgradeChance ?? 0f))
             {
                 var newRarity = ModifierRarity.Upgrade;
                 var newFromLoader = ModUtils.GetModifierRarity(newRarity);
                 if (newRarity != null && newFromLoader != null)
                 {
                     ModifierRarity = newFromLoader;
                 }
             }
             // Downgrade rarity
             else if (rollingStrategyProperties.CanDowngradeRarity(ctx)
                     && Main.rand.NextFloat() <= (ModifierRarity.DowngradeChance ?? 0f))
             {
                 var newRarity = ModifierRarity.Downgrade;
                 var newFromLoader = ModUtils.GetModifierRarity(newRarity);
                 if (newRarity != null && newFromLoader != null)
                 {
                     ModifierRarity = newFromLoader;
                 }
             }
             ctx.Rarity = ModifierRarity;
             // Custom pool provided
             if (rollingStrategyProperties.OverrideRollModifierPool != null)
             {
                 ModifierPool = rollingStrategyProperties.OverrideRollModifierPool.Invoke();
                 noForce = !ModifierPool?._CanRoll(ctx) ?? true;
             }
             // No behavior provided
             if (noForce)
             {
                 // A pool is forced to roll
                 if (rollingStrategyProperties.ForceModifierPool != null)
                 {
                     ModifierPool = ModUtils.GetModifierPool(rollingStrategyProperties.ForceModifierPool.GetType());
                     noForce = !ModifierPool?._CanRoll(ctx) ?? true;
                 }
                 // No pool forced to roll or it's not valid
                 if (noForce)
                 {
                     // Try rolling a predefined (weighted) pool
                     bool rollPredefinedPool = Main.rand.NextFloat() <= rollingStrategyProperties.RollPredefinedPoolChance;
                     noForce = !rollPredefinedPool;
                     if (rollPredefinedPool)
                     {
                         // GetWeightedPool already checks _CanRoll
                         ModifierPool = ContentLoader.ModifierPool.GetWeightedPool(ctx);
                         noForce = ModifierPool == null || !ModifierPool._CanRoll(ctx);
                     }
                     // Roll from all modifiers
                     if (noForce)
                     {
                         ModifierPool = mod.GetAllModifiersPool();
                         if (!ModifierPool._CanRoll(ctx))
{
                             InvalidateRolls();
                             return null;
                         }
                     }
                 }
             }
             // Attempt rolling modifiers
             if (!ctx.Strategy?.Roll(ctx, new RollingStrategyContext(ctx.Item, rollingStrategyProperties)) ?? true)
             {
                 InvalidateRolls();
             }
             ctx.Item.GetGlobalItem<GraphicsGlobalItem>().NeedsUpdate = true;
             return ModifierPool;
         }
override TagCompound Loot.LootModItem.Save (Item item)
Definition at line 219 of file LootModItem.cs.
References Loot.LootModItem.HasRolled, Loot.LootModItem.NeedsSaving(), Loot.Api.Modifier.ModifierRarity.Save(), Loot.Api.Modifier.ModifierPool.Save(), and Loot.LootModItem.SealedModifiers.
         {
             TagCompound tag = new TagCompound
             {
                 // SaveVersion saved since SaveVersion 2, version 1 not present
                 {"SaveVersion", SAVE_VERSION},
                 {"SealedModifiers", SealedModifiers},
                 {"HasRolled", HasRolled},
                 {"ModifierRarity", ModifierRarity.Save(item, ModifierRarity)},
                 {"ModifierPool", ModifierPool.Save(item, ModifierPool)}
             };
             return tag;
         }
Member Data Documentation
override bool Loot.LootModItem.CloneNewInstances => true
Definition at line 31 of file LootModItem.cs.
override bool Loot.LootModItem.InstancePerEntity => true
Definition at line 30 of file LootModItem.cs.
const int Loot.LootModItem.SAVE_VERSION = 3 private
Definition at line 25 of file LootModItem.cs.
Property Documentation
bool Loot.LootModItem.HasRolled get set
Definition at line 35 of file LootModItem.cs.
Referenced by Loot.LootModItem.Load(), Loot.LootModWorld.ModifyWorldGenTasks(), Loot.LootModItem.NetReceive(), Loot.LootModItem.NetSend(), Loot.LootModItem.OnCraft(), Loot.LootModItem.OnPickup(), Loot.LootModItem.RollNewPool(), and Loot.LootModItem.Save().
bool Loot.LootModItem.IsActivated get set
Keeps track of if the particular item was activated ('delegated') Specific usecase see CursedEffect and modifier
Definition at line 46 of file LootModItem.cs.
Referenced by Loot.Caching.ModifierCachePlayer.AddAttachItem(), Loot.Caching.ModifierCachePlayer.AddDetachItem(), and Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding().
bool Loot.LootModItem.JustTinkerModified get set
Definition at line 39 of file LootModItem.cs.
Referenced by Loot.LootModItem.NetReceive(), Loot.LootModItem.NetSend(), and Loot.Hacks.TinkererArmorHackModPlayer.PostUpdate().
ModifierPool Loot.LootModItem.ModifierPool get set
Definition at line 34 of file LootModItem.cs.
Referenced by Loot.LootModItem.Clone(), Loot.LootModItem.ModifyTooltips(), Loot.LootModWorld.ModifyWorldGenTasks(), Loot.LootModItem.OnCraft(), Loot.LootModItem.OnPickup(), Loot.RollingStrategies.NormalRollingStrategy.Roll(), and Loot.LootModItem.RollNewPool().
ModifierRarity Loot.LootModItem.ModifierRarity get set
Definition at line 33 of file LootModItem.cs.
Referenced by Loot.LootModItem.Clone(), Loot.Cubes.PoorCube.GetRollingStrategy(), Loot.Api.Modifier.ModifierPool.Load(), and Loot.LootModItem.RollNewPool().
bool Loot.LootModItem.SealedModifiers get set
Definition at line 36 of file LootModItem.cs.
Referenced by Loot.LootModItem.Load(), Loot.LootModItem.ModifyTooltips(), Loot.LootModItem.NetReceive(), Loot.LootModItem.NetSend(), Loot.LootModItem.PostReforge(), and Loot.LootModItem.Save().
bool Loot.LootModItem.SlottedInCubeUI get set
Definition at line 40 of file LootModItem.cs.
Referenced by Loot.ModSupport.WingSlotSupport.WingSlotSupportGlobalItem.ModifyTooltips().