Even More Modifiers: Loot.Modifiers.WeaponDebuffModifier Class Reference
Loot.Modifiers.WeaponDebuffModifier Class Reference
Defines a modifier that can inflict a debuff, applicable for weapons
Public Member Functions
override ModifierPropertiesBuilder GetModifierProperties (Item item)
override ModifierTooltipBuilder GetTooltip ()
override void HoldItem (Item item, Player player)
override void OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit)
override void OnHitPvp (Item item, Player player, Player target, int damage, bool crit)
Public Member Functions inherited from Loot.Modifiers.WeaponModifier
override bool CanRoll (ModifierContext ctx)
If this Modifier can roll at all in the given context Properties are available here, apart from magnitude and power
void UpdateShootSpeed (Item item, Player player, float speedXBefore, float speedYBefore, ref float speedX, ref float speedY, float percentModifier)
void UpdateUseDamage (Item item, Player player, int damageBefore, ref int damage)
void UpdateUseKnockback (Item item, Player player, float knockbackBefore, ref float knockback)
Public Member Functions inherited from Loot.Core.System.Modifier.Modifier
sealed override void AnglerChat (int type, ref string chat, ref string catchLocation)
virtual void Apply (Item item)
Allows modders to do something when this modifier is applied If a modder needs ModPlayer hooks, they should make their own ModPlayer and apply fields using this hook This is also called for SetDefaults
sealed override void ArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color)
sealed override void ArmorSetShadows (Player player, string set)
sealed override bool Autoload (ref string name)
sealed override void CaughtFishStack (int type, ref int stack)
virtual void Clone (ref Modifier clone)
Allows modders to do custom cloning here Happens after default cloning, which clones various info (mod, type, magnitude and power)
new object Clone ()
sealed override GlobalItem Clone (Item item, Item itemClone)
sealed override void DrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
sealed override bool DrawBody (int body)
sealed override void DrawHair (int head, ref bool drawHair, ref bool drawAltHair)
sealed override void DrawHands (int body, ref bool drawHands, ref bool drawArms)
sealed override bool DrawHead (int head)
sealed override bool DrawLegs (int legs, int shoes)
sealed override void ExtractinatorUse (int extractType, ref int resultType, ref int resultStack)
string GetFormattedUniqueName ()
virtual GlowmaskEntity GetGlowmaskEntity (Item item)
virtual ShaderEntity GetShaderEntity (Item item)
sealed override Vector2 HoldoutOffset (int type)
sealed override Vector2 HoldoutOrigin (int type)
sealed override bool IsAnglerQuestAvailable (int type)
sealed override string IsArmorSet (Item head, Item body, Item legs)
sealed override string IsVanitySet (int head, int body, int legs)
virtual new void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
sealed override void LoadLegacy (Item item, BinaryReader reader)
sealed override bool NeedsSaving (Item item)
sealed override GlobalItem NewInstance (Item item)
sealed override void OpenVanillaBag (string context, Player player, int arg)
virtual bool PostRoll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers)
Returns if the modifier will actually be added after it is rolled. This is called after Roll is called This is used to be able to stop a modifier from being added after it has rolled If the roll is deemed illicit, the next roll is forced to succeed
sealed override bool PreOpenVanillaBag (string context, Player player, int arg)
sealed override void PreUpdateVanitySet (Player player, string set)
virtual void Roll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers)
Allows modders to do something when the modifier is rolled in the given context The passed rolledModifiers are already rolled modifiers on the item
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
sealed override TagCompound Save (Item item)
sealed override void SetDefaults (Item item)
sealed override void SetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes)
sealed override void UpdateArmorSet (Player player, string set)
sealed override void UpdateVanitySet (Player player, string set)
sealed override bool WingUpdate (int wings, Player player, bool inUse)
Properties
abstract float BuffInflictionChance [get]
abstract int BuffTime [get]
abstract int BuffType [get]
Properties inherited from Loot.Core.System.Modifier.Modifier
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
ModifierProperties Properties [get, set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Core.System.Core.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Private Member Functions
string GetBuffName ()
float RoundedBuffTime ()
Additional Inherited Members
Static Public Member Functions inherited from Loot.Modifiers.WeaponModifier
static bool HasVanillaDamage (Item item)
Public Attributes inherited from Loot.Core.System.Modifier.Modifier
sealed override bool CloneNewInstances => true
sealed override bool InstancePerEntity => true
new string Name => GetType().Name
virtual string UniqueName => string.Empty
Detailed Description
Defines a modifier that can inflict a debuff, applicable for weapons
Definition at line 31 of file WeaponDebuffModifier.cs.
Member Function Documentation
string Loot.Modifiers.WeaponDebuffModifier.GetBuffName () private
Definition at line 56 of file WeaponDebuffModifier.cs.
         {
             if (BuffType >= BuffID.Count)
             {
                 return BuffLoader.GetBuff(BuffType)?.DisplayName.GetTranslation(LanguageManager.Instance.ActiveCulture) ?? "null";
             }
             return Lang.GetBuffName(BuffType);
         }
override ModifierPropertiesBuilder Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties (Item item) virtual
Reimplemented from Loot.Core.System.Modifier.Modifier.
Definition at line 39 of file WeaponDebuffModifier.cs.
References Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithMinMagnitude(), and Loot.Core.System.Modifier.ModifierPropertiesBuilder.WithRoundPrecision().
         {
             return base.GetModifierProperties(item)
                 .WithMinMagnitude(5f)
                 .WithMinMagnitude(10f)
                 .WithRoundPrecision(1);
         }
override ModifierTooltipBuilder Loot.Modifiers.WeaponDebuffModifier.GetTooltip () virtual
Reimplemented from Loot.Core.System.Modifier.Modifier.
Definition at line 33 of file WeaponDebuffModifier.cs.
References Loot.Core.System.Modifier.ModifierTooltipBuilder.WithPositive().
         {
             return base.GetTooltip()
                 .WithPositive($"+{Properties.RoundedPower}% chance to inflict {GetBuffName()} for {RoundedBuffTime()}s");
         }
override void Loot.Modifiers.WeaponDebuffModifier.HoldItem (Item item, Player player)
Definition at line 83 of file WeaponDebuffModifier.cs.
References Loot.ModifierPlayer.GetEffect(), and Loot.ModifierPlayer.Player().
         {
             ModifierPlayer.Player(player).GetEffect<WeaponDebuffEffect>()
                 .DebuffChances
                 .Add((BuffType, BuffTime, Properties.RoundedPower / 100f * BuffInflictionChance));
         }
override void Loot.Modifiers.WeaponDebuffModifier.OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit)
Definition at line 66 of file WeaponDebuffModifier.cs.
         {
             if (Main.rand.NextFloat() < Properties.RoundedPower / 100f * BuffInflictionChance)
             {
                 target.AddBuff(BuffType, BuffTime);
             }
         }
override void Loot.Modifiers.WeaponDebuffModifier.OnHitPvp (Item item, Player player, Player target, int damage, bool crit)
Definition at line 74 of file WeaponDebuffModifier.cs.
         {
             if (Main.rand.NextFloat() < Properties.RoundedPower / 100f * BuffInflictionChance)
             {
                 target.AddBuff(BuffType, BuffTime);
             }
         }
float Loot.Modifiers.WeaponDebuffModifier.RoundedBuffTime () private
Definition at line 47 of file WeaponDebuffModifier.cs.
         {
             return (float) Math.Round((double) BuffTime / 60f, Properties.RoundPrecision);
         }
Property Documentation
abstract float Loot.Modifiers.WeaponDebuffModifier.BuffInflictionChance get
Definition at line 54 of file WeaponDebuffModifier.cs.
abstract int Loot.Modifiers.WeaponDebuffModifier.BuffTime get
Definition at line 53 of file WeaponDebuffModifier.cs.
abstract int Loot.Modifiers.WeaponDebuffModifier.BuffType get
Definition at line 52 of file WeaponDebuffModifier.cs.