Even More Modifiers: Loot.Core.ModifierRarity Class Reference
Loot.Core.ModifierRarity Class Reference
Defines the rarity of a modifier
Public Member Functions
ModifierRarity AsNewInstance ()
virtual void Clone (ref ModifierRarity clone)
object Clone ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual bool MatchesRequirements (ModifierPool modifierPool)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Static Public Member Functions
static ModifierRarity GetModifierRarity (ushort type)
Returns the ModifierRarity specified by type, null if not present
Public Attributes
virtual string ItemPrefix => null
virtual string ItemSuffix => null
virtual string Name => GetType().Name
virtual Color OverrideNameColor => null
Properties
abstract Color Color [get]
Mod Mod [get, set]
abstract float RequiredRarityLevel [get]
uint Type [get, set]
Detailed Description
Defines the rarity of a modifier
Definition at line 14 of file ModifierRarity.cs.
Member Function Documentation
ModifierRarity Loot.Core.ModifierRarity.AsNewInstance ()
virtual void Loot.Core.ModifierRarity.Clone (ref ModifierRarity clone) virtual
Definition at line 39 of file ModifierRarity.cs.
         {
         }
object Loot.Core.ModifierRarity.Clone ()
Definition at line 44 of file ModifierRarity.cs.
References Loot.Core.ModifierRarity.Mod, and Loot.Core.ModifierRarity.Type.
         {
             ModifierRarity clone = (ModifierRarity)MemberwiseClone();
             clone.Mod = Mod;
             clone.Type = Type;
             Clone(ref clone);
             return clone;
         }
static ModifierRarity Loot.Core.ModifierRarity.GetModifierRarity (ushort type) static
Returns the ModifierRarity specified by type, null if not present
virtual void Loot.Core.ModifierRarity.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 100 of file ModifierRarity.cs.
References Loot.EMMLoader.GetModifierRarity(), and Loot.Core.ModifierRarity.Load().
Referenced by Loot.Core.ModifierRarity.Load().
         {
         }
virtual bool Loot.Core.ModifierRarity.MatchesRequirements (ModifierPool modifierPool) virtual
virtual void Loot.Core.ModifierRarity.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Parameters
item
reader
Definition at line 58 of file ModifierRarity.cs.
References Loot.Core.ModifierRarity.Mod, Loot.Core.ModifierRarity.NetReceive(), and Loot.Core.ModifierRarity.Type.
Referenced by Loot.Core.ModifierRarity.NetReceive().
         {
         }
virtual void Loot.Core.ModifierRarity.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Parameters
item
writer
Definition at line 85 of file ModifierRarity.cs.
References Loot.Core.ModifierRarity.Mod, and Loot.Core.ModifierRarity.Type.
         {
         }
virtual void Loot.Core.ModifierRarity.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Definition at line 149 of file ModifierRarity.cs.
References Loot.Core.ModifierRarity.Mod, Loot.Core.ModifierRarity.Name, and Loot.Core.ModifierRarity.Save().
Referenced by Loot.Core.ModifierRarity.Save(), and Loot.Core.ModifierPool.Save().
         {
         }
Member Data Documentation
virtual string Loot.Core.ModifierRarity.ItemPrefix => null
Definition at line 21 of file ModifierRarity.cs.
virtual string Loot.Core.ModifierRarity.ItemSuffix => null
Definition at line 22 of file ModifierRarity.cs.
virtual string Loot.Core.ModifierRarity.Name => GetType().Name
Definition at line 19 of file ModifierRarity.cs.
Referenced by Loot.EMMLoader.AddModifierRarity(), and Loot.Core.ModifierRarity.Save().
virtual Color Loot.Core.ModifierRarity.OverrideNameColor => null
Definition at line 20 of file ModifierRarity.cs.
Property Documentation
abstract Color Loot.Core.ModifierRarity.Color get
Definition at line 25 of file ModifierRarity.cs.
Mod Loot.Core.ModifierRarity.Mod get set
Definition at line 16 of file ModifierRarity.cs.
Referenced by Loot.EMMLoader.AddModifierRarity(), Loot.Core.ModifierRarity.Clone(), Loot.EMMLoader.GetNewRarityInstance(), Loot.Core.ModifierRarity.NetReceive(), Loot.Core.ModifierRarity.NetSend(), and Loot.Core.ModifierRarity.Save().
abstract float Loot.Core.ModifierRarity.RequiredRarityLevel get
Definition at line 24 of file ModifierRarity.cs.
uint Loot.Core.ModifierRarity.Type get set
Definition at line 17 of file ModifierRarity.cs.
Referenced by Loot.EMMLoader.AddModifierRarity(), Loot.Core.ModifierRarity.Clone(), Loot.EMMLoader.GetNewRarityInstance(), Loot.Core.ModifierRarity.NetReceive(), and Loot.Core.ModifierRarity.NetSend().