Even More Modifiers: Loot.Core.Graphics.GlowmaskEntity Class Reference
Loot.Core.Graphics.GlowmaskEntity Class Reference
Defines a Glowmask entity, part of GraphicsEntity The entity defines a particular 'glowmask' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Public Member Functions
GlowmaskEntity (object subjectIdentity, bool drawHitbox=false, bool drawGlowmask=true, bool useDestinationRectangle=true, short order=0)
void DoDrawGlowmask (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask=null)
Will draw the glowmask texture
void DoDrawHitbox (SpriteBatch spriteBatch)
Will draw the hitbox around the entity
Rectangle GetFrameRectangle (Texture2D texture)
Protected Member Functions
void LoadAssets (Item item)
Protected Member Functions inherited from Loot.Core.Graphics.GraphicsEntity
GraphicsEntity (object subjectIdentity)
Properties
Rectangle DestinationRectangle [get, set]
bool DrawGlowmask [get, set]
bool DrawHitbox [get, set]
Texture2D GlowmaskTexture [get, protected set]
bool NeedsUpdate [get, set]
short Order [get, set]
bool UseDestinationRectangle [get, set]
Properties inherited from Loot.Core.Graphics.GraphicsEntity
Entity Entity [get, protected set]
object Identity [get, protected set]
Detailed Description
Defines a Glowmask entity, part of GraphicsEntity The entity defines a particular 'glowmask' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Definition at line 15 of file GlowmaskEntity.cs.
Constructor & Destructor Documentation
Loot.Core.Graphics.GlowmaskEntity.GlowmaskEntity (object subjectIdentity, bool drawHitbox = false, bool drawGlowmask = true, bool useDestinationRectangle = true, short order = 0)
Definition at line 25 of file GlowmaskEntity.cs.
             : base(subjectIdentity)
         {
             DrawHitbox = drawHitbox;
             DrawGlowmask = drawGlowmask;
             NeedsUpdate = false;
             UseDestinationRectangle = useDestinationRectangle;
             DestinationRectangle = null;
             Order = order;
         }
Member Function Documentation
void Loot.Core.Graphics.GlowmaskEntity.DoDrawGlowmask (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask = null)
Will draw the glowmask texture
Definition at line 75 of file GlowmaskEntity.cs.
Referenced by Loot.Core.Graphics.GlowmaskGlobalItem.PostDrawInWorld().
         {
             if (DrawGlowmask)
             {
                 Texture2D drawTexture = suppliedGlowmask;
                 if (drawTexture == null)
                 {
                     LoadAssets((Item) Entity);
                     drawTexture = GlowmaskTexture;
                 }
                 // Asset is present
                 if (drawTexture != null)
                 {
                     SpriteEffects effect = SpriteEffects.None;
                     //if (Main.LocalPlayer.gravDir == -1)
                     //  effect |= SpriteEffects.FlipVertically;
                     if (Entity.direction == -1)
                         effect |= SpriteEffects.FlipHorizontally;
                     // Draw the glowmask
                     spriteBatch.Draw
                     (
                         drawTexture,
                         new Vector2
                         (
                             Entity.position.X - Main.screenPosition.X + Entity.width * 0.5f,
                             Entity.position.Y - Main.screenPosition.Y + Entity.height - drawTexture.Height * 0.5f + 2f
                         ),
                         GetFrameRectangle(drawTexture),
                         Color.White,
                         rotation,
                         drawTexture.Size() * 0.5f,
                         scale,
                         effect,
                         0f
                     );
                 }
             }
         }
void Loot.Core.Graphics.GlowmaskEntity.DoDrawHitbox (SpriteBatch spriteBatch)
Will draw the hitbox around the entity
Definition at line 119 of file GlowmaskEntity.cs.
Referenced by Loot.Core.Graphics.GlowmaskGlobalItem.PostDrawInWorld().
         {
             if (DrawHitbox)
             {
                 Rectangle hitbox = Entity.Hitbox;
                 hitbox.Offset((int) -Main.screenPosition.X, (int) -Main.screenPosition.Y);
                 spriteBatch.Draw(Main.magicPixel, hitbox, Color.White);
             }
         }
Rectangle Loot.Core.Graphics.GlowmaskEntity.GetFrameRectangle (Texture2D texture)
Definition at line 37 of file GlowmaskEntity.cs.
         {
             if (UseDestinationRectangle)
             {
                 if (DestinationRectangle.HasValue)
                     return DestinationRectangle.Value;
                 Rectangle rectangle = new Rectangle(0, 0, texture.Width, texture.Height);
                 if (Entity is NPC)
                 {
                     rectangle = ((NPC) Entity).frame;
                 }
                 else if (Entity is Projectile)
                 {
                     rectangle.Y = ((Projectile) Entity).frame * Entity.height;
                 }
                 return rectangle;
             }
             return null;
         }
void Loot.Core.Graphics.GlowmaskEntity.LoadAssets (Item item) protected
Definition at line 60 of file GlowmaskEntity.cs.
References Loot.Core.ModContent.GraphicsModContent.Prepare().
         {
             if (GlowmaskTexture != null) return;
             var graphicsContent = Loot.ModContentManager.GetContent<GraphicsModContent>();
             graphicsContent?.Prepare(item);
             GlowmaskTexture = graphicsContent?.GetPreparedGlowmask(item.type.ToString());
             if (GlowmaskTexture == null)
             {
                 GlowmaskTexture = Main.itemTexture[item.type];
             }
         }
Property Documentation
Rectangle Loot.Core.Graphics.GlowmaskEntity.DestinationRectangle get set
Definition at line 22 of file GlowmaskEntity.cs.
bool Loot.Core.Graphics.GlowmaskEntity.DrawGlowmask get set
Definition at line 18 of file GlowmaskEntity.cs.
bool Loot.Core.Graphics.GlowmaskEntity.DrawHitbox get set
Definition at line 17 of file GlowmaskEntity.cs.
Texture2D Loot.Core.Graphics.GlowmaskEntity.GlowmaskTexture get protected set
Definition at line 20 of file GlowmaskEntity.cs.
bool Loot.Core.Graphics.GlowmaskEntity.NeedsUpdate get set
Definition at line 19 of file GlowmaskEntity.cs.
short Loot.Core.Graphics.GlowmaskEntity.Order get set
Definition at line 23 of file GlowmaskEntity.cs.
bool Loot.Core.Graphics.GlowmaskEntity.UseDestinationRectangle get set
Definition at line 21 of file GlowmaskEntity.cs.