Even More Modifiers: Loot.Api.Ext.ModUtils Class Reference
Loot.Api.Ext.ModUtils Class Reference
Defines a set of utility methods for Mod
Static Public Member Functions
static AllModifiersPool GetAllModifiersPool (this Mod mod)
static Modifier.Modifier GetModifier (Type type)
static Modifier.Modifier GetModifier (this Mod mod, Type type)
static Modifier.Modifier GetModifier (this Mod mod, string name)
static T GetModifier< T > (this Mod mod)
static ModifierEffect GetModifierEffect (Type type)
static ModifierEffect GetModifierEffect (this Mod mod, Type type)
static ModifierEffect GetModifierEffect (this Mod mod, string name)
static T GetModifierEffect< T > (this Mod mod)
static uint GetModifierEffectType (this Mod mod, Type type)
static uint GetModifierEffectType (this Mod mod, string name)
static uint GetModifierEffectType< T > (this Mod mod, string name)
static ModifierPool GetModifierPool (Type type)
static ModifierPool GetModifierPool (this Mod mod, Type type)
static ModifierPool GetModifierPool (this Mod mod, string name)
static T GetModifierPool< T > (this Mod mod)
static uint GetModifierPoolType (this Mod mod, Type type)
static uint GetModifierPoolType (this Mod mod, string name)
static uint GetModifierPoolType< T > (this Mod mod, string name)
static ModifierRarity GetModifierRarity (Type type)
static ModifierRarity GetModifierRarity (this Mod mod, Type type)
static ModifierRarity GetModifierRarity (this Mod mod, string name)
static T GetModifierRarity< T > (this Mod mod)
static uint GetModifierRarityType (this Mod mod, Type type)
static uint GetModifierRarityType (this Mod mod, string name)
static uint GetModifierRarityType< T > (this Mod mod)
static uint GetModifierType (this Mod mod, Type type)
static uint GetModifierType (this Mod mod, string name)
static uint GetModifierType< T > (this Mod mod)
static NullModifier GetNullModifier (this Mod mod)
static NullModifierEffect GetNullModifierEffect (this Mod mod)
static NullModifierPool GetNullModifierPool (this Mod mod)
static NullModifierRarity GetNullModifierRarity (this Mod mod)
Detailed Description
Defines a set of utility methods for Mod
Definition at line 16 of file ModUtils.cs.
Member Function Documentation
static AllModifiersPool Loot.Api.Ext.ModUtils.GetAllModifiersPool (this Mod mod) static
static Modifier.Modifier Loot.Api.Ext.ModUtils.GetModifier (Type type) static
static Modifier.Modifier Loot.Api.Ext.ModUtils.GetModifier (this Mod mod, Type type) static
static Modifier.Modifier Loot.Api.Ext.ModUtils.GetModifier (this Mod mod, string name) static
Definition at line 51 of file ModUtils.cs.
References Loot.Api.Modifier.Modifier.Clone(), and Loot.Api.Loaders.ContentLoader.Modifier.
         {
             if (ContentLoader.Modifier.Map.TryGetValue(mod.Name, out var v))
             {
                 var fod = v.FirstOrDefault(x => x.Value.Name.Equals(name));
                 return (Modifier.Modifier)fod.Value.Clone();
             }
             return null;
         }
static T Loot.Api.Ext.ModUtils.GetModifier< T > (this Mod mod) static
Type Constraints
T : Modifier.Modifier
T : T
T : GetModifier
T : mod
T : typeof
T : T
T : Name
static ModifierEffect Loot.Api.Ext.ModUtils.GetModifierEffect (Type type) static
static ModifierEffect Loot.Api.Ext.ModUtils.GetModifierEffect (this Mod mod, Type type) static
static ModifierEffect Loot.Api.Ext.ModUtils.GetModifierEffect (this Mod mod, string name) static
Definition at line 87 of file ModUtils.cs.
References Loot.Api.Modifier.ModifierEffect.Clone(), and Loot.Api.Loaders.ContentLoader.ModifierEffect.
         {
             if (ContentLoader.ModifierEffect.Map.TryGetValue(mod.Name, out var v))
             {
                 var fod = v.FirstOrDefault(x => x.Value.Name.Equals(name));
                 return (ModifierEffect)fod.Value.Clone();
             }
             return null;
         }
static T Loot.Api.Ext.ModUtils.GetModifierEffect< T > (this Mod mod) static
Type Constraints
T : ModifierEffect
T : T
T : GetModifierEffect
T : mod
T : typeof
T : T
T : Name
static uint Loot.Api.Ext.ModUtils.GetModifierEffectType (this Mod mod, Type type) static
static uint Loot.Api.Ext.ModUtils.GetModifierEffectType (this Mod mod, string name) static
static uint Loot.Api.Ext.ModUtils.GetModifierEffectType< T > (this Mod mod, string name) static
Type Constraints
T : ModifierEffect
T : GetModifierEffectType
T : mod
T : typeof
T : T
T : Name
static ModifierPool Loot.Api.Ext.ModUtils.GetModifierPool (Type type) static
Referenced by Loot.LootModItem.RollNewPool().
static ModifierPool Loot.Api.Ext.ModUtils.GetModifierPool (this Mod mod, Type type) static
static ModifierPool Loot.Api.Ext.ModUtils.GetModifierPool (this Mod mod, string name) static
Definition at line 69 of file ModUtils.cs.
References Loot.Api.Modifier.ModifierPool.Clone(), and Loot.Api.Loaders.ContentLoader.ModifierPool.
         {
             if (ContentLoader.ModifierPool.Map.TryGetValue(mod.Name, out var v))
             {
                 var fod = v.FirstOrDefault(x => x.Value.Name.Equals(name));
                 return (ModifierPool)fod.Value.Clone();
             }
             return null;
         }
static T Loot.Api.Ext.ModUtils.GetModifierPool< T > (this Mod mod) static
Type Constraints
T : ModifierPool
T : T
T : GetModifierPool
T : mod
T : typeof
T : T
T : Name
static uint Loot.Api.Ext.ModUtils.GetModifierPoolType (this Mod mod, Type type) static
static uint Loot.Api.Ext.ModUtils.GetModifierPoolType (this Mod mod, string name) static
static uint Loot.Api.Ext.ModUtils.GetModifierPoolType< T > (this Mod mod, string name) static
Type Constraints
T : ModifierPool
T : GetModifierPoolType
T : mod
T : typeof
T : T
T : Name
static ModifierRarity Loot.Api.Ext.ModUtils.GetModifierRarity (Type type) static
Referenced by Loot.LootModItem.RollNewPool().
static ModifierRarity Loot.Api.Ext.ModUtils.GetModifierRarity (this Mod mod, Type type) static
static ModifierRarity Loot.Api.Ext.ModUtils.GetModifierRarity (this Mod mod, string name) static
Definition at line 33 of file ModUtils.cs.
References Loot.Api.Modifier.ModifierRarity.Clone(), and Loot.Api.Loaders.ContentLoader.ModifierRarity.
         {
             if (ContentLoader.ModifierRarity.Map.TryGetValue(mod.Name, out var v))
             {
                 var fod = v.FirstOrDefault(x => x.Value.Name.Equals(name));
                 return (ModifierRarity)fod.Value.Clone();
             }
             return null;
         }
static T Loot.Api.Ext.ModUtils.GetModifierRarity< T > (this Mod mod) static
Type Constraints
T : ModifierRarity
T : T
T : GetModifierRarity
T : mod
T : typeof
T : T
T : Name
static uint Loot.Api.Ext.ModUtils.GetModifierRarityType (this Mod mod, Type type) static
static uint Loot.Api.Ext.ModUtils.GetModifierRarityType (this Mod mod, string name) static
static uint Loot.Api.Ext.ModUtils.GetModifierRarityType< T > (this Mod mod) static
Type Constraints
T : ModifierRarity
T : GetModifierRarityType
T : mod
T : typeof
T : T
T : Name
static uint Loot.Api.Ext.ModUtils.GetModifierType (this Mod mod, Type type) static
static uint Loot.Api.Ext.ModUtils.GetModifierType (this Mod mod, string name) static
static uint Loot.Api.Ext.ModUtils.GetModifierType< T > (this Mod mod) static
Type Constraints
T : Modifier.Modifier
T : GetModifierType
T : mod
T : typeof
T : T
T : Name
static NullModifier Loot.Api.Ext.ModUtils.GetNullModifier (this Mod mod) static
static NullModifierEffect Loot.Api.Ext.ModUtils.GetNullModifierEffect (this Mod mod) static
static NullModifierPool Loot.Api.Ext.ModUtils.GetNullModifierPool (this Mod mod) static
static NullModifierRarity Loot.Api.Ext.ModUtils.GetNullModifierRarity (this Mod mod) static