Even More Modifiers: Loot.Api.Delegators.ModifierDelegatorPlayer Class Reference
Loot.Api.Delegators.ModifierDelegatorPlayer Class Reference
Holds player-entity data and handles it
Public Member Functions
override void AnglerQuestReward (float rareMultiplier, List< Item > rewardItems)
override bool CanBeHitByNPC (NPC npc, ref int cooldownSlot)
delegate bool CanBeHitByNPCEventRaiser (NPC npc, ref int cooldownSlot)
override bool CanBeHitByProjectile (Projectile proj)
override bool CanHitNPC (Item item, NPC target)
override bool CanHitNPCWithProj (Projectile proj, NPC target)
override bool CanHitPvp (Item item, Player target)
override bool CanHitPvpWithProj (Projectile proj, Player target)
override void CatchFish (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
delegate void CatchFishEventRaiser (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
override bool ConsumeAmmo (Item weapon, Item ammo)
override void DrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
delegate void DrawEffectsEventRaiser (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
override void FrameEffects ()
override void GetDyeTraderReward (List< int > rewardPool)
ModifierEffect GetEffect (Type type)
T GetEffect< T > ()
override void GetFishingLevel (Item fishingRod, Item bait, ref int fishingLevel)
delegate void GetFishingLevelEventRaiser (Item fishingRod, Item bait, ref int fishingLevel)
override void GetHealLife (Item item, bool quickHeal, ref int healValue)
delegate void GetHealLifeEventRaiser (Item item, bool quickHeal, ref int healValue)
override void GetHealMana (Item item, bool quickHeal, ref int healValue)
delegate void GetHealManaEventRaiser (Item item, bool quickHeal, ref int healValue)
override void GetWeaponCrit (Item item, ref int crit)
delegate void GetWeaponCritEventRaiser (Item item, ref int crit)
override void GetWeaponKnockback (Item item, ref float knockback)
delegate void GetWeaponKnockbackEventRaiser (Item item, ref float knockback)
bool HasEffect (Type type)
bool HasEffect< T > ()
override void Hurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
override void Initialize ()
override void Kill (double damage, int hitDirection, bool pvp, PlayerDeathReason damageSource)
override void MeleeEffects (Item item, Rectangle hitbox)
override float MeleeSpeedMultiplier (Item item)
override void ModifyDrawHeadLayers (List< PlayerHeadLayer > layers)
override void ModifyDrawInfo (ref PlayerDrawInfo drawInfo)
delegate void ModifyDrawInfoEventRaiser (ref PlayerDrawInfo drawInfo)
override void ModifyDrawLayers (List< PlayerLayer > layers)
override void ModifyHitByNPC (NPC npc, ref int damage, ref bool crit)
delegate void ModifyHitByNPCEventRaiser (NPC npc, ref int damage, ref bool crit)
override void ModifyHitByProjectile (Projectile proj, ref int damage, ref bool crit)
delegate void ModifyHitByProjectileEventRaiser (Projectile projectile, ref int damage, ref bool crit)
override void ModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
delegate void ModifyHitNPCEventRaiser (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
override void ModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
delegate void ModifyHitNPCWithProjEventRaiser (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
override void ModifyHitPvp (Item item, Player target, ref int damage, ref bool crit)
delegate void ModifyHitPvpEventRaiser (Item item, Player target, ref int damage, ref bool crit)
override void ModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit)
delegate void ModifyHitPvpWithProjEventRaiser (Projectile proj, Player target, ref int damage, ref bool crit)
override void ModifyManaCost (Item item, ref float reduce, ref float mult)
delegate void ModifyManaCostEventRaiser (Item item, ref float reduce, ref float mult)
override bool ModifyNurseHeal (NPC nurse, ref int health, ref bool removeDebuffs, ref string chatText)
delegate bool ModifyNurseHealEventRaiser (NPC nurse, ref int health, ref bool removeDebuffs, ref string chatText)
override void ModifyNursePrice (NPC nurse, int health, bool removeDebuffs, ref int price)
delegate void ModifyNursePriceEventRaiser (NPC nurse, int health, bool removeDebuffs, ref int price)
override void ModifyScreenPosition ()
override void ModifyWeaponDamage (Item item, ref float add, ref float mult, ref float flat)
delegate void ModifyWeaponDamageEventRaiser (Item item, ref float add, ref float mult, ref float flat)
override void ModifyZoom (ref float zoom)
delegate void ModifyZoomEventRaiser (ref float zoom)
override void NaturalLifeRegen (ref float regen)
delegate void NaturalLifeRegenEventRaiser (ref float regen)
override void OnConsumeAmmo (Item weapon, Item ammo)
override void OnHitAnything (float x, float y, Entity victim)
override void OnHitByNPC (NPC npc, int damage, bool crit)
override void OnHitByProjectile (Projectile proj, int damage, bool crit)
override void OnHitNPC (Item item, NPC target, int damage, float knockback, bool crit)
override void OnHitNPCWithProj (Projectile proj, NPC target, int damage, float knockback, bool crit)
override void OnHitPvp (Item item, Player target, int damage, bool crit)
override void OnHitPvpWithProj (Projectile proj, Player target, int damage, bool crit)
override void OnRespawn (Player player)
override void PostHurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
override void PostItemCheck ()
override void PostNurseHeal (NPC nurse, int health, bool removeDebuffs, int price)
override void PostUpdate ()
override void PostUpdateBuffs ()
override void PostUpdateEquips ()
override void PostUpdateMiscEffects ()
override void PostUpdateRunSpeeds ()
override bool PreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool PreHurtEventRaiser (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override bool PreItemCheck ()
override bool PreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool PreKillEventRaiser (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override void PreUpdate ()
override void PreUpdateBuffs ()
override void PreUpdateMovement ()
override void ProcessTriggers (TriggersSet triggersSet)
override void ResetEffects ()
override void SendClientChanges (ModPlayer clientPlayer)
override void SetControls ()
override bool ShiftClickSlot (Item[] inventory, int context, int slot)
override bool Shoot (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
delegate bool ShootEventRaiser (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
override void SyncPlayer (int toWho, int fromWho, bool newPlayer)
override void UpdateAutopause ()
override void UpdateBadLifeRegen ()
override void UpdateDead ()
override void UpdateEquips (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
delegate void UpdateEquipsEventRaiser (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
override void UpdateLifeRegen ()
override void UpdateVanityAccessories ()
override float UseTimeMultiplier (Item item)
Static Public Member Functions
static ModifierDelegatorPlayer GetPlayer (Player player)
Events
Action< float, List< Item > > AnglerQuestRewardEvent
CanBeHitByNPCEventRaiser CanBeHitByNPCEvent
Func< Projectile, bool > CanBeHitByProjectileEvent
Func< Item, NPC, bool?> CanHitNPCEvent
Func< Projectile, NPC, bool?> CanHitNPCWithProjEvent
Func< Item, Player, bool > CanHitPvpEvent
Func< Projectile, Player, bool > CanHitPvpWithProjEvent
CatchFishEventRaiser CatchFishEvent
Func< Item, Item, bool > ConsumeAmmoEvent
DrawEffectsEventRaiser DrawEffectsEvent
Action FrameEffectsEvent
Action< List< int > > GetDyeTraderRewardEvent
GetFishingLevelEventRaiser GetFishingLevelEvent
GetHealLifeEventRaiser GetHealLifeEvent
GetHealManaEventRaiser GetHealManaEvent
GetWeaponCritEventRaiser GetWeaponCritEvent
GetWeaponKnockbackEventRaiser GetWeaponKnockbackEvent
Action< bool, bool, double, int, bool > HurtEvent
Action InitializeEvent
Action< double, int, bool, PlayerDeathReason > KillEvent
Action< Item, Rectangle > MeleeEffectsEvent
Func< Item, float > MeleeSpeedMultiplierEvent
Action< List< PlayerHeadLayer > > ModifyDrawHeadLayersEvent
ModifyDrawInfoEventRaiser ModifyDrawInfoEvent
Action< List< PlayerLayer > > ModifyDrawLayersEvent
ModifyHitByNPCEventRaiser ModifyHitByNPCEvent
ModifyHitByProjectileEventRaiser ModifyHitByProjectileEvent
ModifyHitNPCEventRaiser ModifyHitNPCEvent
ModifyHitNPCWithProjEventRaiser ModifyHitNPCWithProjEvent
ModifyHitPvpEventRaiser ModifyHitPvpEvent
ModifyHitPvpWithProjEventRaiser ModifyHitPvpWithProjEvent
ModifyManaCostEventRaiser ModifyManaCostEvent
ModifyNurseHealEventRaiser ModifyNurseHealEvent
ModifyNursePriceEventRaiser ModifyNursePriceEvent
Action ModifyScreenPositionEvent
ModifyWeaponDamageEventRaiser ModifyWeaponDamageEvent
ModifyZoomEventRaiser ModifyZoomEvent
NaturalLifeRegenEventRaiser NaturalLifeRegenEvent
Action< Item, Item > OnConsumeAmmoEvent
Action< float, float, Entity > OnHitAnythingEvent
Action< NPC, int, bool > OnHitByNPCEvent
Action< Projectile, int, bool > OnHitByProjectileEvent
Action< Item, NPC, int, float, bool > OnHitNPCEvent
Action< Projectile, NPC, int, float, bool > OnHitNPCWithProjEvent
Action< Item, Player, int, bool > OnHitPvpEvent
Action< Projectile, Player, int, bool > OnHitPvpWithProjEvent
Action< Player > OnRespawnEvent
Action< bool, bool, double, int, bool > PostHurtEvent
Action PostItemCheckEvent
Action< NPC, int, bool, int > PostNurseHealEvent
Action PostUpdateBuffsEvent
Action PostUpdateEquipsEvent
Action PostUpdateEvent
Action PostUpdateMiscEffectsEvent
Action PostUpdateRunSpeedsEvent
PreHurtEventRaiser PreHurtEvent
Func< bool > PreItemCheckEvent
PreKillEventRaiser PreKillEvent
Action PreUpdateBuffsEvent
Action PreUpdateEvent
Action PreUpdateMovementEvent
Action< TriggersSet > ProcessTriggersEvent
Action ResetEffectsEvent
Action< ModPlayer > SendClientChangesEvent
Action SetControlsEvent
Func< Item[], int, int, bool > ShiftClickSlotEvent
ShootEventRaiser ShootEvent
Action< int, int, bool > SyncPlayerEvent
Action UpdateAutopauseEvent
Action UpdateBadLifeRegenEvent
Action UpdateDeadEvent
UpdateEquipsEventRaiser UpdateEquipsEvent
Action UpdateLifeRegenEvent
Action UpdateVanityAccessoriesEvent
Func< Item, float > UseTimeMultiplierEvent
Private Attributes
IList< ModifierEffect > _modifierEffects
Detailed Description
Holds player-entity data and handles it
Definition at line 18 of file ModifierDelegatorPlayer.cs.
Member Function Documentation
override void Loot.Api.Delegators.ModifierDelegatorPlayer.AnglerQuestReward (float rareMultiplier, List< Item > rewardItems)
Definition at line 398 of file ModifierDelegatorPlayer.cs.
         {
             AnglerQuestRewardEvent?.Invoke(rareMultiplier, rewardItems);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanBeHitByNPC (NPC npc, ref int cooldownSlot)
Definition at line 332 of file ModifierDelegatorPlayer.cs.
         {
             return CanBeHitByNPCEvent?.Invoke(npc, ref cooldownSlot) ?? base.CanBeHitByNPC(npc, ref cooldownSlot);
         }
delegate bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanBeHitByNPCEventRaiser (NPC npc, ref int cooldownSlot)
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanBeHitByProjectile (Projectile proj)
Definition at line 365 of file ModifierDelegatorPlayer.cs.
         {
             return CanBeHitByProjectileEvent?.Invoke(proj) ?? base.CanBeHitByProjectile(proj);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitNPC (Item item, NPC target)
Definition at line 255 of file ModifierDelegatorPlayer.cs.
         {
             return CanHitNPCEvent?.Invoke(item, target) ?? base.CanHitNPC(item, target);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitNPCWithProj (Projectile proj, NPC target)
Definition at line 287 of file ModifierDelegatorPlayer.cs.
         {
             return CanHitNPCWithProjEvent?.Invoke(proj, target) ?? base.CanHitNPCWithProj(proj, target);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitPvp (Item item, Player target)
Definition at line 268 of file ModifierDelegatorPlayer.cs.
         {
             return CanHitPvpEvent?.Invoke(item, target) ?? base.CanHitPvp(item, target);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitPvpWithProj (Projectile proj, Player target)
Definition at line 312 of file ModifierDelegatorPlayer.cs.
         {
             return CanHitPvpWithProjEvent?.Invoke(proj, target) ?? base.CanHitPvpWithProj(proj, target);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.CatchFish (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
Definition at line 385 of file ModifierDelegatorPlayer.cs.
         {
             CatchFishEvent?.Invoke(fishingRod, bait, power, liquidType, poolSize, worldLayer, questFish, ref caughtType, ref junk);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.CatchFishEventRaiser (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.ConsumeAmmo (Item weapon, Item ammo)
Definition at line 515 of file ModifierDelegatorPlayer.cs.
         {
             return ConsumeAmmoEvent?.Invoke(weapon, ammo) ?? base.ConsumeAmmo(weapon, ammo);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.DrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
Definition at line 411 of file ModifierDelegatorPlayer.cs.
         {
             DrawEffectsEvent?.Invoke(drawInfo, ref r, ref g, ref b, ref a, ref fullBright);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.DrawEffectsEventRaiser (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.FrameEffects ()
Definition at line 229 of file ModifierDelegatorPlayer.cs.
         {
             FrameEffectsEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetDyeTraderReward (List< int > rewardPool)
Definition at line 404 of file ModifierDelegatorPlayer.cs.
         {
             GetDyeTraderRewardEvent?.Invoke(rewardPool);
         }
ModifierEffect Loot.Api.Delegators.ModifierDelegatorPlayer.GetEffect (Type type)
Definition at line 25 of file ModifierDelegatorPlayer.cs.
Referenced by Loot.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.Base.WeaponDebuffModifier.HoldItem(), Loot.Api.Delegators.ModifierDelegatorProjectile.PreAI(), Loot.Api.Strategy.RollingStrategy.RollProperties(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.UpdateEquip(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.UpdateEquip().
         {
             return _modifierEffects.FirstOrDefault(x => x.GetType() == type);
         }
T Loot.Api.Delegators.ModifierDelegatorPlayer.GetEffect< T > ()
Type Constraints
T : ModifierEffect
Definition at line 30 of file ModifierDelegatorPlayer.cs.
                                         : ModifierEffect
         {
             return (T)_modifierEffects.FirstOrDefault(x => x.GetType() == typeof(T));
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetFishingLevel (Item fishingRod, Item bait, ref int fishingLevel)
Definition at line 392 of file ModifierDelegatorPlayer.cs.
         {
             GetFishingLevelEvent?.Invoke(fishingRod, bait, ref fishingLevel);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.GetFishingLevelEventRaiser (Item fishingRod, Item bait, ref int fishingLevel)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealLife (Item item, bool quickHeal, ref int healValue)
Definition at line 488 of file ModifierDelegatorPlayer.cs.
         {
             GetHealLifeEvent?.Invoke(item, quickHeal, ref healValue);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealLifeEventRaiser (Item item, bool quickHeal, ref int healValue)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealMana (Item item, bool quickHeal, ref int healValue)
Definition at line 495 of file ModifierDelegatorPlayer.cs.
         {
             GetHealManaEvent?.Invoke(item, quickHeal, ref healValue);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealManaEventRaiser (Item item, bool quickHeal, ref int healValue)
static ModifierDelegatorPlayer Loot.Api.Delegators.ModifierDelegatorPlayer.GetPlayer (Player player) static
Referenced by Loot.Caching.ModifierCachePlayer.CacheItemModifierEffects(), Loot.Modifiers.Base.WeaponDebuffModifier.HoldItem(), Loot.Api.Strategy.RollingStrategy.RollProperties(), Loot.Caching.ModifierCachePlayer.UpdateAttachments(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.UpdateEquip(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.UpdateEquip(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.UpdateEquip(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.UpdateEquip().
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponCrit (Item item, ref int crit)
Definition at line 509 of file ModifierDelegatorPlayer.cs.
         {
             GetWeaponCritEvent?.Invoke(item, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponCritEventRaiser (Item item, ref int crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponKnockback (Item item, ref float knockback)
Definition at line 502 of file ModifierDelegatorPlayer.cs.
         {
             GetWeaponKnockbackEvent?.Invoke(item, ref knockback);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponKnockbackEventRaiser (Item item, ref float knockback)
bool Loot.Api.Delegators.ModifierDelegatorPlayer.HasEffect (Type type)
bool Loot.Api.Delegators.ModifierDelegatorPlayer.HasEffect< T > ()
Type Constraints
T : ModifierEffect
T : _modifierEffects.Any
T : x
T : x.GetType()
T : typeof
T : T
override void Loot.Api.Delegators.ModifierDelegatorPlayer.Hurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
Definition at line 243 of file ModifierDelegatorPlayer.cs.
         {
             HurtEvent?.Invoke(pvp, quiet, damage, hitDirection, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.Initialize ()
Definition at line 86 of file ModifierDelegatorPlayer.cs.
References Loot.Api.Loaders.ContentLoader.ModifierEffect.
         {
             // Initialize the effects list for this player
             _modifierEffects = new List<ModifierEffect>();
             // Need to initialize with a fresh set of new effect instances
             foreach (var effect in ContentLoader.ModifierEffect.Content.Select(x => x.Value))
             {
                 var clone = (ModifierEffect)effect.Clone();
                 clone.DelegatorPlayer = this;
                 clone.OnInitialize();
                 _modifierEffects.Add(clone);
             }
             InitializeEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.Kill (double damage, int hitDirection, bool pvp, PlayerDeathReason damageSource)
Definition at line 457 of file ModifierDelegatorPlayer.cs.
         {
             KillEvent?.Invoke(damage, hitDirection, pvp, damageSource);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.MeleeEffects (Item item, Rectangle hitbox)
Definition at line 535 of file ModifierDelegatorPlayer.cs.
         {
             MeleeEffectsEvent?.Invoke(item, hitbox);
         }
override float Loot.Api.Delegators.ModifierDelegatorPlayer.MeleeSpeedMultiplier (Item item)
Definition at line 481 of file ModifierDelegatorPlayer.cs.
         {
             return MeleeSpeedMultiplierEvent?.Invoke(item) ?? base.MeleeSpeedMultiplier(item);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawHeadLayers (List< PlayerHeadLayer > layers)
Definition at line 430 of file ModifierDelegatorPlayer.cs.
         {
             ModifyDrawHeadLayersEvent?.Invoke(layers);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawInfo (ref PlayerDrawInfo drawInfo)
Definition at line 418 of file ModifierDelegatorPlayer.cs.
         {
             ModifyDrawInfoEvent?.Invoke(ref drawInfo);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawInfoEventRaiser (ref PlayerDrawInfo drawInfo)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawLayers (List< PlayerLayer > layers)
Definition at line 424 of file ModifierDelegatorPlayer.cs.
         {
             ModifyDrawLayersEvent?.Invoke(layers);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByNPC (NPC npc, ref int damage, ref bool crit)
Definition at line 339 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitByNPCEvent?.Invoke(npc, ref damage, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByNPCEventRaiser (NPC npc, ref int damage, ref bool crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByProjectile (Projectile proj, ref int damage, ref bool crit)
Definition at line 372 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitByProjectileEvent?.Invoke(proj, ref damage, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByProjectileEventRaiser (Projectile projectile, ref int damage, ref bool crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
Definition at line 262 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitNPCEvent?.Invoke(item, target, ref damage, ref knockback, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPCEventRaiser (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
Definition at line 294 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitNPCWithProjEvent?.Invoke(proj, target, ref damage, ref knockback, ref crit, ref hitDirection);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPCWithProjEventRaiser (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvp (Item item, Player target, ref int damage, ref bool crit)
Definition at line 275 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitPvpEvent?.Invoke(item, target, ref damage, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvpEventRaiser (Item item, Player target, ref int damage, ref bool crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit)
Definition at line 319 of file ModifierDelegatorPlayer.cs.
         {
             ModifyHitPvpWithProjEvent?.Invoke(proj, target, ref damage, ref crit);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvpWithProjEventRaiser (Projectile proj, Player target, ref int damage, ref bool crit)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyManaCost (Item item, ref float reduce, ref float mult)
Definition at line 353 of file ModifierDelegatorPlayer.cs.
         {
             ModifyManaCostEvent?.Invoke(item, ref reduce, ref mult);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyManaCostEventRaiser (Item item, ref float reduce, ref float mult)
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNurseHeal (NPC nurse, ref int health, ref bool removeDebuffs, ref string chatText)
Definition at line 67 of file ModifierDelegatorPlayer.cs.
         {
             return ModifyNurseHealEvent?.Invoke(nurse, ref health, ref removeDebuffs, ref chatText) ?? base.ModifyNurseHeal(nurse, ref health, ref removeDebuffs, ref chatText);
         }
delegate bool Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNurseHealEventRaiser (NPC nurse, ref int health, ref bool removeDebuffs, ref string chatText)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNursePrice (NPC nurse, int health, bool removeDebuffs, ref int price)
Definition at line 74 of file ModifierDelegatorPlayer.cs.
         {
             ModifyNursePriceEvent?.Invoke(nurse, health, removeDebuffs, ref price);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNursePriceEventRaiser (NPC nurse, int health, bool removeDebuffs, ref int price)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyScreenPosition ()
Definition at line 436 of file ModifierDelegatorPlayer.cs.
         {
             ModifyScreenPositionEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyWeaponDamage (Item item, ref float add, ref float mult, ref float flat)
Definition at line 346 of file ModifierDelegatorPlayer.cs.
         {
             ModifyWeaponDamageEvent?.Invoke(item, ref add, ref mult, ref flat);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyWeaponDamageEventRaiser (Item item, ref float add, ref float mult, ref float flat)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyZoom (ref float zoom)
Definition at line 443 of file ModifierDelegatorPlayer.cs.
         {
             ModifyZoomEvent?.Invoke(ref zoom);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyZoomEventRaiser (ref float zoom)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.NaturalLifeRegen (ref float regen)
Definition at line 169 of file ModifierDelegatorPlayer.cs.
         {
             NaturalLifeRegenEvent?.Invoke(ref regen);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.NaturalLifeRegenEventRaiser (ref float regen)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnConsumeAmmo (Item weapon, Item ammo)
Definition at line 521 of file ModifierDelegatorPlayer.cs.
         {
             OnConsumeAmmoEvent?.Invoke(weapon, ammo);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitAnything (float x, float y, Entity victim)
Definition at line 541 of file ModifierDelegatorPlayer.cs.
         {
             OnHitAnythingEvent?.Invoke(x, y, victim);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitByNPC (NPC npc, int damage, bool crit)
Definition at line 359 of file ModifierDelegatorPlayer.cs.
         {
             OnHitByNPCEvent?.Invoke(npc, damage, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitByProjectile (Projectile proj, int damage, bool crit)
Definition at line 378 of file ModifierDelegatorPlayer.cs.
         {
             OnHitByProjectileEvent?.Invoke(proj, damage, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitNPC (Item item, NPC target, int damage, float knockback, bool crit)
Definition at line 281 of file ModifierDelegatorPlayer.cs.
         {
             OnHitNPCEvent?.Invoke(item, target, damage, knockback, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitNPCWithProj (Projectile proj, NPC target, int damage, float knockback, bool crit)
Definition at line 300 of file ModifierDelegatorPlayer.cs.
         {
             OnHitNPCWithProjEvent?.Invoke(proj, target, damage, knockback, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitPvp (Item item, Player target, int damage, bool crit)
Definition at line 306 of file ModifierDelegatorPlayer.cs.
         {
             OnHitPvpEvent?.Invoke(item, target, damage, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitPvpWithProj (Projectile proj, Player target, int damage, bool crit)
Definition at line 325 of file ModifierDelegatorPlayer.cs.
         {
             OnHitPvpWithProjEvent?.Invoke(proj, target, damage, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.OnRespawn (Player player)
Definition at line 54 of file ModifierDelegatorPlayer.cs.
         {
             OnRespawnEvent?.Invoke(player);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostHurt (bool pvp, bool quiet, double damage, int hitDirection, bool crit)
Definition at line 249 of file ModifierDelegatorPlayer.cs.
         {
             PostHurtEvent?.Invoke(pvp, quiet, damage, hitDirection, crit);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostItemCheck ()
Definition at line 469 of file ModifierDelegatorPlayer.cs.
         {
             PostItemCheckEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostNurseHeal (NPC nurse, int health, bool removeDebuffs, int price)
Definition at line 80 of file ModifierDelegatorPlayer.cs.
         {
             PostNurseHealEvent?.Invoke(nurse, health, removeDebuffs, price);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdate ()
Definition at line 217 of file ModifierDelegatorPlayer.cs.
         {
             PostUpdateEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateBuffs ()
Definition at line 134 of file ModifierDelegatorPlayer.cs.
         {
             PostUpdateBuffsEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateEquips ()
Definition at line 193 of file ModifierDelegatorPlayer.cs.
         {
             PostUpdateEquipsEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateMiscEffects ()
Definition at line 199 of file ModifierDelegatorPlayer.cs.
         {
             PostUpdateMiscEffectsEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateRunSpeeds ()
Definition at line 205 of file ModifierDelegatorPlayer.cs.
         {
             PostUpdateRunSpeedsEvent?.Invoke();
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.PreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Definition at line 236 of file ModifierDelegatorPlayer.cs.
         {
             return PreHurtEvent?.Invoke(pvp, quiet, ref damage, ref hitDirection, ref crit, ref customDamage, ref playSound, ref genGore, ref damageSource)
                    ?? base.PreHurt(pvp, quiet, ref damage, ref hitDirection, ref crit, ref customDamage, ref playSound, ref genGore, ref damageSource);
         }
delegate bool Loot.Api.Delegators.ModifierDelegatorPlayer.PreHurtEventRaiser (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.PreItemCheck ()
Definition at line 463 of file ModifierDelegatorPlayer.cs.
         {
             return PreItemCheckEvent?.Invoke() ?? base.PreItemCheck();
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.PreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
Definition at line 450 of file ModifierDelegatorPlayer.cs.
         {
             return PreKillEvent?.Invoke(damage, hitDirection, pvp, ref playSound, ref genGore, ref damageSource)
                    ?? base.PreKill(damage, hitDirection, pvp, ref playSound, ref genGore, ref damageSource);
         }
delegate bool Loot.Api.Delegators.ModifierDelegatorPlayer.PreKillEventRaiser (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdate ()
Definition at line 110 of file ModifierDelegatorPlayer.cs.
         {
             PreUpdateEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdateBuffs ()
Definition at line 128 of file ModifierDelegatorPlayer.cs.
         {
             PreUpdateBuffsEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdateMovement ()
Definition at line 211 of file ModifierDelegatorPlayer.cs.
         {
             PreUpdateMovementEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ProcessTriggers (TriggersSet triggersSet)
Definition at line 116 of file ModifierDelegatorPlayer.cs.
         {
             ProcessTriggersEvent?.Invoke(triggersSet);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.ResetEffects ()
Definition at line 147 of file ModifierDelegatorPlayer.cs.
         {
             if (player.GetModPlayer<ModifierCachePlayer>().Ready)
             {
                 ResetEffectsEvent?.Invoke();
             }
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.SendClientChanges (ModPlayer clientPlayer)
Definition at line 181 of file ModifierDelegatorPlayer.cs.
         {
             SendClientChangesEvent?.Invoke(clientPlayer);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.SetControls ()
Definition at line 122 of file ModifierDelegatorPlayer.cs.
         {
             SetControlsEvent?.Invoke();
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.ShiftClickSlot (Item[] inventory, int context, int slot)
Definition at line 60 of file ModifierDelegatorPlayer.cs.
         {
             return ShiftClickSlotEvent?.Invoke(inventory, context, slot) ?? base.ShiftClickSlot(inventory, context, slot);
         }
override bool Loot.Api.Delegators.ModifierDelegatorPlayer.Shoot (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
Definition at line 528 of file ModifierDelegatorPlayer.cs.
         {
             return ShootEvent?.Invoke(item, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack)
                 ?? base.Shoot(item, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
         }
delegate bool Loot.Api.Delegators.ModifierDelegatorPlayer.ShootEventRaiser (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.SyncPlayer (int toWho, int fromWho, bool newPlayer)
Definition at line 175 of file ModifierDelegatorPlayer.cs.
         {
             SyncPlayerEvent?.Invoke(toWho, fromWho, newPlayer);
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateAutopause ()
Definition at line 104 of file ModifierDelegatorPlayer.cs.
         {
             UpdateAutopauseEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateBadLifeRegen ()
Definition at line 187 of file ModifierDelegatorPlayer.cs.
         {
             UpdateBadLifeRegenEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateDead ()
Definition at line 156 of file ModifierDelegatorPlayer.cs.
         {
             UpdateDeadEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateEquips (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
Definition at line 141 of file ModifierDelegatorPlayer.cs.
         {
             UpdateEquipsEvent?.Invoke(ref wallSpeedBuff, ref tileSpeedBuff, ref tileRangeBuff);
         }
delegate void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateEquipsEventRaiser (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateLifeRegen ()
Definition at line 162 of file ModifierDelegatorPlayer.cs.
         {
             UpdateLifeRegenEvent?.Invoke();
         }
override void Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateVanityAccessories ()
Definition at line 223 of file ModifierDelegatorPlayer.cs.
         {
             UpdateVanityAccessoriesEvent?.Invoke();
         }
override float Loot.Api.Delegators.ModifierDelegatorPlayer.UseTimeMultiplier (Item item)
Definition at line 475 of file ModifierDelegatorPlayer.cs.
         {
             return UseTimeMultiplierEvent?.Invoke(item) ?? base.UseTimeMultiplier(item);
         }
Member Data Documentation
IList<ModifierEffect> Loot.Api.Delegators.ModifierDelegatorPlayer._modifierEffects private
Definition at line 20 of file ModifierDelegatorPlayer.cs.
Event Documentation
Action<float, List<Item> > Loot.Api.Delegators.ModifierDelegatorPlayer.AnglerQuestRewardEvent
Definition at line 397 of file ModifierDelegatorPlayer.cs.
CanBeHitByNPCEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.CanBeHitByNPCEvent
Definition at line 331 of file ModifierDelegatorPlayer.cs.
Func<Projectile, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.CanBeHitByProjectileEvent
Definition at line 364 of file ModifierDelegatorPlayer.cs.
Func<Item, NPC, bool?> Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitNPCEvent
Definition at line 254 of file ModifierDelegatorPlayer.cs.
Func<Projectile, NPC, bool?> Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitNPCWithProjEvent
Definition at line 286 of file ModifierDelegatorPlayer.cs.
Func<Item, Player, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitPvpEvent
Definition at line 267 of file ModifierDelegatorPlayer.cs.
Func<Projectile, Player, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.CanHitPvpWithProjEvent
Definition at line 311 of file ModifierDelegatorPlayer.cs.
CatchFishEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.CatchFishEvent
Definition at line 384 of file ModifierDelegatorPlayer.cs.
Func<Item, Item, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.ConsumeAmmoEvent
Definition at line 514 of file ModifierDelegatorPlayer.cs.
DrawEffectsEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.DrawEffectsEvent
Definition at line 410 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.FrameEffectsEvent
Definition at line 228 of file ModifierDelegatorPlayer.cs.
Action<List<int> > Loot.Api.Delegators.ModifierDelegatorPlayer.GetDyeTraderRewardEvent
Definition at line 403 of file ModifierDelegatorPlayer.cs.
GetFishingLevelEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.GetFishingLevelEvent
Definition at line 391 of file ModifierDelegatorPlayer.cs.
GetHealLifeEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealLifeEvent
Definition at line 487 of file ModifierDelegatorPlayer.cs.
GetHealManaEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.GetHealManaEvent
Definition at line 494 of file ModifierDelegatorPlayer.cs.
GetWeaponCritEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponCritEvent
Definition at line 508 of file ModifierDelegatorPlayer.cs.
GetWeaponKnockbackEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.GetWeaponKnockbackEvent
Definition at line 501 of file ModifierDelegatorPlayer.cs.
Action<bool, bool, double, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.HurtEvent
Definition at line 242 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.InitializeEvent
Definition at line 85 of file ModifierDelegatorPlayer.cs.
Action<double, int, bool, PlayerDeathReason> Loot.Api.Delegators.ModifierDelegatorPlayer.KillEvent
Definition at line 456 of file ModifierDelegatorPlayer.cs.
Action<Item, Rectangle> Loot.Api.Delegators.ModifierDelegatorPlayer.MeleeEffectsEvent
Definition at line 534 of file ModifierDelegatorPlayer.cs.
Func<Item, float> Loot.Api.Delegators.ModifierDelegatorPlayer.MeleeSpeedMultiplierEvent
Definition at line 480 of file ModifierDelegatorPlayer.cs.
Action<List<PlayerHeadLayer> > Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawHeadLayersEvent
Definition at line 429 of file ModifierDelegatorPlayer.cs.
ModifyDrawInfoEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawInfoEvent
Definition at line 417 of file ModifierDelegatorPlayer.cs.
Action<List<PlayerLayer> > Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyDrawLayersEvent
Definition at line 423 of file ModifierDelegatorPlayer.cs.
ModifyHitByNPCEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByNPCEvent
Definition at line 338 of file ModifierDelegatorPlayer.cs.
ModifyHitByProjectileEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitByProjectileEvent
Definition at line 371 of file ModifierDelegatorPlayer.cs.
ModifyHitNPCEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPCEvent
Definition at line 261 of file ModifierDelegatorPlayer.cs.
ModifyHitNPCWithProjEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitNPCWithProjEvent
Definition at line 293 of file ModifierDelegatorPlayer.cs.
ModifyHitPvpEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvpEvent
Definition at line 274 of file ModifierDelegatorPlayer.cs.
ModifyHitPvpWithProjEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyHitPvpWithProjEvent
Definition at line 318 of file ModifierDelegatorPlayer.cs.
ModifyManaCostEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyManaCostEvent
Definition at line 352 of file ModifierDelegatorPlayer.cs.
ModifyNurseHealEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNurseHealEvent
Definition at line 66 of file ModifierDelegatorPlayer.cs.
ModifyNursePriceEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyNursePriceEvent
Definition at line 73 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyScreenPositionEvent
Definition at line 435 of file ModifierDelegatorPlayer.cs.
ModifyWeaponDamageEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyWeaponDamageEvent
Definition at line 345 of file ModifierDelegatorPlayer.cs.
ModifyZoomEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ModifyZoomEvent
Definition at line 442 of file ModifierDelegatorPlayer.cs.
NaturalLifeRegenEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.NaturalLifeRegenEvent
Definition at line 168 of file ModifierDelegatorPlayer.cs.
Action<Item, Item> Loot.Api.Delegators.ModifierDelegatorPlayer.OnConsumeAmmoEvent
Definition at line 520 of file ModifierDelegatorPlayer.cs.
Action<float, float, Entity> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitAnythingEvent
Definition at line 540 of file ModifierDelegatorPlayer.cs.
Action<NPC, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitByNPCEvent
Definition at line 358 of file ModifierDelegatorPlayer.cs.
Action<Projectile, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitByProjectileEvent
Definition at line 377 of file ModifierDelegatorPlayer.cs.
Action<Item, NPC, int, float, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitNPCEvent
Definition at line 280 of file ModifierDelegatorPlayer.cs.
Action<Projectile, NPC, int, float, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitNPCWithProjEvent
Definition at line 299 of file ModifierDelegatorPlayer.cs.
Action<Item, Player, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitPvpEvent
Definition at line 305 of file ModifierDelegatorPlayer.cs.
Action<Projectile, Player, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.OnHitPvpWithProjEvent
Definition at line 324 of file ModifierDelegatorPlayer.cs.
Action<Player> Loot.Api.Delegators.ModifierDelegatorPlayer.OnRespawnEvent
Definition at line 53 of file ModifierDelegatorPlayer.cs.
Action<bool, bool, double, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.PostHurtEvent
Definition at line 248 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostItemCheckEvent
Definition at line 468 of file ModifierDelegatorPlayer.cs.
Action<NPC, int, bool, int> Loot.Api.Delegators.ModifierDelegatorPlayer.PostNurseHealEvent
Definition at line 79 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateBuffsEvent
Definition at line 133 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateEquipsEvent
Definition at line 192 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateEvent
Definition at line 216 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateMiscEffectsEvent
Definition at line 198 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PostUpdateRunSpeedsEvent
Definition at line 204 of file ModifierDelegatorPlayer.cs.
PreHurtEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.PreHurtEvent
Definition at line 235 of file ModifierDelegatorPlayer.cs.
Func<bool> Loot.Api.Delegators.ModifierDelegatorPlayer.PreItemCheckEvent
Definition at line 462 of file ModifierDelegatorPlayer.cs.
PreKillEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.PreKillEvent
Definition at line 449 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdateBuffsEvent
Definition at line 127 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdateEvent
Definition at line 109 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.PreUpdateMovementEvent
Definition at line 210 of file ModifierDelegatorPlayer.cs.
Action<TriggersSet> Loot.Api.Delegators.ModifierDelegatorPlayer.ProcessTriggersEvent
Definition at line 115 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.ResetEffectsEvent
Definition at line 146 of file ModifierDelegatorPlayer.cs.
Action<ModPlayer> Loot.Api.Delegators.ModifierDelegatorPlayer.SendClientChangesEvent
Definition at line 180 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.SetControlsEvent
Definition at line 121 of file ModifierDelegatorPlayer.cs.
Func<Item[], int, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.ShiftClickSlotEvent
Definition at line 59 of file ModifierDelegatorPlayer.cs.
ShootEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.ShootEvent
Definition at line 527 of file ModifierDelegatorPlayer.cs.
Action<int, int, bool> Loot.Api.Delegators.ModifierDelegatorPlayer.SyncPlayerEvent
Definition at line 174 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateAutopauseEvent
Definition at line 103 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateBadLifeRegenEvent
Definition at line 186 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateDeadEvent
Definition at line 155 of file ModifierDelegatorPlayer.cs.
UpdateEquipsEventRaiser Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateEquipsEvent
Definition at line 140 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateLifeRegenEvent
Definition at line 161 of file ModifierDelegatorPlayer.cs.
Action Loot.Api.Delegators.ModifierDelegatorPlayer.UpdateVanityAccessoriesEvent
Definition at line 222 of file ModifierDelegatorPlayer.cs.
Func<Item, float> Loot.Api.Delegators.ModifierDelegatorPlayer.UseTimeMultiplierEvent
Definition at line 474 of file ModifierDelegatorPlayer.cs.