Even More Modifiers: Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder Class Reference
Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder Class Reference
A builder for ShaderGraphicsProperties
Public Member Functions
ShaderGraphicsPropertiesBuilder SkipDrawing (bool value)
ShaderGraphicsPropertiesBuilder SkipDrawingGlowmask (bool val)
ShaderGraphicsPropertiesBuilder SkipDrawingShader (bool value)
ShaderGraphicsPropertiesBuilder SkipDrawingSubject (bool value)
ShaderGraphicsPropertiesBuilder WithDrawLayer (ShaderDrawLayer drawLayer)
ShaderGraphicsPropertiesBuilder WithShaderDrawStyle (ShaderDrawStyle shaderDrawStyle)
Public Member Functions inherited from Loot.Api.Builder.PropertyBuilder< ShaderGraphicsProperties >
virtual T Build ()
void WithDefault (IPropertyBuilder< T > defaultPropertyBuilder)
void WithDefault (T defaultValue)
Properties
override ShaderGraphicsProperties DefaultProperty [set]
Properties inherited from Loot.Api.Builder.PropertyBuilder< ShaderGraphicsProperties >
abstract T DefaultProperty [set]
Additional Inherited Members
Protected Member Functions inherited from Loot.Api.Builder.PropertyBuilder< ShaderGraphicsProperties >
PropertyBuilder ()
PropertyBuilder (IPropertyBuilder< T > defaultPropertyBuilder)
PropertyBuilder (T defaultValue)
Protected Attributes inherited from Loot.Api.Builder.PropertyBuilder< ShaderGraphicsProperties >
T Property
Detailed Description
A builder for ShaderGraphicsProperties
Definition at line 22 of file ShaderGraphicsProperties.cs.
Member Function Documentation
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawing (bool value)
Definition at line 59 of file ShaderGraphicsProperties.cs.
References Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawing().
Referenced by Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawing().
             {
                 Property.SkipDrawing = value;
                 return this;
             }
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingGlowmask (bool val)
Definition at line 65 of file ShaderGraphicsProperties.cs.
References Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingGlowmask().
Referenced by Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingGlowmask().
             {
                 Property.SkipDrawingGlowmask = val;
                 return this;
             }
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingShader (bool value)
Definition at line 53 of file ShaderGraphicsProperties.cs.
References Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingShader().
Referenced by Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingShader().
             {
                 Property.SkipDrawingShader = value;
                 return this;
             }
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingSubject (bool value)
Definition at line 47 of file ShaderGraphicsProperties.cs.
References Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingSubject().
Referenced by Loot.Modifiers.WeaponModifiers.Ice.IceModifier.GetShaderEntity(), and Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.SkipDrawingSubject().
             {
                 Property.SkipDrawingSubject = value;
                 return this;
             }
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.WithDrawLayer (ShaderDrawLayer drawLayer)
Definition at line 35 of file ShaderGraphicsProperties.cs.
Referenced by Loot.Modifiers.WeaponModifiers.Ice.IceModifier.GetShaderEntity().
             {
                 Property.DrawLayer = drawLayer;
                 return this;
             }
ShaderGraphicsPropertiesBuilder Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.WithShaderDrawStyle (ShaderDrawStyle shaderDrawStyle)
Definition at line 41 of file ShaderGraphicsProperties.cs.
Referenced by Loot.Modifiers.WeaponModifiers.Ice.IceModifier.GetShaderEntity().
             {
                 Property.ShaderDrawStyle = shaderDrawStyle;
                 return this;
             }
Property Documentation
override ShaderGraphicsProperties Loot.Api.Graphics.Shader.ShaderGraphicsProperties.ShaderGraphicsPropertiesBuilder.DefaultProperty set protected
Definition at line 25 of file ShaderGraphicsProperties.cs.