Even More Modifiers: Loot.Api.Graphics.ShaderEntity Class Reference
Loot.Api.Graphics.ShaderEntity Class Reference
Defines a Shader entity, part of GraphicsEntity The entity defines a particular 'shader' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Public Member Functions
ShaderEntity (object subjectIdentity, int shaderId, ShaderDrawLayer drawLayer=ShaderDrawLayer.Back, ShaderDrawStyle shaderDrawStyle=null, int numSegments=8, int drawDistance=4, Color?shaderDrawColor=null, short order=0)
void DoDrawLayeredEntity (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float scale, float rotation, GlowmaskEntity glowmaskEntity=null)
Will draw all the layers (subject, glowmask, shader) in the proper order
void DoDrawShader (Texture2D shaderTexture, SpriteBatch spriteBatch)
Will draw the shader effect
void DoDrawSubject (Texture2D subjectTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the entity's regular sprite
Public Member Functions inherited from Loot.Api.Graphics.GraphicsEntity
void TryGettingDrawData (float rotation, float scale)
Sets up drawing data initially
void TryUpdatingDrawData (Texture2D texture)
Protected Member Functions
override void LoadAssets (Item item)
Protected Member Functions inherited from Loot.Api.Graphics.GraphicsEntity
GraphicsEntity (object subjectIdentity)
void DrawDrawData (SpriteBatch spriteBatch, DrawData data)
Properties
int DrawDistance [get, set]
ShaderDrawLayer DrawLayer [get, set]
bool NeedsUpdate [get, set]
int NumSegments [get, set]
short Order [get, set]
ShaderDrawStyle ShaderDrawStyle [get, set]
int ShaderId [get, set]
Texture2D ShaderTexture [get, protected set]
Texture2D SubjectTexture [get, protected set]
Properties inherited from Loot.Api.Graphics.GraphicsEntity
Color DrawColor [get, set]
Entity Entity [get, protected set]
bool SkipDrawing [get, set]
bool SkipUpdatingDrawData [get, set]
Additional Inherited Members
Public Attributes inherited from Loot.Api.Graphics.GraphicsEntity
Rectangle DestinationRectangle => DrawData.destinationRectangle
DrawData DrawData
bool UseDestinationRectangle => DrawData.useDestinationRectangle
Detailed Description
Defines a Shader entity, part of GraphicsEntity The entity defines a particular 'shader' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Definition at line 18 of file ShaderEntity.cs.
Constructor & Destructor Documentation
Loot.Api.Graphics.ShaderEntity.ShaderEntity (object subjectIdentity, int shaderId, ShaderDrawLayer drawLayer = ShaderDrawLayer.Back, ShaderDrawStyle shaderDrawStyle = null, int numSegments = 8, int drawDistance = 4, Color? shaderDrawColor = null, short order = 0)
Definition at line 30 of file ShaderEntity.cs.
References Loot.Api.Graphics.Shaders.ShaderDrawStyle.Styles.Default.
             : base(subjectIdentity)
         {
             ShaderId = shaderId;
             DrawLayer = drawLayer;
             ShaderDrawStyle = shaderDrawStyle ?? ShaderDrawStyle.Styles.Default;
             NumSegments = numSegments;
             DrawDistance = drawDistance;
             DrawColor = shaderDrawColor ?? Color.White;
             NeedsUpdate = false;
             Order = 0;
         }
Member Function Documentation
void Loot.Api.Graphics.ShaderEntity.DoDrawLayeredEntity (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float scale, float rotation, GlowmaskEntity glowmaskEntity = null)
Will draw all the layers (subject, glowmask, shader) in the proper order
Definition at line 63 of file ShaderEntity.cs.
Referenced by Loot.Api.Graphics.GraphicsGlobalItem.PreDrawInWorld().
         {
             if (SkipDrawing) return;
             TryGettingDrawData(rotation, scale);
             LoadAssets((Item)Entity);
             // Assets present
             if (SubjectTexture != null && ShaderTexture != null)
             {
                 // Draw the subject based on the drawlayer
                 if (DrawLayer == ShaderDrawLayer.Back)
                 {
                     DoDrawShader(ShaderTexture, spriteBatch);
                     DoDrawSubject(SubjectTexture, spriteBatch, lightColor);
                     glowmaskEntity?.DoDrawGlowmask(spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI);
                 }
                 else if (DrawLayer == ShaderDrawLayer.Middle)
                 {
                     DoDrawSubject(SubjectTexture, spriteBatch, lightColor);
                     DoDrawShader(ShaderTexture, spriteBatch);
                     glowmaskEntity?.DoDrawGlowmask(spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI);
                 }
                 else if (DrawLayer == ShaderDrawLayer.Front)
                 {
                     DoDrawSubject(SubjectTexture, spriteBatch, lightColor);
                     glowmaskEntity?.DoDrawGlowmask(spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI);
                     DoDrawShader(ShaderTexture, spriteBatch);
                 }
             }
             SkipUpdatingDrawData = false;
         }
void Loot.Api.Graphics.ShaderEntity.DoDrawShader (Texture2D shaderTexture, SpriteBatch spriteBatch)
Will draw the shader effect
Definition at line 100 of file ShaderEntity.cs.
References Loot.Api.Graphics.Shaders.ShaderDrawStyle.GetDrawOffset().
         {
             TryUpdatingDrawData(shaderTexture);
             spriteBatch.BeginShaderBatch();
             GameShaders.Armor.Apply(ShaderId, Entity, DrawData);
             var centerPos = DrawData.position;
             for (int i = 0; i < NumSegments; i++)
             {
                 DrawData.position = centerPos + ShaderDrawStyle.GetDrawOffset(this, i);
                 DrawDrawData(spriteBatch, DrawData);
             }
             DrawData.position = centerPos;
             spriteBatch.ResetBatch();
         }
void Loot.Api.Graphics.ShaderEntity.DoDrawSubject (Texture2D subjectTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the entity's regular sprite
Definition at line 120 of file ShaderEntity.cs.
         {
             var drawDataColor = DrawData.color;
             var drawDataTexture = DrawData.texture;
             TryUpdatingDrawData(subjectTexture);
             DrawData.color = lightColor;
             DrawData.texture = subjectTexture;
             DrawDrawData(spriteBatch, DrawData);
             DrawData.color = drawDataColor;
             DrawData.texture = drawDataTexture;
         }
override void Loot.Api.Graphics.ShaderEntity.LoadAssets (Item item) protected virtual
Implements Loot.Api.Graphics.GraphicsEntity.
Definition at line 44 of file ShaderEntity.cs.
References Loot.Api.ModContent.GraphicsModContent.Prepare().
         {
             var graphicsContent = Loot.ModContentManager.GetContent<GraphicsModContent>();
             graphicsContent?.Prepare(item);
             if (SubjectTexture == null)
             {
                 SubjectTexture = Main.itemTexture[item.type];
             }
             if (ShaderTexture == null)
             {
                 ShaderTexture = graphicsContent?.GetPreparedShader(item.type.ToString()) ?? Main.itemTexture[item.type];
             }
         }
Property Documentation
int Loot.Api.Graphics.ShaderEntity.DrawDistance get set
Definition at line 24 of file ShaderEntity.cs.
Referenced by Loot.Api.Graphics.Shaders.AlternateShaderDrawStyle.GetDrawOffset(), and Loot.Api.Graphics.Shaders.DefaultShaderDrawStyle.GetDrawOffset().
ShaderDrawLayer Loot.Api.Graphics.ShaderEntity.DrawLayer get set
Definition at line 20 of file ShaderEntity.cs.
bool Loot.Api.Graphics.ShaderEntity.NeedsUpdate get set
Definition at line 27 of file ShaderEntity.cs.
int Loot.Api.Graphics.ShaderEntity.NumSegments get set
Definition at line 23 of file ShaderEntity.cs.
Referenced by Loot.Api.Graphics.Shaders.AlternateShaderDrawStyle.GetDrawOffset(), and Loot.Api.Graphics.Shaders.DefaultShaderDrawStyle.GetDrawOffset().
short Loot.Api.Graphics.ShaderEntity.Order get set
Definition at line 28 of file ShaderEntity.cs.
ShaderDrawStyle Loot.Api.Graphics.ShaderEntity.ShaderDrawStyle get set
Definition at line 21 of file ShaderEntity.cs.
int Loot.Api.Graphics.ShaderEntity.ShaderId get set
Definition at line 22 of file ShaderEntity.cs.
Texture2D Loot.Api.Graphics.ShaderEntity.ShaderTexture get protected set
Definition at line 26 of file ShaderEntity.cs.
Texture2D Loot.Api.Graphics.ShaderEntity.SubjectTexture get protected set
Definition at line 25 of file ShaderEntity.cs.