Even More Modifiers: Loot.Core.System.ModifierEffect Class Reference
Loot.Core.System.ModifierEffect Class Reference
A ModifierEffect signifies the effect of a modifier on a player It should house the implementation, and delegation of such an effect Methods on effects can be delegated from ModPlayer
Public Member Functions
ModifierEffect AsNewInstance ()
virtual void AttachDelegations (ModifierPlayer player)
Allows modders to perform various delegations when this modifier is detected to become active This method will be invoked one time when the modifier becomes 'active' Alternatively automatic delegation can be used, using the AutoDelegation attribute
virtual void Clone (ref ModifierEffect clone)
A modder can provide custom cloning of effects in this hook
object Clone ()
virtual void DetachDelegations (ModifierPlayer player)
Allows modders to undo their performed delegations in AttachDelegations
virtual void OnInitialize (ModifierPlayer player)
Called when the ModPlayer initializes the effect
virtual void ResetEffects (ModifierPlayer player)
Automatically called when the ModPlayer does its ResetEffects Also automatically called when the delegations of the effect detach
Static Public Member Functions
static ModifierEffect GetModifierEffect (ushort type)
Returns the ModifierEffect specified by type, null if not present
Public Attributes
virtual string Name => GetType().Name
Properties
bool IsBeingDelegated [get, set]
Keeps track of if this particular modifier is being delegated or not This is used to check if this effect's automatic delegation needs to be performed
Mod Mod [get, set]
uint Type [get, set]
Detailed Description
A ModifierEffect signifies the effect of a modifier on a player It should house the implementation, and delegation of such an effect Methods on effects can be delegated from ModPlayer
Definition at line 14 of file ModifierEffect.cs.
Member Function Documentation
ModifierEffect Loot.Core.System.ModifierEffect.AsNewInstance ()
virtual void Loot.Core.System.ModifierEffect.AttachDelegations (ModifierPlayer player) virtual
Allows modders to perform various delegations when this modifier is detected to become active This method will be invoked one time when the modifier becomes 'active' Alternatively automatic delegation can be used, using the AutoDelegation attribute
Definition at line 49 of file ModifierEffect.cs.
         {
         }
virtual void Loot.Core.System.ModifierEffect.Clone (ref ModifierEffect clone) virtual
A modder can provide custom cloning of effects in this hook
Reimplemented in Loot.Modifiers.EquipModifiers.Utility.LightEffect.
Definition at line 100 of file ModifierEffect.cs.
Referenced by Loot.Ext.ModUtils.GetModifierEffect().
         {
         }
object Loot.Core.System.ModifierEffect.Clone ()
Definition at line 104 of file ModifierEffect.cs.
References Loot.EMMLoader.GetModifierEffect(), Loot.Core.System.ModifierEffect.Mod, and Loot.Core.System.ModifierEffect.Type.
         {
             ModifierEffect clone = (ModifierEffect)MemberwiseClone();
             clone.Mod = Mod;
             clone.Type = Type;
             Clone(ref clone);
             return clone;
         }
virtual void Loot.Core.System.ModifierEffect.DetachDelegations (ModifierPlayer player) virtual
Allows modders to undo their performed delegations in AttachDelegations
Definition at line 93 of file ModifierEffect.cs.
         {
         }
static ModifierEffect Loot.Core.System.ModifierEffect.GetModifierEffect (ushort type) static
Returns the ModifierEffect specified by type, null if not present
virtual void Loot.Core.System.ModifierEffect.OnInitialize (ModifierPlayer player) virtual
Called when the ModPlayer initializes the effect
Reimplemented in Loot.Modifiers.WeaponDebuffEffect, Loot.Modifiers.EquipModifiers.Utility.LightEffect, Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlusEffect, and Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesEffect.
Definition at line 32 of file ModifierEffect.cs.
         {
         }
virtual void Loot.Core.System.ModifierEffect.ResetEffects (ModifierPlayer player) virtual
Automatically called when the ModPlayer does its ResetEffects Also automatically called when the delegations of the effect detach
Reimplemented in Loot.Modifiers.WeaponDebuffEffect, Loot.Modifiers.EquipModifiers.Utility.LightEffect, Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlusEffect, Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesEffect, Loot.Modifiers.WeaponModifiers.CursedEffect, Loot.Modifiers.EquipModifiers.Defensive.SurvivalEffect, Loot.Modifiers.EquipModifiers.Defensive.ManaShieldEffect, Loot.Modifiers.EquipModifiers.Utility.LuckEffect, Loot.Modifiers.EquipModifiers.Defensive.DodgeEffect, Loot.Modifiers.EquipModifiers.Defensive.PercentDefBoostEffect, Loot.Modifiers.EquipModifiers.Defensive.ImmunityEffect, and Loot.Modifiers.EquipModifiers.Defensive.LifeRegenEffect.
Definition at line 40 of file ModifierEffect.cs.
         {
         }
Member Data Documentation
virtual string Loot.Core.System.ModifierEffect.Name => GetType().Name
Definition at line 18 of file ModifierEffect.cs.
Referenced by Loot.EMMLoader.AddModifierEffect().
Property Documentation
bool Loot.Core.System.ModifierEffect.IsBeingDelegated get set
Keeps track of if this particular modifier is being delegated or not This is used to check if this effect's automatic delegation needs to be performed
Definition at line 24 of file ModifierEffect.cs.
Mod Loot.Core.System.ModifierEffect.Mod get set
Definition at line 16 of file ModifierEffect.cs.
Referenced by Loot.EMMLoader.AddModifierEffect(), Loot.Core.System.ModifierEffect.Clone(), and Loot.EMMLoader.GetNewEffectInstance().
uint Loot.Core.System.ModifierEffect.Type get set
Definition at line 17 of file ModifierEffect.cs.
Referenced by Loot.Core.System.ModifierEffect.Clone(), Loot.Ext.ModUtils.GetModifierEffect(), and Loot.EMMLoader.GetNewEffectInstance().