Even More Modifiers: Loot.Api.Modifier.ModifierPool Class Reference
Loot.Api.Modifier.ModifierPool Class Reference
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Public Member Functions
virtual bool CanRoll (ModifierContext ctx)
Returns if this pool can roll in the given context Returns true by default
virtual void Clone (ref ModifierPool clone)
Allows modders to do custom cloning Happens after default cloning
object Clone ()
virtual IEnumerable< Modifier > GetModifiers ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Public Attributes
IEnumerable< ModifierTooltipLine[]> Description => ActiveModifiers.Select(m => m.GetTooltip().Build().ToArray())
Returns an enumerable of the tooltiplines of the active modifiers
string Name => GetType().Name
virtual float RollChance => 1f
float TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
IEnumerable< string > UniqueNames
Properties
Modifier[] ActiveModifiers [get, set]
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Api.Content.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Private Member Functions
IEnumerable< Modifier > _GetModifiers ()
Private Attributes
Modifier[] _activeModifiers = new Modifier[0]
PopulatePoolFromAttribute _populatePoolFrom
const int SAVE_VERSION = 3
Detailed Description
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Definition at line 23 of file ModifierPool.cs.
Member Function Documentation
IEnumerable<Modifier> Loot.Api.Modifier.ModifierPool._GetModifiers () private
Definition at line 62 of file ModifierPool.cs.
References Loot.Api.Attributes.PopulatePoolFromAttribute.GetClasses(), and Loot.Api.Loaders.ContentLoader.Modifier.
         {
             if (_populatePoolFrom != null)
             {
                 var classes = _populatePoolFrom.GetClasses().SelectMany(x => x.Value);
                 foreach (var @class in classes)
                 {
                     var m = ContentLoader.Modifier.GetContent(@class);
                     if (m != null)
                     {
                         yield return m;
                     }
                 }
             }
             foreach (Modifier m in GetModifiers())
             {
                 if (m != null)
                 {
                     yield return m;
                 }
             }
         }
virtual bool Loot.Api.Modifier.ModifierPool.CanRoll (ModifierContext ctx) virtual
Returns if this pool can roll in the given context Returns true by default
Reimplemented in Loot.Pools.NullModifierPool.
virtual void Loot.Api.Modifier.ModifierPool.Clone (ref ModifierPool clone) virtual
Allows modders to do custom cloning Happens after default cloning
Definition at line 144 of file ModifierPool.cs.
Referenced by Loot.Api.Ext.ModUtils.GetModifierPool(), and Loot.Content.ModifierPoolContent.GetWeightedPool().
         {
         }
object Loot.Api.Modifier.ModifierPool.Clone ()
Definition at line 148 of file ModifierPool.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.Api.Modifier.ModifierPool.Mod, and Loot.Api.Modifier.ModifierPool.Type.
         {
             ModifierPool clone = (ModifierPool)MemberwiseClone();
             clone.Type = Type;
             clone.Mod = Mod;
             clone.ActiveModifiers =
                 ActiveModifiers?
                     .Select(x => (Modifier)x?.Clone() ?? Loot.Instance.GetNullModifier())
                     .ToArray();
             Clone(ref clone);
             return clone;
         }
virtual IEnumerable<Modifier> Loot.Api.Modifier.ModifierPool.GetModifiers () virtual
Reimplemented in Loot.Pools.AllModifiersPool.
virtual void Loot.Api.Modifier.ModifierPool.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 216 of file ModifierPool.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.LootModItem.GetInfo(), Loot.Api.Modifier.ModifierPool.Load(), Loot.Api.Loaders.ContentLoader.ModifierPool, Loot.Api.Loaders.ContentLoader.ModifierRarity, and Loot.LootModItem.ModifierRarity.
Referenced by Loot.Api.Modifier.ModifierPool.Load().
         {
         }
virtual void Loot.Api.Modifier.ModifierPool.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Definition at line 164 of file ModifierPool.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.Api.Loaders.ContentLoader.ModifierPool, and Loot.Api.Modifier.ModifierPool.NetReceive().
Referenced by Loot.Api.Modifier.ModifierPool.NetReceive().
         {
         }
virtual void Loot.Api.Modifier.ModifierPool.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Definition at line 194 of file ModifierPool.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.Api.Modifier.ModifierPool.Mod, Loot.Api.Modifier.ModifierPool.Name, and Loot.Api.Modifier.ModifierPool.NetSend().
Referenced by Loot.Api.Modifier.ModifierPool.NetSend().
         {
         }
virtual void Loot.Api.Modifier.ModifierPool.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Parameters
tag
Definition at line 301 of file ModifierPool.cs.
References Loot.Api.Modifier.ModifierPool.ActiveModifiers, Loot.Api.Modifier.ModifierPool.Mod, Loot.Api.Modifier.ModifierPool.Name, Loot.Api.Modifier.Modifier.Save(), and Loot.Api.Modifier.ModifierPool.Save().
Referenced by Loot.LootModItem.Save(), and Loot.Api.Modifier.ModifierPool.Save().
         {
         }
Member Data Documentation
Modifier [] Loot.Api.Modifier.ModifierPool._activeModifiers = new Modifier[0] private
Definition at line 48 of file ModifierPool.cs.
PopulatePoolFromAttribute Loot.Api.Modifier.ModifierPool._populatePoolFrom private
Definition at line 55 of file ModifierPool.cs.
IEnumerable<ModifierTooltipLine[]> Loot.Api.Modifier.ModifierPool.Description => ActiveModifiers.Select(m => m.GetTooltip().Build().ToArray())
Returns an enumerable of the tooltiplines of the active modifiers
Definition at line 108 of file ModifierPool.cs.
string Loot.Api.Modifier.ModifierPool.Name => GetType().Name
Definition at line 41 of file ModifierPool.cs.
Referenced by Loot.Api.Modifier.ModifierPool.NetSend(), and Loot.Api.Modifier.ModifierPool.Save().
virtual float Loot.Api.Modifier.ModifierPool.RollChance => 1f
Definition at line 110 of file ModifierPool.cs.
const int Loot.Api.Modifier.ModifierPool.SAVE_VERSION = 3 private
Definition at line 25 of file ModifierPool.cs.
float Loot.Api.Modifier.ModifierPool.TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
Definition at line 102 of file ModifierPool.cs.
IEnumerable<string> Loot.Api.Modifier.ModifierPool.UniqueNames
Initial value:
=>
            ActiveModifiers
                .Where(x => x.UniqueName != string.Empty)
                .Select(x => x.UniqueName)
Definition at line 43 of file ModifierPool.cs.
Property Documentation
Modifier [] Loot.Api.Modifier.ModifierPool.ActiveModifiers get set
Definition at line 50 of file ModifierPool.cs.
Referenced by Loot.Api.Modifier.ModifierPool.Clone(), Loot.LootModItem.Load(), Loot.Api.Modifier.ModifierPool.Load(), Loot.Api.Modifier.ModifierPool.NetReceive(), Loot.Api.Modifier.ModifierPool.NetSend(), Loot.RollingStrategies.NormalRollingStrategy.Roll(), and Loot.Api.Modifier.ModifierPool.Save().
Mod Loot.Api.Modifier.ModifierPool.Mod get set
Definition at line 27 of file ModifierPool.cs.
Referenced by Loot.Api.Modifier.ModifierPool.Clone(), Loot.Api.Modifier.ModifierPool.NetSend(), and Loot.Api.Modifier.ModifierPool.Save().
Mod ILoadableContentSetter. Loot.Api.Modifier.ModifierPool.Mod set private
Definition at line 30 of file ModifierPool.cs.
uint Loot.Api.Modifier.ModifierPool.Type get set
Definition at line 34 of file ModifierPool.cs.
Referenced by Loot.Api.Modifier.ModifierPool.Clone().
uint ILoadableContentSetter. Loot.Api.Modifier.ModifierPool.Type set private
Definition at line 37 of file ModifierPool.cs.