Even More Modifiers: Loot.Core.ModContent.ContentManager Class Reference
Loot.Core.ModContent.ContentManager Class Reference
Public Member Functions
void AddContent (string key, ModContent modContent)
ModContent GetContent (Type type)
ModContent GetContent (string key)
T GetContent< T > ()
Private Attributes
IDictionary< string, ModContent > _contents
IEnumerable< ModContent > _modContents => _contents.Select(x => x.Value)
Detailed Description
Definition at line 8 of file ContentManager.cs.
Member Function Documentation
void Loot.Core.ModContent.ContentManager.AddContent (string key, ModContent modContent)
Definition at line 31 of file ContentManager.cs.
References Loot.Core.ModContent.ModContent._Initialize(), Loot.Core.ModContent.ModContent._Load(), and Loot.Core.ModContent.ModContent.GetRegistryKey().
         {
             if (_contents.ContainsKey(key))
             {
                 throw new Exception($"Key '{key}' already present in ContentManager");
             }
             if (_contents.Values.Contains(modContent))
             {
                 // TODO warn
             }
             modContent._Initialize();
             _contents.Add(key, modContent);
         }
ModContent Loot.Core.ModContent.ContentManager.GetContent (Type type)
Definition at line 19 of file ContentManager.cs.
         {
             ModContent content = (ModContent)_modContents.FirstOrDefault(x => x.GetType() == type);
             return content;
         }
ModContent Loot.Core.ModContent.ContentManager.GetContent (string key)
Definition at line 25 of file ContentManager.cs.
         {
             ModContent content;
             return _contents.TryGetValue(key, out content) ? content : null;
         }
T Loot.Core.ModContent.ContentManager.GetContent< T > ()
Type Constraints
T : ModContent
Definition at line 13 of file ContentManager.cs.
                                          : ModContent
         {
             T content = (T)_modContents.FirstOrDefault(x => x.GetType() == typeof(T));
             return content;
         }
Member Data Documentation
IDictionary<string, ModContent> Loot.Core.ModContent.ContentManager._contents private
Definition at line 10 of file ContentManager.cs.
IEnumerable<ModContent> Loot.Core.ModContent.ContentManager._modContents => _contents.Select(x => x.Value) private
Definition at line 11 of file ContentManager.cs.