Even More Modifiers: Loot.Core.ModContent.TextureContent Class Reference
Loot.Core.ModContent.TextureContent Class Reference abstract
Public Member Functions
void _Initialize ()
void _Load ()
void _Unload ()
void AddTexture (string key, Texture2D texture)
abstract string GetRegistryKey ()
Texture2D GetTexture (string key)
Protected Member Functions
void AddTo (IDictionary< string, Texture2D > dictionary, string key, Texture2D texture)
Texture2D GetFrom (IDictionary< string, Texture2D > dictionary, string key)
virtual void Initialize ()
virtual void Load ()
virtual void ProcessTexture2D (ref Texture2D texture)
virtual void Unload ()
Protected Attributes
IDictionary< string, Texture2D > _textures
Detailed Description
Definition at line 7 of file TextureContent.cs.
Member Function Documentation
void Loot.Core.ModContent.TextureContent._Initialize ()
Definition at line 37 of file TextureContent.cs.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
         {
             _textures = new Dictionary<string, Texture2D>();
             Initialize();
         }
void Loot.Core.ModContent.TextureContent._Load ()
Definition at line 43 of file TextureContent.cs.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
         {
             Load();
         }
void Loot.Core.ModContent.TextureContent._Unload ()
Definition at line 48 of file TextureContent.cs.
         {
             _textures = null;
             Unload();
         }
void Loot.Core.ModContent.TextureContent.AddTexture (string key, Texture2D texture)
Definition at line 32 of file TextureContent.cs.
         {
             AddTo(_textures, key, texture);
         }
void Loot.Core.ModContent.TextureContent.AddTo (IDictionary< string, Texture2D > dictionary, string key, Texture2D texture) protected
Definition at line 22 of file TextureContent.cs.
         {
             if (dictionary.ContainsKey(key))
             {
                 throw new Exception($"Key '{key}' already present in ModContent");
             }
             ProcessTexture2D(ref texture);
             dictionary.Add(key, texture);
         }
Texture2D Loot.Core.ModContent.TextureContent.GetFrom (IDictionary< string, Texture2D > dictionary, string key) protected
Definition at line 11 of file TextureContent.cs.
         {
             Texture2D texture;
             return dictionary.TryGetValue(key, out texture) ? texture : null;
         }
abstract string Loot.Core.ModContent.TextureContent.GetRegistryKey () pure virtual
Implemented in Loot.Core.ModContent.GraphicsContent.
Referenced by Loot.Core.ModContent.ContentManager.AddContent().
Texture2D Loot.Core.ModContent.TextureContent.GetTexture (string key)
Definition at line 17 of file TextureContent.cs.
         {
             return GetFrom(_textures, key);
         }
virtual void Loot.Core.ModContent.TextureContent.Initialize () protected virtual
Reimplemented in Loot.Core.ModContent.GraphicsContent.
Definition at line 54 of file TextureContent.cs.
 { }
virtual void Loot.Core.ModContent.TextureContent.Load () protected virtual
Reimplemented in Loot.Core.ModContent.GraphicsContent.
Definition at line 55 of file TextureContent.cs.
 { }
virtual void Loot.Core.ModContent.TextureContent.ProcessTexture2D (ref Texture2D texture) protected virtual
Reimplemented in Loot.Core.ModContent.GraphicsContent.
Definition at line 53 of file TextureContent.cs.
 { }
virtual void Loot.Core.ModContent.TextureContent.Unload () protected virtual
Reimplemented in Loot.Core.ModContent.GraphicsContent.
Definition at line 56 of file TextureContent.cs.
 { }
Member Data Documentation
IDictionary<string, Texture2D> Loot.Core.ModContent.TextureContent._textures protected
Definition at line 9 of file TextureContent.cs.