Even More Modifiers: Loot.Core.Cubes.CubeUIExtensions Class Reference
Loot.Core.Cubes.CubeUIExtensions Class Reference
Public Member Functions
override bool CanRightClick (Item item)
override void ModifyTooltips (Item item, List< TooltipLine > tooltips)
override void RightClick (Item item, Player player)
Private Member Functions
void RerollUITakeItem (CubeRerollUI ui, Item item)
bool RightClickFunctionalityRequirements (Item item)
void SealUITakeItem (CubeSealUI ui, Item item)
void SwapItemSlot (Item item, VisibilityUI ui, UIInteractableItemPanel itemPanel, Action extraAction=null)
Detailed Description
Definition at line 15 of file CubeUIExtensions.cs.
Member Function Documentation
override bool Loot.Core.Cubes.CubeUIExtensions.CanRightClick (Item item)
Definition at line 18 of file CubeUIExtensions.cs.
References Loot.UI.Core.VisibilityUI.Visible.
         {
             if (!RightClickFunctionalityRequirements(item))
             {
                 return false;
             }
             var ui = Loot.Instance.CubeInterface.CurrentState as CubeUI;
             if (ui == null)
             {
                 return false;
             }
             return ui.Visible && ui.IsItemValidForUISlot(item);
         }
override void Loot.Core.Cubes.CubeUIExtensions.ModifyTooltips (Item item, List< TooltipLine > tooltips)
Definition at line 109 of file CubeUIExtensions.cs.
         {
             var ui = Loot.Instance.CubeInterface;
             var cubeUI = ui?.CurrentState as CubeUI;
             if (cubeUI != null)
             {
                 //todo replace with Loot.WingSlotVersionInvalid when it works
                 if ((ModSupport.GetSupport<WingSlotSupporter>().IsInvalid && item.wingSlot > 0) // block wings if low version if wingslot
                     || !cubeUI.IsItemValidForUISlot(item)
                     || cubeUI.IsSlottedItemInCubeUI())
                 {
                     return;
                 }
                 var i = tooltips.FindIndex(x => x.mod.Equals("Terraria") && x.Name.Equals("ItemName"));
                 if (i != -1)
                 {
                     tooltips[i].text += " (control right click to slot into UI)";
                 }
             }
         }
void Loot.Core.Cubes.CubeUIExtensions.RerollUITakeItem (CubeRerollUI ui, Item item) private
Definition at line 75 of file CubeUIExtensions.cs.
References Loot.UI.Rerolling.CubeRerollUI.UpdateModifierLines().
         {
             SwapItemSlot(item, ui, ui._rerollItemPanel, ui.UpdateModifierLines);
         }
override void Loot.Core.Cubes.CubeUIExtensions.RightClick (Item item, Player player)
Definition at line 48 of file CubeUIExtensions.cs.
         {
             // We need to rerun checks here because our forced right click above
             // becomes meaningless to items that can already be right clicked
             // meaning that items such as goodie bags will end up in this hook
             // regardless of our forced right click functionality in CanRightClick
             // by which we need to assume any possible item can be passed into this hook
             var ui = Loot.Instance.CubeInterface.CurrentState as CubeUI;
             if (ui == null)
             {
                 return;
             }
             if (RightClickFunctionalityRequirements(item) && !(item.modItem is MagicalCube) && ui.Visible && ui.IsItemValidForUISlot(item))
             {
                 if (ui is CubeRerollUI)
                 {
                     RerollUITakeItem(ui as CubeRerollUI, item);
                 }
                 else if (ui is CubeSealUI)
                 {
                     SealUITakeItem(ui as CubeSealUI, item);
                 }
                 // else // item has innate right click or mod allows it, do nothing
             }
         }
bool Loot.Core.Cubes.CubeUIExtensions.RightClickFunctionalityRequirements (Item item) private
Definition at line 34 of file CubeUIExtensions.cs.
         {
             if (ModSupport.GetSupport<WingSlotSupporter>().IsInvalid && item.wingSlot > 0)
             {
                 return false;
             }
             return !PlayerInput.WritingText
                    && Main.hasFocus
                    && Main.keyState.IsKeyDown(Keys.LeftControl)
                    && Loot.Instance.CubeInterface.CurrentState != null;
         }
void Loot.Core.Cubes.CubeUIExtensions.SealUITakeItem (CubeSealUI ui, Item item) private
Definition at line 80 of file CubeUIExtensions.cs.
         {
             SwapItemSlot(item, ui, ui._itemPanel);
         }
void Loot.Core.Cubes.CubeUIExtensions.SwapItemSlot (Item item, VisibilityUI ui, UIInteractableItemPanel itemPanel, Action extraAction = null) private
Definition at line 86 of file CubeUIExtensions.cs.
References Loot.UI.Core.UIInteractableItemPanel.CanTakeItem(), Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UIItemPanel.item, and Loot.EMMItem.SlottedInCubeUI.
         {
             if (itemPanel != null && itemPanel.CanTakeItem(item))
             {
                 if (!itemPanel.item.IsAir)
                 {
                     EMMItem.GetItemInfo(itemPanel.item).SlottedInCubeUI = false;
                     Main.LocalPlayer.QuickSpawnClonedItem(itemPanel.item, itemPanel.item.stack);
                 }
                 Main.PlaySound(SoundID.Grab);
                 itemPanel.item = item.Clone();
                 EMMItem.GetItemInfo(itemPanel.item).SlottedInCubeUI = true;
                 extraAction?.Invoke();
             }
             else
             {
                 item.stack++;
             }
         }