Even More Modifiers: Loot.Api.Graphics.Shader.ShaderEntity Class Reference
Loot.Api.Graphics.Shader.ShaderEntity Class Reference
Defines a Shader entity, part of GraphicsEntity<T> The entity defines a particular 'shader' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Public Member Functions
ShaderEntity (object subjectIdentity, int shaderId, Color?shaderDrawColor=null, short order=0, ShaderGraphicsProperties props=null)
void DoDrawGlowmask (GlowmaskEntity glowmaskEntity, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask=null)
Will draw the glowmask
void DoDrawLayeredEntity (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float scale, float rotation, GlowmaskEntity glowmaskEntity=null, Texture2D suppliedShaderTexture=null, Texture2D suppliedSubjectTexture=null, Texture2D suppliedGlowmaskTexture=null)
Will draw all the layers (subject, glowmask, shader) in the proper order
void DoDrawShader (Texture2D shaderTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the shader effect
void DoDrawSubject (Texture2D subjectTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the entity's regular sprite
Public Member Functions inherited from Loot.Api.Graphics.GraphicsEntity< ShaderGraphicsProperties >
void DrawEntity (SpriteBatch spriteBatch)
void TryGettingDrawData (float rotation, float scale)
Sets up drawing data initially
void TryUpdatingDrawData (Texture2D texture)
Protected Member Functions
override void LoadAssets (Item item)
Protected Member Functions inherited from Loot.Api.Graphics.GraphicsEntity< ShaderGraphicsProperties >
GraphicsEntity (object subjectIdentity)
Properties
int ShaderId [get, set]
Texture2D ShaderTexture [get, protected set]
Texture2D SubjectTexture [get, protected set]
Properties inherited from Loot.Api.Graphics.GraphicsEntity< ShaderGraphicsProperties >
Color DrawColor [get, set]
Entity Entity [get, protected set]
bool NeedsUpdate [get, set]
short Order [get, protected set]
T Properties [get, protected set]
Additional Inherited Members
Public Attributes inherited from Loot.Api.Graphics.GraphicsEntity< ShaderGraphicsProperties >
Rectangle DestinationRectangle
DrawData DrawData
bool UseDestinationRectangle
Detailed Description
Defines a Shader entity, part of GraphicsEntity<T> The entity defines a particular 'shader' "of" the entity and can be drawn appropriately The entity makes use of GraphicsModContent to get art assets
Definition at line 16 of file ShaderEntity.cs.
Constructor & Destructor Documentation
Loot.Api.Graphics.Shader.ShaderEntity.ShaderEntity (object subjectIdentity, int shaderId, Color? shaderDrawColor = null, short order = 0, ShaderGraphicsProperties props = null)
Definition at line 23 of file ShaderEntity.cs.
References Loot.Api.Builder.PropertyBuilder< T >.Build(), and Loot.Api.Graphics.Shader.ShaderGraphicsProperties.Builder.
             : base(subjectIdentity)
         {
             ShaderId = shaderId;
             DrawColor = shaderDrawColor ?? Color.White;
             NeedsUpdate = false;
             Order = order;
             Properties = props ?? ShaderGraphicsProperties.Builder.Build();
         }
Member Function Documentation
void Loot.Api.Graphics.Shader.ShaderEntity.DoDrawGlowmask (GlowmaskEntity glowmaskEntity, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI, Texture2D suppliedGlowmask = null)
Will draw the glowmask
Definition at line 95 of file ShaderEntity.cs.
References Loot.Api.Graphics.Glowmask.GlowmaskEntity.DoDrawGlowmask(), and Loot.Api.Graphics.GraphicsEntity< T >.Properties.
         {
             if (glowmaskEntity == null) return;
             glowmaskEntity.Properties.SkipDrawingGlowmask = Properties.SkipDrawingGlowmask;
             glowmaskEntity.DoDrawGlowmask(spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI, suppliedGlowmask);
         }
void Loot.Api.Graphics.Shader.ShaderEntity.DoDrawLayeredEntity (SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float scale, float rotation, GlowmaskEntity glowmaskEntity = null, Texture2D suppliedShaderTexture = null, Texture2D suppliedSubjectTexture = null, Texture2D suppliedGlowmaskTexture = null)
Will draw all the layers (subject, glowmask, shader) in the proper order
Definition at line 53 of file ShaderEntity.cs.
Referenced by Loot.Api.Graphics.GraphicsGlobalItem.PreDrawInWorld().
         {
             if (Properties.SkipDrawing) return;
             TryGettingDrawData(rotation, scale);
             if (Entity is Item item) LoadAssets(item);
             else Loot.Logger.Warn("Could not identify shader entity identity as item");
             var useSubjectTexture = suppliedSubjectTexture ?? SubjectTexture;
             var useShaderTexture = suppliedShaderTexture ?? ShaderTexture;
             var useGlowmaskTexture = suppliedGlowmaskTexture;
             // Assets present
             if (useSubjectTexture != null && useShaderTexture != null)
             {
                 // Draw the subject based on the drawlayer
                 if (Properties.DrawLayer == ShaderDrawLayer.Back)
                 {
                     DoDrawShader(useShaderTexture, spriteBatch, lightColor);
                     DoDrawSubject(useSubjectTexture, spriteBatch, lightColor);
                     DoDrawGlowmask(glowmaskEntity, spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI, useGlowmaskTexture);
                 }
                 else if (Properties.DrawLayer == ShaderDrawLayer.Middle)
                 {
                     DoDrawSubject(useSubjectTexture, spriteBatch, lightColor);
                     DoDrawShader(useShaderTexture, spriteBatch, lightColor);
                     DoDrawGlowmask(glowmaskEntity, spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI, useGlowmaskTexture);
                 }
                 else if (Properties.DrawLayer == ShaderDrawLayer.Front)
                 {
                     DoDrawSubject(useSubjectTexture, spriteBatch, lightColor);
                     DoDrawGlowmask(glowmaskEntity, spriteBatch, lightColor, alphaColor, rotation, scale, Entity.whoAmI, useGlowmaskTexture);
                     DoDrawShader(useShaderTexture, spriteBatch, lightColor);
                 }
             }
             Properties.SkipUpdatingDrawData = false;
         }
void Loot.Api.Graphics.Shader.ShaderEntity.DoDrawShader (Texture2D shaderTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the shader effect
Definition at line 105 of file ShaderEntity.cs.
         {
             if (Properties.SkipDrawingShader) return;
             var drawDataTexture = DrawData.texture;
             var drawDataColor = DrawData.color;
             DrawData.texture = shaderTexture;
             DrawData.color = lightColor;
             TryUpdatingDrawData(shaderTexture);
             spriteBatch.BeginShaderBatch();
             GameShaders.Armor.Apply(ShaderId, Entity, DrawData);
             var centerPos = DrawData.position;
             Properties.ShaderDrawStyle.DrawShader(spriteBatch, this);
             DrawData.position = centerPos;
             DrawData.texture = drawDataTexture;
             DrawData.color = drawDataColor;
             spriteBatch.ResetBatch();
         }
void Loot.Api.Graphics.Shader.ShaderEntity.DoDrawSubject (Texture2D subjectTexture, SpriteBatch spriteBatch, Color lightColor)
Will draw the entity's regular sprite
Definition at line 131 of file ShaderEntity.cs.
         {
             if (Properties.SkipDrawingSubject) return;
             var drawDataColor = DrawData.color;
             var drawDataTexture = DrawData.texture;
             DrawData.color = lightColor;
             DrawData.texture = subjectTexture;
             TryUpdatingDrawData(subjectTexture);
             DrawEntity(spriteBatch);
             DrawData.color = drawDataColor;
             DrawData.texture = drawDataTexture;
         }
override void Loot.Api.Graphics.Shader.ShaderEntity.LoadAssets (Item item) protected virtual
Implements Loot.Api.Graphics.GraphicsEntity< ShaderGraphicsProperties >.
Definition at line 34 of file ShaderEntity.cs.
References Loot.Api.ModContent.GraphicsModContent.Prepare().
         {
             var graphicsContent = Loot.ModContentManager.GetContent<GraphicsModContent>();
             graphicsContent?.Prepare(item);
             if (SubjectTexture == null)
             {
                 SubjectTexture = Main.itemTexture[item.type];
             }
             if (ShaderTexture == null)
             {
                 ShaderTexture = graphicsContent?.GetPreparedShader(item.type.ToString()) ?? SubjectTexture;
             }
         }
Property Documentation
int Loot.Api.Graphics.Shader.ShaderEntity.ShaderId get set
Definition at line 18 of file ShaderEntity.cs.
Texture2D Loot.Api.Graphics.Shader.ShaderEntity.ShaderTexture get protected set
Definition at line 21 of file ShaderEntity.cs.
Texture2D Loot.Api.Graphics.Shader.ShaderEntity.SubjectTexture get protected set
Definition at line 20 of file ShaderEntity.cs.