Even More Modifiers: Loot.UI.Sealing.UISealItemPanel Class Reference
Loot.UI.Sealing.UISealItemPanel Class Reference
Public Member Functions
UISealItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
override bool CanTakeItem (Item item)
override void PostOnClick (UIMouseEvent evt, UIElement e)
override void PreOnClick (UIMouseEvent evt, UIElement e)
Public Member Functions inherited from Loot.UI.Core.UIInteractableItemPanel
UIInteractableItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null)
virtual void PostOnRightClick ()
override void Update (GameTime gameTime)
Public Member Functions inherited from Loot.UI.Core.UIItemPanel
UIItemPanel (int netID=0, int stack=0, Texture2D hintTexture=null, string hintText=null, string hintOnHover=null)
Additional Inherited Members
Public Attributes inherited from Loot.UI.Core.UIItemPanel
Item item = null
Protected Member Functions inherited from Loot.UI.Core.UIItemPanel
override void DrawSelf (SpriteBatch spriteBatch)
Protected Attributes inherited from Loot.UI.Core.UIInteractableItemPanel
bool RightClickFunctionalityEnabled = true
bool TakeUserItemOnClick = true
Properties inherited from Loot.UI.Core.UIInteractableItemPanel
bool PerformRegularClickInteraction [get, set]
Properties inherited from Loot.UI.Core.UIItemPanel
bool DrawBackgroundPanel [get, set]
Color DrawColor = 1f [get, set]
float DrawScale = false [get, set]
bool DrawStack = true [get, set]
string HintOnHover [get, set]
string HintText [get, set]
Texture2D HintTexture [get, set]
bool ShowOnlyHintOnHover = true [get, set]
Detailed Description
Definition at line 9 of file UISealItemPanel.cs.
Constructor & Destructor Documentation
Loot.UI.Sealing.UISealItemPanel.UISealItemPanel (int netID = 0, int stack = 0, Texture2D hintTexture = null, string hintText = null)
Definition at line 11 of file UISealItemPanel.cs.
                                                                                                                    :
             base(netID, stack, hintTexture, hintText)
         {
             this.RightClickFunctionalityEnabled = false;
             this.HintOnHover = " (click to take item)";
         }
Member Function Documentation
override bool Loot.UI.Sealing.UISealItemPanel.CanTakeItem (Item item) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Referenced by Loot.UI.Sealing.CubeSealUI.IsItemValidForUISlot().
override void Loot.UI.Sealing.UISealItemPanel.PostOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Definition at line 28 of file UISealItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = true;
             }
         }
override void Loot.UI.Sealing.UISealItemPanel.PreOnClick (UIMouseEvent evt, UIElement e) virtual
Reimplemented from Loot.UI.Core.UIInteractableItemPanel.
Definition at line 20 of file UISealItemPanel.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.EMMItem.SlottedInCubeUI.
         {
             if (!item.IsAir)
             {
                 EMMItem.GetItemInfo(item).SlottedInCubeUI = false;
             }
         }