Even More Modifiers: Loot.Api.Core.ModifierPool Class Reference
Loot.Api.Core.ModifierPool Class Reference
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Public Member Functions
virtual bool CanRoll (ModifierContext ctx)
Returns if this pool can roll in the given context Returns true by default
virtual void Clone (ref ModifierPool clone)
Allows modders to do custom cloning Happens after default cloning
object Clone ()
virtual IEnumerable< Modifier > GetModifiers ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Public Attributes
string Name => GetType().Name
virtual float RollChance => 1f
Properties
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Api.Content.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Private Member Functions
IEnumerable< Modifier > _GetModifiers ()
Private Attributes
PopulatePoolFromAttribute _populatePoolFrom
Detailed Description
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Definition at line 37 of file ModifierPool.cs.
Member Function Documentation
IEnumerable<Modifier> Loot.Api.Core.ModifierPool._GetModifiers () private
Definition at line 62 of file ModifierPool.cs.
References Loot.Api.Attributes.PopulatePoolFromAttribute.GetClasses(), and Loot.Api.Loaders.ContentLoader.Modifier.
         {
             if (_populatePoolFrom != null)
             {
                 var classes = _populatePoolFrom.GetClasses().SelectMany(x => x.Value);
                 foreach (var @class in classes)
                 {
                     var m = ContentLoader.Modifier.GetContent(@class);
                     if (m != null)
                     {
                         yield return m;
                     }
                 }
             }
             foreach (Modifier m in GetModifiers())
             {
                 if (m != null)
                 {
                     yield return m;
                 }
             }
         }
virtual bool Loot.Api.Core.ModifierPool.CanRoll (ModifierContext ctx) virtual
Returns if this pool can roll in the given context Returns true by default
Reimplemented in Loot.Api.Core.NullModifierPool.
virtual void Loot.Api.Core.ModifierPool.Clone (ref ModifierPool clone) virtual
Allows modders to do custom cloning Happens after default cloning
Definition at line 144 of file ModifierPool.cs.
Referenced by Loot.Api.Ext.ModUtils.GetModifierPool(), and Loot.Api.Mechanism.ModifierPoolMechanism.GetWeightedPool().
         {
         }
object Loot.Api.Core.ModifierPool.Clone ()
Definition at line 148 of file ModifierPool.cs.
References Loot.Api.Core.ModifierPool.Mod, and Loot.Api.Core.ModifierPool.Type.
         {
             ModifierPool clone = (ModifierPool)MemberwiseClone();
             clone.Type = Type;
             clone.Mod = Mod;
             //clone.ActiveModifiers =
             //  ActiveModifiers?
             //      .Select(x => (Modifier)x?.Clone() ?? Loot.Instance.GetNullModifier())
             //      .ToArray();
             Clone(ref clone);
             return clone;
         }
virtual IEnumerable<Modifier> Loot.Api.Core.ModifierPool.GetModifiers () virtual
Reimplemented in Loot.Pools.AllModifiersPool.
virtual void Loot.Api.Core.ModifierPool.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 179 of file ModifierPool.cs.
Referenced by Loot.LootModItem.Load().
         {
         }
virtual void Loot.Api.Core.ModifierPool.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Definition at line 164 of file ModifierPool.cs.
Referenced by Loot.LootModItem.NetReceive().
         {
         }
virtual void Loot.Api.Core.ModifierPool.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Definition at line 171 of file ModifierPool.cs.
Referenced by Loot.LootModItem.NetSend().
         {
         }
virtual void Loot.Api.Core.ModifierPool.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Parameters
tag
Definition at line 188 of file ModifierPool.cs.
         {
         }
Member Data Documentation
PopulatePoolFromAttribute Loot.Api.Core.ModifierPool._populatePoolFrom private
Definition at line 55 of file ModifierPool.cs.
string Loot.Api.Core.ModifierPool.Name => GetType().Name
Definition at line 53 of file ModifierPool.cs.
virtual float Loot.Api.Core.ModifierPool.RollChance => 1f
Definition at line 110 of file ModifierPool.cs.
Property Documentation
Mod Loot.Api.Core.ModifierPool.Mod get set
Definition at line 39 of file ModifierPool.cs.
Referenced by Loot.Api.Core.ModifierPool.Clone().
Mod ILoadableContentSetter. Loot.Api.Core.ModifierPool.Mod set private
Definition at line 42 of file ModifierPool.cs.
uint Loot.Api.Core.ModifierPool.Type get set
Definition at line 46 of file ModifierPool.cs.
Referenced by Loot.Api.Core.ModifierPool.Clone().
uint ILoadableContentSetter. Loot.Api.Core.ModifierPool.Type set private
Definition at line 49 of file ModifierPool.cs.