Even More Modifiers: Loot.Core.Graphics.ShaderGlobalItem Class Reference
Loot.Core.Graphics.ShaderGlobalItem Class Reference
This class is responsible for handling ShaderEntity that come from the Modifiers on a given item
Public Member Functions
override bool PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
void UpdateEntities (Item item)
Public Attributes
override bool CloneNewInstances => true
override bool InstancePerEntity => true
bool NeedsUpdate
List< ShaderEntity > ShaderEntities = new List<ShaderEntity>()
Detailed Description
This class is responsible for handling ShaderEntity that come from the Modifiers on a given item
Definition at line 15 of file ShaderGlobalItem.cs.
Member Function Documentation
override bool Loot.Core.Graphics.ShaderGlobalItem.PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
Definition at line 48 of file ShaderGlobalItem.cs.
References Loot.Core.Graphics.ShaderEntity.DoDrawLayeredEntity(), Loot.Core.Graphics.ShaderGlobalItem.ShaderEntities, and Loot.Core.Graphics.ShaderGlobalItem.UpdateEntities().
         {
             bool flag = true;
             ShaderGlobalItem shaderInfo = item.GetGlobalItem<ShaderGlobalItem>();
             GlowmaskGlobalItem glowmaskInfo = item.GetGlobalItem<GlowmaskGlobalItem>();
             shaderInfo.UpdateEntities(item);
             glowmaskInfo.UpdateEntities(item);
             for (int i = 0; i < shaderInfo.ShaderEntities.Count; i++)
             {
                 ShaderEntity shaderEntity = shaderInfo.ShaderEntities[i];
                 if (shaderEntity != null)
                 {
                     flag = false;
                     shaderEntity.DoDrawLayeredEntity(spriteBatch, lightColor, alphaColor, scale, rotation, glowmaskInfo.GlowmaskEntities[i]);
                 }
             }
             return flag;
         }
void Loot.Core.Graphics.ShaderGlobalItem.UpdateEntities (Item item)
Definition at line 23 of file ShaderGlobalItem.cs.
References Loot.EMMItem.GetActivePool().
Referenced by Loot.Core.Graphics.ShaderGlobalItem.PreDrawInWorld().
         {
             var pool = EMMItem.GetActivePool(item).ToArray();
             if (!NeedsUpdate && ShaderEntities != null && !ShaderEntities.Any(x => x != null && x.NeedsUpdate))
             {
                 return;
             }
             if (ShaderEntities != null)
             {
                 ShaderEntities.Clear();
                 foreach (var m in pool)
                 {
                     var ent = m.GetShaderEntity(item);
                     ShaderEntities.Add(ent);
                 }
                 ShaderEntities = new List<ShaderEntity>(ShaderEntities.OrderBy(x => x?.Order ?? 0));
             }
             NeedsUpdate = false;
         }
Member Data Documentation
override bool Loot.Core.Graphics.ShaderGlobalItem.CloneNewInstances => true
Definition at line 21 of file ShaderGlobalItem.cs.
override bool Loot.Core.Graphics.ShaderGlobalItem.InstancePerEntity => true
Definition at line 20 of file ShaderGlobalItem.cs.
bool Loot.Core.Graphics.ShaderGlobalItem.NeedsUpdate
Definition at line 18 of file ShaderGlobalItem.cs.
List<ShaderEntity> Loot.Core.Graphics.ShaderGlobalItem.ShaderEntities = new List<ShaderEntity>()
Definition at line 17 of file ShaderGlobalItem.cs.
Referenced by Loot.Core.Graphics.GlowmaskGlobalItem.PostDrawInWorld(), and Loot.Core.Graphics.ShaderGlobalItem.PreDrawInWorld().