Even More Modifiers: Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM Class Reference
Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM Class Reference
Static Public Member Functions
static void Load ()
static void Unload ()
Public Attributes
const int MAX_FRAME = 4
const int MAX_TICK = 6
Static Public Attributes
static Vector2 FRAME = new Vector2(124, 106)
static Texture2D TEX_EIGHTY
static Texture2D TEX_FOURTY
static Texture2D TEX_SIXTY
static Texture2D TEX_TWENTY
Detailed Description
Definition at line 50 of file GuiSoulgauge.cs.
Member Function Documentation
static void Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.Load () static
Definition at line 60 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Load().
                 {
                     TEX_TWENTY = Loot.Instance.GetTexture("UI/Common/Tabs/Soulforging/Soulgauge_anim_20");
                     TEX_FOURTY = Loot.Instance.GetTexture("UI/Common/Tabs/Soulforging/Soulgauge_anim_40");
                     TEX_SIXTY = Loot.Instance.GetTexture("UI/Common/Tabs/Soulforging/Soulgauge_anim_60");
                     TEX_EIGHTY = Loot.Instance.GetTexture("UI/Common/Tabs/Soulforging/Soulgauge_anim_80");
                 }
static void Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.Unload () static
Definition at line 68 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Unload().
                 {
                     TEX_TWENTY = null;
                     TEX_FOURTY = null;
                     TEX_SIXTY = null;
                     TEX_EIGHTY = null;
                 }
Member Data Documentation
Vector2 Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.FRAME = new Vector2(124, 106) static
Definition at line 54 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
const int Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.MAX_FRAME = 4
Definition at line 52 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
const int Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.MAX_TICK = 6
Definition at line 53 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_EIGHTY static
Definition at line 58 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel().
Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_FOURTY static
Definition at line 56 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel().
Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_SIXTY static
Definition at line 57 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel().
Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_TWENTY static
Definition at line 55 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel().