Even More Modifiers: Loot.RollingStrategies.NormalRollingStrategy Class Reference
Loot.RollingStrategies.NormalRollingStrategy Class Reference
A normal rolling strategy, follows normal behavior
Public Member Functions
bool Roll (ModifierContext modifierContext, RollingStrategyContext strategyContext)
Public Member Functions inherited from Loot.Api.Strategy.IRollingStrategy< RollingStrategyContext >
bool Roll (ModifierContext modifierContext, T strategyContext=null)
Protected Member Functions
virtual IEnumerable< Modifier > GetRollableModifiers (ModifierContext context)
Protected Attributes
bool _forceNextRoll
LootModItem modifierItem
RollingStrategyProperties properties
Private Member Functions
WeightedRandom< Modifier > GetRandomList (ModifierContext context)
void InitFields (RollingStrategyContext strategyContext)
Detailed Description
A normal rolling strategy, follows normal behavior
Definition at line 15 of file NormalRollingStrategy.cs.
Member Function Documentation
WeightedRandom<Modifier> Loot.RollingStrategies.NormalRollingStrategy.GetRandomList (ModifierContext context) private
Definition at line 32 of file NormalRollingStrategy.cs.
         {
             WeightedRandom<Modifier> wr = new WeightedRandom<Modifier>();
             foreach (var e in GetRollableModifiers(context))
                 wr.Add(e, e.Properties.RollChance);
             return wr;
         }
virtual IEnumerable<Modifier> Loot.RollingStrategies.NormalRollingStrategy.GetRollableModifiers (ModifierContext context) protected virtual
void Loot.RollingStrategies.NormalRollingStrategy.InitFields (RollingStrategyContext strategyContext) private
Definition at line 26 of file NormalRollingStrategy.cs.
References Loot.LootModItem.GetInfo(), Loot.Api.Strategy.RollingStrategyContext.Item, and Loot.Api.Strategy.RollingStrategyContext.Properties.
         {
             properties = strategyContext.Properties;
             modifierItem = LootModItem.GetInfo(strategyContext.Item);
         }
bool Loot.RollingStrategies.NormalRollingStrategy.Roll (ModifierContext modifierContext, RollingStrategyContext strategyContext)
Definition at line 40 of file NormalRollingStrategy.cs.
References Loot.Api.Core.ModifierPool.ActiveModifiers, Loot.Api.Core.Modifier.Clone(), Loot.Api.Core.ModifierRarity.ExtraLuck, Loot.Api.Strategy.RollingStrategyProperties.ExtraLuck, Loot.Api.Core.ModifierRarity.ExtraMagnitudePower, Loot.Api.Delegators.ModifierDelegatorPlayer.GetEffect(), Loot.Api.Core.Modifier.GetModifierProperties(), Loot.Api.Delegators.ModifierDelegatorPlayer.GetPlayer(), Loot.Api.Core.ModifierProperties.IsUnique, Loot.Api.Core.ModifierContext.Item, Loot.Api.Strategy.RollingStrategyProperties.MagnitudePower, Loot.Api.Strategy.RollingStrategyProperties.MaxRollableLines, Loot.Api.Strategy.RollingStrategyProperties.MinModifierRolls, Loot.LootModItem.ModifierPool, Loot.Api.Core.ModifierContext.Player, Loot.Api.Core.Modifier.PostRoll(), Loot.Api.Core.Modifier.Properties, Loot.Api.Core.ModifierContext.Rarity, Loot.Api.Core.Modifier.Roll(), Loot.Api.Core.ModifierProperties.RollMagnitudeAndPower(), Loot.Api.Strategy.RollingStrategyProperties.RollNextChance, and Loot.Api.Core.Modifier.Type.
         {
             InitFields(strategyContext);
             var wr = GetRandomList(modifierContext);
             var list = new List<Modifier>();
             // Up to n times, try rolling a mod
             // TODO since we can increase lines rolled, make it so that MaxRollableLines influences the number of rows drawn in the UI
             for (int i = 0; i < properties.MaxRollableLines; ++i)
             {
                 // If there are no mods left, or we fail the roll, break.
                 if (wr.elements.Count <= 0
                     || !_forceNextRoll
                     && list.Count >= properties.MinModifierRolls
                     && Main.rand.NextFloat() > properties.RollNextChance)
                 {
                     break;
                 }
                 _forceNextRoll = false;
                 // Get a next weighted random mod
                 // Clone the mod (new instance) and roll its properties, then roll it
                 Modifier rolledModifier = (Modifier)wr.Get().Clone();
                 float luck = properties.ExtraLuck;
                 float magnitudePower = properties.MagnitudePower;
                 if (modifierContext.Player != null)
                 {
                     luck += ModifierDelegatorPlayer.GetPlayer(modifierContext.Player).GetEffect<LuckEffect>().Luck;
                 }
                 if (modifierContext.Rarity != null)
                 {
                     luck += modifierContext.Rarity.ExtraLuck;
                     magnitudePower += modifierContext.Rarity.ExtraMagnitudePower;
                 }
                 rolledModifier.Properties =
                     rolledModifier.GetModifierProperties(modifierContext.Item)
                         .Build()
                         .RollMagnitudeAndPower(magnitudePower, luck);
                 rolledModifier.Roll(modifierContext, list);
                 // If the mod deemed to be unable to be added,
                 // Force that the next roll is successful
                 // (no RNG on top of RNG)
                 if (!rolledModifier.PostRoll(modifierContext, list))
                 {
                     _forceNextRoll = true;
                     continue;
                 }
                 // The mod can be added
                 list.Add(rolledModifier);
                 // If it is a unique modifier, remove it from the list to be rolled
                 if (rolledModifier.Properties.IsUnique)
                 {
                     wr.elements.RemoveAll(x => x.Item1.Type == rolledModifier.Type);
                     wr.needsRefresh = true;
                 }
             }
             modifierItem.ModifierPool.ActiveModifiers = list.ToArray();
             return list.Any();
         }
Member Data Documentation
bool Loot.RollingStrategies.NormalRollingStrategy._forceNextRoll protected
Definition at line 18 of file NormalRollingStrategy.cs.
LootModItem Loot.RollingStrategies.NormalRollingStrategy.modifierItem protected
Definition at line 21 of file NormalRollingStrategy.cs.
RollingStrategyProperties Loot.RollingStrategies.NormalRollingStrategy.properties protected
Definition at line 20 of file NormalRollingStrategy.cs.