Even More Modifiers: Loot.Core.System.Modifier.ModifierPool Class Reference
Loot.Core.System.Modifier.ModifierPool Class Reference
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Public Member Functions
virtual bool CanRoll (ModifierContext ctx)
Returns if this pool can roll in the given context Returns true by default
virtual void Clone (ref ModifierPool clone)
Allows modders to do custom cloning Happens after default cloning
object Clone ()
virtual IEnumerable< Modifier > GetModifiers ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Public Attributes
IEnumerable< ModifierTooltipLine[]> Description => ActiveModifiers.Select(m => m.GetTooltip().Build())
Returns an enumerable of the tooltiplines of the active modifiers
string Name => GetType().Name
virtual float RollChance => 1f
float TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
IEnumerable< string > UniqueNames
Properties
Modifier[] ActiveModifiers [get, set]
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Core.System.Core.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Private Member Functions
IEnumerable< Modifier > _GetModifiers ()
Private Attributes
PopulatePoolFromAttribute _populatePoolFrom
const int SAVE_VERSION = 3
Detailed Description
Defines a modifier pool. A modifier pool holds a certain amount of effects in an array It allows to roll a 'themed' item if it hits an already defined pool Up to 4 effects are drawn from the pool, and activated
Definition at line 22 of file ModifierPool.cs.
Member Function Documentation
IEnumerable<Modifier> Loot.Core.System.Modifier.ModifierPool._GetModifiers () private
Definition at line 56 of file ModifierPool.cs.
References Loot.Core.Attributes.PopulatePoolFromAttribute.GetClasses(), and Loot.Core.System.Loaders.ContentLoader.Modifier.
         {
             if (_populatePoolFrom != null)
             {
                 var classes = _populatePoolFrom.GetClasses().SelectMany(x => x.Value);
                 foreach (var @class in classes)
                 {
                     var m = ContentLoader.Modifier.GetContent(@class);
                     if (m != null)
                     {
                         yield return m;
                     }
                 }
             }
             foreach (Modifier m in GetModifiers())
             {
                 if (m != null)
                 {
                     yield return m;
                 }
             }
         }
virtual bool Loot.Core.System.Modifier.ModifierPool.CanRoll (ModifierContext ctx) virtual
Returns if this pool can roll in the given context Returns true by default
virtual void Loot.Core.System.Modifier.ModifierPool.Clone (ref ModifierPool clone) virtual
Allows modders to do custom cloning Happens after default cloning
Definition at line 138 of file ModifierPool.cs.
Referenced by Loot.Ext.ModUtils.GetModifierPool(), and Loot.Core.System.Content.ModifierPoolContent.GetWeightedPool().
         {
         }
object Loot.Core.System.Modifier.ModifierPool.Clone ()
Definition at line 142 of file ModifierPool.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.Core.System.Modifier.ModifierPool.Mod, and Loot.Core.System.Modifier.ModifierPool.Type.
         {
             ModifierPool clone = (ModifierPool)MemberwiseClone();
             clone.Type = Type;
             clone.Mod = Mod;
             clone.ActiveModifiers =
                 ActiveModifiers?
                     .Select(x => x?.Clone())
                     .Cast<Modifier>()
                     .ToArray();
             Clone(ref clone);
             return clone;
         }
virtual IEnumerable<Modifier> Loot.Core.System.Modifier.ModifierPool.GetModifiers () virtual
Reimplemented in Loot.Pools.AllModifiersPool.
virtual void Loot.Core.System.Modifier.ModifierPool.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 211 of file ModifierPool.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.EMMItem.GetItemInfo(), Loot.Core.System.Modifier.ModifierPool.Load(), Loot.Core.System.Loaders.ContentLoader.ModifierPool, Loot.Core.System.Loaders.ContentLoader.ModifierRarity, and Loot.EMMItem.ModifierRarity.
Referenced by Loot.Core.System.Modifier.ModifierPool.Load().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierPool.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Definition at line 159 of file ModifierPool.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.Core.System.Loaders.ContentLoader.ModifierPool, and Loot.Core.System.Modifier.ModifierPool.NetReceive().
Referenced by Loot.Core.System.Modifier.ModifierPool.NetReceive().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierPool.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Definition at line 189 of file ModifierPool.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.Core.System.Modifier.ModifierPool.Mod, Loot.Core.System.Modifier.ModifierPool.Name, and Loot.Core.System.Modifier.ModifierPool.NetSend().
Referenced by Loot.Core.System.Modifier.ModifierPool.NetSend().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierPool.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item, TagCompound)
Parameters
tag
Definition at line 296 of file ModifierPool.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.Core.System.Modifier.ModifierPool.Mod, Loot.Core.System.Modifier.ModifierPool.Name, Loot.Core.System.Modifier.Modifier.Save(), and Loot.Core.System.Modifier.ModifierPool.Save().
Referenced by Loot.Core.System.Modifier.ModifierPool.Save(), and Loot.EMMItem.Save().
         {
         }
Member Data Documentation
PopulatePoolFromAttribute Loot.Core.System.Modifier.ModifierPool._populatePoolFrom private
Definition at line 49 of file ModifierPool.cs.
IEnumerable<ModifierTooltipLine[]> Loot.Core.System.Modifier.ModifierPool.Description => ActiveModifiers.Select(m => m.GetTooltip().Build())
Returns an enumerable of the tooltiplines of the active modifiers
Definition at line 102 of file ModifierPool.cs.
string Loot.Core.System.Modifier.ModifierPool.Name => GetType().Name
Definition at line 40 of file ModifierPool.cs.
Referenced by Loot.Core.System.Modifier.ModifierPool.NetSend(), and Loot.Core.System.Modifier.ModifierPool.Save().
virtual float Loot.Core.System.Modifier.ModifierPool.RollChance => 1f
Definition at line 104 of file ModifierPool.cs.
const int Loot.Core.System.Modifier.ModifierPool.SAVE_VERSION = 3 private
Definition at line 24 of file ModifierPool.cs.
float Loot.Core.System.Modifier.ModifierPool.TotalRarityLevel => ActiveModifiers.Select(m => m.Properties.RarityLevel).DefaultIfEmpty(0).Sum()
Returns the sum of the rarity levels of the active modifiers
Definition at line 96 of file ModifierPool.cs.
IEnumerable<string> Loot.Core.System.Modifier.ModifierPool.UniqueNames
Initial value:
=>
            ActiveModifiers
                .Where(x => x.UniqueName != string.Empty)
                .Select(x => x.UniqueName)
Definition at line 42 of file ModifierPool.cs.
Property Documentation
Modifier [] Loot.Core.System.Modifier.ModifierPool.ActiveModifiers get set
Definition at line 47 of file ModifierPool.cs.
Referenced by Loot.Core.System.Modifier.ModifierPool.Clone(), Loot.Core.System.Modifier.ModifierPool.Load(), Loot.EMMItem.Load(), Loot.Core.System.Modifier.ModifierPool.NetReceive(), Loot.Core.System.Modifier.ModifierPool.NetSend(), Loot.EMMItem.RollNewModifiers(), and Loot.Core.System.Modifier.ModifierPool.Save().
Mod Loot.Core.System.Modifier.ModifierPool.Mod get set
Definition at line 26 of file ModifierPool.cs.
Referenced by Loot.Core.System.Modifier.ModifierPool.Clone(), Loot.Core.System.Modifier.ModifierPool.NetSend(), and Loot.Core.System.Modifier.ModifierPool.Save().
Mod ILoadableContentSetter. Loot.Core.System.Modifier.ModifierPool.Mod set private
Definition at line 29 of file ModifierPool.cs.
uint Loot.Core.System.Modifier.ModifierPool.Type get set
Definition at line 33 of file ModifierPool.cs.
Referenced by Loot.Core.System.Modifier.ModifierPool.Clone(), and Loot.Ext.ModUtils.GetModifierPool().
uint ILoadableContentSetter. Loot.Core.System.Modifier.ModifierPool.Type set private
Definition at line 36 of file ModifierPool.cs.