Even More Modifiers: Loot.ActivatedModifierItem Class Reference
Loot.ActivatedModifierItem Class Reference
Public Member Functions
bool IsInInventory (Item item, Player player)
bool IsInVanitySot (Item item, Player player)
Returns if the item is in a player's vanity slot
bool ShouldBeIgnored (Item item, Player player)
override void UpdateAccessory (Item item, Player player, bool hideVisual)
override void UpdateEquip (Item item, Player player)
Static Public Member Functions
static ActivatedModifierItem Item (Item item)
Public Attributes
override bool CloneNewInstances => true
override bool InstancePerEntity => true
Properties
bool IsActivated [get, set]
Keeps track of if the particular item was activated ('delegated') Specific usecase see CursedEffect and modifier
bool IsCheated [get, set]
Keeps track of if the item was activated whilst in a vanity slot (by another mod) In this case activated means giving its regular bonuses
Private Member Functions
bool IsNotEquippedAtAll (Item item, Player player)
Detailed Description
Definition at line 12 of file ModifierItem.cs.
Member Function Documentation
bool Loot.ActivatedModifierItem.IsInInventory (Item item, Player player)
Definition at line 35 of file ModifierItem.cs.
Referenced by Loot.ActivatedModifierItem.ShouldBeIgnored().
         {
             return player.inventory.Any(x => x.IsTheSameAs(item));
         }
bool Loot.ActivatedModifierItem.IsInVanitySot (Item item, Player player)
Returns if the item is in a player's vanity slot
Definition at line 43 of file ModifierItem.cs.
Referenced by Loot.ActivatedModifierItem.ShouldBeIgnored(), Loot.ActivatedModifierItem.UpdateAccessory(), and Loot.ActivatedModifierItem.UpdateEquip().
         {
             return player.armor.Skip(13).Any(x => x.IsTheSameAs(item));
         }
bool Loot.ActivatedModifierItem.IsNotEquippedAtAll (Item item, Player player) private
Definition at line 48 of file ModifierItem.cs.
Referenced by Loot.ActivatedModifierItem.UpdateAccessory(), and Loot.ActivatedModifierItem.UpdateEquip().
         {
             return !player.armor.Any(x => x.IsTheSameAs(item));
         }
static ActivatedModifierItem Loot.ActivatedModifierItem.Item (Item item) static
Referenced by Loot.Modifiers.ModifierCachePlayer.AddAttachItem(), Loot.Modifiers.ModifierCachePlayer.AddDetachItem(), Loot.Modifiers.ModifierCachePlayer.CacheModifierEffects(), Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding(), Loot.EMMItem.ModifyTooltips(), Loot.ActivatedModifierItem.UpdateEquip(), and Loot.Modifiers.ModifierCachePlayer.UpdateVanityCache().
bool Loot.ActivatedModifierItem.ShouldBeIgnored (Item item, Player player)
Definition at line 29 of file ModifierItem.cs.
References Loot.ActivatedModifierItem.IsCheated, Loot.ActivatedModifierItem.IsInInventory(), and Loot.ActivatedModifierItem.IsInVanitySot().
Referenced by Loot.ModifierItem.AltFunctionUse(), Loot.ModifierItem.CanEquipAccessory(), Loot.ModifierItem.CanHitNPC(), Loot.ModifierItem.CanHitPvp(), Loot.ModifierItem.CanPickup(), Loot.ModifierItem.CanRightClick(), Loot.ModifierItem.CanUseItem(), Loot.ModifierItem.ChoosePrefix(), Loot.ModifierItem.ConsumeAmmo(), Loot.ModifierItem.ConsumeItem(), Loot.ModifierItem.GetAlpha(), Loot.ModifierItem.GetWeaponCrit(), Loot.ModifierItem.GetWeaponDamage(), Loot.ModifierItem.GetWeaponKnockback(), Loot.ModifierItem.GrabRange(), Loot.ModifierItem.GrabStyle(), Loot.ModifierItem.HoldItem(), Loot.ModifierItem.HoldItemFrame(), Loot.ModifierItem.HoldStyle(), Loot.ModifierItem.HorizontalWingSpeeds(), Loot.ModifierItem.ItemSpace(), Loot.ModifierItem.MeleeEffects(), Loot.ModifierItem.MeleeSpeedMultiplier(), Loot.ModifierItem.ModifyHitNPC(), Loot.ModifierItem.ModifyHitPvp(), Loot.EMMItem.ModifyTooltips(), Loot.ModifierItem.NewPreReforge(), Loot.ModifierItem.OnCraft(), Loot.ModifierItem.OnHitNPC(), Loot.ModifierItem.OnHitPvp(), Loot.ModifierItem.OnPickup(), Loot.ModifierItem.PickAmmo(), Loot.ModifierItem.PostDrawInInventory(), Loot.ModifierItem.PostDrawInWorld(), Loot.ModifierItem.PostDrawTooltip(), Loot.ModifierItem.PostDrawTooltipLine(), Loot.ModifierItem.PostReforge(), Loot.ModifierItem.PostUpdate(), Loot.ModifierItem.PreDrawInInventory(), Loot.ModifierItem.PreDrawInWorld(), Loot.ModifierItem.PreDrawTooltip(), Loot.ModifierItem.PreDrawTooltipLine(), Loot.ModifierItem.ReforgePrice(), Loot.ModifierItem.RightClick(), Loot.ModifierItem.SetDefaults(), Loot.ModifierItem.Shoot(), Loot.ModifierItem.Update(), Loot.ModifierItem.UpdateAccessory(), Loot.ModifierItem.UpdateEquip(), Loot.ModifierItem.UpdateInventory(), Loot.ModifierItem.UseItem(), Loot.ModifierItem.UseItemFrame(), Loot.ModifierItem.UseItemHitbox(), Loot.ModifierItem.UseStyle(), Loot.ModifierItem.UseTimeMultiplier(), and Loot.ModifierItem.VerticalWingSpeeds().
         {
             return !IsCheated && IsInVanitySot(item, player)
                     || IsCheated && !IsInVanitySot(item, player) && !IsInInventory(item, player);
         }
override void Loot.ActivatedModifierItem.UpdateAccessory (Item item, Player player, bool hideVisual)
Definition at line 53 of file ModifierItem.cs.
References Loot.ActivatedModifierItem.IsCheated, Loot.ActivatedModifierItem.IsInVanitySot(), and Loot.ActivatedModifierItem.IsNotEquippedAtAll().
         {
             if (IsInVanitySot(item, player) || IsNotEquippedAtAll(item, player))
             {
                 IsCheated = true;
             }
             else
             {
                 IsCheated = false;
             }
         }
override void Loot.ActivatedModifierItem.UpdateEquip (Item item, Player player)
Definition at line 65 of file ModifierItem.cs.
References Loot.ActivatedModifierItem.IsCheated, Loot.ActivatedModifierItem.IsInVanitySot(), Loot.ActivatedModifierItem.IsNotEquippedAtAll(), and Loot.ActivatedModifierItem.Item().
         {
             if (IsInVanitySot(item, player) || IsNotEquippedAtAll(item, player))
             {
                 IsCheated = true;
             }
             else
             {
                 IsCheated = false;
             }
         }
Member Data Documentation
override bool Loot.ActivatedModifierItem.CloneNewInstances => true
Definition at line 15 of file ModifierItem.cs.
override bool Loot.ActivatedModifierItem.InstancePerEntity => true
Definition at line 14 of file ModifierItem.cs.
Property Documentation
bool Loot.ActivatedModifierItem.IsActivated get set
Keeps track of if the particular item was activated ('delegated') Specific usecase see CursedEffect and modifier
Definition at line 21 of file ModifierItem.cs.
Referenced by Loot.Modifiers.ModifierCachePlayer.AddAttachItem(), Loot.Modifiers.ModifierCachePlayer.AddDetachItem(), and Loot.Modifiers.WeaponModifiers.CursedEffect.CurseHolding().
bool Loot.ActivatedModifierItem.IsCheated get set
Keeps track of if the item was activated whilst in a vanity slot (by another mod) In this case activated means giving its regular bonuses
Definition at line 27 of file ModifierItem.cs.
Referenced by Loot.Modifiers.ModifierCachePlayer.CacheModifierEffects(), Loot.ActivatedModifierItem.ShouldBeIgnored(), Loot.ActivatedModifierItem.UpdateAccessory(), Loot.ActivatedModifierItem.UpdateEquip(), and Loot.Modifiers.ModifierCachePlayer.UpdateVanityCache().