Even More Modifiers: Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing Class Reference
Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing Class Reference
Classes
class ANIM
class STATIC
Static Public Member Functions
static Rectangle GetDrawFrame ()
static Texture2D GetTextureByLevel (GaugeLevel level)
static bool IsAnimation (GaugeLevel level)
static void Load ()
static void Unload ()
static void Update ()
Properties
static bool IsLoaded [get, private set]
Static Private Attributes
static Texture2D _activeTexture
static short _frame
static short _tick
Detailed Description
Definition at line 11 of file GuiSoulgauge.cs.
Member Function Documentation
static Rectangle Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetDrawFrame () static
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
static Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel (GaugeLevel level) static
Definition at line 80 of file GuiSoulgauge.cs.
References Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_EIGHTY, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.STATIC.TEX_EMPTY, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_FOURTY, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.STATIC.TEX_FULL, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_SIXTY, and Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.TEX_TWENTY.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
             {
                 switch (level)
                 {
                     default:
                     case GaugeLevel.ZERO:
                         return STATIC.TEX_EMPTY;
                     case GaugeLevel.HUNDRED:
                         return STATIC.TEX_FULL;
                     case GaugeLevel.TWENTY:
                         return ANIM.TEX_TWENTY;
                     case GaugeLevel.FOURTY:
                         return ANIM.TEX_FOURTY;
                     case GaugeLevel.SIXTY:
                         return ANIM.TEX_SIXTY;
                     case GaugeLevel.EIGHTY:
                         return ANIM.TEX_EIGHTY;
                 }
             }
static bool Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.IsAnimation (GaugeLevel level) static
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
static void Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Load () static
Definition at line 15 of file GuiSoulgauge.cs.
References Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.STATIC.Load(), and Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.Load().
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
             {
                 if (!IsLoaded)
                 {
                     STATIC.Load();
                     ANIM.Load();
                     IsLoaded = true;
                 }
             }
static void Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Unload () static
Definition at line 25 of file GuiSoulgauge.cs.
References Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.STATIC.Unload(), and Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.Unload().
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
             {
                 STATIC.Unload();
                 ANIM.Unload();
                 IsLoaded = false;
             }
static void Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update () static
Definition at line 104 of file GuiSoulgauge.cs.
References Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.FRAME, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetDrawFrame(), Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.GetTextureByLevel(), Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.IsAnimation(), Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.IsLoaded, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Load(), Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.MAX_FRAME, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.ANIM.MAX_TICK, Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Unload(), and Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().
             {
                 _tick++;
                 if (_tick >= ANIM.MAX_TICK)
                 {
                     _tick = 0;
                     _frame++;
                     if (_frame >= ANIM.MAX_FRAME)
                     {
                         _frame = 0;
                     }
                 }
             }
Member Data Documentation
Texture2D Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing._activeTexture static private
Definition at line 102 of file GuiSoulgauge.cs.
short Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing._frame static private
Definition at line 101 of file GuiSoulgauge.cs.
short Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing._tick static private
Definition at line 100 of file GuiSoulgauge.cs.
Property Documentation
bool Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.IsLoaded static get private set
Definition at line 13 of file GuiSoulgauge.cs.
Referenced by Loot.UI.Common.Tabs.Soulforging.GuiSoulgauge.GaugeDrawing.Update().