Even More Modifiers: Loot.Core.System.Modifier.ModifierRarity Class Reference
Loot.Core.System.Modifier.ModifierRarity Class Reference
Defines the rarity of a modifier
Public Member Functions
virtual void Clone (ref ModifierRarity clone)
object Clone ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual bool MatchesRequirements (ModifierPool modifierPool)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Public Attributes
virtual string ItemPrefix => null
virtual string ItemSuffix => null
string Name => GetType().Name
virtual Color OverrideNameColor => null
virtual string RarityName => Name
Properties
abstract Color Color [get]
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
abstract float RequiredRarityLevel [get]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Core.System.Core.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Detailed Description
Defines the rarity of a modifier
Definition at line 15 of file ModifierRarity.cs.
Member Function Documentation
virtual void Loot.Core.System.Modifier.ModifierRarity.Clone (ref ModifierRarity clone) virtual
Definition at line 44 of file ModifierRarity.cs.
Referenced by Loot.Ext.ModUtils.GetModifierRarity().
         {
         }
object Loot.Core.System.Modifier.ModifierRarity.Clone ()
Definition at line 48 of file ModifierRarity.cs.
References Loot.Core.System.Modifier.ModifierRarity.Mod, and Loot.Core.System.Modifier.ModifierRarity.Type.
         {
             ModifierRarity clone = (ModifierRarity) MemberwiseClone();
             clone.Mod = Mod;
             clone.Type = Type;
             Clone(ref clone);
             return clone;
         }
virtual void Loot.Core.System.Modifier.ModifierRarity.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 100 of file ModifierRarity.cs.
References Loot.Core.System.Modifier.ModifierRarity.Load(), and Loot.Core.System.Loaders.ContentLoader.ModifierRarity.
Referenced by Loot.Core.System.Modifier.ModifierRarity.Load().
         {
         }
virtual bool Loot.Core.System.Modifier.ModifierRarity.MatchesRequirements (ModifierPool modifierPool) virtual
virtual void Loot.Core.System.Modifier.ModifierRarity.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Parameters
item
reader
Definition at line 62 of file ModifierRarity.cs.
References Loot.Core.System.Loaders.ContentLoader.ModifierRarity, and Loot.Core.System.Modifier.ModifierRarity.NetReceive().
Referenced by Loot.Core.System.Modifier.ModifierRarity.NetReceive().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierRarity.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Parameters
item
writer
Definition at line 86 of file ModifierRarity.cs.
References Loot.Core.System.Modifier.ModifierRarity.Mod, and Loot.Core.System.Modifier.ModifierRarity.Name.
         {
         }
virtual void Loot.Core.System.Modifier.ModifierRarity.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Definition at line 149 of file ModifierRarity.cs.
References Loot.Core.System.Modifier.ModifierRarity.Mod, Loot.Core.System.Modifier.ModifierRarity.Name, and Loot.Core.System.Modifier.ModifierRarity.Save().
Referenced by Loot.Core.System.Modifier.ModifierRarity.Save(), and Loot.Core.System.Modifier.ModifierPool.Save().
         {
         }
Member Data Documentation
virtual string Loot.Core.System.Modifier.ModifierRarity.ItemPrefix => null
Definition at line 35 of file ModifierRarity.cs.
virtual string Loot.Core.System.Modifier.ModifierRarity.ItemSuffix => null
Definition at line 36 of file ModifierRarity.cs.
string Loot.Core.System.Modifier.ModifierRarity.Name => GetType().Name
Definition at line 31 of file ModifierRarity.cs.
Referenced by Loot.Core.System.Modifier.ModifierRarity.NetSend(), and Loot.Core.System.Modifier.ModifierRarity.Save().
virtual Color Loot.Core.System.Modifier.ModifierRarity.OverrideNameColor => null
Definition at line 34 of file ModifierRarity.cs.
virtual string Loot.Core.System.Modifier.ModifierRarity.RarityName => Name
Definition at line 33 of file ModifierRarity.cs.
Property Documentation
abstract Color Loot.Core.System.Modifier.ModifierRarity.Color get
Definition at line 39 of file ModifierRarity.cs.
Mod Loot.Core.System.Modifier.ModifierRarity.Mod get set
Definition at line 17 of file ModifierRarity.cs.
Referenced by Loot.Core.System.Modifier.ModifierRarity.Clone(), Loot.Core.System.Modifier.ModifierRarity.NetSend(), and Loot.Core.System.Modifier.ModifierRarity.Save().
Mod ILoadableContentSetter. Loot.Core.System.Modifier.ModifierRarity.Mod set private
Definition at line 20 of file ModifierRarity.cs.
abstract float Loot.Core.System.Modifier.ModifierRarity.RequiredRarityLevel get
Definition at line 38 of file ModifierRarity.cs.
uint Loot.Core.System.Modifier.ModifierRarity.Type get set
Definition at line 24 of file ModifierRarity.cs.
Referenced by Loot.Core.System.Modifier.ModifierRarity.Clone(), and Loot.Ext.ModUtils.GetModifierRarity().
uint ILoadableContentSetter. Loot.Core.System.Modifier.ModifierRarity.Type set private
Definition at line 27 of file ModifierRarity.cs.