Even More Modifiers: Loot.Core.System.ModifierPropertiesBuilder Class Reference
Loot.Core.System.ModifierPropertiesBuilder Class Reference
The ModifierPropertiesBuilder implements the builder pattern for ModifierProperties It provides a structured way to create ("build") an instance of ModifierProperties It is used in Modifier.GetModifierProperties to dynamically build the ModifierProperties for that Modifier.
Public Member Functions
ModifierPropertiesBuilder ()
ModifierPropertiesBuilder (ModifierProperties defaultProperties)
ModifierPropertiesBuilder (ModifierPropertiesBuilder defaultBuilder)
ModifierProperties Build ()
ModifierPropertiesBuilder IsUniqueModifier (bool val)
ModifierPropertiesBuilder UsingDefault (ModifierProperties val)
ModifierPropertiesBuilder UsingDefault (ModifierPropertiesBuilder val)
ModifierPropertiesBuilder WithBasePower (float val)
ModifierPropertiesBuilder WithMagnitudeStrength (float val)
ModifierPropertiesBuilder WithMaxMagnitude (float val)
ModifierPropertiesBuilder WithMinMagnitude (float val)
ModifierPropertiesBuilder WithRarityLevel (float val)
ModifierPropertiesBuilder WithRollChance (float val)
ModifierPropertiesBuilder WithRoundPrecision (int val)
Properties
float BasePower [protected get, set]
ModifierPropertiesBuilder DefaultBuilder [set]
ModifierProperties DefaultProperties [set]
bool IsUnique [protected get, set]
float MagnitudeStrength [protected get, set]
float MaxMagnitude [protected get, set]
float MinMagnitude [protected get, set]
float RarityLevel [protected get, set]
float RollChance [protected get, set]
int RoundPrecision [protected get, set]
Detailed Description
The ModifierPropertiesBuilder implements the builder pattern for ModifierProperties It provides a structured way to create ("build") an instance of ModifierProperties It is used in Modifier.GetModifierProperties to dynamically build the ModifierProperties for that Modifier.
Definition at line 9 of file ModifierPropertiesBuilder.cs.
Constructor & Destructor Documentation
Loot.Core.System.ModifierPropertiesBuilder.ModifierPropertiesBuilder ()
Definition at line 11 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = new ModifierProperties();
         }
Loot.Core.System.ModifierPropertiesBuilder.ModifierPropertiesBuilder (ModifierProperties defaultProperties)
Definition at line 16 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = defaultProperties;
         }
Loot.Core.System.ModifierPropertiesBuilder.ModifierPropertiesBuilder (ModifierPropertiesBuilder defaultBuilder)
Definition at line 21 of file ModifierPropertiesBuilder.cs.
         {
             DefaultBuilder = defaultBuilder;
         }
Member Function Documentation
ModifierProperties Loot.Core.System.ModifierPropertiesBuilder.Build ()
Definition at line 154 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Core.System.Modifier.Clone(), and Loot.Core.System.Modifier.Load().
         {
             return new ModifierProperties(
                 MinMagnitude,
                 MaxMagnitude,
                 MagnitudeStrength,
                 BasePower,
                 RarityLevel,
                 RollChance,
                 RoundPrecision,
                 IsUnique);
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.IsUniqueModifier (bool val)
Definition at line 148 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties().
         {
             IsUnique = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.UsingDefault (ModifierProperties val)
Definition at line 94 of file ModifierPropertiesBuilder.cs.
         {
             DefaultProperties = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.UsingDefault (ModifierPropertiesBuilder val)
Definition at line 100 of file ModifierPropertiesBuilder.cs.
         {
             DefaultBuilder = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithBasePower (float val)
Definition at line 124 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.SpeedPlus.GetModifierProperties().
         {
             BasePower = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithMagnitudeStrength (float val)
Definition at line 118 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifier.GetModifierProperties().
         {
             MagnitudeStrength = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithMaxMagnitude (float val)
Definition at line 112 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.Thorns.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.KnockbackPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.SpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.FishingPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.AmmoReduce.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.WingTimePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.VelocityDamage.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.ManaReduce.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.CritPlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Utility.LuckPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties(), and Loot.Modifiers.EquipModifiers.Utility.LightPlus.GetModifierProperties().
         {
             MaxMagnitude = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithMinMagnitude (float val)
Definition at line 106 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.WeaponModifiers.MissingHealthDamage.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamageWithManaCost.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus.GetModifierProperties(), and Loot.Modifiers.WeaponModifiers.CursedDamage.GetModifierProperties().
         {
             MinMagnitude = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithRarityLevel (float val)
Definition at line 130 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties().
         {
             RarityLevel = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithRollChance (float val)
Definition at line 136 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.EquipModifiers.Defensive.HealthPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ManaPlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity.GetModifierProperties(), Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.LifeRegen.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.DodgeChance.GetModifierProperties(), Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance.GetModifierProperties(), and Loot.Modifiers.EquipModifiers.Defensive.ManaShield.GetModifierProperties().
         {
             RollChance = val;
             return this;
         }
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.WithRoundPrecision (int val)
Definition at line 142 of file ModifierPropertiesBuilder.cs.
Referenced by Loot.Modifiers.WeaponModifiers.VelocityDamage.GetModifierProperties(), and Loot.Modifiers.WeaponDebuffModifier.GetModifierProperties().
         {
             RoundPrecision = val;
             return this;
         }
Property Documentation
float Loot.Core.System.ModifierPropertiesBuilder.BasePower protected get set
Definition at line 45 of file ModifierPropertiesBuilder.cs.
ModifierPropertiesBuilder Loot.Core.System.ModifierPropertiesBuilder.DefaultBuilder set
Definition at line 90 of file ModifierPropertiesBuilder.cs.
ModifierProperties Loot.Core.System.ModifierPropertiesBuilder.DefaultProperties set
Definition at line 75 of file ModifierPropertiesBuilder.cs.
bool Loot.Core.System.ModifierPropertiesBuilder.IsUnique protected get set
Definition at line 69 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.ModifierPropertiesBuilder.MagnitudeStrength protected get set
Definition at line 39 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.ModifierPropertiesBuilder.MaxMagnitude protected get set
Definition at line 33 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.ModifierPropertiesBuilder.MinMagnitude protected get set
Definition at line 27 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.ModifierPropertiesBuilder.RarityLevel protected get set
Definition at line 51 of file ModifierPropertiesBuilder.cs.
float Loot.Core.System.ModifierPropertiesBuilder.RollChance protected get set
Definition at line 57 of file ModifierPropertiesBuilder.cs.
int Loot.Core.System.ModifierPropertiesBuilder.RoundPrecision protected get set
Definition at line 63 of file ModifierPropertiesBuilder.cs.