Even More Modifiers: Loot.Core.System.Modifier.ModifierProperties Class Reference
Loot.Core.System.Modifier.ModifierProperties Class Reference
Defines the properties of a modifier
Public Member Functions
ModifierProperties (float minMagnitude=1f, float maxMagnitude=1f, float magnitudeStrength=1f, float basePower=1f, float rarityLevel=1f, float rollChance=1f, int roundPrecision=0, bool isUnique=false)
virtual void Load (Item item, TagCompound tag)
virtual void NetReceive (Item item, BinaryReader reader)
virtual void NetSend (Item item, BinaryWriter writer)
ModifierProperties RollMagnitudeAndPower (float magnitudePower=1f, float lukStat=0f)
virtual void Save (Item item, TagCompound tag)
Public Attributes
readonly float BasePower
readonly bool IsUnique
readonly float MagnitudeStrength
readonly float MaxMagnitude
readonly float MinMagnitude
readonly float RarityLevel
readonly float RollChance
readonly int RoundPrecision
Static Public Attributes
static ModifierPropertiesBuilder Builder => new ModifierPropertiesBuilder()
Properties
float Magnitude [get, set]
float Power [get, set]
float RoundedPower [get, private set]
Private Member Functions
float RollMagnitude (float magnitudePower, float lukStat)
float RollPower ()
Private Attributes
float _power
Detailed Description
Defines the properties of a modifier
Definition at line 11 of file ModifierProperties.cs.
Constructor & Destructor Documentation
Loot.Core.System.Modifier.ModifierProperties.ModifierProperties (float minMagnitude = 1f, float maxMagnitude = 1f, float magnitudeStrength = 1f, float basePower = 1f, float rarityLevel = 1f, float rollChance = 1f, int roundPrecision = 0, bool isUnique = false)
Definition at line 39 of file ModifierProperties.cs.
         {
             MinMagnitude = minMagnitude;
             MaxMagnitude = maxMagnitude;
             MagnitudeStrength = magnitudeStrength;
             BasePower = basePower;
             RarityLevel = rarityLevel;
             RollChance = rollChance;
             RoundPrecision = roundPrecision;
             IsUnique = isUnique;
         }
Member Function Documentation
virtual void Loot.Core.System.Modifier.ModifierProperties.Load (Item item, TagCompound tag) virtual
Definition at line 127 of file ModifierProperties.cs.
References Loot.Core.System.Modifier.ModifierProperties.Load(), and Loot.Core.System.Modifier.ModifierProperties.RollMagnitudeAndPower().
Referenced by Loot.Core.System.Modifier.ModifierProperties.Load().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierProperties.NetReceive (Item item, BinaryReader reader) virtual
Definition at line 85 of file ModifierProperties.cs.
References Loot.Core.System.Modifier.ModifierProperties.NetReceive().
Referenced by Loot.Core.System.Modifier.ModifierProperties.NetReceive().
         {
         }
virtual void Loot.Core.System.Modifier.ModifierProperties.NetSend (Item item, BinaryWriter writer) virtual
Definition at line 100 of file ModifierProperties.cs.
References Loot.Core.System.Modifier.ModifierProperties.Magnitude, Loot.Core.System.Modifier.ModifierProperties.NetSend(), and Loot.Core.System.Modifier.ModifierProperties.Power.
Referenced by Loot.Core.System.Modifier.ModifierProperties.NetSend().
         {
         }
float Loot.Core.System.Modifier.ModifierProperties.RollMagnitude (float magnitudePower, float lukStat) private
Definition at line 72 of file ModifierProperties.cs.
         {
             float useMin = MinMagnitude * (1f + magnitudePower / 10f);
             float useMax = MaxMagnitude * magnitudePower;
             float randomMag = (useMin + Main.rand.NextFloat() * (useMax - useMin));
             return randomMag * MagnitudeStrength;
         }
ModifierProperties Loot.Core.System.Modifier.ModifierProperties.RollMagnitudeAndPower (float magnitudePower = 1f, float lukStat = 0f)
Definition at line 51 of file ModifierProperties.cs.
Referenced by Loot.Core.System.Modifier.ModifierProperties.Load(), and Loot.EMMItem.RollNewModifiers().
         {
             Magnitude = RollMagnitude(magnitudePower, lukStat);
             int iterations = (int) Math.Ceiling(lukStat) / 2;
             // makes you more lucky rolling better magnitudes
             for (int i = 0; i < iterations; i++)
             {
                 float rolledMagnitude = RollMagnitude(magnitudePower, lukStat);
                 if (rolledMagnitude > Magnitude)
                 {
                     Magnitude = rolledMagnitude;
                 }
             }
             Power = RollPower();
             return this;
         }
float Loot.Core.System.Modifier.ModifierProperties.RollPower () private
Definition at line 80 of file ModifierProperties.cs.
         {
             return BasePower * Magnitude;
         }
virtual void Loot.Core.System.Modifier.ModifierProperties.Save (Item item, TagCompound tag) virtual
Definition at line 111 of file ModifierProperties.cs.
References Loot.Core.System.Modifier.ModifierProperties.Magnitude, Loot.Core.System.Modifier.ModifierProperties.Power, and Loot.Core.System.Modifier.ModifierProperties.Save().
Referenced by Loot.Core.System.Modifier.ModifierProperties.Save().
         {
         }
Member Data Documentation
float Loot.Core.System.Modifier.ModifierProperties._power private
Definition at line 25 of file ModifierProperties.cs.
readonly float Loot.Core.System.Modifier.ModifierProperties.BasePower
Definition at line 19 of file ModifierProperties.cs.
ModifierPropertiesBuilder Loot.Core.System.Modifier.ModifierProperties.Builder => new ModifierPropertiesBuilder() static
Definition at line 14 of file ModifierProperties.cs.
Referenced by Loot.Modifiers.Base.EquipModifier.GetModifierProperties().
readonly bool Loot.Core.System.Modifier.ModifierProperties.IsUnique
Definition at line 23 of file ModifierProperties.cs.
Referenced by Loot.EMMItem.RollNewModifiers().
readonly float Loot.Core.System.Modifier.ModifierProperties.MagnitudeStrength
Definition at line 18 of file ModifierProperties.cs.
readonly float Loot.Core.System.Modifier.ModifierProperties.MaxMagnitude
Definition at line 17 of file ModifierProperties.cs.
readonly float Loot.Core.System.Modifier.ModifierProperties.MinMagnitude
Definition at line 16 of file ModifierProperties.cs.
readonly float Loot.Core.System.Modifier.ModifierProperties.RarityLevel
Definition at line 20 of file ModifierProperties.cs.
readonly float Loot.Core.System.Modifier.ModifierProperties.RollChance
Definition at line 21 of file ModifierProperties.cs.
readonly int Loot.Core.System.Modifier.ModifierProperties.RoundPrecision
Definition at line 22 of file ModifierProperties.cs.
Property Documentation
float Loot.Core.System.Modifier.ModifierProperties.Magnitude get set
Definition at line 24 of file ModifierProperties.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.Modifier.Load(), Loot.Core.System.Modifier.ModifierProperties.NetSend(), and Loot.Core.System.Modifier.ModifierProperties.Save().
float Loot.Core.System.Modifier.ModifierProperties.Power get set
Definition at line 28 of file ModifierProperties.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.Modifier.Load(), Loot.Core.System.Modifier.ModifierProperties.NetSend(), and Loot.Core.System.Modifier.ModifierProperties.Save().
float Loot.Core.System.Modifier.ModifierProperties.RoundedPower get private set
Definition at line 37 of file ModifierProperties.cs.