Even More Modifiers: Loot.UI.Rerolling.CubeRerollUI Class Reference
Loot.UI.Rerolling.CubeRerollUI Class Reference
A UIState that provides the ability to reroll an item's modifier
Public Member Functions
override bool IsItemValidForUISlot (Item item)
override bool IsSlottedItemInCubeUI ()
override void OnInitialize ()
override void ToggleUI (UserInterface theInterface, UIState uiStateInstance)
void UpdateModifierLines ()
Public Member Functions inherited from Loot.UI.Core.DraggableUIState
override void OnInitialize ()
Public Member Functions inherited from Loot.UI.Core.VisibilityUI
virtual void ToggleUI (Terraria.UI.UserInterface theInterface, UIState uiStateInstance)
Public Attributes
override Item SlottedItem => _rerollItemPanel.item
Public Attributes inherited from Loot.UI.Core.VisibilityUI
bool Visible
Private Member Functions
bool MatchesRerollRequirements ()
void OnRerollClick (UIMouseEvent evt, UIElement listeningelement)
void RerollModifierPool (Item newItem)
Private Attributes
UIPanel _backPanel
UIPanel _cubeListPanel
UIModifierPanel[] _modifierPanels
UIImageButton _rerollButton
const float PADDING = 5f
Additional Inherited Members
Protected Member Functions inherited from Loot.UI.Core.DraggableUIState
void AddDragPanel (UIPanel panel)
override void DrawSelf (SpriteBatch spriteBatch)
Properties inherited from Loot.UI.Core.CubeUI
abstract Item SlottedItem [get]
Detailed Description
A UIState that provides the ability to reroll an item's modifier
Definition at line 23 of file CubeRerollUI.cs.
Member Function Documentation
override bool Loot.UI.Rerolling.CubeRerollUI.IsItemValidForUISlot (Item item) virtual
Implements Loot.UI.Core.CubeUI.
override bool Loot.UI.Rerolling.CubeRerollUI.IsSlottedItemInCubeUI () virtual
Implements Loot.UI.Core.CubeUI.
bool Loot.UI.Rerolling.CubeRerollUI.MatchesRerollRequirements () private
Definition at line 180 of file CubeRerollUI.cs.
References Loot.UI.Rerolling.UIRerollItemPanel.CanTakeItem(), Loot.UI.Core.UICubeItemPanel.CanTakeItem(), Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UIItemPanel.item, and Loot.EMMItem.SealedModifiers.
         {
             bool match = _rerollItemPanel != null
                    && _cubePanel != null
                    && !_rerollItemPanel.item.IsAir && !_cubePanel.item.IsAir
                    && _rerollItemPanel.CanTakeItem(_rerollItemPanel.item)
                    && _cubePanel.CanTakeItem(_cubePanel.item)
                    && !EMMItem.GetItemInfo(_rerollItemPanel.item).SealedModifiers;
             bool hasItem = Main.LocalPlayer.inventory.Any(x => x.type == _cubePanel.item.type)
                            || (Main.mouseItem?.type == _cubePanel?.item?.type);
             return match && hasItem;
         }
override void Loot.UI.Rerolling.CubeRerollUI.OnInitialize ()
Definition at line 111 of file CubeRerollUI.cs.
         {
             _itemRollProperties = new ItemRollProperties();
             float halfScreenWidth = Main.screenWidth / 2f;
             float halfScreenHeight = Main.screenHeight / 2f;
             Color baseColor = new Color(73, 94, 171);
             _backPanel = new UIPanel();
             _backPanel.Width.Set(600f, 0f);
             _backPanel.Height.Set(200f, 0f);
             _backPanel.Left.Set(halfScreenWidth - _backPanel.Width.Pixels / 2f, 0f);
             _backPanel.Top.Set(halfScreenHeight - _backPanel.Height.Pixels / 2f, 0f);
             _cubeListPanel = new UIPanel
             {
                 Width = new StyleDimension { Pixels = 600f },
                 Height = new StyleDimension { Pixels = 50f },
                 Left = new StyleDimension { Pixels = _backPanel.Left.Pixels },
                 Top = new StyleDimension { Pixels = _backPanel.Top.Pixels + _backPanel.Height.Pixels },
             };
             Append(_cubeListPanel);
             Append(_backPanel);
             AddDragPanel(_cubeListPanel);
             AddDragPanel(_backPanel);
             base.OnInitialize();
             Texture2D btnCloseTexture = ModContent.GetTexture("Terraria/UI/InfoIcon_8");
             UIImageButton closeButton = new UIImageButton(btnCloseTexture);
             closeButton.Left.Set(_backPanel.Width.Pixels - btnCloseTexture.Width * 2f - PADDING, 0f);
             closeButton.Top.Set(0f, 0f);
             closeButton.Width.Set(btnCloseTexture.Width, 0f);
             closeButton.Height.Set(btnCloseTexture.Height, 0f);
             closeButton.OnClick += (evt, element) => { ToggleUI(Loot.Instance.CubeInterface, Loot.Instance.CubeRerollUI); };
             _backPanel.Append(closeButton);
             _cubePanel = new UICubeItemPanel(hintTexture: Loot.Instance.GetTexture("Core/Cubes/MagicalCube"), hintText: "Place a cube here");
             _cubePanel.Top.Set(0f, 0f);
             _backPanel.Append(_cubePanel);
             _rerollItemPanel = new UIRerollItemPanel(hintTexture: ModContent.GetTexture("Terraria/Item_24"), hintText: "Place an item to reroll here");
             _rerollItemPanel.Top.Set(_cubePanel.Top.Pixels + _rerollItemPanel.Height.Pixels + PADDING, 0f);
             _backPanel.Append(_rerollItemPanel);
             _modifierPanels = new UIModifierPanel[4];
             for (int i = 0; i < 4; i++)
             {
                 _modifierPanels[i] = new UIModifierPanel();
                 var panel = _modifierPanels[i];
                 panel.Left.Set(PADDING + _cubePanel.Left.Pixels + _cubePanel.Width.Pixels, 0f);
                 panel.Height.Set(40, 0f);
                 panel.Top.Set(i * PADDING + panel.Height.Pixels * i, 0f);
                 panel.Width.Set(_backPanel.Width.Pixels - closeButton.Width.Pixels * 2f - panel.Left.Pixels - PADDING * 2f, 0f);
                 panel.BackgroundColor = baseColor;
                 _backPanel.Append(panel);
             }
             Texture2D rerollTexture = ModContent.GetTexture("Terraria/UI/Craft_Toggle_3");
             _rerollButton = new UIImageButton(rerollTexture);
             _rerollButton.Width.Set(UIItemPanel.PANEL_WIDTH, 0f);
             _rerollButton.Height.Set(UIItemPanel.PANEL_WIDTH, 0f);
             _rerollButton.Top.Set(_rerollItemPanel.Top.Pixels + _rerollItemPanel.Height.Pixels + PADDING - _cubeListPanel.Height.Pixels, 0.33f);
             _rerollButton.Left.Set(_rerollItemPanel.Left.Pixels + PADDING * 2f, 0f);
             _rerollButton.OnClick += OnRerollClick;
             _backPanel.Append(_rerollButton);
         }
void Loot.UI.Rerolling.CubeRerollUI.OnRerollClick (UIMouseEvent evt, UIElement listeningelement) private
Definition at line 213 of file CubeRerollUI.cs.
References Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UICubeItemPanel.InteractionLogic(), Loot.UI.Core.UIItemPanel.item, Loot.EMMItem.ModifierPool, and Loot.UI.Core.UICubeItemPanel.RecalculateStack().
         {
             if (MatchesRerollRequirements())
             {
                 _itemRollProperties = new ItemRollProperties();
                 _cubePanel.InteractionLogic(_itemRollProperties);
                 _cubePanel.RecalculateStack();
                 // No slotted cubes available
                 if (_cubePanel.item.stack <= 0)
                 {
                     SoundHelper.PlayCustomSound(SoundHelper.SoundType.Decline);
                     _cubePanel.item.TurnToAir();
                     return;
                 }
                 // Refresh item
                 Item newItem = new Item();
                 newItem.netDefaults(_rerollItemPanel.item.type);
                 // Clone to preserve modded data
                 newItem = newItem.CloneWithModdedDataFrom(_rerollItemPanel.item);
                 EMMItem.GetItemInfo(newItem).ModifierPool = null; // unload previous pool
                 // Restore prefix
                 if (_rerollItemPanel.item.prefix > 0)
                 {
                     newItem.Prefix(_rerollItemPanel.item.prefix);
                 }
                 RerollModifierPool(newItem);
                 UpdateModifierLines();
                 Main.PlaySound(SoundID.Item37, -1, -1);
                 bool checkMouse = true;
                 // Remove stack from player's inventory
                 // .Take 58 because 59th slot is MouseItem for some reason.
                 foreach (Item item in Main.LocalPlayer.inventory.Take(58))
                 {
                     if (item.type == _cubePanel.item.type)
                     {
                         checkMouse = false;
                         item.stack--;
                         break;
                     }
                 }
                 if (checkMouse)
                 {
                     // This check should be redundant; otherwise we should never have reached this point
                     //if (Main.mouseItem?.type == _cubePanel.item.type)
                     Main.mouseItem.stack--;
                     if (Main.mouseItem.stack <= 0)
                     {
                         Main.mouseItem.TurnToAir();
                     }
                 }
                 _cubePanel.RecalculateStack();
                 DetermineAvailableCubes();
                 // No slotted cubes available
                 if (_cubePanel.item.stack <= 0)
                 {
                     _cubePanel.item.TurnToAir();
                 }
             }
             else
             {
                 SoundHelper.PlayCustomSound(SoundHelper.SoundType.Decline);
             }
         }
void Loot.UI.Rerolling.CubeRerollUI.RerollModifierPool (Item newItem) private
Definition at line 195 of file CubeRerollUI.cs.
References Loot.EMMItem.GetItemInfo(), and Loot.UI.Core.UIItemPanel.item.
         {
             ModifierContext ctx = new ModifierContext
             {
                 Method = ModifierContextMethod.OnCubeReroll,
                 Item = newItem,
                 Player = Main.LocalPlayer,
                 CustomData = new Dictionary<string, object>
                 {
                     {"Source", "CubeRerollUI"}
                 }
             };
             var pool = EMMItem.GetItemInfo(newItem).RollNewPool(ctx, _itemRollProperties);
             pool?.ApplyModifiers(newItem);
             _rerollItemPanel.item = newItem.Clone();
         }
override void Loot.UI.Rerolling.CubeRerollUI.ToggleUI (UserInterface theInterface, UIState uiStateInstance)
Definition at line 36 of file CubeRerollUI.cs.
References Loot.UI.Rerolling.UIRerollItemPanel.CanTakeItem(), Loot.EMMItem.GetItemInfo(), Loot.UI.Core.UIItemPanel.item, and Loot.EMMItem.SlottedInCubeUI.
         {
             base.ToggleUI(theInterface, uiStateInstance);
             if (Visible)
             {
                 DetermineAvailableCubes();
                 return;
             }
             // If ui closed, we need to retrieve the slotted items
             var ui = Loot.Instance.CubeRerollUI;
             SoundHelper.PlayCustomSound(SoundHelper.SoundType.CloseUI);
             // Clear of the slotted cube type
             ui._cubePanel?.item.TurnToAir();
             // If there is an item slotted
             if (ui._rerollItemPanel != null
                 && !ui._rerollItemPanel.item.IsAir)
             {
                 Main.LocalPlayer.QuickSpawnClonedItem(ui._rerollItemPanel.item, ui._rerollItemPanel.item.stack);
                 ui._rerollItemPanel.item.TurnToAir();
             }
             // Clear lines
             ui.UpdateModifierLines();
         }
void Loot.UI.Rerolling.CubeRerollUI.UpdateModifierLines ()
Definition at line 285 of file CubeRerollUI.cs.
References Loot.EMMItem.GetActivePool(), Loot.UI.Core.UIItemPanel.item, and Loot.UI.Core.UIModifierPanel.UpdateText().
Referenced by Loot.Core.Cubes.CubeUIExtensions.RerollUITakeItem().
         {
             foreach (var panel in _modifierPanels)
             {
                 panel.ResetText();
             }
             if (_rerollItemPanel == null
                 || _rerollItemPanel.item.IsAir
                 || _modifierPanels == null)
             {
                 return;
             }
             int i = 0;
             IEnumerable<ModifierTooltipLine[]> getTooltipLines(Item item)
                 => EMMItem.GetActivePool(item)
                     .Select(x => x.TooltipLines)
                     .Take(4)
                     .Where(x => x != null);
             foreach (var lines in getTooltipLines(_rerollItemPanel.item))
             {
                 string line = lines.Aggregate("", (current, tooltipLine) => current + $"{tooltipLine.Text} ");
                 line = line.TrimEnd();
                 _modifierPanels[i].UpdateText(line);
                 i++;
             }
             Recalculate();
         }
Member Data Documentation
UIPanel Loot.UI.Rerolling.CubeRerollUI._backPanel private
Definition at line 31 of file CubeRerollUI.cs.
UIPanel Loot.UI.Rerolling.CubeRerollUI._cubeListPanel private
Definition at line 33 of file CubeRerollUI.cs.
UIModifierPanel [] Loot.UI.Rerolling.CubeRerollUI._modifierPanels private
Definition at line 34 of file CubeRerollUI.cs.
UIImageButton Loot.UI.Rerolling.CubeRerollUI._rerollButton private
Definition at line 32 of file CubeRerollUI.cs.
const float Loot.UI.Rerolling.CubeRerollUI.PADDING = 5f private
Definition at line 25 of file CubeRerollUI.cs.
override Item Loot.UI.Rerolling.CubeRerollUI.SlottedItem => _rerollItemPanel.item
Definition at line 108 of file CubeRerollUI.cs.