Even More Modifiers: Loot.Api.Modifier.ModifierRarity Class Reference
Loot.Api.Modifier.ModifierRarity Class Reference
Defines the rarity of a modifier
Public Member Functions
virtual void Clone (ref ModifierRarity clone)
object Clone ()
virtual void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
virtual void NetReceive (Item item, BinaryReader reader)
Allows the modder to do custom NetReceive
virtual void NetSend (Item item, BinaryWriter writer)
Allows modder to do custom NetSend here
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Public Attributes
virtual Type Downgrade => null
virtual float DowngradeChance => null
Describes the chance of this rarity downgrading to the previous tier If null, is the same as 0f (no chance)
virtual float ExtraLuck => 0f
virtual float ExtraMagnitudePower => 0f
virtual string ItemPrefix => null
virtual string ItemSuffix => null
string Name => GetType().Name
virtual Color OverrideNameColor => null
virtual string RarityName => Name
virtual Type Upgrade => null
virtual float UpgradeChance => null
Describes the chance of this rarity upgrading to the next tier If null, is the same as 0f (no chance)
Properties
abstract Color Color [get]
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Api.Content.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Private Attributes
const int SAVE_VERSION = 2
Detailed Description
Defines the rarity of a modifier
Definition at line 15 of file ModifierRarity.cs.
Member Function Documentation
virtual void Loot.Api.Modifier.ModifierRarity.Clone (ref ModifierRarity clone) virtual
Definition at line 59 of file ModifierRarity.cs.
Referenced by Loot.Api.Ext.ModUtils.GetModifierRarity().
         {
         }
object Loot.Api.Modifier.ModifierRarity.Clone ()
Definition at line 63 of file ModifierRarity.cs.
References Loot.Api.Modifier.ModifierRarity.Mod, and Loot.Api.Modifier.ModifierRarity.Type.
         {
             ModifierRarity clone = (ModifierRarity)MemberwiseClone();
             clone.Mod = Mod;
             clone.Type = Type;
             Clone(ref clone);
             return clone;
         }
virtual void Loot.Api.Modifier.ModifierRarity.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Definition at line 115 of file ModifierRarity.cs.
References Loot.Api.Modifier.ModifierRarity.Load(), and Loot.Api.Loaders.ContentLoader.ModifierRarity.
Referenced by Loot.Api.Modifier.ModifierRarity.Load().
         {
         }
virtual void Loot.Api.Modifier.ModifierRarity.NetReceive (Item item, BinaryReader reader) virtual
Allows the modder to do custom NetReceive
Parameters
item
reader
Definition at line 77 of file ModifierRarity.cs.
References Loot.Api.Loaders.ContentLoader.ModifierRarity, and Loot.Api.Modifier.ModifierRarity.NetReceive().
Referenced by Loot.Api.Modifier.ModifierRarity.NetReceive().
         {
         }
virtual void Loot.Api.Modifier.ModifierRarity.NetSend (Item item, BinaryWriter writer) virtual
Allows modder to do custom NetSend here
Parameters
item
writer
Definition at line 101 of file ModifierRarity.cs.
References Loot.Api.Modifier.ModifierRarity.Mod, and Loot.Api.Modifier.ModifierRarity.Name.
         {
         }
virtual void Loot.Api.Modifier.ModifierRarity.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Definition at line 171 of file ModifierRarity.cs.
References Loot.Api.Modifier.ModifierRarity.Mod, Loot.Api.Modifier.ModifierRarity.Name, and Loot.Api.Modifier.ModifierRarity.Save().
Referenced by Loot.Api.Modifier.ModifierRarity.Save(), and Loot.LootModItem.Save().
         {
         }
Member Data Documentation
virtual Type Loot.Api.Modifier.ModifierRarity.Downgrade => null
Definition at line 54 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.RollNewPool().
virtual float Loot.Api.Modifier.ModifierRarity.DowngradeChance => null
Describes the chance of this rarity downgrading to the previous tier If null, is the same as 0f (no chance)
Definition at line 50 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.RollNewPool().
virtual float Loot.Api.Modifier.ModifierRarity.ExtraLuck => 0f
Definition at line 53 of file ModifierRarity.cs.
Referenced by Loot.RollingStrategies.NormalRollingStrategy.Roll().
virtual float Loot.Api.Modifier.ModifierRarity.ExtraMagnitudePower => 0f
Definition at line 52 of file ModifierRarity.cs.
Referenced by Loot.RollingStrategies.NormalRollingStrategy.Roll().
virtual string Loot.Api.Modifier.ModifierRarity.ItemPrefix => null
Definition at line 37 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.ModifyTooltips().
virtual string Loot.Api.Modifier.ModifierRarity.ItemSuffix => null
Definition at line 38 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.ModifyTooltips().
string Loot.Api.Modifier.ModifierRarity.Name => GetType().Name
Definition at line 33 of file ModifierRarity.cs.
Referenced by Loot.Api.Modifier.ModifierRarity.NetSend(), and Loot.Api.Modifier.ModifierRarity.Save().
virtual Color Loot.Api.Modifier.ModifierRarity.OverrideNameColor => null
Definition at line 36 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.ModifyTooltips().
virtual string Loot.Api.Modifier.ModifierRarity.RarityName => Name
Definition at line 35 of file ModifierRarity.cs.
const int Loot.Api.Modifier.ModifierRarity.SAVE_VERSION = 2 private
Definition at line 17 of file ModifierRarity.cs.
virtual Type Loot.Api.Modifier.ModifierRarity.Upgrade => null
Definition at line 55 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.RollNewPool().
virtual float Loot.Api.Modifier.ModifierRarity.UpgradeChance => null
Describes the chance of this rarity upgrading to the next tier If null, is the same as 0f (no chance)
Definition at line 44 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.RollNewPool().
Property Documentation
abstract Color Loot.Api.Modifier.ModifierRarity.Color get
Definition at line 57 of file ModifierRarity.cs.
Referenced by Loot.LootModItem.ModifyTooltips().
Mod Loot.Api.Modifier.ModifierRarity.Mod get set
Definition at line 19 of file ModifierRarity.cs.
Referenced by Loot.Api.Modifier.ModifierRarity.Clone(), Loot.Api.Modifier.ModifierRarity.NetSend(), and Loot.Api.Modifier.ModifierRarity.Save().
Mod ILoadableContentSetter. Loot.Api.Modifier.ModifierRarity.Mod set private
Definition at line 22 of file ModifierRarity.cs.
uint Loot.Api.Modifier.ModifierRarity.Type get set
Definition at line 26 of file ModifierRarity.cs.
Referenced by Loot.Api.Modifier.ModifierRarity.Clone(), and Loot.LootModItem.RollNewPool().
uint ILoadableContentSetter. Loot.Api.Modifier.ModifierRarity.Type set private
Definition at line 29 of file ModifierRarity.cs.