Even More Modifiers: Loot.EMMLoader Class Reference
Loot.EMMLoader Class Reference
The loader, handles all loading
Static Public Member Functions
static void AddModifier (Modifier modifier, Mod mod)
Adds a Modifier
static void AddModifierEffect (ModifierEffect effect, Mod mod)
Adds a ModifierEffect
static void AddModifierPool (ModifierPool pool, Mod mod)
Adds a ModifierPool
static void AddModifierRarity (ModifierRarity rarity, Mod mod)
Adds a rarity
static Modifier GetModifier (uint type)
Returns the ModifierEffect specified by type, null if not present
static Modifier GetModifier (string modname, string poolTypeName)
static Modifier GetModifier (Type type)
static ModifierEffect GetModifierEffect (uint type)
Returns the ModifierEffect specified by type, null if not present
static ModifierEffect GetModifierEffect (string modname, string effectTypeName)
static ModifierEffect GetModifierEffect (Type type)
static ModifierPool GetModifierPool (uint type)
Returns the Modifier specified by type, null if not present
static ModifierPool GetModifierPool (string modname, string poolTypeName)
static ModifierPool GetModifierPool (Type type)
static ModifierRarity GetModifierRarity (uint type)
Returns the ModifierRarity specified by type, null if not present
static ModifierRarity GetModifierRarity (string modname, string rarityTypeName)
static ModifierRarity GetModifierRarity (Type type)
static void RegisterAssets (Mod mod, string folder, bool clearOwnTextures=true)
static void RegisterMod (Mod mod)
Registers specified mod, enabling autoloading for that mod
static IReadOnlyCollection< ModifierEffect > RequestModifierEffects ()
Requests all ModifierEffects, and returns them as a readonly collection
static IReadOnlyCollection< ModifierPool > RequestModifierPools ()
Requests all ModifierPools, and returns them as a readonly collection
static IReadOnlyCollection< ModifierRarity > RequestModifierRarities ()
Requests all ModifierRarities, and returns them as a readonly collection
static IReadOnlyCollection< Modifier > RequestModifiers ()
Requests all Modifiers, and returns them as a readonly collection
static void SetupContent (Mod mod)
Sets up content for the specified mod
Static Private Member Functions
static Modifier _GetModifier (string modname, string modifierTypeName)
static ModifierEffect _GetModifierEffect (string modname, string effectTypeName)
static ModifierPool _GetModifierPool (string modname, string poolTypeName)
static ModifierRarity _GetModifierRarity (string modname, string rarityTypeName)
static void AutoloadModifier (Type type, Mod mod)
Autoloads a Modifier
static void AutoloadModifierEffect (Type type, Mod mod)
Autoloads a ModifierEffect
static void AutoloadModifierPool (Type type, Mod mod)
Autoloads a ModifierPool
static void AutoloadModifierRarity (Type type, Mod mod)
Autoloads a rarity
static ModifierEffect GetNewEffectInstance (ModifierEffect effect)
static Modifier GetNewModifierInstance (Modifier modifier)
static ModifierPool GetNewPoolInstance (ModifierPool pool)
static ModifierRarity GetNewRarityInstance (ModifierRarity rarity)
Static Private Attributes
static uint effectNextID
static uint modifierNextID
static uint poolNextID
static uint rarityNextID
Detailed Description
The loader, handles all loading
Definition at line 23 of file EMMLoader.cs.
Member Function Documentation
static Modifier Loot.EMMLoader._GetModifier (string modname, string modifierTypeName) static private
Definition at line 671 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.GetModifier().
         {
             return ModifiersMap[modname].FirstOrDefault(x => x.Key.Equals(modifierTypeName)).Value;
         }
static ModifierEffect Loot.EMMLoader._GetModifierEffect (string modname, string effectTypeName) static private
Definition at line 681 of file EMMLoader.cs.
References Loot.EMMLoader.RequestModifierEffects(), Loot.EMMLoader.RequestModifierPools(), Loot.EMMLoader.RequestModifierRarities(), and Loot.EMMLoader.RequestModifiers().
Referenced by Loot.EMMLoader.GetModifierEffect().
         {
             return EffectsMap[modname].FirstOrDefault(x => x.Key.Equals(effectTypeName)).Value;
         }
static ModifierPool Loot.EMMLoader._GetModifierPool (string modname, string poolTypeName) static private
Definition at line 666 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.GetModifierPool().
         {
             return PoolsMap[modname].FirstOrDefault(x => x.Key.Equals(poolTypeName)).Value;
         }
static ModifierRarity Loot.EMMLoader._GetModifierRarity (string modname, string rarityTypeName) static private
Definition at line 676 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.GetModifierRarity().
         {
             return RaritiesMap[modname].FirstOrDefault(x => x.Key.Equals(rarityTypeName)).Value;
         }
static void Loot.EMMLoader.AddModifier (Modifier modifier, Mod mod) static
Adds a Modifier
Definition at line 449 of file EMMLoader.cs.
References Loot.Core.Modifier.Mod, Loot.Core.Modifier.Name, and Loot.Core.Modifier.Type.
Referenced by Loot.EMMLoader.AutoloadModifier().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("AddModifier can only be called from Mod.Load or Mod.Autoload");
             }
             List<ModifierMap> lem;
             if (!ModifiersMap.TryGetValue(mod.Name, out lem))
             {
                 throw new Exception($"ModifierMaps for {mod.Name} not found");
             }
             if (lem.Exists(x => x.Value.Name.Equals(modifier.Name)))
             {
                 throw new Exception($"You have already added a modifier with the name {modifier.Name}");
             }
             modifier.Mod = mod;
             modifier.Type = ReserveModifierID();
             Modifiers[modifier.Type] = modifier;
             ModifiersMap[mod.Name].Add(new ModifierMap(modifier.Name, modifier));
         }
static void Loot.EMMLoader.AddModifierEffect (ModifierEffect effect, Mod mod) static
Adds a ModifierEffect
Definition at line 486 of file EMMLoader.cs.
References Loot.Core.ModifierEffect.Mod, and Loot.Core.ModifierEffect.Name.
Referenced by Loot.EMMLoader.AutoloadModifierEffect().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("AddModifierEffect can only be called from Mod.Load or Mod.Autoload");
             }
             List<EffectMap> lem;
             if (!EffectsMap.TryGetValue(mod.Name, out lem))
             {
                 throw new Exception($"EffectsMap for {mod.Name} not found");
             }
             if (lem.Exists(x => x.Value.Name.Equals(effect.Name)))
             {
                 throw new Exception($"You have already added a modifier with the name {effect.Name}");
             }
             //verbose GetCustomAttributes call
             //because we call the constructor, it will throw our
             //validation exceptions on load instead on entering world
             var attributes = effect
                 .GetType()
                 .GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance)
                 // ReSharper disable once ReturnValueOfPureMethodIsNotUsed
                 .Select(x => x.GetCustomAttributes(false).OfType<DelegationPrioritizationAttribute>());
             foreach (var attribute in attributes.SelectMany(x => x))
             {
                 Activator.CreateInstance(attribute.GetType(), attribute.DelegationPrioritization, attribute.DelegationLevel);
             }
             effect.Mod = mod;
             effect.Type = ReserveEffectID();
             Effects[effect.Type] = effect;
             EffectsMap[mod.Name].Add(new EffectMap(effect.Name, effect));
         }
static void Loot.EMMLoader.AddModifierPool (ModifierPool pool, Mod mod) static
Adds a ModifierPool
Definition at line 367 of file EMMLoader.cs.
References Loot.Core.ModifierPool.Mod, Loot.Core.ModifierPool.Name, and Loot.Core.ModifierPool.Type.
Referenced by Loot.EMMLoader.AutoloadModifierPool().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("AddModifierPool can only be called from Mod.Load or Mod.Autoload");
             }
             if (!Mods.ContainsKey(mod.Name))
             {
                 throw new Exception($"Mod {mod.Name} is not registered, please register before adding");
             }
             List<PoolMap> lmm;
             if (!PoolsMap.TryGetValue(mod.Name, out lmm))
             {
                 throw new Exception($"PoolMaps for {mod.Name} not found");
             }
             if (lmm.Exists(x => x.Value.Name.Equals(pool.Name)))
             {
                 throw new Exception($"You have already added a ModifierPool with the name {pool.Name}");
             }
             pool.Mod = mod;
             pool.Type = ReservePoolID();
             Pools[pool.Type] = pool;
             PoolsMap[mod.Name].Add(new PoolMap(pool.Name, pool));
         }
static void Loot.EMMLoader.AddModifierRarity (ModifierRarity rarity, Mod mod) static
Adds a rarity
Definition at line 408 of file EMMLoader.cs.
References Loot.Core.ModifierRarity.Mod, Loot.Core.ModifierRarity.Name, and Loot.Core.ModifierRarity.Type.
Referenced by Loot.EMMLoader.AutoloadModifierRarity().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("AddRarity can only be called from Mod.Load or Mod.Autoload");
             }
             if (!Mods.ContainsKey(mod.Name))
             {
                 throw new Exception($"Mod {mod.Name} is not registered, please register before adding");
             }
             List<RarityMap> lrm;
             if (!RaritiesMap.TryGetValue(mod.Name, out lrm))
             {
                 throw new Exception($"RarityMaps for {mod.Name} not found");
             }
             if (lrm.Exists(x => x.Value.Name.Equals(rarity.Name)))
             {
                 throw new Exception($"You have already added a rarity with the name {rarity.Name}");
             }
             rarity.Mod = mod;
             rarity.Type = ReserveRarityID();
             Rarities[rarity.Type] = rarity;
             RaritiesMap[mod.Name].Add(new RarityMap(rarity.Name, rarity));
         }
static void Loot.EMMLoader.AutoloadModifier (Type type, Mod mod) static private
Autoloads a Modifier
Definition at line 440 of file EMMLoader.cs.
References Loot.EMMLoader.AddModifier().
Referenced by Loot.EMMLoader.SetupContent().
         {
             Modifier modifier = (Modifier)Activator.CreateInstance(type);
             AddModifier(modifier, mod);
         }
static void Loot.EMMLoader.AutoloadModifierEffect (Type type, Mod mod) static private
Autoloads a ModifierEffect
Definition at line 477 of file EMMLoader.cs.
References Loot.EMMLoader.AddModifierEffect().
Referenced by Loot.EMMLoader.SetupContent().
         {
             ModifierEffect effect = (ModifierEffect)Activator.CreateInstance(type);
             AddModifierEffect(effect, mod);
         }
static void Loot.EMMLoader.AutoloadModifierPool (Type type, Mod mod) static private
Autoloads a ModifierPool
Definition at line 358 of file EMMLoader.cs.
References Loot.EMMLoader.AddModifierPool().
Referenced by Loot.EMMLoader.SetupContent().
         {
             ModifierPool modifierPool = (ModifierPool)Activator.CreateInstance(type);
             AddModifierPool(modifierPool, mod);
         }
static void Loot.EMMLoader.AutoloadModifierRarity (Type type, Mod mod) static private
Autoloads a rarity
Definition at line 399 of file EMMLoader.cs.
References Loot.EMMLoader.AddModifierRarity().
Referenced by Loot.EMMLoader.SetupContent().
         {
             ModifierRarity rarity = (ModifierRarity)Activator.CreateInstance(type);
             AddModifierRarity(rarity, mod);
         }
static Modifier Loot.EMMLoader.GetModifier (uint type) static
Returns the ModifierEffect specified by type, null if not present
Definition at line 278 of file EMMLoader.cs.
Referenced by Loot.Core.Modifier.Load(), and Loot.Core.ModifierPool.ModifierPool().
         {
             return type < modifierNextID ? (Modifier)Modifiers[type].Clone() : null;
         }
static Modifier Loot.EMMLoader.GetModifier (string modname, string poolTypeName) static
Definition at line 605 of file EMMLoader.cs.
References Loot.EMMLoader._GetModifier(), and Loot.EMMLoader.GetNewModifierInstance().
         {
             var modifier = _GetModifier(modname, poolTypeName);
             return GetNewModifierInstance(modifier);
         }
static Modifier Loot.EMMLoader.GetModifier (Type type) static
Definition at line 611 of file EMMLoader.cs.
References Loot.EMMLoader.GetNewModifierInstance().
         {
             var pool = Modifiers.Values.FirstOrDefault(x => x.GetType().FullName == type.FullName);
             return GetNewModifierInstance(pool);
         }
static ModifierEffect Loot.EMMLoader.GetModifierEffect (uint type) static
Returns the ModifierEffect specified by type, null if not present
Definition at line 294 of file EMMLoader.cs.
Referenced by Loot.Core.ModifierEffect.Clone().
         {
             return type < effectNextID ? (ModifierEffect)Effects[type].Clone() : null;
         }
static ModifierEffect Loot.EMMLoader.GetModifierEffect (string modname, string effectTypeName) static
Definition at line 654 of file EMMLoader.cs.
References Loot.EMMLoader._GetModifierEffect(), and Loot.EMMLoader.GetNewEffectInstance().
         {
             var effect = _GetModifierEffect(modname, effectTypeName);
             return GetNewEffectInstance(effect);
         }
static ModifierEffect Loot.EMMLoader.GetModifierEffect (Type type) static
Definition at line 660 of file EMMLoader.cs.
References Loot.EMMLoader.GetNewEffectInstance().
         {
             var effect = Effects.Values.FirstOrDefault(x => x.GetType().FullName == type.FullName);
             return GetNewEffectInstance(effect);
         }
static ModifierPool Loot.EMMLoader.GetModifierPool (uint type) static
Returns the Modifier specified by type, null if not present
Definition at line 286 of file EMMLoader.cs.
Referenced by Loot.Core.ModifierPool.Load().
         {
             return type < poolNextID ? (ModifierPool)Pools[type].Clone() : null;
         }
static ModifierPool Loot.EMMLoader.GetModifierPool (string modname, string poolTypeName) static
Definition at line 581 of file EMMLoader.cs.
References Loot.EMMLoader._GetModifierPool(), and Loot.EMMLoader.GetNewPoolInstance().
         {
             var pool = _GetModifierPool(modname, poolTypeName);
             return GetNewPoolInstance(pool);
         }
static ModifierPool Loot.EMMLoader.GetModifierPool (Type type) static
Definition at line 587 of file EMMLoader.cs.
References Loot.EMMLoader.GetNewPoolInstance().
         {
             var pool = Pools.Values.FirstOrDefault(x => x.GetType().FullName == type.FullName);
             return GetNewPoolInstance(pool);
         }
static ModifierRarity Loot.EMMLoader.GetModifierRarity (uint type) static
Returns the ModifierRarity specified by type, null if not present
Definition at line 270 of file EMMLoader.cs.
Referenced by Loot.Core.ModifierRarity.Load().
         {
             return type < rarityNextID ? (ModifierRarity)Rarities[type].Clone() : null;
         }
static ModifierRarity Loot.EMMLoader.GetModifierRarity (string modname, string rarityTypeName) static
Definition at line 630 of file EMMLoader.cs.
References Loot.EMMLoader._GetModifierRarity(), and Loot.EMMLoader.GetNewRarityInstance().
         {
             var rarity = _GetModifierRarity(modname, rarityTypeName);
             return GetNewRarityInstance(rarity);
         }
static ModifierRarity Loot.EMMLoader.GetModifierRarity (Type type) static
Definition at line 636 of file EMMLoader.cs.
References Loot.EMMLoader.GetNewRarityInstance().
         {
             var rarity = Rarities.Values.FirstOrDefault(x => x.GetType().FullName == type.FullName);
             return GetNewRarityInstance(rarity);
         }
static ModifierEffect Loot.EMMLoader.GetNewEffectInstance (ModifierEffect effect) static private
Definition at line 642 of file EMMLoader.cs.
References Loot.Core.ModifierEffect.Mod, and Loot.Core.ModifierEffect.Type.
Referenced by Loot.EMMLoader.GetModifierEffect().
         {
             var instance = effect;
             if (effect != null)
             {
                 instance = (ModifierEffect)Activator.CreateInstance(effect.GetType());
                 instance.Type = effect.Type;
                 instance.Mod = effect.Mod;
             }
             return instance;
         }
static Modifier Loot.EMMLoader.GetNewModifierInstance (Modifier modifier) static private
Definition at line 593 of file EMMLoader.cs.
References Loot.Core.Modifier.Mod, and Loot.Core.Modifier.Type.
Referenced by Loot.EMMLoader.GetModifier().
         {
             var instance = modifier;
             if (modifier != null)
             {
                 instance = (Modifier)Activator.CreateInstance(modifier.GetType());
                 instance.Type = modifier.Type;
                 instance.Mod = modifier.Mod;
             }
             return instance;
         }
static ModifierPool Loot.EMMLoader.GetNewPoolInstance (ModifierPool pool) static private
Definition at line 569 of file EMMLoader.cs.
References Loot.Core.ModifierPool.Mod, and Loot.Core.ModifierPool.Type.
Referenced by Loot.EMMLoader.GetModifierPool().
         {
             var instance = pool;
             if (pool != null)
             {
                 instance = (ModifierPool)Activator.CreateInstance(pool.GetType());
                 instance.Type = pool.Type;
                 instance.Mod = pool.Mod;
             }
             return instance;
         }
static ModifierRarity Loot.EMMLoader.GetNewRarityInstance (ModifierRarity rarity) static private
Definition at line 617 of file EMMLoader.cs.
References Loot.Core.ModifierRarity.Mod, and Loot.Core.ModifierRarity.Type.
Referenced by Loot.EMMLoader.GetModifierRarity().
         {
             var instance = rarity;
             if (rarity != null)
             {
                 instance = (ModifierRarity)Activator.CreateInstance(rarity.GetType());
                 instance.Type = rarity.Type;
                 instance.Mod = rarity.Mod;
             }
             return instance;
         }
static void Loot.EMMLoader.RegisterAssets (Mod mod, string folder, bool clearOwnTextures = true) static
Definition at line 128 of file EMMLoader.cs.
References Loot.Core.ModifierPool.Clone(), Loot.EMMLoader.effectNextID, Loot.EMMLoader.modifierNextID, Loot.EMMLoader.poolNextID, and Loot.EMMLoader.rarityNextID.
Referenced by Loot.Loot.Load().
         {
             if (mod == null)
             {
                 throw new NullReferenceException("Mod is null in RegisterAssets");
             }
             if (Loot.ContentManager == null)
             {
                 throw new NullReferenceException("Loot.ContentManager is null in RegisterAssets");
             }
             var graphicsContent = Loot.ContentManager.GetContent<ModGraphicsContent>();
             if (graphicsContent == null)
             {
                 throw new NullReferenceException("ModGraphicsContent is null in RegisterAssets");
             }
             if (folder.StartsWith($"{mod.Name}/"))
             {
                 folder = folder.Replace($"{mod.Name}/", "");
             }
             string keyPass = $"{mod.Name}/{folder}";
             graphicsContent.AddKeyPass(mod.Name, keyPass);
             FieldInfo texturesField = typeof(Mod).GetField("textures", BindingFlags.Instance | BindingFlags.NonPublic);
             Dictionary<string, Texture2D> dictionary = ((Dictionary<string, Texture2D>)texturesField?.GetValue(mod));
             if (dictionary == null)
             {
                 throw new NullReferenceException($"textures dictionary for mod {mod.Name} was null");
             }
             var textures = dictionary.Where(x => x.Key.StartsWith(folder)).ToList();
             var glowmasks = textures.Where(x => x.Key.EndsWith("_Glowmask") || x.Key.EndsWith("_Glow")).ToList();
             var shaders = textures.Where(x => x.Key.EndsWith("_Shader") || x.Key.EndsWith("_Shad")).ToList();
             foreach (var kvp in glowmasks)
             {
                 string assetKey = graphicsContent.GetAssetKey(kvp.Value.Name, mod);
                 if (assetKey == null) continue;
                 if (graphicsContent.AnyGlowmaskAssetExists(assetKey, mod))
                 {
                     throw new Exception($"{mod.Name} attempted to add a glowmask asset already present: {assetKey}");
                 }
                 graphicsContent.AddGlowmaskTexture(assetKey, kvp.Value);
                 if (clearOwnTextures)
                 {
                     dictionary.Remove(kvp.Key);
                 }
             }
             foreach (var kvp in shaders)
             {
                 string assetKey = graphicsContent.GetAssetKey(kvp.Value.Name, mod);
                 if (assetKey == null) continue;
                 if (graphicsContent.AnyShaderAssetExists(assetKey, mod))
                 {
                     throw new Exception($"{mod.Name} attempted to add a shader asset already present: {assetKey}");
                 }
                 graphicsContent.AddShaderTexture(assetKey, kvp.Value);
                 if (clearOwnTextures)
                 {
                     dictionary.Remove(kvp.Key);
                 }
             }
             // sanity check
             graphicsContent.Prepare(mod);
             graphicsContent.ClearPreparation();
         }
static void Loot.EMMLoader.RegisterMod (Mod mod) static
Registers specified mod, enabling autoloading for that mod
Definition at line 100 of file EMMLoader.cs.
Referenced by Loot.Loot.Load(), and LootTests.UnitTests.LogEMMLoaderEntries().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("RegisterMod can only be called from Mod.Load or Mod.Autoload");
             }
             if (Mods.ContainsKey(mod.Name))
             {
                 throw new Exception($"Mod {mod.Name} is already registered");
             }
             Assembly code;
 #if DEBUG
             code = Assembly.GetAssembly(mod.GetType());
 #else
             code = mod.Code;
 #endif
             Mods.Add(new KeyValuePair<string, Assembly>(mod.Name, code));
             RaritiesMap.Add(new KeyValuePair<string, List<RarityMap>>(mod.Name, new List<RarityMap>()));
             ModifiersMap.Add(new KeyValuePair<string, List<ModifierMap>>(mod.Name, new List<ModifierMap>()));
             PoolsMap.Add(new KeyValuePair<string, List<PoolMap>>(mod.Name, new List<PoolMap>()));
             EffectsMap.Add(new KeyValuePair<string, List<EffectMap>>(mod.Name, new List<EffectMap>()));
             //          GlobalModifiersMap.Add(new KeyValuePair<string, List<GlobalModifierMap>>(mod.Name, new List<GlobalModifierMap>()));
         }
static IReadOnlyCollection<ModifierEffect> Loot.EMMLoader.RequestModifierEffects () static
Requests all ModifierEffects, and returns them as a readonly collection
Returns
Referenced by Loot.EMMLoader._GetModifierEffect().
static IReadOnlyCollection<ModifierPool> Loot.EMMLoader.RequestModifierPools () static
Requests all ModifierPools, and returns them as a readonly collection
Returns
Referenced by Loot.EMMLoader._GetModifierEffect(), and LootTests.UnitTests.LogEMMLoaderEntries().
static IReadOnlyCollection<ModifierRarity> Loot.EMMLoader.RequestModifierRarities () static
Requests all ModifierRarities, and returns them as a readonly collection
Returns
Referenced by Loot.EMMLoader._GetModifierEffect(), and LootTests.UnitTests.LogEMMLoaderEntries().
static IReadOnlyCollection<Modifier> Loot.EMMLoader.RequestModifiers () static
Requests all Modifiers, and returns them as a readonly collection
Returns
Referenced by Loot.EMMLoader._GetModifierEffect(), and LootTests.UnitTests.LogEMMLoaderEntries().
static void Loot.EMMLoader.SetupContent (Mod mod) static
Sets up content for the specified mod
Definition at line 302 of file EMMLoader.cs.
References Loot.EMMLoader.AutoloadModifier(), Loot.EMMLoader.AutoloadModifierEffect(), Loot.EMMLoader.AutoloadModifierPool(), and Loot.EMMLoader.AutoloadModifierRarity().
Referenced by Loot.Loot.Load(), and LootTests.UnitTests.LogEMMLoaderEntries().
         {
             bool? b = mod.GetType().GetField("loading", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(mod) as bool?;
             if (b != null && !b.Value)
             {
                 throw new Exception("SetupContent for EMMLoader can only be called from Mod.Load or Mod.Autoload");
             }
             if (!Mods.ContainsKey(mod.Name))
             {
                 throw new Exception($"Mod {mod.Name} is not yet registered in EMMLoader");
             }
             var ordered = Mods.FirstOrDefault(x => x.Key.Equals(mod.Name))
                 .Value
                 .GetTypes()
                 .OrderBy(x => x.FullName, StringComparer.InvariantCulture)
                 .Where(t => t.IsClass && !t.IsAbstract)
                 .ToList(); /* || type.GetConstructor(new Type[0]) == null*/
             var rarities = ordered.Where(x => x.IsSubclassOf(typeof(ModifierRarity)));
             var modifiers = ordered.Where(x => x.IsSubclassOf(typeof(Modifier)));
             var pools = ordered.Where(x => x.IsSubclassOf(typeof(ModifierPool)));
             var effects = ordered.Where(x => x.IsSubclassOf(typeof(ModifierEffect)));
             //          var globalModifiers = ordered.Where(x => x.IsSubclassOf(typeof(GlobalModifier)));
             // important: load things in order. (modifiers relies on all.. etc.)
             foreach (Type type in rarities)
             {
                 AutoloadModifierRarity(type, mod);
             }
             foreach (Type type in modifiers)
             {
                 AutoloadModifier(type, mod);
             }
             foreach (Type type in pools)
             {
                 AutoloadModifierPool(type, mod);
             }
             foreach (Type effect in effects)
             {
                 AutoloadModifierEffect(effect, mod);
             }
             //          foreach (Type type in globalModifiers)
             //          {
             //              AutoloadGlobalModifier(type, mod);
             //          }
         }
Member Data Documentation
uint Loot.EMMLoader.effectNextID static private
Definition at line 28 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.RegisterAssets().
uint Loot.EMMLoader.modifierNextID static private
Definition at line 26 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.RegisterAssets().
uint Loot.EMMLoader.poolNextID static private
Definition at line 27 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.RegisterAssets().
uint Loot.EMMLoader.rarityNextID static private
Definition at line 25 of file EMMLoader.cs.
Referenced by Loot.EMMLoader.RegisterAssets().