Even More Modifiers: Loot.ModifierProjectile Class Reference
Loot.ModifierProjectile Class Reference
Public Member Functions
override GlobalProjectile Clone ()
ModifierProjectile GetInfo (Projectile projectile, Mod givenMod=null)
override void ModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
override void ModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit)
override void ModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit)
override void OnHitNPC (Projectile projectile, NPC target, int damage, float knockback, bool crit)
override void OnHitPlayer (Projectile projectile, Player target, int damage, bool crit)
override void OnHitPvp (Projectile projectile, Player target, int damage, bool crit)
override bool PreAI (Projectile projectile)
Public Attributes
override bool CloneNewInstances => true
bool FirstTick
override bool InstancePerEntity => true
bool NeedsClear
float SnapshotCritMulti = 1f
List<(int type, int time, float chance)> SnapshotDebuffChances = new List<(int type, int time, float chance)>()
float SnapshotHealthyFoesMulti = 1f
Private Member Functions
void AttemptDebuff (Projectile projectile, Player target)
void AttemptDebuff (Projectile projectile, NPC target)
void CritBonus (Projectile projectile, ref int damage, bool crit)
void HealthyBonus (Projectile projectile, ref int damage, NPC target)
void HealthyBonus (Projectile projectile, ref int damage, Player target)
Detailed Description
Definition at line 11 of file ModifierProjectile.cs.
Member Function Documentation
void Loot.ModifierProjectile.AttemptDebuff (Projectile projectile, Player target) private
Definition at line 34 of file ModifierProjectile.cs.
Referenced by Loot.ModifierProjectile.OnHitNPC(), Loot.ModifierProjectile.OnHitPlayer(), and Loot.ModifierProjectile.OnHitPvp().
         {
             foreach (var x in SnapshotDebuffChances)
             {
                 if (Main.rand.NextFloat() < x.chance)
                 {
                     target.AddBuff(x.type, x.time);
                 }
             }
         }
void Loot.ModifierProjectile.AttemptDebuff (Projectile projectile, NPC target) private
Definition at line 45 of file ModifierProjectile.cs.
         {
             foreach (var x in SnapshotDebuffChances)
             {
                 if (Main.rand.NextFloat() < x.chance)
                 {
                     target.AddBuff(x.type, x.time);
                 }
             }
         }
override GlobalProjectile Loot.ModifierProjectile.Clone ()
Definition at line 16 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.GetInfo(), and Loot.ModifierProjectile.SnapshotDebuffChances.
         {
             var clone = (ModifierProjectile) MemberwiseClone();
             clone.SnapshotDebuffChances = new List<(int type, int time, float chance)>(SnapshotDebuffChances);
             return clone;
         }
void Loot.ModifierProjectile.CritBonus (Projectile projectile, ref int damage, bool crit) private
Definition at line 72 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.GetInfo().
Referenced by Loot.ModifierProjectile.ModifyHitNPC(), Loot.ModifierProjectile.ModifyHitPlayer(), and Loot.ModifierProjectile.ModifyHitPvp().
         {
             if (crit)
             {
                 damage = (int) Math.Ceiling(damage * GetInfo(projectile).SnapshotCritMulti);
             }
         }
ModifierProjectile Loot.ModifierProjectile.GetInfo (Projectile projectile, Mod givenMod = null)
Referenced by Loot.ModifierProjectile.Clone(), Loot.ModifierProjectile.CritBonus(), and Loot.ModifierProjectile.PreAI().
void Loot.ModifierProjectile.HealthyBonus (Projectile projectile, ref int damage, NPC target) private
Definition at line 56 of file ModifierProjectile.cs.
Referenced by Loot.ModifierProjectile.ModifyHitNPC(), Loot.ModifierProjectile.ModifyHitPlayer(), and Loot.ModifierProjectile.ModifyHitPvp().
         {
             if (target.life == target.lifeMax)
             {
                 damage = (int) Math.Ceiling(damage * SnapshotHealthyFoesMulti);
             }
         }
void Loot.ModifierProjectile.HealthyBonus (Projectile projectile, ref int damage, Player target) private
Definition at line 64 of file ModifierProjectile.cs.
         {
             if (target.statLife == target.statLifeMax2)
             {
                 damage = (int) Math.Ceiling(damage * SnapshotHealthyFoesMulti);
             }
         }
override void Loot.ModifierProjectile.ModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
Definition at line 116 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.CritBonus(), and Loot.ModifierProjectile.HealthyBonus().
         {
             HealthyBonus(projectile, ref damage, target);
             CritBonus(projectile, ref damage, crit);
             base.ModifyHitNPC(projectile, target, ref damage, ref knockback, ref crit, ref hitDirection);
         }
override void Loot.ModifierProjectile.ModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit)
Definition at line 124 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.CritBonus(), and Loot.ModifierProjectile.HealthyBonus().
         {
             HealthyBonus(projectile, ref damage, target);
             CritBonus(projectile, ref damage, crit);
             base.ModifyHitPlayer(projectile, target, ref damage, ref crit);
         }
override void Loot.ModifierProjectile.ModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit)
Definition at line 131 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.CritBonus(), and Loot.ModifierProjectile.HealthyBonus().
         {
             HealthyBonus(projectile, ref damage, target);
             CritBonus(projectile, ref damage, crit);
             base.ModifyHitPvp(projectile, target, ref damage, ref crit);
         }
override void Loot.ModifierProjectile.OnHitNPC (Projectile projectile, NPC target, int damage, float knockback, bool crit)
Definition at line 138 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.AttemptDebuff().
         {
             AttemptDebuff(projectile, target);
             base.OnHitNPC(projectile, target, damage, knockback, crit);
         }
override void Loot.ModifierProjectile.OnHitPlayer (Projectile projectile, Player target, int damage, bool crit)
Definition at line 144 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.AttemptDebuff().
         {
             AttemptDebuff(projectile, target);
             base.OnHitPlayer(projectile, target, damage, crit);
         }
override void Loot.ModifierProjectile.OnHitPvp (Projectile projectile, Player target, int damage, bool crit)
Definition at line 150 of file ModifierProjectile.cs.
References Loot.ModifierProjectile.AttemptDebuff().
         {
             AttemptDebuff(projectile, target);
             base.OnHitPvp(projectile, target, damage, crit);
         }
override bool Loot.ModifierProjectile.PreAI (Projectile projectile)
Definition at line 80 of file ModifierProjectile.cs.
References Loot.ModifierPlayer.GetEffect(), and Loot.ModifierProjectile.GetInfo().
         {
             var mproj = GetInfo(projectile);
             // On first tick, copy over player stats
             if (!mproj.FirstTick)
             {
                 mproj.FirstTick = true;
                 // Snapshot current player values
                 if (projectile.owner != 255 && projectile.friendly && projectile.owner == Main.myPlayer)
                 {
                     var mplr = Main.LocalPlayer.GetModPlayer<ModifierPlayer>();
                     mproj.SnapshotDebuffChances = mplr.GetEffect<WeaponDebuffEffect>().DebuffChances.ToList();
                     mproj.SnapshotHealthyFoesMulti = mplr.GetEffect<HealthyFoesEffect>().Multiplier;
                     if (!projectile.minion) // minions do not crit
                     {
                         mproj.SnapshotCritMulti = mplr.GetEffect<CritDamagePlusEffect>().Multiplier;
                     }
                 }
                 else if (projectile.owner == 255)
                 {
                     // TODO snapshot npc values. possible?
                 }
             }
             if (NeedsClear)
             {
                 mproj.SnapshotHealthyFoesMulti = 1f;
                 mproj.SnapshotDebuffChances.Clear();
             }
             return base.PreAI(projectile);
         }
Member Data Documentation
override bool Loot.ModifierProjectile.CloneNewInstances => true
Definition at line 14 of file ModifierProjectile.cs.
bool Loot.ModifierProjectile.FirstTick
Definition at line 29 of file ModifierProjectile.cs.
override bool Loot.ModifierProjectile.InstancePerEntity => true
Definition at line 13 of file ModifierProjectile.cs.
bool Loot.ModifierProjectile.NeedsClear
Definition at line 28 of file ModifierProjectile.cs.
float Loot.ModifierProjectile.SnapshotCritMulti = 1f
Definition at line 31 of file ModifierProjectile.cs.
List<(int type, int time, float chance)> Loot.ModifierProjectile.SnapshotDebuffChances = new List<(int type, int time, float chance)>()
Definition at line 32 of file ModifierProjectile.cs.
Referenced by Loot.ModifierProjectile.Clone().
float Loot.ModifierProjectile.SnapshotHealthyFoesMulti = 1f
Definition at line 30 of file ModifierProjectile.cs.