Even More Modifiers: Loot.Core.System.Modifier.Modifier Class Reference
Loot.Core.System.Modifier.Modifier Class Reference
Defines a modifier, which is an unloaded GlobalItem Making it a GlobalItem gives easy access to all hooks The various hooks are called by our own GlobalItem In your Modifier, it is safe to assume when one of the hooks is called, that item currently is modified by this modifier
Public Member Functions
sealed override void AnglerChat (int type, ref string chat, ref string catchLocation)
virtual void Apply (Item item)
Allows modders to do something when this modifier is applied If a modder needs ModPlayer hooks, they should make their own ModPlayer and apply fields using this hook This is also called for SetDefaults
sealed override void ArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color)
sealed override void ArmorSetShadows (Player player, string set)
sealed override bool Autoload (ref string name)
virtual bool CanRoll (ModifierContext ctx)
If this Modifier can roll at all in the given context Properties are available here, apart from magnitude and power
sealed override void CaughtFishStack (int type, ref int stack)
virtual void Clone (ref Modifier clone)
Allows modders to do custom cloning here Happens after default cloning, which clones various info (mod, type, magnitude and power)
new object Clone ()
sealed override GlobalItem Clone (Item item, Item itemClone)
sealed override void DrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
sealed override bool DrawBody (int body)
sealed override void DrawHair (int head, ref bool drawHair, ref bool drawAltHair)
sealed override void DrawHands (int body, ref bool drawHands, ref bool drawArms)
sealed override bool DrawHead (int head)
sealed override bool DrawLegs (int legs, int shoes)
sealed override void ExtractinatorUse (int extractType, ref int resultType, ref int resultStack)
string GetFormattedUniqueName ()
virtual GlowmaskEntity GetGlowmaskEntity (Item item)
virtual ModifierPropertiesBuilder GetModifierProperties (Item item)
virtual ShaderEntity GetShaderEntity (Item item)
virtual ModifierTooltipBuilder GetTooltip ()
sealed override Vector2 HoldoutOffset (int type)
sealed override Vector2 HoldoutOrigin (int type)
sealed override bool IsAnglerQuestAvailable (int type)
sealed override string IsArmorSet (Item head, Item body, Item legs)
sealed override string IsVanitySet (int head, int body, int legs)
virtual new void Load (Item item, TagCompound tag)
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
sealed override void LoadLegacy (Item item, BinaryReader reader)
sealed override bool NeedsSaving (Item item)
sealed override GlobalItem NewInstance (Item item)
sealed override void OpenVanillaBag (string context, Player player, int arg)
virtual bool PostRoll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers)
Returns if the modifier will actually be added after it is rolled. This is called after Roll is called This is used to be able to stop a modifier from being added after it has rolled If the roll is deemed illicit, the next roll is forced to succeed
sealed override bool PreOpenVanillaBag (string context, Player player, int arg)
sealed override void PreUpdateVanitySet (Player player, string set)
virtual void Roll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers)
Allows modders to do something when the modifier is rolled in the given context The passed rolledModifiers are already rolled modifiers on the item
virtual void Save (Item item, TagCompound tag)
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
sealed override TagCompound Save (Item item)
sealed override void SetDefaults (Item item)
sealed override void SetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes)
sealed override void UpdateArmorSet (Player player, string set)
sealed override void UpdateVanitySet (Player player, string set)
sealed override bool WingUpdate (int wings, Player player, bool inUse)
Public Attributes
sealed override bool CloneNewInstances => true
sealed override bool InstancePerEntity => true
new string Name => GetType().Name
virtual string UniqueName => string.Empty
Properties
Mod Mod [get, set]
Mod ILoadableContentSetter. Mod [set]
ModifierProperties Properties [get, set]
uint Type [get, set]
uint ILoadableContentSetter. Type [set]
Properties inherited from Loot.Core.System.Core.ILoadableContent
Mod Mod [get]
string Name [get]
uint Type [get]
Detailed Description
Defines a modifier, which is an unloaded GlobalItem Making it a GlobalItem gives easy access to all hooks The various hooks are called by our own GlobalItem In your Modifier, it is safe to assume when one of the hooks is called, that item currently is modified by this modifier
Definition at line 20 of file Modifier.cs.
Member Function Documentation
sealed override void Loot.Core.System.Modifier.Modifier.AnglerChat (int type, ref string chat, ref string catchLocation)
Definition at line 240 of file Modifier.cs.
         {
         }
virtual void Loot.Core.System.Modifier.Modifier.Apply (Item item) virtual
Allows modders to do something when this modifier is applied If a modder needs ModPlayer hooks, they should make their own ModPlayer and apply fields using this hook This is also called for SetDefaults
Reimplemented in Loot.Modifiers.WeaponModifiers.DamageWithManaCost, Loot.Modifiers.WeaponModifiers.VelocityPlus, Loot.Modifiers.WeaponModifiers.ManaReduce, and Loot.Modifiers.WeaponModifiers.SpeedPlus.
Definition at line 91 of file Modifier.cs.
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.ArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color)
Definition at line 248 of file Modifier.cs.
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.ArmorSetShadows (Player player, string set)
Definition at line 244 of file Modifier.cs.
         {
         }
sealed override bool Loot.Core.System.Modifier.Modifier.Autoload (ref string name)
virtual bool Loot.Core.System.Modifier.Modifier.CanRoll (ModifierContext ctx) virtual
If this Modifier can roll at all in the given context Properties are available here, apart from magnitude and power
Reimplemented in Loot.Modifiers.WeaponModifiers.CursedDamage, Loot.Modifiers.WeaponModifiers.VelocityPlus, Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity, Loot.Modifiers.WeaponModifiers.DamageWithManaCost, Loot.Modifiers.WeaponModifiers.CritPlus, Loot.Modifiers.WeaponModifiers.ManaReduce, Loot.Modifiers.WeaponModifiers.AmmoReduce, Loot.Modifiers.WeaponModifiers.KnockbackPlus, Loot.Modifiers.Base.EquipModifier, Loot.Modifiers.Base.WeaponModifier, Loot.Modifiers.Base.AccessoryModifier, and Loot.Modifiers.Base.ArmorModifier.
sealed override void Loot.Core.System.Modifier.Modifier.CaughtFishStack (int type, ref int stack)
Definition at line 236 of file Modifier.cs.
         {
         }
virtual void Loot.Core.System.Modifier.Modifier.Clone (ref Modifier clone) virtual
Allows modders to do custom cloning here Happens after default cloning, which clones various info (mod, type, magnitude and power)
Definition at line 99 of file Modifier.cs.
Referenced by Loot.Ext.ModUtils.GetModifier(), and Loot.EMMItem.RollNewModifiers().
         {
         }
new object Loot.Core.System.Modifier.Modifier.Clone ()
Definition at line 103 of file Modifier.cs.
References Loot.Core.System.Modifier.ModifierPropertiesBuilder.Build(), Loot.Core.System.Modifier.Modifier.GetModifierProperties(), Loot.Core.System.Modifier.ModifierProperties.Magnitude, Loot.Core.System.Modifier.Modifier.Mod, Loot.Core.System.Loaders.ContentLoader.Modifier, Loot.Core.System.Modifier.Modifier.Name, Loot.Core.System.Modifier.ModifierProperties.Power, Loot.Core.System.Modifier.Modifier.Properties, and Loot.Core.System.Modifier.Modifier.Type.
         {
             Modifier clone = (Modifier)MemberwiseClone();
             clone.Mod = Mod;
             clone.Type = Type;
             clone.Properties = Properties;
             Clone(ref clone);
             return clone;
         }
sealed override GlobalItem Loot.Core.System.Modifier.Modifier.Clone (Item item, Item itemClone)
sealed override void Loot.Core.System.Modifier.Modifier.DrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
Definition at line 252 of file Modifier.cs.
         {
         }
sealed override bool Loot.Core.System.Modifier.Modifier.DrawBody (int body)
sealed override void Loot.Core.System.Modifier.Modifier.DrawHair (int head, ref bool drawHair, ref bool drawAltHair)
Definition at line 258 of file Modifier.cs.
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.DrawHands (int body, ref bool drawHands, ref bool drawArms)
Definition at line 262 of file Modifier.cs.
         {
         }
sealed override bool Loot.Core.System.Modifier.Modifier.DrawHead (int head)
sealed override bool Loot.Core.System.Modifier.Modifier.DrawLegs (int legs, int shoes)
sealed override void Loot.Core.System.Modifier.Modifier.ExtractinatorUse (int extractType, ref int resultType, ref int resultStack)
Definition at line 232 of file Modifier.cs.
         {
         }
string Loot.Core.System.Modifier.Modifier.GetFormattedUniqueName ()
virtual GlowmaskEntity Loot.Core.System.Modifier.Modifier.GetGlowmaskEntity (Item item) virtual
virtual ModifierPropertiesBuilder Loot.Core.System.Modifier.Modifier.GetModifierProperties (Item item) virtual
Reimplemented in Loot.Modifiers.WeaponModifiers.CursedDamage, Loot.Modifiers.EquipModifiers.Utility.LightPlus, Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus, Loot.Modifiers.EquipModifiers.Defensive.ManaShield, Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance, Loot.Modifiers.EquipModifiers.Defensive.DodgeChance, Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus, Loot.Modifiers.Base.WeaponDebuffModifier, Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus, Loot.Modifiers.EquipModifiers.Defensive.LifeRegen, Loot.Modifiers.EquipModifiers.Utility.LuckPlus, Loot.Modifiers.WeaponModifiers.DamagePlusDaytime, Loot.Modifiers.WeaponModifiers.DamageWithManaCost, Loot.Modifiers.WeaponModifiers.Ice.IcyModifier, Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity, Loot.Modifiers.EquipModifiers.Utility.WingTimePlus, Loot.Modifiers.WeaponModifiers.CritPlus, Loot.Modifiers.WeaponModifiers.DamagePlus, Loot.Modifiers.WeaponModifiers.ManaReduce, Loot.Modifiers.WeaponModifiers.VelocityDamage, Loot.Modifiers.EquipModifiers.Defensive.HealthPlus, Loot.Modifiers.EquipModifiers.Defensive.ManaPlus, Loot.Modifiers.EquipModifiers.Defensive.Thorns, Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus, Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus, Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus, Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus, Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus, Loot.Modifiers.EquipModifiers.Utility.FishingPlus, Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus, Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus, Loot.Modifiers.WeaponModifiers.AmmoReduce, Loot.Modifiers.WeaponModifiers.KnockbackPlus, Loot.Modifiers.WeaponModifiers.MissingHealthDamage, Loot.Modifiers.WeaponModifiers.SpeedPlus, Loot.Modifiers.WeaponModifiers.VelocityPlus, and Loot.Modifiers.Base.EquipModifier.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.Modifier.Load(), and Loot.EMMItem.RollNewModifiers().
virtual ShaderEntity Loot.Core.System.Modifier.Modifier.GetShaderEntity (Item item) virtual
Reimplemented in Loot.Modifiers.WeaponModifiers.Ice.IceModifier.
virtual ModifierTooltipBuilder Loot.Core.System.Modifier.Modifier.GetTooltip () virtual
Reimplemented in Loot.Modifiers.WeaponModifiers.CursedDamage, Loot.Modifiers.EquipModifiers.Utility.LightPlus, Loot.Modifiers.EquipModifiers.Offensive.CritDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.HealthyFoesBonus, Loot.Modifiers.EquipModifiers.Defensive.ManaShield, Loot.Modifiers.EquipModifiers.Defensive.SurvivalChance, Loot.Modifiers.EquipModifiers.Defensive.DodgeChance, Loot.Modifiers.EquipModifiers.Defensive.ImmunityTimePlus, Loot.Modifiers.Base.WeaponDebuffModifier, Loot.Modifiers.EquipModifiers.Defensive.PercentDefenseBonus, Loot.Modifiers.EquipModifiers.Defensive.LifeRegen, Loot.Modifiers.EquipModifiers.Utility.LuckPlus, Loot.Modifiers.WeaponModifiers.DamagePlusDaytime, Loot.Modifiers.WeaponModifiers.DamageWithManaCost, Loot.Modifiers.WeaponModifiers.Ice.IcyModifier, Loot.Modifiers.EquipModifiers.Defensive.KnockbackImmunity, Loot.Modifiers.EquipModifiers.Utility.WingTimePlus, Loot.Modifiers.WeaponModifiers.CritPlus, Loot.Modifiers.WeaponModifiers.DamagePlus, Loot.Modifiers.WeaponModifiers.ManaReduce, Loot.Modifiers.WeaponModifiers.VelocityDamage, Loot.Modifiers.EquipModifiers.Defensive.HealthPlus, Loot.Modifiers.EquipModifiers.Defensive.ManaPlus, Loot.Modifiers.EquipModifiers.Defensive.Thorns, Loot.Modifiers.EquipModifiers.Offensive.MagicCritPlus, Loot.Modifiers.EquipModifiers.Offensive.MagicDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.MeleeCritPlus, Loot.Modifiers.EquipModifiers.Offensive.MeleeDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.MinionDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.RangedCritPlus, Loot.Modifiers.EquipModifiers.Offensive.RangedDamagePlus, Loot.Modifiers.EquipModifiers.Offensive.ThrownCritPlus, Loot.Modifiers.EquipModifiers.Offensive.ThrownDamagePlus, Loot.Modifiers.EquipModifiers.Utility.FishingPlus, Loot.Modifiers.EquipModifiers.Utility.MiningSpeedPlus, Loot.Modifiers.EquipModifiers.Utility.MoveSpeedPlus, Loot.Modifiers.WeaponModifiers.AmmoReduce, Loot.Modifiers.WeaponModifiers.KnockbackPlus, Loot.Modifiers.WeaponModifiers.MissingHealthDamage, Loot.Modifiers.WeaponModifiers.SpeedPlus, and Loot.Modifiers.WeaponModifiers.VelocityPlus.
sealed override Vector2 Loot.Core.System.Modifier.Modifier.HoldoutOffset (int type)
sealed override Vector2 Loot.Core.System.Modifier.Modifier.HoldoutOrigin (int type)
sealed override bool Loot.Core.System.Modifier.Modifier.IsAnglerQuestAvailable (int type)
sealed override string Loot.Core.System.Modifier.Modifier.IsArmorSet (Item head, Item body, Item legs)
sealed override string Loot.Core.System.Modifier.Modifier.IsVanitySet (int head, int body, int legs)
virtual new void Loot.Core.System.Modifier.Modifier.Load (Item item, TagCompound tag) virtual
Allows modder to do custom loading here Use the given TC to pull data you saved using Save(Item,TagCompound)
Parameters
tag
Reimplemented in Loot.Modifiers.WeaponModifiers.RandomDebuff, and Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.
Definition at line 145 of file Modifier.cs.
References Loot.Core.System.Modifier.ModifierPropertiesBuilder.Build(), Loot.Core.System.Modifier.Modifier.GetModifierProperties(), Loot.Core.System.Modifier.Modifier.Load(), Loot.Core.System.Modifier.ModifierProperties.Magnitude, Loot.Core.System.Loaders.ContentLoader.Modifier, Loot.Core.System.Modifier.ModifierProperties.Power, and Loot.Core.System.Modifier.Modifier.Properties.
Referenced by Loot.Core.System.Modifier.Modifier.Load().
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.LoadLegacy (Item item, BinaryReader reader)
Definition at line 279 of file Modifier.cs.
         {
         }
sealed override bool Loot.Core.System.Modifier.Modifier.NeedsSaving (Item item)
sealed override GlobalItem Loot.Core.System.Modifier.Modifier.NewInstance (Item item)
sealed override void Loot.Core.System.Modifier.Modifier.OpenVanillaBag (string context, Player player, int arg)
Definition at line 286 of file Modifier.cs.
         {
         }
virtual bool Loot.Core.System.Modifier.Modifier.PostRoll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers) virtual
Returns if the modifier will actually be added after it is rolled. This is called after Roll is called This is used to be able to stop a modifier from being added after it has rolled If the roll is deemed illicit, the next roll is forced to succeed
Reimplemented in Loot.Modifiers.WeaponModifiers.RandomDebuff.
Referenced by Loot.EMMItem.RollNewModifiers().
sealed override bool Loot.Core.System.Modifier.Modifier.PreOpenVanillaBag (string context, Player player, int arg)
sealed override void Loot.Core.System.Modifier.Modifier.PreUpdateVanitySet (Player player, string set)
Definition at line 292 of file Modifier.cs.
         {
         }
virtual void Loot.Core.System.Modifier.Modifier.Roll (ModifierContext ctx, IEnumerable< Modifier > rolledModifiers) virtual
Allows modders to do something when the modifier is rolled in the given context The passed rolledModifiers are already rolled modifiers on the item
Reimplemented in Loot.Modifiers.WeaponModifiers.RandomDebuff, and Loot.Modifiers.WeaponModifiers.DamagePlusDaytime.
Definition at line 73 of file Modifier.cs.
Referenced by Loot.EMMItem.RollNewModifiers().
         {
         }
virtual void Loot.Core.System.Modifier.Modifier.Save (Item item, TagCompound tag) virtual
Allows modder to do custom saving here Use the given TC to put data you want to save, which can be loaded using Load(Item,TagCompound)
Reimplemented in Loot.Modifiers.WeaponModifiers.DamagePlusDaytime, and Loot.Modifiers.WeaponModifiers.RandomDebuff.
Definition at line 200 of file Modifier.cs.
References Loot.Core.System.Modifier.Modifier.Mod, Loot.Core.System.Modifier.Modifier.Name, Loot.Core.System.Modifier.Modifier.Properties, and Loot.Core.System.Modifier.Modifier.Save().
Referenced by Loot.Core.System.Modifier.Modifier.Save(), and Loot.Core.System.Modifier.ModifierPool.Save().
         {
         }
sealed override TagCompound Loot.Core.System.Modifier.Modifier.Save (Item item)
sealed override void Loot.Core.System.Modifier.Modifier.SetDefaults (Item item)
Definition at line 223 of file Modifier.cs.
         {
             base.SetDefaults(item);
             Apply(item);
         }
sealed override void Loot.Core.System.Modifier.Modifier.SetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes)
Definition at line 299 of file Modifier.cs.
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.UpdateArmorSet (Player player, string set)
Definition at line 303 of file Modifier.cs.
         {
         }
sealed override void Loot.Core.System.Modifier.Modifier.UpdateVanitySet (Player player, string set)
Definition at line 307 of file Modifier.cs.
         {
         }
sealed override bool Loot.Core.System.Modifier.Modifier.WingUpdate (int wings, Player player, bool inUse)
Member Data Documentation
sealed override bool Loot.Core.System.Modifier.Modifier.CloneNewInstances => true
Definition at line 221 of file Modifier.cs.
sealed override bool Loot.Core.System.Modifier.Modifier.InstancePerEntity => true
Definition at line 220 of file Modifier.cs.
new string Loot.Core.System.Modifier.Modifier.Name => GetType().Name
Definition at line 36 of file Modifier.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), and Loot.Core.System.Modifier.Modifier.Save().
virtual string Loot.Core.System.Modifier.Modifier.UniqueName => string.Empty
Definition at line 37 of file Modifier.cs.
Property Documentation
Mod Loot.Core.System.Modifier.Modifier.Mod get set
Definition at line 22 of file Modifier.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), and Loot.Core.System.Modifier.Modifier.Save().
Mod ILoadableContentSetter. Loot.Core.System.Modifier.Modifier.Mod set private
Definition at line 25 of file Modifier.cs.
ModifierProperties Loot.Core.System.Modifier.Modifier.Properties get set
Definition at line 43 of file Modifier.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.Modifier.Load(), Loot.EMMItem.RollNewModifiers(), and Loot.Core.System.Modifier.Modifier.Save().
uint Loot.Core.System.Modifier.Modifier.Type get set
Definition at line 29 of file Modifier.cs.
Referenced by Loot.Core.System.Modifier.Modifier.Clone(), Loot.Ext.ModUtils.GetModifier(), and Loot.EMMItem.RollNewModifiers().
uint ILoadableContentSetter. Loot.Core.System.Modifier.Modifier.Type set private
Definition at line 32 of file Modifier.cs.