Even More Modifiers: Loot.Api.Loaders.LoadingFunneler Class Reference
Loot.Api.Loaders.LoadingFunneler Class Reference
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Static Public Member Functions
static void AddMod (Mod mod)
Static Private Member Functions
static void LoadMod ()
static void LoadModForClient ()
static void UnloadMod ()
Detailed Description
The LoadingFunneler's purpose is to funnel all loading and unloading to one class
Definition at line 21 of file LoadingFunneler.cs.
Member Function Documentation
static void Loot.Api.Loaders.LoadingFunneler.AddMod (Mod mod) static
Definition at line 23 of file LoadingFunneler.cs.
References Loot.Api.Loaders.RegistryLoader.AddContent(), and Loot.Api.Loaders.RegistryLoader.RegisterMod().
         {
             RegistryLoader.RegisterMod(mod);
             RegistryLoader.AddContent(mod);
         }
static void Loot.Api.Loaders.LoadingFunneler.LoadMod () static private
Definition at line 54 of file LoadingFunneler.cs.
References Loot.Api.Loaders.RegistryLoader.AddContent(), Loot.Api.Loaders.ContentLoader.Modifier, Loot.Api.Loaders.ContentLoader.ModifierEffect, Loot.Api.Loaders.ContentLoader.ModifierPool, Loot.Api.Loaders.ContentLoader.ModifierRarity, and Loot.Api.Loaders.RegistryLoader.RegisterMod().
         {
             ModSupportTunneler.Init();
             ContentLoader.Initialize();
             ContentLoader.Load();
             RegistryLoader.Initialize();
             RegistryLoader.Load();
             RegistryLoader.RegisterMod(Loot.Instance);
             ContentLoader.Modifier.AddContent(typeof(NullModifier), Loot.Instance);
             ContentLoader.ModifierPool.AddContent(typeof(NullModifierPool), Loot.Instance);
             ContentLoader.ModifierRarity.AddContent(typeof(NullModifierRarity), Loot.Instance);
             ContentLoader.ModifierEffect.AddContent(typeof(NullModifierEffect), Loot.Instance);
             RegistryLoader.AddContent(Loot.Instance);
             if (Main.dedServ)
             {
                 ModSupportTunneler.AddServerSupport();
             }
         }
static void Loot.Api.Loaders.LoadingFunneler.LoadModForClient () static private
Definition at line 77 of file LoadingFunneler.cs.
References Loot.Api.Loaders.AssetLoader.RegisterAssets().
         {
             Loot.ModContentManager = new ModContentManager();
             Loot.ModContentManager.Initialize(Loot.Instance);
             Loot.Instance.GuiInterface = new UserInterface();
             Loot.Instance.GuiState = new GuiTabWindow();
             Loot.Instance.GuiState.Activate();
             AssetLoader.RegisterAssets(Loot.Instance, "GraphicsAssets");
             ModSupportTunneler.AddClientSupport();
             // TODO IL patch management
             new UseItemEffectsHack().Hack();
         }
static void Loot.Api.Loaders.LoadingFunneler.UnloadMod () static private
Definition at line 93 of file LoadingFunneler.cs.
         {
             ContentLoader.Unload();
             RegistryLoader.Unload();
             Loot.ModContentManager?.Unload();
             Loot.ModContentManager = null;
             //UnloadStaticRefs()
         }