Even More Modifiers: Loot.Core.System.Strategy.NormalRollingStrategy Class Reference
Loot.Core.System.Strategy.NormalRollingStrategy Class Reference
A normal rolling strategy, follows normal behavior
Public Member Functions
bool Roll (ModifierContext modifierContext, RollingStrategyContext strategyContext)
Public Member Functions inherited from Loot.Core.System.Strategy.IRollingStrategy< RollingStrategyContext >
bool Roll (ModifierContext modifierContext, T strategyContext=null)
Protected Member Functions
virtual IEnumerable< Modifier.Modifier > GetRollableModifiers (ModifierContext context)
Protected Attributes
bool _forceNextRoll
EMMItem modifierItem
RollingStrategyProperties properties
Private Member Functions
WeightedRandom< Modifier.Modifier > GetRandomList (ModifierContext context)
void InitFields (RollingStrategyContext strategyContext)
Detailed Description
A normal rolling strategy, follows normal behavior
Definition at line 13 of file NormalRollingStrategy.cs.
Member Function Documentation
WeightedRandom<Modifier.Modifier> Loot.Core.System.Strategy.NormalRollingStrategy.GetRandomList (ModifierContext context) private
Definition at line 30 of file NormalRollingStrategy.cs.
         {
             WeightedRandom<Modifier.Modifier> wr = new WeightedRandom<Modifier.Modifier>();
             foreach (var e in GetRollableModifiers(context))
                 wr.Add(e, e.Properties.RollChance);
             return wr;
         }
virtual IEnumerable<Modifier.Modifier> Loot.Core.System.Strategy.NormalRollingStrategy.GetRollableModifiers (ModifierContext context) protected virtual
void Loot.Core.System.Strategy.NormalRollingStrategy.InitFields (RollingStrategyContext strategyContext) private
Definition at line 24 of file NormalRollingStrategy.cs.
References Loot.EMMItem.GetItemInfo(), Loot.Core.System.Strategy.RollingStrategyContext.Item, and Loot.Core.System.Strategy.RollingStrategyContext.Properties.
         {
             properties = strategyContext.Properties;
             modifierItem = EMMItem.GetItemInfo(strategyContext.Item);
         }
bool Loot.Core.System.Strategy.NormalRollingStrategy.Roll (ModifierContext modifierContext, RollingStrategyContext strategyContext)
Definition at line 38 of file NormalRollingStrategy.cs.
References Loot.Core.System.Modifier.ModifierPool.ActiveModifiers, Loot.Core.System.Modifier.Modifier.Clone(), Loot.Core.System.Modifier.ModifierRarity.ExtraLuck, Loot.Core.System.Strategy.RollingStrategyProperties.ExtraLuck, Loot.Core.System.Modifier.ModifierRarity.ExtraMagnitudePower, Loot.ModifierPlayer.GetEffect(), Loot.Core.System.Modifier.ModifierContext.Item, Loot.Core.System.Strategy.RollingStrategyProperties.MagnitudePower, Loot.Core.System.Strategy.RollingStrategyProperties.MaxRollableLines, Loot.Core.System.Strategy.RollingStrategyProperties.MinModifierRolls, Loot.EMMItem.ModifierPool, Loot.ModifierPlayer.Player(), Loot.Core.System.Modifier.ModifierContext.Player, Loot.Core.System.Modifier.ModifierContext.Rarity, and Loot.Core.System.Strategy.RollingStrategyProperties.RollNextChance.
         {
             InitFields(strategyContext);
             var wr = GetRandomList(modifierContext);
             var list = new List<Modifier.Modifier>();
             // Up to n times, try rolling a mod
             // TODO since we can increase lines rolled, make it so that MaxRollableLines influences the number of rows drawn in the UI
             for (int i = 0; i < properties.MaxRollableLines; ++i)
             {
                 // If there are no mods left, or we fail the roll, break.
                 if (wr.elements.Count <= 0
                     || !_forceNextRoll
                     && list.Count >= properties.MinModifierRolls
                     && Main.rand.NextFloat() > properties.RollNextChance)
                 {
                     break;
                 }
                 _forceNextRoll = false;
                 // Get a next weighted random mod
                 // Clone the mod (new instance) and roll its properties, then roll it
                 Modifier.Modifier rolledModifier = (Modifier.Modifier)wr.Get().Clone();
                 float luck = properties.ExtraLuck;
                 float magnitudePower = properties.MagnitudePower;
                 if (modifierContext.Player != null)
                 {
                     luck += ModifierPlayer.Player(modifierContext.Player).GetEffect<LuckEffect>().Luck;
                 }
                 if (modifierContext.Rarity != null)
                 {
                     luck += modifierContext.Rarity.ExtraLuck;
                     magnitudePower += modifierContext.Rarity.ExtraMagnitudePower;
                 }
                 rolledModifier.Properties =
                     rolledModifier.GetModifierProperties(modifierContext.Item).Build()
                         .RollMagnitudeAndPower(
                             magnitudePower: magnitudePower,
                             lukStat: luck);
                 rolledModifier.Roll(modifierContext, list);
                 // If the mod deemed to be unable to be added,
                 // Force that the next roll is successful
                 // (no RNG on top of RNG)
                 if (!rolledModifier.PostRoll(modifierContext, list))
                 {
                     _forceNextRoll = true;
                     continue;
                 }
                 // The mod can be added
                 list.Add(rolledModifier);
                 // If it is a unique modifier, remove it from the list to be rolled
                 if (rolledModifier.Properties.IsUnique)
                 {
                     wr.elements.RemoveAll(x => x.Item1.Type == rolledModifier.Type);
                     wr.needsRefresh = true;
                 }
             }
             modifierItem.ModifierPool.ActiveModifiers = list.ToArray();
             return list.Any();
         }
Member Data Documentation
bool Loot.Core.System.Strategy.NormalRollingStrategy._forceNextRoll protected
Definition at line 16 of file NormalRollingStrategy.cs.
EMMItem Loot.Core.System.Strategy.NormalRollingStrategy.modifierItem protected
Definition at line 19 of file NormalRollingStrategy.cs.
RollingStrategyProperties Loot.Core.System.Strategy.NormalRollingStrategy.properties protected
Definition at line 18 of file NormalRollingStrategy.cs.